### ISSUE TITLE
Product Export - Locale menu is empty ?

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#10058]
**I'm reporting a Bug**

Trying to configure the product export ... the locale menu is empty (I have to language fr_FR and de_DE), there is no auto completion. For information, it is not empty if I try to export the ProductModel.

Version:2.3.43 CE

![Capture du 2019-05-20 11-56-31](https://user-images.githubusercontent.com/5048627/58013708-7df17e00-7af7-11e9-823a-28f999ddcaa9.png)

Thanks

**Comment by Doodoune** [comment]
Can you check if the call `/configuration/channel/rest/ecommerce` has your locales in his response?
Example:
![network](https://user-images.githubusercontent.com/34027529/58165002-28e47200-7c87-11e9-9130-85076502b031.png)

Can you check also if you have some errors in your console?
Example:
![console](https://user-images.githubusercontent.com/34027529/58164997-26821800-7c87-11e9-85dc-5cdc1740f1ca.png)

Do you have some custom code or it's a vanilla PIM?

**Comment by grabelle** [comment]
Hi,
Yes it is a clean install.
I get an error 404 for this call

GET /configuration/channel/rest/ecommerce HTTP/1.1
Host: ------------------------------------

![Capture du 2019-05-22 14-13-59](https://user-images.githubusercontent.com/5048627/58173624-1de80c80-7c9c-11e9-9c47-2696eadd751c.png)

**Comment by Doodoune** [comment]
Can you see something on your log (var/log/prod.log or dev.log depending on your environment)?

**Comment by grabelle** [comment]
Sorry, I just delete the export and recreate it. It works now.

**Comment by Doodoune** [comment]
Okay, so I close this issue.
