### ISSUE TITLE
API error when fetching products (CE v3.2)

### ISSUE THREAD

**Issue by ndoussonpga** [akeneo/pim-community-dev#10066]
Hi, after installing PIM v3.2 on my computer with Docker, init it with fixtures as described in documentation from my PIM 2.x csv/yml (updated for sure) and added some products via API, i've encountered an error when i requested product :

`[2019-05-21 11:56:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 10 passed to Akeneo\Pim\Enrichment\Component\Product\Connector\ReadModel\ConnectorProduct::__construct() must be of the type array, null given, called in /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php on line 142" at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php line 58 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 10 passed to Akeneo\\Pim\\Enrichment\\Component\\Product\\Connector\\ReadModel\\ConnectorProduct::__construct() must be of the type array, null given, called in /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php on line 142 at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php:58)"} []`

After discussing with my colleague, i added one **association** via web ui and the error not happen again.

I've asking on Slack before coming here and @ahocquard suggested me to open an issue because it may be a bug ;)

[akeneo-pim-system-info_2019-05-21_13_20.txt](https://github.com/akeneo/pim-community-dev/files/3202743/akeneo-pim-system-info_2019-05-21_13_20.txt)

Don't hesitate if you need more information.

Nicolas.

**Comment by mmetayer** [comment]
Hello @ndoussonpga, there is indeed an issue when your catalog does not have any association type at all, we'll fix as soon as possible.
