### ISSUE TITLE
Job has been executed - stop email

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#10071]
Hi,
I use the latest 2.3 ... I would like to avoid to get a mail notification when a jod has been executed ... what should I do ?

Thx
Guillaume

**Comment by ptitkosmos** [comment]
Hi,

faced the same problem, even if only username is done as parameter and not email. Any configuration to stop sending email to user that does not want to ?

Regards

**Comment by rjwebdev** [comment]
This is done by setting the `akeneo_batch.enable_mail_notification` to false in your application config

**Comment by ptitkosmos** [comment]
> 
> 
> This is done by setting the `akeneo_batch.enable_mail_notification` to false in your application config

Thank you for your answer, but this is a global parameter. My will was to avoid sending message for a defined user (the one used for batch import). No matter, we planned to stop using akeneo in the next months.
