### ISSUE TITLE
Module not found: Error: Can't resolve 'pim/form-builder' in '/home/node/web/bundles/pimui/js'

### ISSUE THREAD

**Issue by vsilent** [akeneo/pim-community-dev#10126]
**I'm reporting a Bug**

Module not found: Error: Can't resolve 'pim/form-builder' in '/home/node/web/bundles/pimui/js'

pim-community-standard 3.0.21 fresh install. 
https://github.com/akeneo/pim-community-standard/archive/v3.0.21.tar.gz

**Comment by vsilent** [comment]
yarn install v1.13.0
warning package.json: No license field
warning pim-community-standard@2.0.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.65s.
yarn run v1.13.0
warning package.json: No license field
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
$ NODE_PATH=node_modules node $npm_package_config_check --source=$npm_package_config_source
Starting webpack from /home/node in prod mode

WebpackCleanupPlugin: 0 file(s) deleted.
Version: webpack 3.5.5
Time: 10761ms
              Asset       Size  Chunks             Chunk Names
        main.min.js     191 kB       0  [emitted]  main
      vendor.min.js  701 bytes       1  [emitted]  vendor
    manifest.min.js    1.44 kB       2  [emitted]  manifest
    main.min.js.map     931 kB       0  [emitted]  main
  vendor.min.js.map    1.76 kB       1  [emitted]  vendor
manifest.min.js.map    7.72 kB       2  [emitted]  manifest

ERROR in ./web/bundles/pimui/js/index.js
Module not found: Error: Can't resolve 'pim/form-builder' in '/home/node/web/bundles/pimui/js'
 @ ./web/bundles/pimui/js/index.js 1:13-138
 @ multi babel-polyfill ./web/bundles/pimui/js/index.js

**Comment by akovalyov** [comment]
@vsilent just experienced the same issue. In my case it was when using docker for php while using node on host. It was fixed after switching to php on host machine and launching `php bin/console pim:installer:dump-require-paths`.

**Comment by jmleroux** [comment]
This issue is closed for inactivity. Please feel free to reopen it if needed.
Regards.

**Comment by asimlqt** [comment]
I'm getting a similar error:

```
ERROR in ./public/bundles/akeneoconnectivityconnection/js/controller/audit.tsx
Module not found: Error: Can't resolve '@akeneo-pim-community/connectivity-connection' in '/var/www/html/pim/public/bundles/akeneoconnectivityconnection/js/controller'
```

Akeneo: 4.0.52 CE
Node: 10.22.0
Yarn: 1.22.5
