### ISSUE TITLE
Category tree - drag and drop works terribly bad

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#10128]
**I'm reporting a Bug**

2.3

I have problem with editing trees of categories.
Drag and drop category nodes does not always work. Move node in right place - it's hard task!

I have not been so angry for a long time!!!!

**Comment by Doodoune** [comment]
Hi @userz58,

Can you indicate some reproducible behaviors? (with a step by step scenario) 

For example, I reproduce a bug with category tree:
- Install an ice_cat_catalog 
- Go on category tree edition 
- Select "Sales catalog" category tree 
- Open "brand" subcategory and scroll down, drag one category and scroll up to put this category as the same level than "brand" 
-> it always failed

I've raised an issue for the behavior that I describe, I'll keep you updated for this issue.

Regards,

**Comment by userz58** [comment]
i installed pim 2.3 with ice_cat_catalog 

1 open Settings > Categories
2 select tree Sales catalog
3 move category A4Tech in 3M (will last node)
4 move category Adapt in 3M (will last node)
5 move category ASUS in 3M (will last node)
6 move category Cisco in 3M (will last node)
7 try to set category Cisco second on second position (into category  3M)

in my case, node trying jump on firts place

**Comment by userz58** [comment]
![category](https://user-images.githubusercontent.com/2612186/60189352-6feef580-9839-11e9-84a9-35a9f436570e.gif)

**Comment by pierallard** [comment]
Hi @userz58 !
Thanks for your report.
I'm trying to reproduce your example since hours ; most of the time, it works, sometimes, it does not. I did not succeed to find an "always reproducible example".
Your current install seems to be more reproducible than me. Can you help me a little finding the issue?
Can you please comment the content of the file `/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less`, then rebuild the CSS or the PIM? You will see the original design jstree.
Then, try again to reproduce the bug. If you succeed, I'm interested by another video step by step as you sent.

Thanks !
Pierre

**Comment by userz58** [comment]
without styles it looks terrible, but works good
![jstree-no-css](https://user-images.githubusercontent.com/2612186/60200313-8a7f9980-984e-11e9-9b95-b9f9740ea23e.gif)

**Comment by pierallard** [comment]
So it's a PIM issue.
I created a PR for you, not finished, but to see if it already fixes your issue.
Can you patch your 2.3 with this file and check if everything is still working file please ?

Pierre

**Comment by userz58** [comment]
1. Difficult to drop node in the right place. Now the node trying to jump into the category in front of which I want to put the dragged node.  It is necessary to increase the distance between the nodes. Drop places too narrow.
![jstree-patched](https://user-images.githubusercontent.com/2612186/60264738-a0dc3280-98ec-11e9-8196-1f8b54d5ecfa.gif)

2. New error - when you try to pull out a node into a folder above
![jstree-patched-out](https://user-images.githubusercontent.com/2612186/60264743-a3d72300-98ec-11e9-9c60-ca91ce10f67b.gif)

**Comment by pierallard** [comment]
Hi @userz58 
I added a new commit.
Can you check if the behavior is better ?

**Comment by userz58** [comment]
last patch is work perfect

**Comment by pierallard** [comment]
Cool ! Let me consolidate a little bit my commit, fix some issues then we will merge it.
Thanks for your feedbacks!

**Comment by pierallard** [comment]
Done!

**Comment by userz58** [comment]
![background](https://user-images.githubusercontent.com/2612186/60898124-92d5cc80-a271-11e9-8ee3-74e12c656860.jpg)

**Comment by userz58** [comment]
Could you check:
![background](https://user-images.githubusercontent.com/2612186/60898271-a41ed900-a271-11e9-8fc8-22098783ce98.jpg)

background copying for categories without children
