### ISSUE TITLE
Products Grid customisation lost on logout

### ISSUE THREAD

**Issue by bncbodrogi** [akeneo/pim-community-dev#10159]
Hey,

We are using [Akeneo 3.1 Community SE](https://github.com/akeneo/pim-community-standard/tree/3.1).
I'm not actually sure if this is a bug report or a feature request but either way, there is a functionality that I would love to see regarding the "Products" tab on the UI.

So when I edit the "Columns" on the "Products" view and apply my changes, everything seems to work as expected, the view now contains the selected columns.
However, after logging out and back in again, this information seems to be lost and I can only see the default Columns on tha page.

Is this the expected behaviour?
If so,
- Is there a chance that you will add a way where we can permanently save column configuration?
- Are you aware of any plugins or modules that provide the above-described functionality?
- If none of the above, can you point me in the right direction where/how we could implement this ourselves?

Thanks in advance,
Bence

**Comment by pierallard** [comment]
Hi @bncbodrogi 
When you have your product grid as you want, clic on the '...' near Views/Default view in the top left of the product grid, then select 'Create view'.

After creation, you can go to your user settings, Additional Tab, then you have a new field called "Default product grid view". Select the one you created, and it will load this view in each login by default!

Pierre

**Comment by bncbodrogi** [comment]
Hi @pierallard!
Nice one, thanks for your answer, I kind of got carried away with other tasks in the meantime and forgot to check back on this.
Cheers!
Bence
