### ISSUE TITLE
Ajout d'attributs suivant critère par l'utilisateur

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#10196]
Désolé je vais faire cette demande en français car je ne maitrise pas assez bien l'anglais pour être clair.

Dans les attributs est-ce qu'il y aurait une solution pour que la personne en charge de remplir les fiches produits puisse ajouter des champs. Je donne un exemple pour être plus clair.

Mes produits sont soumis à une ou x réglementations mais pas forcément toutes les mêmes pour tout les produits. Pour certaine réglementations je dois fournir un certificat sous forme de pdf, doc...

Pour le moment je procède de cette manière : 
- Je crée un groupe d'attributs du nom de la réglementation;
- Je créé un attribut de type Oui/Non pour chaque réglementations;
- Je crée un attribut de type fichier pour chaque réglementations, voir plusieurs attributs fichiers pour une même réglementation.

Du coups je me retrouve avec une liste d'attributs à rallonge dont certain ne seront pas remplie car le produit n'est pas concerné par toute les réglementations.

**Ce qu'il me faudrait**
Lorsque je remplie une fiche produit, j'active la réglementation FDES (par exemple) et automatiquement l'attribut correspondant au chargement du fichier réglementaire est chargé sur la fiche produit.

Ce fonctionnement pourrait être même aller sur des images : je créé des attributs oui/non pour activer ou désactiver l'ajout d'une photo d'usage, une autre de mise en situation...

**Comment by Doodoune** [comment]
Bonjour Philippe,

Si j'ai bien compris votre problème, il serait possible de le faire avec le PIM en version Entreprise Edition. Mais pas avec la Community Edition.

 En EE, il est possible d'appliquer des permissions sur les groupes d'attributs. Ainsi certains utilisateurs ne verrait que certains groupes d'attributs sur les fiches produits en fonction de leurs droits.

Cordialement,

**Comment by Philippe-M** [comment]
A priori je n'ai pas réussi à être clair ;)

L'idée n'est pas gérer des droits sur la création ou non d'attributs, ils sont déjà créés. L'idée est plutôt d'éviter de voir, sur une fiche produit, des attributs qui ne lui sont pas utile.

En fait ce n'est pas un groupe d'attributs (notion déjà existante) mais un ensemble d'attributs. l'attribut oui/non permet juste d'activer l'ensemble.

**Comment by Doodoune** [comment]
A priori j'avais bien compris, mais je me suis peut être mal exprimée :) je vais reformuler ma réponse.

Non nous n'avons pas de moyen natif (ni en EE ni en CE) de gérer les ensembles d'attributs comme vous le désirez. Nous avons seulement les groupes d'attributs comme "ensemble d'attributs".

Le plus proche scénario que vous pourrez mettre en place (uniquement sur une EE) est le suivant.

En EE vous pouvez appliquer des permissions sur les groupes.
Ainsi vous pouvez créer un groupe d'attribut "Réglementation 1" et pouvez mettre les droits de vue ou d'édition uniquement pour ce groupe pour le role "EnrichAttributeRegl1". 
Imaginons également un autre groupe d'attribut "Réglementation 2" et un role "EnrichAttributeRegl2" appliqué de la même manière sur lui.

Quand un utilisateur ayant le role "EnrichAttributeRegl2", viendra enrichir une fiche produit, il verra uniquement les attributs appartenant au groupe "Réglementation 2" - il ne verra pas les attributs du groupe "Réglementation 1".

C'est le moyen qui colle le plus à votre phrase : 

> L'idée est plutôt d'éviter de voir, sur une fiche produit, des attributs qui ne lui sont pas utile.

J'ai conscience que cela ne colle pas tout à fait à votre scénario puisque nous n'avons pas de système permettant d'activer ou désactiver telle ou telle fonctionnalité. 
Je vous explique seulement ce qui est possible de mettre en place nativement avec le PIM pour coller au mieux à vos besoins. :)

En espérant être plus claire,
Cordialement,

**Comment by Philippe-M** [comment]
Merci pour vos précisions cette fois j'ai compris. Je testerais ce comportement lorsque nous serrons passé en EE ;)

**Comment by Doodoune** [comment]
Je me permet de clôre ce ticket.
Bonne journée. :)
