### ISSUE TITLE
User plainPassword validation doesn't work more

### ISSUE THREAD

**Issue by vasiliy-sam** [akeneo/pim-community-dev#10193]
Reproducible:

Akeneo 3.0.20
Demo instance with Akeneo 3.1.5 as well (http://demo.akeneo.com/)

Validation worked with Akeneo 2.3.*. So it is a regression bug.

**I'm reporting a Bug**
User plainPassword validation doesn't work

Entity Akeneo\UserManagement\Component\Model\User has validation for all fields.
https://github.com/akeneo/pim-community-dev/blob/3.0/src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml#L20

UserManager erase 'plainPassowrd' field before validation is called.
https://github.com/akeneo/pim-community-dev/blob/3.0/src/Akeneo/UserManagement/Bundle/Manager/UserManager.php#L89

So I can change password to, for example '1' and password will be saved. So it is not possible to manage any validation rules.

Steps:
1. Open tab 'Password'
http://demo.akeneo.com/#/user/1/edit
2. Set new password '1'
3. Save user.

Actual result: No validation. User is saved.
Expected result: All configured validation warnings appear.

Thanks

**Comment by Doodoune** [comment]
Hi @vasiliy-sam,

A fix for this issue was released today in the version 3.0.24 of the PIM. 
It will be available soon in v3.1 (depending on our pull-up process)
We will keep you updated about when it will be available in 3.1.

Regards,

**Comment by Doodoune** [comment]
I closed this issue, it's solved in 3.2.

Regards,
