### ISSUE TITLE
MediaAttributeSetter.php line 33:    Type error: Argument 2 passed to ...

### ISSUE THREAD

**Issue by vsilent** [akeneo/pim-community-dev#10215]
Type error on fresh Akeneo install 

```
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating doctrine/lexer (v1.0.1 => 1.0.2): Downloading (100%)
  - Updating akeneo/pim-community-dev (v3.1.5 => v3.1.6): Downloading (100%)
```

Create session table
Create configuration table
Load jobs for fixtures. (data set: PimInstallerBundle:minimal)

```
In MediaAttributeSetter.php line 33:

  Type error: Argument 2 passed to Akeneo\Pim\Enrichment\Component\Product\Updater\Setter\MediaAttributeSetter::__construct() must implement interface Akeneo\Tool\Compone
  nt\FileStorage\Repository\FileInfoRepositoryInterface, instance of Akeneo\Tool\Component\FileStorage\File\FileStorer given, called in /home/akeneo/var/cache/prod/Contai
  nerWpsyp6c/getPimCatalog_Updater_Setter_RegistryService.php on line 26
```

**Comment by Doodoune** [comment]
Hi @vsilent,

Sorry for the delay, can you please tell me which version of the PIM did you try to install? (v3.0? v3.1? master?)
If it's a fresh install, I imagine that you don't have custom code.
Which documentation did you follow?

Regards,

**Comment by vsilent** [comment]
Hi  @Doodoune,  pim-community-standard-v3.1-latest.tar.gz ,  I followed  https://docs.akeneo.com/2.0/install_pim/installation_docker.html, 
I hoped command sequence must remain the same and for version 3.

**Comment by Doodoune** [comment]
Hi, 
Command sequence can change between versions, especially between major versions.
Please use the documentation adapted to the version of the PIM that you want to install (here is v3.1):
https://docs.akeneo.com/3.1/install_pim/docker/installation_docker.html
Regards,

**Comment by vsilent** [comment]
Thank you,  will try and will let you know.

**Comment by vsilent** [comment]
No changes so far. It still fails.

**Comment by Doodoune** [comment]
Hi @vsilent,
Did you still have your issue? 
Regards,

**Comment by jmleroux** [comment]
PR closed for inactivity. Please feel free to reopen it if needed.
Regards
