### ISSUE TITLE
Mass Edit Price - Update

### ISSUE THREAD

**Issue by derdeakon** [akeneo/pim-community-dev#1021]
Hello,

i want to update more than 1 Product per mass edit function. After i've selected the products and fill in the new price in the field, i want to confirm this action. I got every time the same error message "Sorry, Page was not correctly loaded".

for more infos i took a look in the console:
The message was: Fatal error: Call to a member function setData() on a non-object in /mnt/data/home/public/projects/akeneo/pim/vendor/akeneo/pim-community-dev/src/Pim/Bundle/EnrichBundle/MassEditAction/EditCommonAttributes.php on line <i>420</i>

Anybody knows the error?

How can i fix this problem?

**Comment by moblong** [comment]
Hello,

i have the same issue since Version 1.3.x until 1.4.7. 
Could anyone help me ?
