### ISSUE TITLE
[Feature] duplicate an attribute

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#10226]
In future versions is it planned to be able to apply an attribute.

For example, I have a "choice list" attribute containing 30 options (to be multiplied by the number of local). On my product sheets this attribute is repeated 3 times, there is just the name and description that are different. For the moment I have to re-create the attribute 3 times whereas by the application I could create it once and for the 2 others just change the name and the description.

**Comment by Doodoune** [comment]
Hi Philippe-M,

You can use imports to duplicate attribute option and attributes easily. 

To have an attribute option import job profile, you can create a new import profile with the job `attribute option import` CSV or XSLX :
![Screenshot 2019-06-17 at 16 17 59](https://user-images.githubusercontent.com/34027529/59613503-4fc78400-911f-11e9-9f97-4d6ef6aae2b0.png)

It can help you to duplicate easily an attribute.

Regards,

**Comment by Philippe-M** [comment]
Very good idea, I had not thought of it at all. It is a workaround.

Thank you.
