### ISSUE TITLE
User Role change order groups

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#10264]
With Akeneo CE 3.1.6, I created a user role that does not have the right to modify the attribute groups but can consult the list in "Settings> Attribute groups"

![image](https://user-images.githubusercontent.com/4558101/60022650-860f8100-9694-11e9-9c25-80abe133059f.png)

![image](https://user-images.githubusercontent.com/4558101/60022689-97588d80-9694-11e9-912f-ffb17318c045.png)

Once connected with this user I can still change the order of appearance on the product sheet of these groups.

Before
![image](https://user-images.githubusercontent.com/4558101/60022754-b22b0200-9694-11e9-87fe-86a91c0cc1e2.png)

After
![image](https://user-images.githubusercontent.com/4558101/60022777-c111b480-9694-11e9-905f-28dc44b61213.png)

Connected with a Catalog Manager account
![image](https://user-images.githubusercontent.com/4558101/60022923-0fbf4e80-9695-11e9-9a35-060010e8143c.png)

**Comment by Doodoune** [comment]
Hi @Philippe-M,

Effectively, it's a bug. A user that doesn't have the permission to "Sort attribute groups" must not have the possibility to change the order of the attribute group.

I've created a ticket for this issue. 
I'll keep you updated.

Regards,

**Comment by Doodoune** [comment]
Hi @Philippe-M!

The 3.1.8 was released and contain a fix for this issue. :tada: 
Now only a user that has the role "Sort attribute groups" can be able to change the order of the attribute groups.

I close this issue but feel free to re-open it if needed.

Regards,
