### ISSUE TITLE
Yes/No attribute filter

### ISSUE THREAD

**Issue by SSMellow** [akeneo/pim-community-dev#10279]
**I'm reporting a Bug**

Hello,

Faced a bug, which was reported earlier https://github.com/akeneo/pim-community-dev/issues/4629 and in the comment it was mentioned that is is fixed.

Currently, I'm using Akeneo 2.3.36, but in comments Akeneo member said that it was fixed in 1.7, 2.x and higher,  but this bug appears in new versions too.

What could be a solution for this?

**Comment by Doodoune** [comment]
Hi @SSMellow,

The issue solved in #4629 was a filter problem. 
I've just made a test and it's still fixed. 

> In the product grid when filtering for a Yes/No attribute, the No-filter doesn't work as expected: When the attribute has the value "No" the product gets not displayed when filtering for this.
Steps to reproduce on http://demo.akeneo.com/:
- Create a new product with the "Digitals camera" family
- The attribute "Auto focus lock" in the Attribute group "Technical" is "No" in this new product. Return to the product grid.
- Filter the attribute "Auto focus lock" for the value "No"

If you talk about that:
> releasing a new boolean attribute that will manage 3 states: Yes, No and no value

Unfortunately, it has not been released and it is not yet prioritized, but it's still on the Product team's pipe.

Regards,

**Comment by SSMellow** [comment]
@Doodoune thank you for your response, but actually problem a bit differs from previous bug. If you try adding new Yes/No attribute to existing product then filtering with Yes/No fails.

**Comment by SSMellow** [comment]
@Doodoune any suggestions here?

**Comment by Doodoune** [comment]
Hi @SSMellow, sorry for the delay. Actually I don't see a better way than using rules (in Enterprise Edition) or to import values for this attribute (for all your product)  just after adding this attribute to your family. 
For us, it's work as designed.
Your product doesn't have value for this attribute yet so it will not be sorted. If you save your product, it will have a product value and after that, it could be filtered.
