### ISSUE TITLE
Mix of translations on bulk actions

### ISSUE THREAD

**Issue by AngelVazquezArroyo** [akeneo/pim-community-dev#10307]
**I'm reporting a Bug**

If you have selected for example german as interface language. On bulk actions, there is a mix of english and german words. 

That ist a bug on 3.0

![image](https://user-images.githubusercontent.com/20241064/60491007-08590000-9ca8-11e9-8ce8-0250501de724.png)

**Comment by AngelVazquezArroyo** [comment]
Missing translations on jsmessages.de_DE.yml under
```
pim_enrich.mass_edit.product:
  operation:
```
**add_to_existing_product_model** and **change_family**

Under 
```
pim_enrich.mass_edit.product:
  step:
    choose:
```
**label_count**

**Comment by pierallard** [comment]
Hi @AngelVazquezArroyo 

Thanks for the report.
Akeneo only provides the full software in English. We use external tool to translate the PIM in other languages. You can complete the missing translations directly in Crowdin if it's missing : https://docs.akeneo.com/3.0/contribute_to_pim/translate.html
They will automatically be merged once they're validated by a proofreader. You can become proofreader of german if you want to participate to the translations!

I close this issue.
