### ISSUE TITLE
Rest User Controller condition bug

### ISSUE THREAD

**Issue by SSMellow** [akeneo/pim-community-dev#10304]
https://github.com/akeneo/pim-community-dev/blob/b1363e675e4d9795c20634ac73936c58f034c5e1/src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php#L183

Found a bug in `IF` condition: `$user->getId() !== $user->getId()`. 
Should be `$user->getId() !== $currentUser->getId()`

**Comment by Doodoune** [comment]
Hi @SSMellow,
Would you like to contribute to a patch? Every contribution is very welcome.
Let me know if you need help!

**Comment by jmleroux** [comment]
Fixed in #10738
