### ISSUE TITLE
reopen #10128

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#10348]
**I'm reporting a Bug**
2.3 
after updating there were problems with scrolling the tree

**Comment by userz58** [comment]
![products](https://user-images.githubusercontent.com/2612186/61067451-3826a700-a410-11e9-9569-fc256d8c0344.jpg)
i can't find why is it happends

**Comment by userz58** [comment]
@jmleroux, could you patch 2.3 ?

**Comment by jmleroux** [comment]
yep, i'll try to find the time.

**Comment by jmleroux** [comment]
Should be fixed in #10414

**Comment by jmleroux** [comment]
Tagged in v2.3.55
