### ISSUE TITLE
Integrity constraint violation: 1048 Column 'option_id' cannot be null

### ISSUE THREAD

**Issue by darleenburkhardt** [akeneo/pim-community-dev#10351]
PIM Community Edition 3.0.30

After Update from 3.0.15 I can't add attributes:
"The field "attribute" is not mapped by Doctrine, so it cannot be validated for uniqueness.

**Comment by Doodoune** [comment]
Hi @darleenburkhardt,

I don't understand your issue. Can you be more clear?
You talk about column "option_id" cannot be null in the title and you talk about another issue in the description.
You can't add an attribute on what? Through the code? The UI?
Regards,

**Comment by Doodoune** [comment]
I close this issue. Feel free to re-open it if needed with more details.
Regards,
