### ISSUE TITLE
Missing command for frontend acceptance tests

### ISSUE THREAD

**Issue by Autegar** [akeneo/pim-community-dev#10445]
I wanted to perform the existing frontend acceptance tests, but there is a command in the documentation that does not exist. (**bin/console pim:installer:dump-extensions**)

https://github.com/akeneo/pim-community-dev/blob/master/tests/front/WRITING-FRONT-TESTS.md

**Comment by Doodoune** [comment]
Hi @Autegar,
Yes, this command has been deleted in the v3.1 - the github link: 
https://github.com/akeneo/pim-community-dev/commit/a6755d4a0841920df56b2737614e7279b910cb26#diff-690ec7a5964f33f4e3fb0f376519186f

You can instead launch the command `yarn update-extensions`.

We will update the file.

Regards,

**Comment by Doodoune** [comment]
I closed this issue, feel free to reopen it if needed.
Regards,
