### ISSUE TITLE
[BUG] docker-compose doesnt work as expected

### ISSUE THREAD

**Issue by frzifus** [akeneo/pim-community-dev#10444]
the error occurs on the `master` and `3.2` branch
i have performed the following steps but without success:
```shell
git clone git@github.com:akeneo/pim-community-standard.git
export DOCKER_PORT_HTTP=8080
docker-compose up -d 
```
then I visited with the browser `127.0.0.1:8080`.
there i expected a dashboard but got the following message:
```php

Warning: require(/srv/pim/web/../vendor/autoload.php): failed to open stream: No such file or directory in /srv/pim/web/app.php on line 6

Fatal error: require(): Failed opening required '/srv/pim/web/../vendor/autoload.php' (include_path='.:/usr/share/php') in /srv/pim/web/app.php on line 6
```

**Comment by mmetayer** [comment]
Hello @frzifus, 
it looks like you didn't install the PIM, please follow the steps described in [this documentation](https://docs.akeneo.com/latest/install_pim/docker/installation_docker.html#install-and-run-akeneo).

I'm closing this ticket now, but feel free to ask if you need more info.

Regards,
Mathias
