### ISSUE TITLE
[3.2] The order of attribute groups is not saving

### ISSUE THREAD

**Issue by Denis-Slastinin** [akeneo/pim-community-dev#10452]
**I'm reporting a Bug**
Tried to sort groups like in this guide:
https://help.akeneo.com/pim/v3/articles/manage-your-attribute-groups.html
But the order is not preserved.

**Comment by Doodoune** [comment]
Hi,

I made some test on http://demo.akeneo.com, and I wasn't able to reproduce the issue.
Could you please provide me steps to reproduce your error?

Best regards,
Elodie

**Comment by Doodoune** [comment]
I closed this issue.
Feel free to reopen it with steps to reproduce it.

Regards,
