### ISSUE TITLE
[Question] add custom less file in custom bundle

### ISSUE THREAD

**Issue by bartoszkubicki** [akeneo/pim-community-dev#10509]
There is awesome css guide, but it doesn't contain information how to add new .less file in custom bundle. How it can be achieved?

`
"name": "akeneo/pim-community-dev",
            "version": "v3.0.14",
`

**Comment by pierallard** [comment]
Hi @bartoszkubicki 
You have to add your .less file in your custom bundle.
Then, add a line into an Resource/config/assets.yml, like this
https://github.com/akeneo/pim-community-dev/blob/3.0/src/Akeneo/Platform/Bundle/UIBundle/Resources/config/assets.yml
It will be added automatically when you will rebuild your front application.

**Comment by bartoszkubicki** [comment]
@pierallard Thank you for help. In which section of `assets.yml` should I place my custom file? as `bem`?

**Comment by oliverde8** [comment]
It's the `css` section, with a key and the path to the less. 

Note that in Akeneo 3.1 this has been changed, and you simply need to create a this file `Resources/public/less/index.less` and it will be imported automatically.

**Comment by Doodoune** [comment]
I closed this issue, feel free to reopen it if needed.
