### ISSUE TITLE
memory leak during categories import (akeneo:batch:job-queue-consumer-daemon)

### ISSUE THREAD

**Issue by killoff** [akeneo/pim-community-dev#10566]
**Akeneo system info**

[akeneo-pim-system-info_2019-08-12_09_31.txt](https://github.com/akeneo/pim-community-dev/files/3491336/akeneo-pim-system-info_2019-08-12_09_31.txt)

**The issue**

I am trying to import categories from CSV file (via file upload).
File is ~100Kb and contains ~4000 categories.
4 root categories with their trees each ~1000 subcategories.
[categories.txt](https://github.com/akeneo/pim-community-dev/files/3491377/categories.txt)

Queue daemon is being run in prod mode:
`bin/console akeneo:batch:job-queue-consumer-daemon --env=prod`

Unfortunately, daemon does not have any option for memory limit (smth like -d memory_limit being passed to php cli).

I could increase memory_limit, however, it seems to me that 256Mb should be more than enough for importing 4K categories. 

Exception trace is below

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 2097160 bytes) in /vendor/symfony/symfony/src/Symfony/Component/Stopwatch/StopwatchEvent.php on line 105

Call Stack:
    0.0002     397672   1. {main}() /bin/console:0
    0.0170    1873976   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /bin/console:36
    0.0409    2274208   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
    0.1930   11938240   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
    0.1942   11942816   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:255
    0.1942   11942816   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
    0.4256   24062880   7. Akeneo\Tool\Bundle\BatchBundle\Command\BatchCommand->run() /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:987
    0.4258   24064088   8. Akeneo\Tool\Bundle\BatchBundle\Command\BatchCommand->execute() /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
    0.8642   42333784   9. Akeneo\Tool\Component\Batch\Job\Job->execute() /vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php:156
    0.8735   42406976  10. Akeneo\Tool\Component\Batch\Job\Job->doExecute() /vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php:160
    0.9085   42515240  11. Akeneo\Tool\Component\Batch\Job\Job->handleStep() /vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php:226
    0.9085   42516216  12. Akeneo\Tool\Component\Batch\Step\ItemStep->execute() /vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php:263
    0.9135   42525992  13. Akeneo\Tool\Component\Batch\Step\ItemStep->doExecute() /vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php:100
   60.7201  257209248  14. Akeneo\Tool\Component\Batch\Step\ItemStep->write() /vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/ItemStep.php:128
```

**Comment by killoff** [comment]
Increased memory_limit to 512M => categories are being imported.
However, 4000 products do not pass:
`Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes)`

csv file contains only 3 columns: `sku;categories;name-de_CH`

**Comment by nicolasfl** [comment]
Same here. Can we have a feedback on that point ? Is there a configuration to set to improve the product import speed ?

**Comment by Reiner030** [comment]
https://docs.akeneo.com/3.1/install_pim/manual/installation_ce_archive.html
has this call referenced:
`$ php -d memory_limit=3G ../composer.phar install --optimize-autoloader --prefer-dist`

So it should be possible to switch the above command
`bin/console akeneo:batch:job-queue-consumer-daemon --env=prod`
to e.g.
`php -d memory_limit=3G bin/console akeneo:batch:job-queue-consumer-daemon --env=prod`
?

**Comment by Doodoune** [comment]
Hi!

We fix an issue on this command in the version 3.0.23 (2019-06-11). Did your PIM is on a recent patch?

Regards,

**Comment by jmleroux** [comment]
PR closed without activity during the past weeks. Feel free to reopen it if needed.
Regards.
