### ISSUE TITLE
3.2.2 pim_catalog_price_collection with back-end type prices 500 error

### ISSUE THREAD

**Issue by afserali** [akeneo/pim-community-dev#10564]
**I'm reporting a Bug**

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Akeneo\Channel\Bundle\Doctrine\Query\FindActivatedCurrencies::forChannel() must be of the type string, integer given, called in /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilter.php on line 54" at /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php line 41 {"exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): Type error: Argument 1 passed to Akeneo\Channel\Bundle\Doctrine\Query\FindActivatedCurrencies::forChannel() must be of the type string, integer given, called in /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilter.php on line 54 at /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php:41)"} []

I am using community version 3.2.2

**Comment by Doodoune** [comment]
Hi @afserali,

Please descript the expected behavior, the encountered behavior and the steps to reproduce in the description of your issue.

Regards,

**Comment by afserali** [comment]
that I have Two Price Attribute one is Price and anthor is Special price .. if i try to add both . it 500 Error ..


request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Akeneo\Channel\Bundle\Doctrine\Query\FindActivatedCurrencies::forChannel() must be of the type string, integer given, called in /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilter.php on line 54" at /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php line 41 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Akeneo\\Channel\\Bundle\\Doctrine\\Query\\FindActivatedCurrencies::forChannel() must be of the type string, integer given, called in /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilter.php on line 54 at /var/www/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php:41)"} []
