### ISSUE TITLE
API: get products returns internal server error

### ISSUE THREAD

**Issue by maxbaerten** [akeneo/pim-community-dev#10573]
**I'm reporting a Bug**
Hi,

Perhaps this issue is already fixed, but we were experiencing problems with the API - getproducts. We received an internal server error when sending the request

**Server side** showed us the following
GetGroupAssociationsByProductIdentifiers:fetchByProductIdentifier must by of type array, null returned

We had no association types, so we added a test association which fixed the internal server error on the API {{url}}/api/rest/v1/products and gave back the products

[akeneo-pim-system-info_2019-08-12_14_36.txt](https://github.com/akeneo/pim-community-dev/files/3492961/akeneo-pim-system-info_2019-08-12_14_36.txt)

**Comment by Doodoune** [comment]
Hi @maxbaerten,

I don't reproduce the issue on http://demo.akeneo.com. I've tried to :
- remove all association types
- call the API with theses requests 
=> GET {{url}}/api/rest/v1/products
=> GET {{url}}/api/rest/v1/products/AKNSTK

And I don't reproduce your error. 
Could you send us a step by step way to reproduce it?

Regards,

**Comment by Doodoune** [comment]
I close this issue.
Feel free to reopen with steps to reproduce it.

Regards,
