### ISSUE TITLE
Incorrect title on categories page

### ISSUE THREAD

**Issue by ghoot31** [akeneo/pim-community-dev#10587]
When viewing Settings->Categories page, the page title is not changing correctly. It's expected to state current selected tree node. What happens is when you select a node for the first time, the twig key is visible:

![twig key visible](https://user-images.githubusercontent.com/38385699/63003037-9dd6da80-be77-11e9-81da-d8f27534170b.png)

After that, the page title shows previously, not currently selected node:

![node title not matching](https://user-images.githubusercontent.com/38385699/63003193-f8703680-be77-11e9-9305-a20197d0616b.png)

Probably caused by /pimui/js/page-title.js controller being called to late, thus not providing the translation on the first time, and updating it only after the page title has been already rendered when selected node changes.

System info:
[akeneo-pim-system-info_2019-08-14_07_32.txt](https://github.com/akeneo/pim-community-dev/files/3500266/akeneo-pim-system-info_2019-08-14_07_32.txt)

**Comment by Doodoune** [comment]
Hi, 
We fix this issue in the version 3.2.7. 
We are closing this issue, feel free to reopen it if needed.
Regards,
