### ISSUE TITLE
How many times can the API request?

### ISSUE THREAD

**Issue by H-YuYu** [akeneo/pim-community-dev#10626]
I'm asking a Question：
I have a 100W product quantity and want to use the API to get product information, but a single request can request up to 100 records. Is there a limit on the frequency of API requests?

**Comment by Doodoune** [comment]
Hi @H-YuYu,
For such volumetry, I advise you to use the method "search after" to get all your products.
https://api.akeneo.com/documentation/pagination.html#the-search-after-method
Regarding the frequency of call, it will depend on your server configuration.
Regards,

**Comment by jmleroux** [comment]
PR closed after several weeks of inactivity. Feel free to reopen it if needed.
Regards.
