### ISSUE TITLE
Frontend: Unable to load "System>Configuration" /system/locale/ui | jquery.js:9666

### ISSUE THREAD

**Issue by hinadmin** [akeneo/pim-community-dev#10687]
**Ubuntu 1604:** [Akeneo: System Install Ubuntu 1604](https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/system_install_ubuntu_1604.html)
**Akeneo**: [Latest Standard 2.3 Icecat (2.3.28)](https://download.akeneo.com/pim-community-standard-v2.3-latest-icecat.tar.gz)

**COMMAND**:

> "sudo php -d memory_limit=3G ../composer.phar install --optimize-autoloader --prefer-dist"

I get these notifications/warnings but it all runs ok

> Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.

> "Warning: Ambiguous class resolution, 
> 
> "Pim\Upgrade\schema\Version_1_5_20151121110000_index_logged_at" was found in both "$baseDir . '/upgrades/1.4-1.5/Version_1_5_20151121110000_index_logged_at.php" and "/var/www/html/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.4-1.5/Version_1_5_20151121110000_index_logged_at.php", the first will be used." .........and some more yellow-marked

**COMMAND**:

> sudo bin/console pim:install --force --symlink --clean --env=prod

All ok, but with symfony warning

> WARNING | To avoid internationalization data inconsistencies upgrade the symfony/intl component.

If needed to update - then how to?

**Frontend:**
It all works (products edit, navigation ect.) - but when I go to "System>Configuration" or try to "edit a user" it keeps loading.
![akeneo_500_internal_server](https://user-images.githubusercontent.com/13964766/64331279-cc595880-cfd2-11e9-8226-440f5387dfcf.PNG)

![500_error_js](https://user-images.githubusercontent.com/13964766/64332787-789c3e80-cfd5-11e9-8614-2b59d0a11b72.PNG)

Might be related to this version of Akeneo?
Is there any guide to apply the latest patch? (2.3.60)

Tried to clear cache, reinstalling ect....

**Comment by Doodoune** [comment]
Hi!
You can found the guide "How to apply a patch" in our documentation : 
https://docs.akeneo.com/2.3/migrate_pim/apply_patch/apply_patch_ce.html

Don't hesitate to look on your logs (var/logs/prod.log) to have more information about the 500 error and send us the line that corresponds to this error.

Regards,

**Comment by hinadmin** [comment]
Hi. Thanks for the link regarding patch, I will take a look at that.

Here is my prod.log

> [2019-09-05 11:28:24] request.INFO: Matched route "pim_localization_locale_index". {"route":"pim_localization_locale_index","route_parameters":{"_controller":"pim_localization.controller.locale:indexAction","_route":"pim_localization_locale_index"},"request_uri":"http://52.164.224.247/system/locale/ui","method":"GET"} []
> [2019-09-05 11:28:54] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BufferedBundleReader.php line 45 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BufferedBundleReader.php:45)"} []
> [2019-09-05 11:31:34] request.INFO: Matched route "oro_user_update". {"route":"oro_user_update","route_parameters":{"_controller":"Oro\\Bundle\\UserBundle\\Controller\\UserController::updateAction","id":"1","_route":"oro_user_update"},"request_uri":"http://52.164.224.247/user/update/1","method":"GET"} []
> [2019-09-05 11:32:04] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/JsonBundleReader.php line 41 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/JsonBundleReader.php:41)"} []
> [2019-09-05 11:32:59] request.INFO: Matched route "pim_localization_locale_index". {"route":"pim_localization_locale_index","route_parameters":{"_controller":"pim_localization.controller.locale:indexAction","_route":"pim_localization_locale_index"},"request_uri":"http://52.164.224.247/system/locale/ui","method":"GET"} []
> [2019-09-05 11:33:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php line 112 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php:112)"} []
>

**Comment by hinadmin** [comment]
It worked after applying the latest patch (2.3.60)
Closing

**Comment by lukebd** [comment]
Fix for this issue for anyone using Akeneo 2.0.52
The Symfony version has issues so if you change your composer.json to require symfony 3.4.26

    "require": {
        "symfony/symfony": "3.4.26 as 3.4.2",

If on a later version of Akeneo change 3.4.2 to reflect the version Akeneo expects. 3.4.4 etc
