### ISSUE TITLE
Update 3.0 to 3.1 error

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#10707]
Hello, I am trying to update version 3.0CE to 3.1CE. 

When I run the command: 

`php bin/console cache:clear --env=prod`

I have the following error

![image](https://user-images.githubusercontent.com/4558101/64708771-6e86ae00-d4b5-11e9-9a73-1f62ba60bde7.png)

Mysql Server version: 5.7.26
Apache/2.4.25 (Debian)
PHP 7.2.22-1
nodejs v10.16.0
Elasticsearch 6.8.1

**Comment by Doodoune** [comment]
Hi Philippe,

Did you follow the file UPGRADE.md (at the root of the PIM) to upgrade your PIM?
What is the step that raises you this error?

Regards,

**Comment by Philippe-M** [comment]
Hi Doodoune, 

I used this readme well to follow the update procedure.

This error occurs in step 4 of the "Migrate your custom code" paragraph. But by rereading the procedure I realize that it is in the case where I customized my installation of Akeneo which is not my case. I am on a standard installation.

But if I do not realize this step and I stop at step 10 of "Migrate your standard project" I have a blank page and in the logs apache I :

`Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "VoterInitializerListener" from namespace "Knp\\Bundle\\MenuBundle\\EventListener".\nDid you forget a "use" statement for another namespace? in /var/www/html/pim-community-standard/var/cache/prod/ContainerJjy8q4b/appProdProjectContainer.php:5602\nStack trace:\n#0 /var/www/html/pim-community-standard/var/cache/prod/ContainerJjy8q4b/appProdProjectContainer.php(4668): ContainerJjy8q4b\\appProdProjectContainer->getKnpMenu_Listener_VotersService()\n#1 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(229): ContainerJjy8q4b\\appProdProjectContainer->ContainerJjy8q4b\\{closure}()\n#2 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(61): Symfony\\Component\\EventDispatcher\\EventDispatcher->sortListeners('kernel.request')\n#3 /var/www/html/pim-community-standard/vendor/symf...\n'`

**Comment by Doodoune** [comment]
Did you do a composer update? Maybe your KnpBundle is not up to date.

**Comment by Philippe-M** [comment]
I found the cause of the mistake. Before launching

`bin / console cache: clear --env = prod`

You must empty the directory var/cache/_[prod, dev]_. Astonishing to have to delete the cache to launch the command that purges the cache ...;)

**Comment by Doodoune** [comment]
Glad that you solved your issue. 
I close this issue. Feel free to reopen it if needed.
