### ISSUE TITLE
Russian text in English js/messages file

### ISSUE THREAD

**Issue by andrew-smart** [akeneo/pim-community-dev#10741]
Running v3.2.8 (although also confirmed on 3.0.x)

The translation for "job" (Работа) is in Russian in the English translation files;

https://github.com/akeneo/pim-community-dev/blob/3.2/src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/messages.en_GB.yml#L1

and

https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_GB.yml#L69

![Screenshot 2019-09-18 at 10 36 36](https://user-images.githubusercontent.com/1692003/65137297-fb26f400-da00-11e9-896a-722e205c57e6.png)

**Comment by Doodoune** [comment]
Nice catch!
I've corrected it on Crowdin. It will be available soon. 
Regards,

**Comment by Doodoune** [comment]
It's fixed !
I close this issue.

Regards,
