### ISSUE TITLE
External products API does not conform to the documentation

### ISSUE THREAD

**Issue by pbloigu** [akeneo/pim-community-dev#10804]
The external products API at http://demo.akeneo.com/api/rest/v1/products produces a response that's not in line with the documentation provided at https://api.akeneo.com/api-reference.html#get_products

As of this writing, the version installed at demo.akeneo.com seems to be 3.2.9 CE. 

http://demo.akeneo.com/api/rest/v1/products?pagination_type=page produces a result starting with 
```
{
    "_links": {
        "self": {
            "href": "http://demo.akeneo.com/api/rest/v1/products?page=1&with_count=false&pagination_type=page&limit=10"
        },
        "first": {
            "href": "http://demo.akeneo.com/api/rest/v1/products?page=1&with_count=false&pagination_type=page&limit=10"
        },
        "next": {
            "href": "http://demo.akeneo.com/api/rest/v1/products?page=2&with_count=false&pagination_type=page&limit=10"
        }
    },
    "current_page": 1,
    "_embedded": {
        "items": [
            {
```
If we pay attention to the "items" property, and compare it to the linked documentation, we can spot a difference. In the documentation there's an example response, that begins with:

```
{
  "_links": {
    "self": {
      "href": "https://demo.akeneo.com/api/rest/v1/products?page=3&limit=3"
    },
    "first": {
      "href": "https://demo.akeneo.com/api/rest/v1/products?page=1&limit=3"
    },
    "previous": {
      "href": "https://demo.akeneo.com/api/rest/v1/products?page=2&limit=3"
    },
    "next": {
      "href": "https://demo.akeneo.com/api/rest/v1/products?page=4&limit=3"
    }
  },
  "current_page": 3,
  "_embedded": {
    "_items": [
      {
```

As we can see there's a difference: "items" vs "_items". We've  been using the Swagger documentation available at https://github.com/akeneo/pim-api-docs to generate a client, which now doesn't work as the Swagger documentation also says "_items" while the API actually produces "items".

**Comment by fitn** [comment]
Hello @pbloigu 

Thank you a lot to have raised this issue. The documentation has been deployed and this problem should be fixed :)

Regards,
