### ISSUE TITLE
Database size Akeneo Version:CE 3.0.11

### ISSUE THREAD

**Issue by lauwiex** [akeneo/pim-community-dev#10829]
Hello,

Does anyone else has trouble with huge size of the Akeneo database?
We have a table akeneo_batch_warning this has a size of 37 gb :O

thanks.

Laurens

**Comment by Doodoune** [comment]
Hi @lauwiex,

Natively we provide two commands to purge some data from your database :
- `bin/console akeneo:batch:purge-job-execution` - Purge jobs execution older than number of days you want except the last one, by default 90 days 
https://docs.akeneo.com/3.0/maintain_pim/purge/purge_job_execution.html
- `bin/console pim:versioning:purge` - Purge version of entities older than number of days exept the first and the last one, by default 90 days
https://docs.akeneo.com/3.0/maintain_pim/purge/purge_version_entities.html#how-to-adapt-the-version-purger-to-your-needs

Hope it will help you to purge your database.

Regards,
Elodie

**Comment by lauwiex** [comment]
Hi @Doodoune ,

Thanks for your reply. I'm going look into this. This seems hopeful 

Best regards,

Laurens
