### ISSUE TITLE
UserContext possible values' documentation

### ISSUE THREAD

**Issue by Rashguir** [akeneo/pim-community-dev#10925]
**I'm asking a Question**
Hi, i've been able to find 2 values for the `get` method of `pim/user-context` (`uiLocale`, `username`) in the documentation, but i can't manage to find an exhaustive list of possible values.

Where can i find it? 

If that page does not exist, is it possible to get user's groups from this context?

Thank you

Please submit your question via the forum https://www.akeneo.com/forums/forum/programming-questions/ <- this redirects to your homepage...

**Comment by Rashguir** [comment]
OK, i've found it :

```
define(['pim/user-context'], function(UserContext) {
    var userGroups = UserContext.get('groups');
})
```

It's just a shame that this kind of information is not explicit in the documentation... :/

**Comment by Rashguir** [comment]
miss clicked, re-open

**Comment by pierallard** [comment]
Sorry about the delay
You will find every information in this file
src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php

Regards
Pierre

**Comment by Rashguir** [comment]
Hi,

Thanks for the tip!
I the mean time, i'll leave this open as it is not properly documented.

Regards,
Rashguir

**Comment by pierallard** [comment]
@Rashguir 
Don't hesitate to do a PR with a little comment in the user-context.js file, to explain where these values come from!
Pierre

**Comment by Rashguir** [comment]
@pierallard 
As it is not the only thing that needs documentation on this solution, i consider that the effort needs to come from Akeneo, instead of the community. 
There's a huge delta between what's possible to do versus what's documented... :/

Every produced code in an open source project needs to be documented.
That's the bare minimum...

**Comment by pierallard** [comment]
@Rashguir 

I totally understand your point of view. We know our documentation is not complete, and sometimes outdated. We try to document most common use cases for code customization, but every user has different need. It's impossible to document every line of code (more than 700k in the project source).
Plus, as the customization can be done almost everywhere in the code, we have to focus on a list of subjects.
You will find a lot of documentation in https://help.akeneo.com/, in https://docs.akeneo.com/latest/index.html or in https://github.com/akeneo/pim-community-dev/tree/master/internal_doc . These 3 sources are open source and can be improved.
Documentation is an endless subject, if you think a part of the code is too complicated or miss documentation, and you think other users can have issues on this subject, I encourage you to participate to this project.
