### ISSUE TITLE
Attribute as Textarea - Frontend Filter 

### ISSUE THREAD

**Issue by michster** [akeneo/pim-community-dev#10921]
Hi,

I don't know if this is a real bug but here's the situation:

We have a attribute called articletext where we store some details of the article. So far so good. This attribute is a type of textarea with multiple lines. Each line is separated by \r\n.
Now if I want to filter this attribute on the frontend, with for example: 

articletext -> contains: "red"

and red isn't in the first line, I don't get any results. Maybe some of you have the same issue?

Thanks in advance,
michster

**Comment by Doodoune** [comment]
Hi @michster,
What is your PIM version, please?
I've made a test on demo.akeneo.com and I won't reproduce the problem.

![bluered](https://user-images.githubusercontent.com/34027529/67779101-79e16900-fa64-11e9-9c3f-7ec945b1a00c.png)
![redblue](https://user-images.githubusercontent.com/34027529/67779109-7d74f000-fa64-11e9-920d-80a0b8e39f8d.png)
![contain_red](https://user-images.githubusercontent.com/34027529/67779097-751cb500-fa64-11e9-8309-6f65a7bc7a9c.png)

Regards,
Elodie

**Comment by michster** [comment]
Hi @Doodoune 

thanks for your advice. 

We are using the version 3.0.11. I think I will first update our Akeneo. 
I'll get back to you.

Regards,
Mike

**Comment by michster** [comment]
Hi @Doodoune, 

An update doesn't have any effect to this behavior.

I've tested it on the demo.akeneo.com with the following example:

![image](https://user-images.githubusercontent.com/13812473/71092642-ed237380-21a7-11ea-9243-775aea58617d.png)

I searched for "Blue".

![image](https://user-images.githubusercontent.com/13812473/71092772-2b209780-21a8-11ea-8e65-5cfc0ecbe681.png)

…and I don't get the Smartphone as a result.

Hopefully you can now reproduce this kind of "issue".

Best regards,
michster

**Comment by Doodoune** [comment]
Hi!

We've created a ticket on the Maintenance team regarding this issue. (internal reference PIM-9035)
We will keep you updated about his resolution.

Regards,

**Comment by Doodoune** [comment]
Hi! 

Great news, a fix is available in the version v3.0.62!
Link to the related PR: https://github.com/akeneo/pim-community-dev/pull/11313

We changed an ElasticSearch configuration so to you have to clean your indexes in your PIM and regenerate them with these commands:
`
# reset ALL elastic search indexes 
bin/console akeneo:elasticsearch:reset-indexes --env=prod

# Index products
bin/console pim:product:index --all --env=prod

# Index product model
bin/console pim:product-model:index --all --env=prod
`

I closed this issue, don't hesitate to ask if you have any question regarding the fix.

Regards,
