### ISSUE TITLE
Products can save associations with self

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#10969]
**I'm reporting a Bug**
When saving associations X_SELL, it is necessary to delete the SKU linking the product to itself

**Comment by Doodoune** [comment]
Hi,
What is the version of your PIM?
Could you describe more precisely your issue? I understand that you can't save a new association if you already have the product himself associated. 
I tried on demo.akeneo.com but I won't reproduce it.

Regards,
Elodie

**Comment by userz58** [comment]
Example from demo site:
![demo1](https://user-images.githubusercontent.com/2612186/67803579-69e67b00-fa9e-11e9-9516-bf9d451a86da.png)

**Comment by Doodoune** [comment]
Hi,

Some client used association to create "packs" with the product himself and some other products.
So for us, it's not an issue.

Regards,
Elodie
