### ISSUE TITLE
Issue with routing

### ISSUE THREAD

**Issue by venkatadri19** [akeneo/pim-community-dev#11124]
Hi,

I am new to akeneo project version (3.2) cant able to find route method name from where its loading from.
I cant able to find routing method for route name ("pim_enrich_product_index") for the url (#/enrich/product/) 
Can u please help me for finding that route and loading from which method in akeneo.

**Comment by venkatadri19** [comment]
I have finded out route  "pim_enrich_product_index"  all are there in this following path

 "/var/www/html/akeneo-pim/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml"

**Comment by Doodoune** [comment]
Hi! 

Glad to see that you found the solution. 
I closed this issue, it can be reopened if needed.

Regards,
