### ISSUE TITLE
Issues installink Akeneo CE using Composer

### ISSUE THREAD

**Issue by Aerendir** [akeneo/pim-community-dev#11141]
**I'm reporting a Bug**

Version: 3.2.21

I'm trying to install Akeneo PIM using Composer.

I run the command to create the project through Composer:

```console
$ composer create-project --prefer-dist akeneo/pim-community-standard ./pim-project "@stable"
```
> Source: https://github.com/akeneo/pim-community-standard#using-composer-to-create-the-project

The project is correctly created.

Then I followed all the steps listed in [Installing Akeneo PIM Community Edition (CE) with the Archive](Installing Akeneo PIM Community Edition (CE) with the Archive) but the last one to create the first super admin user, gives me a lot of errors.

The command I'm using is this:

```console
$ bin/console --env=prod pim:user:create superadmin 1234 my.email@gmail.com Adamo Aerendir en_US --admin -n -vvv
```

I'm going to list them...

# 1. No activated locale

>  [InvalidArgumentException]                                                                         
>  There is no activated locale. The catalog default locale of the user must be an activated locale.

The errors come from the [line 373 of file `CreateUserCommand.php` in `Akeneo/UserManagementBundle`](https://github.com/akeneo/pim-community-dev/blob/v3.2.21/src/Akeneo/UserManagement/Bundle/Command/CreateUserCommand.php#L373):

```php
...

$activatedLocaleCodes = $this->getContainer()->get('pim_catalog.repository.locale')->getActivatedLocaleCodes();

...
```

As far as I understand, the problem is that there is no default locale set.

### 1. I checked `.env` file:
In the `.env` file I have the env variable `APP_DEFAULT_LOCALE`
```env
...
APP_DEFAULT_LOCALE=en
...
```

### 2. I checked the `app/config/parameters.yml` file

In `app/config/parameters.yml` I have the param `locale`:

```yaml
# This file is auto-generated during the composer install
parameters:
    ...
    locale: en
    ...
```

### 3. Check for some other config somewhere

Searching on Google, I came on the page "[Manage your locales](https://help.akeneo.com/pim/v3/articles/manage-your-locales.html)".

So I thought that I should set manually in the database the param. And I did...

Opened the table `pim_catalog_locale` and added a line with those params:

- `id`: autogenerated (1)
- `code`: `en_US`
- `is_activated`: `1`

## Result

Manually adding the default locale to the database, solved the issue.

# 2. The group doesn't exist

> [Akeneo\Tool\Component\StorageUtils\Exception\InvalidPropertyException (300)]    
>  Property "groups" expects a valid group. The group does not exist, "all" given.

## What I checked

I'm currently investigating the error: I think I need to create a default group somewhere...

I tried to reinstall the database, but without re-creating Elastic Search Indexes and fixtures.

The command `pim:installer:db`, in fact, tries to recreate the ElasticSearch indexes.

But I don't have Elastic Search installed and so the command failed.

Failing the command at the creation of indexes, it completely stops executing and doesn't do the other steps required to make the Akeneo installation working.

### Improvement

Specify in the documentation that the correct command to run is:

```console
$ pim:installer:db --withoutIndexes --withoutFixtures
```

NOTE: The creation of fixtures also causes some errors.

Then, specify that to create the indexes another command has to be run and for fixtures is the same.

## RESULT

This didn't solved the issue: I'm still not able to create a new User due to the absence of the default locale in the database (as explained above).

**Comment by Aerendir** [comment]
Ok, I solved the problem...

The problem was the command `pim:installer:db`.

The command, in fact, tries to recreate the ElasticSearch indexes.

But I don't have Elastic Search installed and so the command failed.

Failing the command at the creation of indexes, it completely stops executing and doesn't do the other steps required to make the Akeneo installation working.

# SOLUTION

Specify in the documentation that the correct command to run is:

```console
$ pim:installer:db --withoutIndexes --withoutFixtures
```

NOTE: The creation of fixtures also causes some errors.

Then, specify that to create the indexes another command has to be run and for fixtures is the same.

**Comment by Aerendir** [comment]
Ok, reading the system requirements, I saw there is ElasticSearch as required: I'm simply going to install it...

**Comment by chadwcarlson** [comment]
I'm running into the same issue - is adding the locale manually as @Aerendir suggests above still the best solution?

```bash
$ bin/console pim:user:create -n --admin admin XXXXX admin@example.com Admin Istrator en
19:16:40 CRITICAL  [console] Error thrown while running command "pim:user:create -n --admin admin 'XXXXX' 'admin@example.com' Admin Istrator en". Message: "There is no activated locale. The catalog default locale of the user must be an activated locale." ["exception" => InvalidArgumentException { …},"command" => "pim:user:create -n --admin admin 'XXXXX' 'admin@example.com' Admin Istrator en","message" => "There is no activated locale. The catalog default locale of the user must be an activated locale."]
```

**Comment by amirhmoradi** [comment]
Face the same issue, here is how it fixed it:

On my config, I was using MariaDB 10.6, but Akeneo is not compatible with MariaDB (I am surprised to find this!!)
I had to change my config to MySQL 8 and installation worked.
