### ISSUE TITLE
The route "acme_custom_index" does not exist.

### ISSUE THREAD

**Issue by davidverbeek** [akeneo/pim-community-dev#11233]
Hello All,

I tried to create a new page as per the documentation 

https://docs.akeneo.com/3.2/design_pim/guides/add_new_page.html

But it is giving me "The route "acme_custom_index" does not exist" error.

![route](https://user-images.githubusercontent.com/50629081/70714082-68e77100-1d0d-11ea-9d5f-778cd4543076.png)

Please let me know where I am doing wrong.

**Comment by Doodoune** [comment]
Hi @davidverbeek,

Akeneo is based on the framework Symfony. To add a routing file in your custom bundle, you have to add the routing in the main routing configuration.

Did you add the routing.yml in your file app/config/routing.yml?

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it if needed.

Regards,
