### ISSUE TITLE
BUG : When I create a Family with the code "rest" I get an ERROR

### ISSUE THREAD

**Issue by Thijzer** [akeneo/pim-community-dev#11245]
**I'm reporting a Bug**

This is a bug discovered in Akeneo 3.2 and I suspect every Akeneo release has this issue.
When I create a Family with the code **"rest"** I get an ERROR.

The bug was discovered last friday, the issue is located at the **route-matcher.js** file.
This code is responsible of finding a route match.
The problem in this case is that route matcher found 4 possible routes where the last one is the actual route.

What I think went wrong is the order of the route list, 
Symfony's order of routes is important when handling them but I think the ordering in javascript is not represented equally.

Maybe not all routes need to synced in js, could also be a solution.

**Comment by jmleroux** [comment]
Hello @Thijzer ,

I'm glad to tell you we have this issue on our maintenance board and we will fix it in our maintenance workflow.

Regards
