### ISSUE TITLE
Attribute code breaks the product model datagrid

### ISSUE THREAD

**Issue by excursions** [akeneo/pim-community-dev#11265]
**I'm reporting a Bug**

**Preconditions:**

1. Attribute as main image in family is at level 1
2. Attribute as main image's code starts with a number i.e. `2ndpic`

**Result:**
Root products grid not visible

**Expected Result:**
Root products grid is properly displayed

**Reason:**
[`a_image.code`](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php#L242) is parsed as a number instead of string

**Comment by valerie-schneider** [comment]
Hello there,

We are currently investigating this issue, thank you for sharing! 
We will keep you posted. 

Have a good day,
Valérie from the Support team.

**Comment by valerie-schneider** [comment]
Hi Julian, 

Sorry for my super late feedback, we solved this issue with the patch 3.2.27 - the issue was on the attribute codes of the images. 

Have a good day,
Valérie

**Comment by excursions** [comment]
Thank you, Valérie.
