### ISSUE TITLE
Upgrade documentation from 2.3 to 3.x is missing

### ISSUE THREAD

**Issue by duo-nv** [akeneo/pim-community-dev#11320]
According to the documentation, there is a guide to upgrade Akeneo 2.3 to 3.x
https://docs.akeneo.com/3.2/migrate_pim/upgrade_major_version.html#migrate-from-2-0-to-3-2
It links to these urls:
https://github.com/akeneo/pim-community-standard/blob/master/UPGRADE-3.0.md
https://github.com/akeneo/pim-community-standard/blob/master/UPGRADE-3.1.md
https://github.com/akeneo/pim-community-standard/blob/master/UPGRADE-3.2.md

However, I get a 404 on all of them.

**Comment by Doodoune** [comment]
Hi!

Nice catch! We already solve this error on the documentation so I closed this issue.
For the next time, do not hesitate to contribute with a PR in https://github.com/akeneo/pim-docs.

Regards,
