### ISSUE TITLE
Database issue during installation

### ISSUE THREAD

**Issue by aselam** [akeneo/pim-community-dev#11343]
Hello,

I'm trying to install PIM but i stumbled an issue. I followed this documentation: https://docs.akeneo.com/master/install_pim/manual/index.html

Everything went smoothly until I tried to install the database:

> $ php bin/console --env=prod pim:installer:db
> Prepare database schema
> Dropped database `akeneo_pim` for connection named default
> Created database `akeneo_pim` for connection named default
> 
>  !
>  ! [CAUTION] This operation should not be executed in a production environment!
>  !
> 
>  Creating database schema...
> 
> 21:29:41 ERROR     [console] Error thrown while running command "doctrine:schema:create --no-debug=1 --env=prod". Message: "Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE oro_config (id INT AUTO_INCREMENT NOT NULL, entity VARCHAR(255) DEFAULT NULL, record_id INT DEFAULT NULL, UNIQUE INDEX CONFIG_UQ_ENTITY (entity, record_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC':
> 
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes' while executing DDL: CREATE TABLE oro_config (id INT AUTO_INCREMENT NOT NULL, entity VARCHAR(255) DEFAULT NULL, record_id INT DEFAULT NULL, UNIQUE INDEX CONFIG_UQ_ENTITY (entity, record_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC" ["exception" => Doctrine\ORM\Tools\ToolsException { …},"command" => "doctrine:schema:create --no-debug=1 --env=prod","message" => """  Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE oro_config (id INT AUTO_INCREMENT NOT NULL, entity VARCHAR(255) DEFAULT NULL, record_id INT DEFAULT NULL, UNIQUE INDEX CONFIG_UQ_ENTITY (entity, record_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC':\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes' while executing DDL: CREATE TABLE oro_config (id INT AUTO_INCREMENT NOT NULL, entity VARCHAR(255) DEFAULT NULL, record_id INT DEFAULT NULL, UNIQUE INDEX CONFIG_UQ_ENTITY (entity, record_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC  """]
> 
> In AbstractMySQLDriver.php line 125:
> 
>   An exception occurred while executing 'CREATE TABLE oro_config (id INT AUTO_INCREMENT NOT NULL, entity VARCHAR(255) DEFAULT NULL, record_id INT DEFAULT NULL, UNIQUE INDEX CONFIG_UQ_ENTITY (entity, record_id
>   ), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC':
> 
>   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

I'm running the following versions:

> $ php --version
> PHP 7.3.13-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Dec 18 2019 14:48:49) ( NTS )

> $ mysql --version
> mysql  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Thanks in advance for your help.

**Comment by Doodoune** [comment]
Hi, 

What version did you try to install?

Did your server follow the according system requirements?

_SR for 3.2:_
https://docs.akeneo.com/3.2/install_pim/manual/system_requirements/system_requirements.html

_SR for 3.0:_
https://docs.akeneo.com/3.0/install_pim/manual/system_requirements/system_requirements.html

Regards,

**Comment by aselam** [comment]
Hello,

I think i pinpointed the issue, indirectly. As i just wanted to test, i replaced all encoding with utf8 (not utf8mb4) and stumbled upon another issue related to JSON datatype. Then I learned that MariaDB 10.1 doesn't have the same JSON datatype support as MySQL 5.7... 

I suppose my issue is related to MariaDB. I'll try again with the proper requirements in place.

Thanks
