### ISSUE TITLE
BUG: Product save in 3.2 sets wrong Content-type

### ISSUE THREAD

**Issue by cborup** [akeneo/pim-community-dev#11374]
**I'm reporting a Bug**

Frontend Bug. Found in 3.2.5 still there in 3.2.29.
Also reproducible on demo.akaneo.com. 

The ajax request generated when saving a product has a application/json payload. But is sendt with a content-type of application/x-www-form-urlencoded.

On platform.sh this is a problem because the load balancer there will do a sanity check on the request. The check will fail if the payload is larger than 4096 bytes because there is a limit on the length of individual keys.

In my case the request is POST'ed to /enrich/product/rest/1682. It will fail consistently if the payload is larger than 4096 bytes.

**Comment by Doodoune** [comment]
Hi @cborup,

Thanks for your contribution! :tada: 
I close this issue as your PR has been merged.

Have a nice day!
