### ISSUE TITLE
No version 4.0 found as per wiki instructions

### ISSUE THREAD

**Issue by simplenotezy** [akeneo/pim-community-dev#11397]
**I'm reporting a Bug**

In the documentation you write you need to run:

     php -d memory_limit=4G /usr/local/bin/composer create-project --prefer-dist \
    akeneo/pim-community-standard /srv/pim "4.0.*@stable"

But that doesn't work as there is no `4.0` stable release. Instead I believe you need to run

    php -d memory_limit=4G /usr/local/bin/composer create-project --prefer-dist \
    akeneo/pim-community-standard /srv/pim "3.*@stable"

**Comment by Doodoune** [comment]
@simplenotezy - Could you send us the link of the documentation concern?

Thanks!

**Comment by simplenotezy** [comment]
@Doodoune  https://github.com/akeneo/pim-community-standard

**Comment by Doodoune** [comment]
Okay, that's normal.
On the master branch, we are working on the new 4.0 that is not released yet :)

You could switch to a branch in a stable version like 3.2.

Regards,

**Comment by Doodoune** [comment]
I close this issue as our 4.0 was released and now it's available :)
