### ISSUE TITLE
Blank page on the install

### ISSUE THREAD

**Issue by florianvp** [akeneo/pim-community-dev#11428]
Hello,

I have following all the Akeneo's tutorial and requirements and I have a blank page on the web repertory.

There is my Apache logs : (an extract, this is the same error with differents pid)

[Fri Jan 17 11:00:53.787635 2020] [:error] [pid 21196] [client 92.184.117.143:40962] PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/html/akeneo/pim-community-standard/app/AppKernel.php on line 176

There is my  php -v  :

PHP 7.2.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec 18 2019 14:57:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.26-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Any idea ?

Thanks,

**Comment by Doodoune** [comment]
Hi @florianvp,
Did your system follow the requirements? https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_requirements.html

It seems that it doesn't like the ": string" but it's a standard of Php 7.2. Did you also have your Apache PHP in 7.2 version?
Regards,

**Comment by florianvp** [comment]
Hi @Doodoune,

Thank you so much for your reply.

It's true it came from here, I have found in issue few days ago.

Thanks,
Regards,
