### ISSUE TITLE
Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerLoader()

### ISSUE THREAD

**Issue by davidverbeek** [akeneo/pim-community-dev#11447]
Hello every one, I am trying to setup "job queue daemon" using supervisor as mention in below url 

https://docs.akeneo.com/3.2/install_pim/manual/daemon_queue.html#purpose-of-the-queue

Now when I tried to start the daemon process it giving me below error 

PHP Fatal error:  Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerLoader() must be an instance of Doctrine\Common\Annotations\void, none returned in /home/staginggyzs/domains/stagingakeneo.gyzs.nl/application/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:117
Stack trace:
#0 /home/staginggyzs/domains/stagingakeneo.gyzs.nl/application/app/autoload.php(13): Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(Array)
#1 /home/staginggyzs/domains/stagingakeneo.gyzs.nl/application/bin/console_cron(18): require('/home/staginggy...')
#2 {main}
  thrown in /home/staginggyzs/domains/stagingakeneo.gyzs.nl/application/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 117

when I run the akeneo from the browser it is working fine. This error is coming only when called from the supervisor. Below are the details

Akeneo Version :- 3.2
Php version : 7.2.2
Doctrine/annotation : v1.6.0
doctrine/orm :- v2.6.3
Supervisor configuration file :- 

[program:akeneo_queue_daemon]
command=/usr/local/bin/php /home/staging/domains/staging.test.nl/application/bin/console akeneo:batch:job-queue-consumer-daemon --env=prod
autostart=false
autorestart=true
stderr_logfile=/var/log/akeneo_daemon.err.log
stdout_logfile=/var/log/akeneo_daemon.out.log
user=staginguser

Please help me.

**Comment by jmleroux** [comment]
Hello @davidverbeek ,

COuld you please verify that you are running the same PHP version on web server (Apache or Nginx) and on CLI server. To do that, you can simply type `php -v` in the terminal.

**Comment by jmleroux** [comment]
Hello,

I will close this issue because there was no answer since 20 days. Feel free to reopen it if needed.

Regards
