### ISSUE TITLE
Product page throws console error "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by WebLenn** [akeneo/pim-community-dev#11470]
I have a fresh install of CE 3.2.33 and all worked fine until I added my attributes and changed the locale & currency for my channel.

After this change the product page no longer loads and throws a console error:

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at n.loadDataGrid (main.min.js?74d43ddddd9cad421a4d37f5be004b31:1)
    at u (vendor.min.js?74d43ddddd9cad421a4d37f5be004b31:1)
    at Object.fireWith [as resolveWith] (vendor.min.js?74d43ddddd9cad421a4d37f5be004b31:1)
    at F (vendor.min.js?74d43ddddd9cad421a4d37f5be004b31:1)
    at XMLHttpRequest.<anonymous> (vendor.min.js?74d43ddddd9cad421a4d37f5be004b31:1)
```

I tried changing the locale & currency settings back to default en_US & USD but this had no effect.
Any ideas why i'm encountering this issue and any possible fixes ?

**Comment by Doodoune** [comment]
Could you open your inspector and check on the newtwork tab what command failed?
![Screenshot from 2020-01-22 15-53-45](https://user-images.githubusercontent.com/34027529/72904582-6d04a680-3d2f-11ea-9c14-2f38d8bffe5a.png)

Did you have errors in your var/logs/prod.log?
Regards,

**Comment by WebLenn** [comment]
In the network tab there are no requests failing, but after looking at the logs with my hosting provider we discovered we were using MariaDB version that didn't support `JSON_ARRAYAGG`.

We'll switch to MySQL 5.7/5.8 to fix this issue, i'll close this ticket since this issue is most likely due to incorrect hosting config.

Thanks for the reply!
