### ISSUE TITLE
Problematic conversion of `convert` field of measure-families in REST API

### ISSUE THREAD

**Issue by cice** [akeneo/pim-community-dev#11477]
**I'm reporting a Bug**

I was just working with the REST API and looking at the response returned by https://api.akeneo.com/api-reference.html#measure_families_get etc. 
This endpoint returns the `convert` array as a (merged) JSON **object**. This is problematic, because conversions that rely on multiple steps (e.g. temperature), must be of course applied in proper order. A JSON **object**, though, is by definition unordered, and receiving the proper order is more or less coincidence.

Here's the relevant line:
https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Component/Api/Converter/MeasureFamilyConverter.php#L47

**Comment by jmleroux** [comment]
Hello @cice ,

Thanks for raising this issue. You are totally right, and we are currently working to fix it during Q1 2020.

Regards
