### ISSUE TITLE
Fix random tests/legacy/features/pim/enrichment/product/validation/remove_validation_error_on_correction.feature:21

### ISSUE THREAD

**Issue by fitn** [akeneo/pim-community-dev#11480]
Then I should not see validation tooltip "This value should not be a decimal.": Expecting to not see validation error, "This value should not be a decimal." found
Failed asserting that true is false.

https://circleci.com/gh/akeneo/pim-community-dev/26701#tests/containers/14

**Comment by ahocquard** [comment]
It's because the UI is not yet correctly refreshed after the save, so it checks there is no error message but it's still here because the save is not completely done.

Fixed here https://github.com/akeneo/pim-community-dev/pull/11517 (change order because the first check uses a spin).

**Comment by ahocquard** [comment]
Fixed.
