### ISSUE TITLE
Fix random: tests/legacy/features/pim/enrichment/product/datagrid/datagrid_views.feature:50

### ISSUE THREAD

**Issue by fitn** [akeneo/pim-community-dev#11481]
And I should see the text "Some shoes": Spin : timeout of 20 excedeed, with message : Cannot find the text "Some shoes" (Context\Spin\TimeoutException)

https://circleci.com/gh/akeneo/pim-community-dev/26721#tests/containers/1

**Comment by ahocquard** [comment]
After investigation, it's because we reach the timeout during the last "And I should see the text "Some shoes"".

The method to get the text takes too much time: 
```
    And I should see the text "Some shoes"                                  # Context\AssertionContext::assertPageContainsText()
      │ float(2.2598869800568)
      │ float(3.8870730400085)
      │ float(3.779876947403)
```

As we reduced the timeout... it's unstable.

**Comment by ahocquard** [comment]
Maybe fixed by incrementing the timeout...
