### ISSUE TITLE
ES indexing process using too much memory

### ISSUE THREAD

**Issue by stefandoorn** [akeneo/pim-community-dev#11525]
In Akeneo v3.1.x I run this on a model with about 20.000 products under it:

```
$ php bin/console pim:product-model:index product_model_here
1 product models found for indexing
    0 [>---------------------------]PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/AbstractProductValueNormalizer.php on line 46

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/AbstractProductValueNormalizer.php on line 46
```

Of course it's an option to put more memory to this box, but I also have the impression that there is a memory leak somewhere that makes this process rather inefficient. 

The product itself has about 10 attributes, the model around 40. Nothing customised, only the default Akeneo attributes are used.

Similar on this kind of models when I'm trying to import, it takes forever (100 products per hour), which might be a related issue.

In case it's interesting for debugging purposes, I can share in private more information about this set-up with around 180.000 products under around 300 models (with 150 parent models), self-hosted on K8S.

**Comment by ahocquard** [comment]
Hello,

Did you try with `--env=prod`? The development environment is set by default and it leaks (because logs are kept in memory).

**Comment by jmleroux** [comment]
Any news?

**Comment by jmleroux** [comment]
I close this ticket without answer since almost 30 days.
Feel free to reopen it if needed.

**Comment by stefandoorn** [comment]
Ah, sorry. Yes, it's running in prod environment with debug disabled. I'm doing that via my ENV vars inside the docker container, so don't have to provide it on the CLI anymore.
