### ISSUE TITLE
Increase upload max file size

### ISSUE THREAD

**Issue by dalarcia** [akeneo/pim-community-dev#11562]
Hi group!!

I'm testing the brand new Akeneo 4.0 using docker for the installation and I noticed that when I try to import a file bigger than 2MB, it gives up a flashing message:

**"Unable to upload the file. Its size may exceed the configured maximum upload size on your PHP or HTTP server configuration"**

I have tried to change the parameter upload_max_filesize = 20M in the php.ini file inside the fpm container under the folders:
/etc/php/7.3/fpm/
/etc/php/7.3/cli/

Then I run make up outside the container, in the pim folder but the error is still the same.

Any idea on what I'm doing wrong?

Best regards and thanks in advance!!

**Comment by Doodoune** [comment]
For the FPM config, it needs to restart fpm/apache to be taking into account (not for the cli). Did you restart it?

**Comment by dalarcia** [comment]
HI Doodoune.

You are right, same on me :-D

I'm guessing that if I take down the container this changes to the php.ini file will be gone, so maybe, I should create some dedicated volume for this?

Thank you very much.

**Comment by Doodoune** [comment]
You could change your docker.yml to auto add a php.ini with your modification to auto-add it when you are restarting your container.

I close this issue, feel free to reopen it if needed.

Regards,

**Comment by sachinPatolia** [comment]
I am getting the same issue I tried all   but it won't come with a solution please help me
