### ISSUE TITLE
GLOB_BRACE used in Kernel.php is not compatible with all Linux based OS's

### ISSUE THREAD

**Issue by oliverde8** [akeneo/pim-community-dev#11583]
**I'm reporting a Bug**

I am installing a Akeneo 4.0.5 on php 7.3.14 on a Alpine distribution and having the fallowing warning

```
Warning: use of undefined constant GLOB_BRACE
```
This is due to the usage of this constant in the [Kernel.php](https://github.com/akeneo/pim-community-dev/blob/4.0/std-build/Kernel.php#L115)

According to the PHP [documentation](https://www.php.net/manual/fr/function.glob.php)
> Note: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris.

The symfony load using the finder works perfectly as it has a workaround. So IMHO that should be used instead of using glob directly.

Regards,

**Comment by l-lotz** [comment]
In fact the braces could be removed altogether, as they only list one variant. "/{packages}/" is equivalent to "/packages/" as there is only the variant "packages". It would be a different story if it was "/{packages,}/" (notice the empty variant) or "/{packages,routes}/". Or is there some use for this that I am not aware of?

**Comment by jmleroux** [comment]
Interesting case. I will take some info.

**Comment by jmleroux** [comment]
We do not really support non GNU platforms, but in this case the flag is useless and that's why i made the PR.

**Comment by jmleroux** [comment]
Merged.
