### ISSUE TITLE
Category XLSX import

### ISSUE THREAD

**Issue by jacky-raimond** [akeneo/pim-community-dev#11592]
Hi,

When I try to import an XSLX file for the categories I'm seeing an error:

```
FAILED
File not found at path: category_import_xlsx/category.xlsx
```

This error occurs when I'm uploading the file, but also when it's on the server. Please let me know how we can fix this problem.

**Comment by jmleroux** [comment]
See #11593

**Comment by simonrl** [comment]
Hi @jacky-raimond 

did you solve it?
I'm running into the same error with categories and products.

Thanks
-- Simon
