### ISSUE TITLE
Akeneo V4 install error - Yarn EACCES

### ISSUE THREAD

**Issue by joaotnlima** [akeneo/pim-community-dev#11623]
**I'm reporting a Bug**

Running install of akeneo V4.
After composer successfully install deps I ran make dev and:

make dependencies
docker-compose run -u node --rm node yarn install
yarn install v1.21.1
error An unexpected error occurred: "EACCES: permission denied, mkdir '/home/node/.yarn/v6'".
info If you think this is a bug, please open a bug report with the information provided in "/srv/pim/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Makefile:21: recipe for target 'node_modules' failed
make[1]: *** [node_modules] Error 1
make[1]: Leaving directory '/****/akeneo'
Makefile:65: recipe for target 'dev' failed
make: *** [dev] Error 2

Docker Version
Docker version 19.03.6, build 369ce74a3c
Docker-Compose Version
docker-compose version 1.25.4, build 8d51620a

**Comment by aligent-lturner** [comment]
The `.yarn` folder is set up as a volume - by default using `~/.cache/yarn`, or `${HOST_YARN_CACHE_FOLDER}` if you've set it. Check the permissions on that folder.

**Comment by soestm** [comment]
@aligent-lturner I had the same issue. Changed the permissions of `~/.cache/yarn` . Now it works. Thanks!

**Comment by joaotnlima** [comment]
Hello, solved the issue with :z in the yarn cache folder:
'YARN_CACHE_FOLDER: '/home/node/.yarn:z

Thanks ;)

**Comment by Edweis** [comment]
Thanks, running `sudo chown ec2-user ~/.cache/yarn` fixed for me (ec2-user is the user running the command).

**Comment by oumaymaabdesslem** [comment]
sudo chown ec2-user ~/.cache/yarn , I didn't understand what ec2-user , does not work for me

**Comment by allenprado** [comment]
> sudo chown ec2-user ~/.cache/yarn , I didn't understand what ec2-user , does not work for me

Because you have to set your user in this "command", to get your user just run the command id,.

**Comment by benanianas** [comment]
`sudo chown -R "user" ~/.cache/yarn ` worked for me !

**Comment by dooblem** [comment]
I think this issue should be re-opened.

I had it with a fresh akeneo v5 install. When the ~/.cache/yarn directory do not exist, the docker volume mount creates the directory automatically, with root owner.

Then the yarn install crashes. However if you already have a ~/cache/yarn directory (created by yarn with the good ownership), the install is OK.

To reproduce:

1. Remove the ~/cache/yarn directory
2. composer create project (from https://docs.akeneo.com/5.0/install_pim/docker/installation_docker.html)
3. make dev (from https://docs.akeneo.com/5.0/install_pim/docker/installation_docker.html)

**Comment by bruno-teksial** [comment]
Remove this line
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/node/.yarn'

**Comment by Jars-of-jam-Scheduler** [comment]
> @aligent-lturner I had the same issue. Changed the permissions of `~/.cache/yarn` . Now it works. Thanks!

Is it a really good solution to type `sudo chown <the_user> ~/.cache/yarn` just to be able to use it as a Docker volume for the installation script of Akeneo? I don't think so, tell me if I'm wrong..

I don't see any solution more adequate in these GitHub issue's answers. @allenprado @Edweis , except perhaps the solution of @joaotnlima who seems to have defined the Yarn cache used by the setup script of Akeneo as a new directory instead of `~/cache/yarn`. Better solution indeed, I guess.

Please don't hesitate to correct me.

**Comment by joaotnlima** [comment]
Hello, been a while :)

Adding some more info found here: https://docs.docker.com/storage/bind-mounts/


![Screenshot 2022-06-30 at 22 57 36](https://user-images.githubusercontent.com/1760345/176785911-c6be8814-fcd3-486a-948c-0bb1b8af9db9.png)
