### ISSUE TITLE
Missing translation for Brightness measure family and units

### ISSUE THREAD

**Issue by m-kotowski** [akeneo/pim-community-dev#11672]
In https://github.com/akeneo/pim-community-dev/blob/4.0/src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml you added Brightness and its units.

In the translation files in folder https://github.com/akeneo/pim-community-dev/tree/4.0/src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations, corresponding entries are missing.

It would also be great to know how the structure will change with the next release because in master branch, I cannot find these files anymore. Instead it seems as if you use another approach to define the translations (https://github.com/akeneo/pim-community-dev/blob/73fbbbbaeef01200d79ae8b8e2ee2fde633b969d/src/Akeneo/Tool/Bundle/MeasureBundle/Installer/MeasurementInstaller.php)!?

Thank you in advance

**Comment by jmleroux** [comment]
Hello @m-kotowski ,

Thank you for raising this issue. I will see if we can handle it in maintenance.
Also, contributions are very welcome if you want :wink: 

Regards,
JM

**Comment by LaureBro** [comment]
Hello @m-kotowski, 
Yes, we are working on improving metrics/measurement management for our V5. 
Best,
