### ISSUE TITLE
Incorrect schema used for thumbnail image requests

### ISSUE THREAD

**Issue by RicardsRikmanis** [akeneo/pim-community-dev#11819]
Hello,

I'm using Akeneo CE 4.0.8 behind https termination proxy. All works well, but it seems that product thumbnail image URL requests are generated with http instead of https. This in turn trips the CSP which will block the request.

Temp solution for this is to rewrite CSP to be more lax, but this will still produce mixed content warnings and "Not Secure" messages.

**Comment by Trogie-Vynckier** [comment]
Same thing here: traefik.io as in front as https termination in a docker environment.

**Comment by xawill** [comment]
Same here. Any progress on this issue ?

**Comment by RicardsRikmanis** [comment]
Long time no see. It's seems this was just a case where the documentation for Akeneo failed to mention this. If we dig around Symfony docs we can find this part https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly

In any case, this can be resolved by adding `TRUSTED_PROXY_IPS=127.0.0.1,REMOTE_ADDR` to the `.env` file. Tested on fresh v5.0.53 Akeneo installation
