### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'AppKernel' not found

### ISSUE THREAD

**Issue by ddpete** [akeneo/pim-community-dev#11914]
During the final steps of an Akeneo upgrade using composer on Ubuntu 18.04 I get the following error:

> Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'AppKernel' not found in /var/www/akeneo/pim-community-standard/web/app.php:5\nStack trace:\n#0 {main}\n thrown in /var/www/akeneo/pim-community-standard/web/app.php on line 5\n'

In looking at line 5 in the app folder, it looks like AppKernel is called, but also has a line that is commented out. I'm not sure what it is looking for. I've changed the value to "true" but no luck.

use Symfony\Component\HttpFoundation\Request;

> require __DIR__.'/../vendor/autoload.php';
> $kernel = new AppKernel('prod', false);
> //$kernel = new AppCache($kernel);

**Comment by ddpete** [comment]
The error had nothing to do with the AppKernal.php file. Oddly enough this was solved by adding the following to the composer.json file:

> "require": {
>         "symfony/flex": "^1.0"
> },

**Comment by jmleroux** [comment]
Indeed it's stange, because requiring pim-community-dev implies the correct flex requirements, as you can see here: https://github.com/akeneo/pim-community-dev/blob/4.0/composer.json#L86

Anyway, i'm glad your problem is solved. :+1: 

Let's close this one.
