### ISSUE TITLE
Allowed memory size exhausted on classic csv products import

### ISSUE THREAD

**Issue by simoncarre** [akeneo/pim-community-dev#11929]
Hi!

I have memory issues during large csv products import:

```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8388608 bytes) in .../vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php on line 183
```

What is the tip for importing important CSV files? Do you have to manually cut the files?

PHP Version : 7.2.29
PHP Memory limit : 1024MB
Akeneo Version : CE 3.2.46

**Comment by jmleroux** [comment]
Hello @simoncarre ,

I see a `DebugClassLoader` reference. Are you working in prod mode?

**Comment by simoncarre** [comment]
Hello @jmleroux,

Thank you for quick response. I created a `preprod` environment which is a copy of the` prod` environment (copy of `app/config/config_prod.yml` to `app/config/config_preprod.yml`).
My queue command running is : `/usr/bin/php /var/www/my-project/current/bin/console akeneo:batch:job-queue-consumer-daemon --env=preprod --no-debug`

**Comment by jmleroux** [comment]
Is it possible to test in prod mode or do you have to much difference?

**Comment by simoncarre** [comment]
I tested in `prod` mode and it actually works without issues. Thank you!
I was missing the environment variable `SYMFONY_DEBUG` for the `preprod` environment :

File `bin/console` :
```
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(['--no-debug', '']) && $env !== 'prod' && false === $behat;
```
