### ISSUE TITLE
Null pointer exception on Product::getVariationLevel without a Parent

### ISSUE THREAD

**Issue by shavounet** [akeneo/pim-community-dev#12049]
Context
* Akeneo 2.3, but reproducible in above versions

# Description

I have some custom code that trigger `\Akeneo\Pim\Enrichment\Component\Product\EntityWithFamilyVariant\KeepOnlyValuesForVariation::updateEntitiesWithFamilyVariant` which himself trigger `\Akeneo\Pim\Enrichment\Component\Product\Model\EntityWithFamilyVariantInterface::getVariationLevel`.

When it encounters a product without a parent, it fails where it shouldn't due to the following error : `Call to a member function getVariationLevel() on null at vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Model/AbstractProduct.php:778`.

**Comment by shavounet** [comment]
Note : I think my test case is not great because it's still failing for other reasons... but my PR is still useful.

**Comment by jmleroux** [comment]
Fixed by #14367
