### ISSUE TITLE
How to create Families using csv import

### ISSUE THREAD

**Issue by mannydoaba** [akeneo/pim-community-dev#1218]
I was able to create Categories, Attributes and Attributes Options using CSV Import. but I don't see a way to import families

**Comment by shandyDev** [comment]
I implemented family import like I said above, but I got this error:
```
Neither the property "requirements" nor one of the methods "setRequirements()", "__set()" or "__call()" exist and have public access in class "Pim\Bundle\CatalogBundle\Entity\FamilyTranslation". 
```

Akeneo PIM v1.3.1
Used for batch job: 
         processor: pim_base_connector.processor.family
         writer:    pim_base_connector.writer.doctrine

**Comment by panploenes** [comment]
Im stuck there too.
