### ISSUE TITLE
Product media POST API : always returning a 422 error

### ISSUE THREAD

**Issue by radhikavm** [akeneo/pim-community-dev#12441]
Using Akeneo Bitnami instance: v3.2

I am trying to use the `http://hostname/api/rest/v1/media-files` API for upload images using node-fetch & `form-data`

The code I have is as follows: 

`let imgContents = fs.createReadStream('./images/image.jpg');
    let prodVal = JSON.stringify({"identifier":"9310047212283", "attribute":"Product_Image_Hero", "scope": null,"locale":null});
    let frmData = new FormData();
    frmData.append('file', imgContents, {filename: 'image.jpg','Content-Type': 'image/jpeg'});
    frmData.append('product', prodVal); `

`let url = 'http://hostname/api/rest/v1/media-files
    return fetch(url, {
        method: 'POST',
        headers: {
            'Authorization': 'Bearer ' + access_token,
            'Content-Type': 'multipart/form-data'
        },
        body: frmData
    });`

tried using  `axios` as well but the API is always returning the error as below:  

`{"code":422,"message":"You should at least give one of the following properties: \"product\" or \"product_model\"."}`

Can someone help with this error.

However using Postman this works perfectly fine.

**Comment by radhikavm** [comment]
Hi 
Closing this as I resolved it, the error was the header need content-length added to it. Once I added that it all works as expected.

**Comment by MPishpecki** [comment]
Would you be so kind as to post an example. No mater how we format the data for the 
endpoint http://hostname/api/rest/v1/media-files
we always get
{"code":422,"message":"You should at least give one of the following properties: \"product\" or \"product_model\"."}

The endpoint is so very poorly documented that its just a source of time waste for anyone using it.
