### ISSUE TITLE
Error when running webpack 

### ISSUE THREAD

**Issue by BramBeekman** [akeneo/pim-community-dev#12547]
:bug: **I'm reporting a Bug** :bug:

After installing Akeneo and i want to run webpack i get this error; 

ERROR in /data/web/akeneo/pim-community-standard/web/bundles/pimui/js/view/base.ts
./web/bundles/pimui/js/view/base.ts
[tsl] ERROR in /data/web/akeneo/pim-community-standard/web/bundles/pimui/js/view/base.ts(94,28)
      TS2538: Type 'undefined' cannot be used as an index type.
error Command failed with exit code 2.

**Comment by comanche76** [comment]
Hi,
today in our company we ran the same error.
Can you explain to me how you solved it?

Thank in advance!

**Comment by BramBeekman** [comment]
> Hi,
> today in our company we ran the same error.
> Can you explain to me how you solved it?
> 
> Thanks in advance!


Change: return this.extensions[extensionKey] to: return this.extensions[extensionKey!]

in file: /public/js/view/base.ts

**Comment by Olaf1989** [comment]
A pull request is already open to resolve this, see: https://github.com/akeneo/pim-community-dev/pull/12538
