### ISSUE TITLE
Migration from 3.2 -> 4.0 composer required --dev rector/rector 0.7.20

### ISSUE THREAD

**Issue by amitvkhajanchi** [akeneo/pim-community-dev#12575]
:bug: **I'm reporting a Bug** :bug:

using Akeneo v.4.0.49

In the instruction for the docs there is section on using rector/rector
https://docs.akeneo.com/4.0/migrate_pim/upgrade/upgrade_from_32_to_40.html

Since the article was written rector now has conflict with doctrine/annotation 1.8.0 used in Akeneo.
As result following command:  composer require --dev rector/rector will throw and error.
Replace this with: composer require --dev rector/rector 0.7.20 

Note:  0.7.20 is the last version using scan-fatal-errors command mentioned in above documentation.
           0.7.25 is the last version with compatibility with doctrine/annotation 1.8.0

**Comment by sylvainraye** [comment]
Thanks that helped me !

**Comment by cice** [comment]
> 🐛 **I'm reporting a Bug** 🐛
> 
> using Akeneo v.4.0.49
> 
> In the instruction for the docs there is section on using rector/rector
> https://docs.akeneo.com/4.0/migrate_pim/upgrade/upgrade_from_32_to_40.html
> 
> Since the article was written rector now has conflict with doctrine/annotation 1.8.0 used in Akeneo.
> As result following command: composer require --dev rector/rector will throw and error.
> Replace this with: composer require --dev rector/rector 0.7.20
> 
> Note: 0.7.20 is the last version using scan-fatal-errors command mentioned in above documentation.
> 0.7.25 is the last version with compatibility with doctrine/annotation 1.8.0

thanks, saved my life :)

**Comment by amitvkhajanchi** [comment]
Not active issue anymore as solution for above is already presented.
