### ISSUE TITLE
NumberFormat does a weird cutoff of leading zeros.

### ISSUE THREAD

**Issue by Thijzer** [akeneo/pim-community-dev#12578]
NumberFormat does a weird cutoff of leading zeros.

https://github.com/akeneo/pim-community-dev/blob/5018a160ec5b9dd634f0822f08d36d064afa15ef/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/ProductValueNormalizer.php#L148

```php
    function formatNumber($data)
    {
        $formattedNumber = number_format($data, 4, '.', '');
        return strlen($formattedNumber) >= strlen($data) ? $formattedNumber : rtrim($data, '0');
    }

$number='15.000000000'; # value prior to decimal change from 10 to 4
echo formatNumber($number);

# result "15." as a decimal value
```

**Comment by pierallard** [comment]
Thanks for your bug report!
It has been fixed here
https://github.com/akeneo/pim-community-dev/pull/12841
