### ISSUE TITLE
Being able to query product/models by their identifiers/codes via tha API

### ISSUE THREAD

**Issue by jjanvier** [akeneo/pim-community-dev#12637]
Asking for a friend :p 

Hello Akeneo, 

I hope you're all going well :) 

I have a list of products and product models I'd like to retrieve from Akeneo API. I know only their code/identifier. And I can't get them directly via the  GET  `/api/rest/v1/products` or `/api/rest/v1/product-models` endpoints :(

Indeed those endpoints do not allow me to search on `identifier` or on `code`, which seems to be a base need. I have to use unitary endpoints (``/api/rest/v1/products/{identifier}`) instead, which will increase the load on the server.

Is this enhancement in the roadmap?

**Comment by jjanvier** [comment]
FYI, I also opened a ticket here https://github.com/akeneo/api-php-client/issues/188...

**Comment by pierrejolly** [comment]
Hello Julien,

Currently you can filter by `identifier` like this : `/api/rest/v1/products?search={"identifier":[{"operator":"IN","value":["1111111171", "13620748"]}]}`

**Comment by jjanvier** [comment]
Ah thanks. 
On product models, the identifier property is called "code", not "identifier". So I tried 

```php
        $productModels = $this->apiClientFactory->getClient()->getProductModelApi()->all(
            50,
            ['search' => ['code' => [['operator' => 'IN', 'value' => $akeneoProductModelIds]]]]
        );
```

which doesn't work

**Comment by jjanvier** [comment]
I think it would be good do explicitly list all the properties in https://api.akeneo.com/documentation/filter.html#filter-on-product-properties.

And same for product models.

Thanks for the help anyway :)

**Comment by timonburkard** [comment]
I agree, it is misleading. I tried filtering for 'code' first as well.
