### ISSUE TITLE
Webpack extensions bug

### ISSUE THREAD

**Issue by SSMellow** [akeneo/pim-community-dev#12692]
:bug: **I'm reporting a Bug** :bug:

Hi,

Akeneo version - Akeneo 2.3.36
I faced an issue while running `yarn run webpack` - 

 `ERROR in /home/project/src/web/bundles/pimenrich/js/view/base.ts(94,28)
      TS2538: Type 'undefined' cannot be used as an index type.`

Found out that you need to fix `base.ts` or require `@types/underscore` (https://github.com/akeneo/pim-community-dev/issues/12547), but:

1. It is not possible to override base.ts, because webpack first of all compiles it and then it fails so if I override it via requirejs.yml it will compile it anyway and error will be thrown.

2. To require `@types/underscore` you need a TypeScript version `>=3.1`. Current bundle version only supports typescript `^2.7.2` so it is not possible to require any higher version above 3.1, because check-requirements anyway will install any below this one.

Suggestion:

- Create a patch and update typescript to "typescript": "3.5.1", because Akeneo works with it like a charm, everything works as expected.

**Comment by SSMellow** [comment]
Fixed by pushing `yarn.lock` into repository from another project with same package.json versions. But I think the bug is still relevant.

**Comment by Doodoune** [comment]
Hi! 

I closed this issue as we already fixed this issue on the last version of 2.3. The field package.json has been updated regarding "@types/underscore" :) 

Best regards,
Elodie

**Comment by prakharsaxena2** [comment]
I just noticed that the download link for getting the latest version is getting an archive with akeneo 2.3.28  instead of 2.3 latest one , could this be related?
