### ISSUE TITLE
ERROR in node_modules/@types/babel__traverse/index.d.ts file

### ISSUE THREAD

**Issue by damiankryger** [akeneo/pim-community-dev#12703]
Hi! Today we encountered a bug on version 3.2.66. We tried also update to the latest version (3.2.69). The bug is related to the `/srv/pim/node_modules/@types/babel__traverse/index.d.ts` file. Below I put a fragment of the error message (because the original one is to big to paste it here).

```
ERROR in /srv/pim/node_modules/@types/babel__traverse/index.d.ts
[tsl] ERROR in /srv/pim/node_modules/@types/babel__traverse/index.d.ts(1137,37)
      TS1005: ';' expected.

ERROR in /srv/pim/node_modules/@types/babel__traverse/index.d.ts
[tsl] ERROR in /srv/pim/node_modules/@types/babel__traverse/index.d.ts(1137,43)
      TS1109: Expression expected.

ERROR in /srv/pim/node_modules/@types/babel__traverse/index.d.ts
[tsl] ERROR in /srv/pim/node_modules/@types/babel__traverse/index.d.ts(1139,1)
      TS1128: Declaration or statement expected.
```

Has anybody the same issue? I need to resolve it as soon as possible because it blocks our team.

I will be very grateful for help.

**Comment by jmleroux** [comment]
Thank you for raising an issue, alas it has been raised just before in #12698 :wink: 

We will work on it

**Comment by damiankryger** [comment]
@jmleroux Thank you for your quick response. But are you sure that this issue the same like the mentioned by you?
