### ISSUE TITLE
Duplicate keys in yaml files

### ISSUE THREAD

**Issue by fmeyertoens** [akeneo/pim-community-dev#12704]
:bug: **I'm reporting a Bug** :bug:

In yaml all keys of a node have to be unique. This is not the case in the following two files:

1. Duplicate key: `readOnly`
https://github.com/akeneo/pim-community-dev/blob/9b46c11fa43c3283ec184f27b6d14eff6fa3eeb0/src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml#L104-L109

1. Duplicate key: `pim-job-instance-csv-product-model-export-edit-validation`
https://github.com/akeneo/pim-community-dev/blob/77afae35cfa2ceb3e9add69021e11f38a7ecf295/src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml#L237
https://github.com/akeneo/pim-community-dev/blob/77afae35cfa2ceb3e9add69021e11f38a7ecf295/src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml#L285

**Comment by pierallard** [comment]
Thanks for reporting this issue!
This has been fixed in master branch.
