### ISSUE TITLE
Importing Price Field Issue

### ISSUE THREAD

**Issue by wyamout** [akeneo/pim-community-dev#12830]
Getting this error when trying to import prices from a CSV file

In PriceCollectionValueFactory.php line 126:

  Argument 1 passed to Akeneo\Pim\Enrichment\Component\Product\Factory\Value\
  PriceCollectionValueFactory::sortByCurrency() must be of the type array, st
  ring given, called in /var/www/akeneo/vendor/akeneo/pim-community-dev/src/A
  keneo/Pim/Enrichment/Component/Product/Factory/Value/PriceCollectionValueFa
  ctory.php on line 23

**Comment by pierallard** [comment]
Hi @wyamout !
Thanks for reporting this bug.
Can you share us the CSV file you're trying to import please ?

**Comment by wyamout** [comment]
@pierallard turn out the header was missing the currency. Closing this issue my bad.
