### ISSUE TITLE
Bug with patch 3.2.71 when i run webpack

### ISSUE THREAD

**Issue by FouedSmile** [akeneo/pim-community-dev#12840]
In the last command for installation of akeneo , i shared with you this bug when i run wepback:

ERROR in /var/www/html/akeneo/pim-community-standard/web/bundles/pimdatagrid/js/datagrid/column-selector.ts
./web/bundles/pimdatagrid/js/datagrid/column-selector.ts
[tsl] ERROR in /var/www/html/akeneo/pim-community-standard/web/bundles/pimdatagrid/js/datagrid/column-selector.ts(466,5)
      TS2322: Type 'Partial<{ [name: string]: Column; }>' is not assignable to type '{ [name: string]: Column; }'.
  Index signatures are incompatible.
    Type 'Column | undefined' is not assignable to type 'Column'.
      Type 'undefined' is not assignable to type 'Column'.

ERROR in /var/www/html/akeneo/pim-community-standard/web/bundles/pimui/js/view/base.ts
./web/bundles/pimui/js/view/base.ts
[tsl] ERROR in /var/www/html/akeneo/pim-community-standard/web/bundles/pimui/js/view/base.ts(94,28)
      TS2538: Type 'undefined' cannot be used as an index type.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any idée how to resolve it ?

**Comment by pierallard** [comment]
This is the same issue than this one
https://github.com/akeneo/pim-community-dev/issues/12698
I close this issue to avoid duplicate :)
