### ISSUE TITLE
Sample data installation with error

### ISSUE THREAD

**Issue by bartoll** [akeneo/pim-community-dev#12947]
:bug: **I'm reporting a Bug** :bug:

I would like to install sample data in my akeneo pim.

I run a command:

<pre>php bin/console pim:installer:db --catalog vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev</pre>

and get an error as below

<pre>22:20:05 <font color="#C4A000">ERROR    </font> <font color="#C4A000">[batch]</font> Encountered an error executing the step: An exception occurred while executing &apos;WITH locale_specific_codes AS (
    SELECT attribute_locale.attribute_id, JSON_ARRAYAGG(locale.code) AS locale_codes
    FROM pim_catalog_attribute_locale attribute_locale
    INNER JOIN pim_catalog_locale locale ON attribute_locale.locale_id = locale.id
    GROUP BY attribute_locale.attribute_id
)
SELECT attribute.code,
       attribute.attribute_type,
       attribute.properties,
       attribute.is_scopable,
       attribute.is_localizable,
       attribute.metric_family,
       attribute.decimals_allowed,
       attribute.backend_type,
       COALESCE(locale_codes, JSON_ARRAY()) AS available_locale_codes
FROM pim_catalog_attribute attribute
    LEFT JOIN locale_specific_codes on attribute.id = attribute_id    
WHERE code IN (?)&apos; with params [&quot;brand&quot;]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &apos;locale_specific_codes AS (
    SELECT attribute_locale.attribute_id, JSON_ARRAYA&apos; at line 1
</pre>

What is the problem? Am I doing something wrong?

**Comment by teemuvaltonen** [comment]
I have the same problem. Using PHP 7.2.33 and MySql 5.7.30 and running those via MAMP Pro

**Comment by akosglue** [comment]
which akeneo and mysql version?

**Comment by teemuvaltonen** [comment]
Akeneo PIM 4.0 CE
And I am using the newest MAMP Pro, which is 6.0.1. And MySql is 5.7.30, which comes with the MAMP.

I also tried to install the newest Akeneo PIM with the docker and that went ok.

**Comment by ReggieTe** [comment]
Try upgrading to mysql 8.0  ,looks like *WITH* is not supported in 5.7
https://dev.mysql.com/doc/refman/8.0/en/with.html

**Comment by bartoll** [comment]
@ReggieTe thank you. Your suggestion gives it works :+1:
