### ISSUE TITLE
Export, disable generate zip file

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#13216]
Hello, I use the export model produced in csv format to automate the export of certain fields and media from the command line to then reprocess the csv file in python to import it into another database and transfer the media files with rsync on another server. The problem is that this export is trying to create a zip file containing the media when I don't need it.

Is there a possibility to change this behavior or to apply the export model by disabling the creation of the zip file?

Thank you in advance.

**Comment by StevenVAIDIE** [comment]
Hello Philippe, 

Yes, you can disabled it by disable the option "Export files and images" in the "Global settings" tab of the product export profile
![Capture du 2021-01-20 09-09-52](https://user-images.githubusercontent.com/7239572/105145658-54c09680-5aff-11eb-97da-3bb13765ff19.png)
