### ISSUE TITLE
Error while saving product family

### ISSUE THREAD

**Issue by pkraeutli** [akeneo/pim-community-dev#13711]
When trying to save a Family, an error message is displayed and changes are not persisted.

![Screenshot 2021-01-12 at 20 16 28](https://user-images.githubusercontent.com/886082/104361723-1e898280-5513-11eb-9ec9-38dbb9aafdd6.png)

Log shows the following error:

```
[2021-01-12 20:16:24] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO pim_catalog_family_translation (label, locale, foreign_key) VALUES (?, ?, ?)' with params ["Standard", "de_CH", 2]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'de_CH-2' for key 'locale_foreign_key_idx'" at /[REDACTED]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 74 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO pim_catalog_family_translation (label, locale, foreign_key) VALUES (?, ?, ?)' with params [\"Standard\", \"de_CH\", 2]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'de_CH-2' for key 'locale_foreign_key_idx' at /home/astina/apps/bime-pim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:74, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'de_CH-2' for key 'locale_foreign_key_idx' at /home/astina/apps/bime-pim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'de_CH-2' for key 'locale_foreign_key_idx' at /[REDACTED]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141)"} []
```

So there is an SQL error:
```
INSERT INTO pim_catalog_family_translation (label, locale, foreign_key) VALUES (?, ?, ?)' 
with params ["Standard", "de_CH", 2]:  
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'de_CH-2' for key 'locale_foreign_key_idx'
```

When I delete the rows with foreign_key=2 from `pim_catalog_family_translation` I can save the form, but after that the error occurs again.

*System information*
[akeneo-pim-system-info_2021-01-12_20_15.txt](https://github.com/akeneo/pim-community-dev/files/5804289/akeneo-pim-system-info_2021-01-12_20_15.txt)

**Comment by colin-lansbergen** [comment]
I've got the exact same issue. We are on 3.2.78 (not on 3.2.80 yet).

**Comment by nocturnalfrog** [comment]
Same here: Version:CE 3.2.76 Rabbit Transit

**Comment by colin-lansbergen** [comment]
We fixed it by reindexing the elastic-search!

**Comment by pkraeutli** [comment]
@colin-lansbergen which command did you use?

```
akeneo:elasticsearch:reset-indexes      Resets all registered ES indexes
pim:product-model:index                 Index all or some product models into Elasticsearch
pim:product:index                       Index all or some products into Elasticsearch
```

**Comment by pkraeutli** [comment]
OK I did `bin/console pim:product:index --all` and now I can save product families without errors. Thanks @colin-lansbergen !

**Comment by nocturnalfrog** [comment]
I tried the command but the error still persists.

**Comment by pkraeutli** [comment]
@nocturnalfrog I also did `akeneo:elasticsearch:reset-indexes` beforehand

**Comment by nocturnalfrog** [comment]
I tried that command too but that command fails with 'The parameter "elasticsearch_indexing_commands" must be defined.'...
----

[apache@www3 pim-community-standard]$ bin/console akeneo:elasticsearch:reset-indexes --env=prod  -vvv 
This action will entirely reset the following indexes in the PIM:
novolab_akeneo_pim_product
novolab_akeneo_pim_product_model
novolab_akeneo_pim_product_and_product_model
Are you sure you want to proceed ? (Y/n)y
Resetting the index: novolab_akeneo_pim_product
Resetting the index: novolab_akeneo_pim_product_model
Resetting the index: novolab_akeneo_pim_product_and_product_model

All the indexes have been successfully reset!

You can now use the following commands to manually re-index the entities you want:
16:33:05 ERROR     [console] Error thrown while running command "akeneo:elasticsearch:reset-indexes --env=prod -vvv". Message: "The parameter "elasticsearch_indexing_commands" must be defined."
[
  "exception" => Symfony\Component\DependencyInjection\Exception\InvalidArgumentException {
    #message: "The parameter "elasticsearch_indexing_commands" must be defined."
    #code: 0
    #file: "./var/cache/prod/Container0xslxse/appProdProjectContainer.php"
    #line: 6797
    trace: {
      ./var/cache/prod/Container0xslxse/appProdProjectContainer.php:6797 {
        › if (!(isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || array_key_exists($name, $this->parameters))) {
        ›     throw new InvalidArgumentException(sprintf('The parameter "%s" must be defined.', $name));
        › }
      }
      ./vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php:181 { …}
      ./vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php:56 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1000 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:255 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148 { …}
      ./bin/console:36 { …}
    }
  },
  "command" => "akeneo:elasticsearch:reset-indexes --env=prod -vvv",
  "message" => "The parameter "elasticsearch_indexing_commands" must be defined."
]
16:33:05 DEBUG     [console] Command "akeneo:elasticsearch:reset-indexes --env=prod -vvv" exited with code "1"
[
  "command" => "akeneo:elasticsearch:reset-indexes --env=prod -vvv",
  "code" => 1
]

In appProdProjectContainer.php line 6797:
                                                                              
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The parameter "elasticsearch_indexing_commands" must be defined.            
                                                                              

Exception trace:
  at /var/www/html/novolab.pimpark.be/pim-community-standard/var/cache/prod/Container0xslxse/appProdProjectContainer.php:6797
 Container0xslxse\appProdProjectContainer->getParameter() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php:181
 Akeneo\Tool\Bundle\ElasticsearchBundle\Command\ResetIndexesCommand->showSuccessMessages() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php:56
 Akeneo\Tool\Bundle\ElasticsearchBundle\Command\ResetIndexesCommand->execute() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/novolab.pimpark.be/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/novolab.pimpark.be/pim-community-standard/bin/console:36

akeneo:elasticsearch:reset-indexes [-1|--reset-indexes] [-i|--index INDEX] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
