### ISSUE TITLE
Using EventDispatcherInterface in CleanRemovedAttributesFromProductAndProductModelCommand in Akeneo 4.*

### ISSUE THREAD

**Issue by wimulkeman** [akeneo/pim-community-dev#13795]
The following error occures in Akeneo > 4.0.74 when the `event_dispatcher` service is decorated or replaced and thereby no using the EventDispatcher class.

```
 It for Argument 6 passed to Akeneo\Pim\Enrichment\Bundle\Command\CleanRemovedAttributesFromProductAndProductModelCommand::__construct() must be an instance of Symfony\Component\EventDispatcher\EventDispatcher, instance of Symfony\Comp  
  onent\HttpKernel\Debug\TraceableEventDispatcher given,
```

In the file CleanRemovedAttributesFromProductAndProductModelCommand as a 6sth argument the EventDispatcher class is used (introduced in Akeneo 4.0.75 https://github.com/akeneo/pim-community-dev/commit/a481642b5087a5a68477728bbc15e347acb7332f#diff-f59419c149acd6ae76560cd097cca0e3673a78adb436be18c9307fe4c9694faa).

Because the class is used instead of the interface this implementation will break as soon as the `event_dispatcher` service is decorated. The decoration happens when you include the `symfony/stopwatch` bundle (which is done by the `symplify/easy-coding-standard` for example).

The solution is to use the EventDispatcherInterface as is already done for Akeneo 5.0.1 https://github.com/akeneo/pim-community-dev/commit/1983acb4ad0fbdcc76156d182f23856f242291cf.

**Comment by wimulkeman** [comment]
If I can help by creating a pull request, please let me now.

**Comment by tseho** [comment]
will be fixed by https://github.com/akeneo/pim-community-dev/pull/13787

**Comment by wimulkeman** [comment]
Thanks for the fix
