### ISSUE TITLE
Cannot login in Akeneo with default credentials

### ISSUE THREAD

**Issue by sagarparker** [akeneo/pim-community-dev#14259]
I am not able to login into Akeneo community edition 4.0 with default credentials.

![Screenshot from 2021-04-14 11-23-07](https://user-images.githubusercontent.com/32793769/114660965-cf224080-9d13-11eb-936d-ee3de1ed58cb.png)

**Comment by pierrejolly** [comment]
Are you sure the user exist in db ? Try to create a new one with `bin/console pim:user:create`

**Comment by sagarparker** [comment]
Thanks
