### ISSUE TITLE
Dependency errors

### ISSUE THREAD

**Issue by allenprado** [akeneo/pim-community-dev#14308]
Hi everyone I am getting some dependency error, I am trying to set Akeneo Community Standard on Ubuntu 10.20 NO Docker.
The terminal details are below:

root@ubuntu:/srv/pim# NO_DOCKER=true make pim-prod
make cache
make[1]: Entering directory '/srv/pim'
rm -rf var/cache && php bin/console cache:warmup

 // Warming up the cache for the prod environment with debug false                                                      

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.                                           
                                                                                                                        

make[1]: Leaving directory '/srv/pim'
make assets
make[1]: Entering directory '/srv/pim'
rm -rf public/bundles public/js
php bin/console pim:installer:assets --symlink --clean
Akeneo PIM assets
Dumping exposed routes.

[file+] /srv/pim/src/../public/js/routes.js

 Installing assets as hard copies.

 --- ------------------------------------ ---------------- 
      Bundle                               Method / Error  
 --- ------------------------------------ ---------------- 
  ✔   FOSJsRoutingBundle                   copy            
  ✔   OroConfigBundle                      copy            
  ✔   AkeneoMeasureBundle                  copy            
  ✔   PimUserBundle                        copy            
  ✔   AkeneoPimEnrichmentBundle            copy            
  ✔   AkeneoPimStructureBundle             copy            
  ✔   PimAnalyticsBundle                   copy            
  ✔   PimDashboardBundle                   copy            
  ✔   PimDataGridBundle                    copy            
  ✔   PimImportExportBundle                copy            
  ✔   PimNotificationBundle                copy            
  ✔   PimUIBundle                          copy            
  ✔   AkeneoConnectivityConnectionBundle   copy            
  ✔   AkeneoCommunicationChannelBundle     copy            
  ✔   AkeneoDataQualityInsightsBundle      copy            
 --- ------------------------------------ ---------------- 

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.  

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           
                                                                                                                        

Generating require.js main config
08:16:35 [file+] ca_ES.js
08:16:35 [file+] da_DK.js
08:16:35 [file+] de_DE.js
08:16:35 [file+] en_AU.js
08:16:35 [file+] en_GB.js
08:16:35 [file+] en_NZ.js
08:16:35 [file+] en_US.js
08:16:35 [file+] es_ES.js
08:16:35 [file+] fi_FI.js
08:16:35 [file+] fr_FR.js
08:16:35 [file+] hr_HR.js
08:16:35 [file+] it_IT.js
08:16:35 [file+] ja_JP.js
08:16:35 [file+] ko_KR.js
08:16:35 [file+] nl_NL.js
08:16:36 [file+] pl_PL.js
08:16:36 [file+] pt_BR.js
08:16:36 [file+] pt_PT.js
08:16:36 [file+] ru_RU.js
08:16:36 [file+] sv_SE.js
08:16:36 [file+] sv_SE.js
08:16:36 [file+] tl_PH.js
08:16:36 [file+] zh_CN.js

 Trying to install assets as relative symbolic links.

 --- ------------------------------------ ------------------ 
      Bundle                               Method / Error    
 --- ------------------------------------ ------------------ 
  ✔   FOSJsRoutingBundle                   relative symlink  
  ✔   OroConfigBundle                      relative symlink  
  ✔   AkeneoMeasureBundle                  relative symlink  
  ✔   PimUserBundle                        relative symlink  
  ✔   AkeneoPimEnrichmentBundle            relative symlink  
  ✔   AkeneoPimStructureBundle             relative symlink  
  ✔   PimAnalyticsBundle                   relative symlink  
  ✔   PimDashboardBundle                   relative symlink  
  ✔   PimDataGridBundle                    relative symlink  
  ✔   PimImportExportBundle                relative symlink  
  ✔   PimNotificationBundle                relative symlink  
  ✔   PimUIBundle                          relative symlink  
  ✔   AkeneoConnectivityConnectionBundle   relative symlink  
  ✔   AkeneoCommunicationChannelBundle     relative symlink  
  ✔   AkeneoDataQualityInsightsBundle      relative symlink  
 --- ------------------------------------ ------------------ 

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           
                                                                                                                        

make[1]: Leaving directory '/srv/pim'
make dsm
make[1]: Entering directory '/srv/pim'
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 yarnpkg --cwd=vendor/akeneo/pim-community-dev/akeneo-design-system install --frozen-lockfile
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.87s.
yarnpkg --cwd=vendor/akeneo/pim-community-dev/akeneo-design-system run lib:build
yarn run v1.22.5
$ tsc -p ./tsconfig.build.json
Done in 2.85s.
make[1]: Leaving directory '/srv/pim'
make javascript-prod
make[1]: Entering directory '/srv/pim'
rm -rf public/dist
yarnpkg run webpack
yarn run v1.22.5
$ yarn requirements && yarn generate-models && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
$ node $npm_package_config_source/frontend/build/check-requirements.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'colors'
Require stack:
- /srv/pim/vendor/akeneo/pim-community-dev/frontend/build/check-requirements.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/srv/pim/vendor/akeneo/pim-community-dev/frontend/build/check-requirements.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/srv/pim/vendor/akeneo/pim-community-dev/frontend/build/check-requirements.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[1]: *** [Makefile:45: javascript-prod] Error 1
make[1]: Leaving directory '/srv/pim'
make: *** [Makefile:91: pim-prod] Error 2

**Comment by mmetayer** [comment]
Hello @allenprado, as stated in [the documentation](https://docs.akeneo.com/master/install_pim/manual/installation_ce.html#launching-the-pim-in-prod-mode), the right command to install the PIM from scratch is 
```console
NO_DOCKER=true make prod
```

In your case, it looks like you simply miss the front dependencies, so you can go with
```console
NO_DOCKER=true make node_modules
NO_DOCKER=true make pim-prod
```

**Comment by allenprado** [comment]
Tomorrow when I come back to my job I will test it and let you know, thank you very much anyway!

**Comment by allenprado** [comment]
Hi, Did exactly that you said and I am getting now:

In StaticNoPingConnectionPool.php line 64:
                                        
  No alive nodes found in your cluster  
                                       
make[1]: Leaving directory '/srv/pim'
root@ubuntu:/srv/pim#

**Comment by mmetayer** [comment]
Hello again @allenprado, please make sure you followed all the steps in https://docs.akeneo.com/master/install_pim/manual/installation_ce.html#launching-the-pim-in-prod-mode, and that you meet the requirements for running the PIM (https://docs.akeneo.com/master/install_pim/manual/system_requirements/system_requirements.html)
In your case it seems you didn't configure the env variable for your Elasticsearch server (e.g `APP_INDEX_HOSTS='localhost:9200'`)

**Comment by allenprado** [comment]
Sorry to bother you but I've followed all the step with no error, and my .env is in /srv/pim/.env:

# DON'T EDIT THIS FILE !
# IT COULD BE OVERWRITTEN DURING THE LAST UPDATE
# You must use .env.local to overload ENV VARs
env file:

APP_ENV=prod
APP_DEBUG=0
APP_DATABASE_HOST=localhost
APP_DATABASE_PORT=null
APP_DATABASE_NAME=akeneo_pim
APP_DATABASE_USER=akeneo_pim
APP_DATABASE_PASSWORD=akeneo_pim
APP_DEFAULT_LOCALE=en
APP_SECRET=ThisTokenIsNotSoSecretChangeIt
APP_INDEX_HOSTS=elasticsearch:9200
APP_PRODUCT_AND_PRODUCT_MODEL_INDEX_NAME=akeneo_pim_product_and_product_model
APP_CONNECTION_ERROR_INDEX_NAME=akeneo_connectivity_connection_error
MAILER_URL=null://localhost?encryption=tls&auth_mode=login&username=foo&password=>
AKENEO_PIM_URL=http://localhost:8080
APP_ELASTICSEARCH_TOTAL_FIELDS_LIMIT=10000
FLAG_QUANTIFIED_ASSOCIATION_ENABLED=1
COMM_PANEL_API_URL=https://pim-comm-panel.akeneo.com

**Comment by allenprado** [comment]
Hi sorry to bother you, I've fixed the .env and now when I run the command (NO_DOCKER=true make pim-prod or NO_DOCKER=true make prod), I get the return below but the localhost:8080 is not accessible.

root@ubuntu:/srv/pim# NO_DOCKER=true make prod
make dependencies
make[1]: Entering directory '/srv/pim'
php -d memory_limit=4G /usr/local/bin/composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/doctrine-cache-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
76 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json

Synchronizing package.json with PHP packages
Don't forget to run npm install --force or yarn install --force to refresh your JavaScript dependencies!
> bash vendor/akeneo/pim-community-dev/std-build/install-required-files.sh
src/ directory already exists. Not preparing the directory content.
make[1]: Leaving directory '/srv/pim'
make pim-prod
make[1]: Entering directory '/srv/pim'
make cache
make[2]: Entering directory '/srv/pim'
rm -rf var/cache && php bin/console cache:warmup

 // Warming up the cache for the prod environment with debug                      
 // false                                                                         

                                                                                  
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.     
                                                                                  

make[2]: Leaving directory '/srv/pim'
make assets
make[2]: Entering directory '/srv/pim'
rm -rf public/bundles public/js
php bin/console pim:installer:assets --symlink --clean
Akeneo PIM assets
Dumping exposed routes.

[file+] /srv/pim/src/../public/js/routes.js

 Installing assets as hard copies.

 --- ------------------------------------ ---------------- 
      Bundle                               Method / Error  
 --- ------------------------------------ ---------------- 
  ✔   FOSJsRoutingBundle                   copy            
  ✔   OroConfigBundle                      copy            
  ✔   AkeneoMeasureBundle                  copy            
  ✔   PimUserBundle                        copy            
  ✔   AkeneoPimEnrichmentBundle            copy            
  ✔   AkeneoPimStructureBundle             copy            
  ✔   PimAnalyticsBundle                   copy            
  ✔   PimDashboardBundle                   copy            
  ✔   PimDataGridBundle                    copy            
  ✔   PimImportExportBundle                copy            
  ✔   PimNotificationBundle                copy            
  ✔   PimUIBundle                          copy            
  ✔   AkeneoConnectivityConnectionBundle   copy            
  ✔   AkeneoCommunicationChannelBundle     copy            
  ✔   AkeneoDataQualityInsightsBundle      copy            
 --- ------------------------------------ ---------------- 

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets
 !        you have to run this command again.                                     

                                                                                  
 [OK] All assets were successfully installed.                                     
                                                                                  

Generating require.js main config
15:16:07 [file+] ca_ES.js
15:16:07 [file+] da_DK.js
15:16:07 [file+] de_DE.js
15:16:08 [file+] en_AU.js
15:16:08 [file+] en_GB.js
15:16:08 [file+] en_NZ.js
15:16:08 [file+] en_US.js
15:16:08 [file+] es_ES.js
15:16:08 [file+] fi_FI.js
15:16:08 [file+] fr_FR.js
15:16:08 [file+] hr_HR.js
15:16:08 [file+] it_IT.js
15:16:08 [file+] ja_JP.js
15:16:08 [file+] ko_KR.js
15:16:08 [file+] nl_NL.js
15:16:09 [file+] pl_PL.js
15:16:09 [file+] pt_BR.js
15:16:09 [file+] pt_PT.js
15:16:09 [file+] ru_RU.js
15:16:09 [file+] sv_SE.js
15:16:09 [file+] sv_SE.js
15:16:09 [file+] tl_PH.js
15:16:09 [file+] zh_CN.js

 Trying to install assets as relative symbolic links.

 --- ------------------------------------ ------------------ 
      Bundle                               Method / Error    
 --- ------------------------------------ ------------------ 
  ✔   FOSJsRoutingBundle                   relative symlink  
  ✔   OroConfigBundle                      relative symlink  
  ✔   AkeneoMeasureBundle                  relative symlink  
  ✔   PimUserBundle                        relative symlink  
  ✔   AkeneoPimEnrichmentBundle            relative symlink  
  ✔   AkeneoPimStructureBundle             relative symlink  
  ✔   PimAnalyticsBundle                   relative symlink  
  ✔   PimDashboardBundle                   relative symlink  
  ✔   PimDataGridBundle                    relative symlink  
  ✔   PimImportExportBundle                relative symlink  
  ✔   PimNotificationBundle                relative symlink  
  ✔   PimUIBundle                          relative symlink  
  ✔   AkeneoConnectivityConnectionBundle   relative symlink  
  ✔   AkeneoCommunicationChannelBundle     relative symlink  
  ✔   AkeneoDataQualityInsightsBundle      relative symlink  
 --- ------------------------------------ ------------------ 

                                                                                  
 [OK] All assets were successfully installed.                                     
                                                                                  

make[2]: Leaving directory '/srv/pim'
make dsm
make[2]: Entering directory '/srv/pim'
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 yarnpkg --cwd=vendor/akeneo/pim-community-dev/akeneo-design-system install --frozen-lockfile
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 2.06s.
yarnpkg --cwd=vendor/akeneo/pim-community-dev/akeneo-design-system run lib:build
yarn run v1.22.5
$ tsc -p ./tsconfig.build.json
Done in 3.98s.
make[2]: Leaving directory '/srv/pim'
make javascript-prod
make[2]: Entering directory '/srv/pim'
rm -rf public/dist
yarnpkg run webpack
yarn run v1.22.5
$ yarn requirements && yarn generate-models && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
$ node $npm_package_config_source/frontend/build/check-requirements.js
Checking PIM frontend requirements
$ yarn --cwd=node_modules/@akeneo-pim-community/communication-channel generate-models
$ node $npm_package_config_generate_models_script src/definitions/ src/models/
Starting webpack from /srv/pim in prod mode 
Version: webpack 4.44.2
Time: 30808ms
Built at: 04/21/2021 3:16:51 PM
                                      Asset       Size  Chunks                    Chunk Names
assets/41db83c1c1d72900f79ef0cf71bb0937.svg  573 bytes          [emitted]         
assets/669652e3db73e445544c39e1d428e100.svg   1.48 KiB          [emitted]         
assets/75daeed2d5f5d8530728812ebaa79be1.svg   3.28 KiB          [emitted]         
assets/8ee3c1d9360c6111af2705453022a4bb.svg  678 bytes          [emitted]         
assets/93b575e6d38167ac3865176e1e7d2603.svg   63.8 KiB          [emitted]         
assets/999aefd96c0c9c7b25d9c72feaf1c600.svg     94 KiB          [emitted]         
assets/b75ec1b84575fa845fee0859388959b9.svg    116 KiB          [emitted]         
assets/ba39fecef75f6f7493df78d1aae3e303.svg    137 KiB          [emitted]         
                                main.min.js   1.67 MiB       0  [emitted]  [big]  main
                              vendor.min.js   6.12 MiB       1  [emitted]  [big]  vendor
Entrypoint main [big] = vendor.min.js main.min.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  main.min.js (1.67 MiB)
  vendor.min.js (6.12 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (7.79 MiB)
      vendor.min.js
      main.min.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Done in 34.50s.
make[2]: Leaving directory '/srv/pim'
make css
make[2]: Entering directory '/srv/pim'
rm -rf public/css
yarnpkg run less
yarn run v1.22.5
$ node $npm_package_config_styles

Starting LESS compilation

‣ vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Bundle/Resources/public/less/index.less
‣ vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimDataGridBundle/Resources/public/less/index.less
‣ vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
‣ vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/less/index.less
‣ vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/public/less/index.less
‣ vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/index.less


✓ Saved CSS to public/css/pim.css
Done in 2.79s.
make[2]: Leaving directory '/srv/pim'
make javascript-extensions
make[2]: Entering directory '/srv/pim'
yarnpkg run update-extensions
yarn run v1.22.5
$ node $npm_package_config_source/frontend/build/update-extensions.js
Updating form extensions.json
Done in 1.24s.
make[2]: Leaving directory '/srv/pim'
APP_ENV=prod make database O="--catalog vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal"
make[2]: Entering directory '/srv/pim'
php bin/console pim:installer:db --catalog vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal
Prepare database schema
Dropped database `akeneo_pim` for connection named default
Created database `akeneo_pim` for connection named default

 !                                                                                
 ! [CAUTION] This operation should not be executed in a production environment!   
 !                                                                                

 Creating database schema...

                                                                                  
 [OK] Database schema created successfully!                                       
                                                                                  


 Updating database schema...

     3 queries were executed

                                                                                  
 [OK] Database schema updated successfully!                                       
                                                                                  

Reset elasticsearch indexes
Create session table
Create configuration table
Create messenger table
Load jobs for fixtures. (data set: vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal)
Fixtures fixtures_currency_csv has been successfully executed.
Fixtures fixtures_locale_csv has been successfully executed.
Fixtures fixtures_user_group_csv has been successfully executed.
Fixtures fixtures_category_csv has been successfully executed.
Fixtures fixtures_attribute_group_csv has been successfully executed.
Fixtures fixtures_group_type_csv has been successfully executed.
Fixtures fixtures_attribute_csv has been successfully executed.
Fixtures fixtures_channel_csv has been successfully executed.
Fixtures fixtures_association_type_csv has been successfully executed.
Fixtures fixtures_attribute_options_csv has been successfully executed.
Fixtures fixtures_family_csv has been successfully executed.
Fixtures fixtures_job_yml has been successfully executed.
Fixtures fixtures_family_variant_csv has been successfully executed.
Fixtures fixtures_group_csv has been successfully executed.
Fixtures fixtures_user_role_csv has been successfully executed.
Fixtures fixtures_user_csv has been successfully executed.
Fixtures fixtures_product_model_csv has been successfully executed.
Fixtures fixtures_product_csv has been successfully executed.

Delete jobs for fixtures.
Versioning is already up to date.
make[2]: Leaving directory '/srv/pim'
make[1]: Leaving directory '/srv/pim'
root@ubuntu:/srv/pim# ^C
root@ubuntu:/srv/pim#

**Comment by mmetayer** [comment]
You now need to configure your web server, as described in https://docs.akeneo.com/5.0/install_pim/manual/system_requirements/system_install_ubuntu_2004.html#system-installation please make sure you've followed all the described steps :slightly_smiling_face:. Also, I advise you against using the `root` user to install the PIM (for instance Apache will likely need write permissions on ceratian directories for the `www-data` user, see https://symfony.com/doc/current/setup/file_permissions.html)
I'm going to close this issue now, as it is not code-related and the install went well, but feel free to join our [slack user group](http://akeneopim-ug.herokuapp.com/) or post a question on [stackoverflow](https://stackoverflow.com/questions/tagged/akeneo) to get further help

**Comment by allenprado** [comment]
Thank you very much
