### ISSUE TITLE
The EntityManager is closed

### ISSUE THREAD

**Issue by apoorvAkeo** [akeneo/pim-community-dev#14855]
:bug: **I'm reporting a Bug** :bug:

Please update to the last available patch for the version.

For version >= 1.4, please go to "System > system info", download the text report and attach it to the issue.

Then explain the expected behavior, the encountered behavior and the steps to reproduce.

Please note that we do offer support only in a "_best effort_" mode without any engagment on the resolution time.

:wrench: **I'm submitting a Feature Request** :wrench:

Explain the use case and the expected behavior. We will consider it and submit to the Core team.

:question: **I'm asking a Question** :question:

I am exporting products sheets then getting error and stop the execution of products exportation. error is "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'code' at row 1". here i am attaching a screenshot below.
![Screenshot_51](https://user-images.githubusercontent.com/86642708/123735661-3c7a5200-d8bd-11eb-93a7-f323d2a7340f.png)

:paperclip: **I'm using the Enterprise Edition** :paperclip:

Please use your access to our support service desk.

**Comment by mmetayer** [comment]
Hello @apoorvAkeo, the `wk_woocommerce_data_mapping` table is not part of the PIM, so this issue cannot be qualified nor fixed on our side. I suppose you are using the akeneo woocommerce connector, I advise you to get support from the connector's maintainers [here](https://marketplace.akeneo.com/extension/woocommerce-akeneo-connector/get-support).
