### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted

### ISSUE THREAD

**Issue by aloksinha3110** [akeneo/pim-community-dev#15276]
[root@pm pim]# docker run -ti -u www-data --rm     -v $(pwd):/srv/pim -v ~/.composer:/var/www/.composer -w /srv/pim     akeneo/pim-php-dev:5.0 php /usr/local/bin/composer create-project     akeneo/pim-community-standard /srv/pim "5.0.*@stable"
Creating a "akeneo/pim-community-standard" project at "./"
Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.cache/composer/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Installing akeneo/pim-community-standard (v5.0.46)
  - Downloading akeneo/pim-community-standard (v5.0.46)
  - Installing akeneo/pim-community-standard (v5.0.46): Extracting archive
Created project in /srv/pim
Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.cache/composer/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 655360 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Decisions.php on line 202
PhpErr:
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 655360 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Decisions.php on line 202

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**[root@pm pim]# php -r "echo ini_get('memory_limit').PHP_EOL;"
2048M
[root@pm pim]#**

**Comment by Doodoune** [comment]
Hi @aloksinha3110,

You have a permission issue on the directory  /var/www/.cache or /var/www/.cache/composer - please check the permissions on this directory 
```Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable.```.

**Comment by aloksinha3110** [comment]
how to give permission?

**Comment by Doodoune** [comment]
With chmod  / chown commands

**Comment by aloksinha3110** [comment]
I set 777 and owner is root but still showing error

**Comment by Doodoune** [comment]
It should be another user than root... because composer isn't launched with root access

**Comment by aloksinha3110** [comment]
docker run -ti -u www-data --rm \
    -v $(pwd):/srv/pim -v ~/.composer:/var/www/.composer -w /srv/pim \
    akeneo/pim-php-dev:4.0 php -d memory_limit=4G /usr/local/bin/composer create-project \
    akeneo/pim-community-standard /srv/pim "4.0.*@stable"
    
    
    I am running this cmd

**Comment by Doodoune** [comment]
So your composer directory should have the user "www-data" to be writable by your command
