### ISSUE TITLE
Quick export: Link "Download generated files" missing

### ISSUE THREAD

**Issue by ibs83278** [akeneo/pim-community-dev#16409]
Hello,
after upgrading from Akeneo CE version 5 to 6 the product´s quick export feature still works and the files are generated under /tmp... directory. But in the GUI, the link "**Download generated files**" is missing at the top right corner when I look at the export´s report. 
It is a fresh installation with Ubuntu 20.04, I reinstalled the assets, cleared cache an so on. No success. Can anybody confirm this behaviour?
Thanks.

**Comment by timonburkard** [comment]
Did you check if the quick export is configured to export the media files as well?

![image](https://user-images.githubusercontent.com/54314495/156831805-6c20383b-32f0-44d3-b542-fc5ea5252697.png)

**Comment by ibs83278** [comment]
> Did you check if the quick export is configured to export the media files as well?
> 
> ![image](https://user-images.githubusercontent.com/54314495/156831805-6c20383b-32f0-44d3-b542-fc5ea5252697.png)

I tried both "With media" and "Without media", this doesn´t make any difference.
But thank you anyway!

**Comment by timonburkard** [comment]
I don't have a v6 environment at hand, so I can't reproduce, sorry.

**Comment by timonburkard** [comment]
In the meantime I have a v6 environment at hand and tried to reproduce your issue with the following config:
![image](https://user-images.githubusercontent.com/54314495/162997869-3d61bbeb-f2d2-4567-9a0d-f2572796cb14.png)

Which gives me on the top right corner the following options:
![image](https://user-images.githubusercontent.com/54314495/162997680-8f517991-774c-4290-b680-1e2d3547466d.png)

I get a zip-file which contains all the media files of the corresponding product in the directory "files":
![image](https://user-images.githubusercontent.com/54314495/162997821-b5b7a136-b9d3-4baa-be7e-324fdf15c642.png)

**Comment by ibs83278** [comment]
Thank you very much for testing, so in your environment everything works as expected. Strange, I have 2 quite different installations, in both of them the "Download" button at the top right corner is missing.

![akeneo6_missing_downloadlink](https://user-images.githubusercontent.com/69475130/163391404-d103810f-2efb-4d40-bcc8-1ddef3e4cf60.jpg)

But anyway now I know that is seems not to be a bug but an issue on my system.

**Comment by timonburkard** [comment]
Maybe this helps? https://github.com/akeneo/pim-community-dev/issues/9616

**Comment by ibs83278** [comment]
> Maybe this helps? #9616

Thank you very very much! This brought me on the right way. Checked the directories var/file_storage and below, these directories had no write permissions. So going into 'var' directory and executing
`find file_storage/ -type d -exec chmod 755 {} +`
`find file_storage/ -type f -exec chmod 644 {} +`
resolved my issue as you can see here, the blue download button now is at the top right corner:
![akeneo6_missing_downloadlink_resolved](https://user-images.githubusercontent.com/69475130/163567095-104de84a-85cf-4470-b4ec-dc5e202f937d.jpg)

Thanks again an have a nice weekend!

**Comment by timonburkard** [comment]
Happy to heat that. You too!

**Comment by stevelou2** [comment]
I had same problem of missing the download button, then found the var/file_storage folder owner was root instead of www-data.
Changed owner and verified permission, fixed.
