### ISSUE TITLE
Extra slash in file path when importing zip files

### ISSUE THREAD

**Issue by ajmnz** [akeneo/pim-community-dev#16969]
:bug: **I'm reporting a Bug** :bug:

### Description

When importing products with the built-in CSV connector and using compressed files, the resolved path to the contents is incorrectly built, including an extra slash.

Given a zip file that looks like the following:

```
products.zip
 |   data.csv
 └── images
      |  product-image-1.jpg
      |  product-image-2.jpg
      |  ...
```

With the CSV having the product image defined as

```
sku;img
123;images/product-image-1.jpg
```

Always outputs the same error, due to an extra slash being added after the job's temp directory.

```
Property "img" expects a valid pathname as data, "/tmp/akeneo_batch_6278c35e90aa8//test-akeneo/images/product-image-1.jpg" given.
                                                                                ~~~
                                                                                 ^
```

### Cause

After further digging, the error seems to come from `Akeneo/Tool/Bundle/ConnectorBundle/EventListener/FetchRemoteFileBeforeImport.php`

https://github.com/akeneo/pim-community-dev/blob/8270399503b7123ca896e7d558aeb8ffd8ef91df/src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/FetchRemoteFileBeforeImport.php#L59

If we remove `DIRECTORY_SEPARATOR`, everything seems to work again.

---

Since it doesn't seem like this specific class is used anywhere else, I'd be willing to open a PR to address this issue.

Related #12602

**Comment by agghanim** [comment]
issue still persists in v7.0 while using local import (not tested with upload)

**Comment by fmeyertoens** [comment]
I'm running into the same problem. Can you explain how or when this was fixed?

**Comment by ajmnz** [comment]
> I'm running into the same problem. Can you explain how or when this was fixed?

I don't remember, to be fair, I think I made a quick script to upload them via API. Sorry I can't be of any help

**Comment by Talae** [comment]
I'm working with the CE 6.0.90 version.
I have the same problem, I  use an xlsx or csv and picture loaded by ftp
I made the modification to supress the //, but the problem still the same.
Property "IMAGE_1" expects a valid pathname as data, "/tmp/akeneo_batch_64c0d2dfdc614/files/41557/IMAGE_1/voiture-porteur-vintage-bleu-petrole.jpg" given.
If I  use the xls and compressed file, no warning, I see the name of the picture in the field , but the picture is not load and if I try to download , file not found.

I have to manage 57 000 products...... I 'm blocked 
If any one has a solution ?
