### ISSUE TITLE
Data Flows - Inbound - products created/updated - empty chart

### ISSUE THREAD

**Issue by Przemnowa** [akeneo/pim-community-dev#16967]
Hi, 
Akeneo 6.0.25 - I have problem with display created/updated chart in data source connection. 
![obraz](https://user-images.githubusercontent.com/94534760/167243370-613ff883-5979-4b3c-8d3e-1f3c19f12118.png)

Errors are displayed OK:
![obraz](https://user-images.githubusercontent.com/94534760/167243397-712924a6-5a50-4e3b-bf27-ad300954c67d.png)

**Comment by timonburkard** [comment]
@Przemnowa did you set the [flow type](https://help.akeneo.com/pim/serenity/articles/manage-your-connections.html#choose-your-flow-type) of your connection to "Source connection"?

**Comment by timonburkard** [comment]
@Przemnowa and you are actually updating or creating **products** with this connection? (product-models are not displayed, only products)

**Comment by Przemnowa** [comment]
@timonburkard  Yes, I use [api-php-client](https://github.com/akeneo/api-php-client) to connect with PIM. Errors are displayed OK:
![obraz](https://user-images.githubusercontent.com/94534760/170028067-e080e7a7-b349-43f1-81a8-cfccf516918f.png)

The problem is when I add or update products.

**Comment by timonburkard** [comment]
@Przemnowa when connection to the PIM, are you using the dedicated **connection user** or are you using a **UI user**?

**Comment by Przemnowa** [comment]
@timonburkard Thank you for your time! Maybe something is wrong with server configuration? But strange is that errors working fine :)

**Comment by timonburkard** [comment]
I am not too experienced with server configurations, honestly.

The function call looks fine. And as you said the products get updated correctly in the PIM I don't think it is related to `usertList()`. But if you'd like me to take a more detailed look at this part, I might help if you provide the definition of `$products`.

**Comment by Przemnowa** [comment]
Thank you! 


`/**
         * Array with converted data SAP to Akeneo
         */
        $products[] =
            [
                'identifier' => $product->{'ean'},
                'family' => 'books',
                'values' => [
                    // Main data
                    'name' => [
                        [
                            'data' => $product->{'name'},
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                    'alternative_name' => [
                        [
                            'data' => $product->{'alternative_name'},
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                    'product_type' => [
                        [
                            'data' => productTypeAttributeMapping($product->{'Kod'}),
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                    // Price data
                    'price' => [
                        [
                            'data' => [
                                [
                                    'amount' => $product->{'price'},
                                    'currency' => 'PLN',
                                ],
                            ],
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                    'cennik_usd' => [
                        [
                            'data' => strval($product->{'cennik_usd'}),
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                    'cennik_eur' => [
                        [
                            'data' => strval($product->{'cennik_eur'}),
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                    'tax_class_id' => [
                        [
                            'data' => vatIdAttributeMapping($product->{'stawka_vat'}),
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                    // Visibility data
                    'Widoczne_B2B' => [
                        [
                            'data' => visibilityAttributeMapping($product->{'widoczneb2b'}),
                            'locale' => null,
                            'scope' => null,
                        ],
                    ],
                ],
            ];`

**Comment by timonburkard** [comment]
I notice you don't have any product values in your PIM. Are you sure the update of the products via API works?

**Comment by kaur58** [comment]
You can try and run php bin/console akeneo:connectivity-audit:update-data

**Comment by Przemnowa** [comment]
> You can try and run php bin/console akeneo:connectivity-audit:update-data

It works! What's doing this instruction?
I have to run this instruction in evry time, when I want refresh data?
![obraz](https://user-images.githubusercontent.com/94534760/181005016-e5b64081-0320-4d51-a51d-f06a4c492040.png)

**Comment by kaur58** [comment]
I haven't dug to deep into yet but yes it seems like ju need to add this command to CRON
