### ISSUE TITLE
Failed to launch the job profile. Make sure it is valid and that you have right to launch it.

### ISSUE THREAD

**Issue by aloksinha3110** [akeneo/pim-community-dev#17379]
I am getting an error of **"Failed to launch the job profile. Make sure it is valid and that you have the right to launch it."**

I am using v6.0

<img width="1335" alt="Screenshot 2022-07-04 at 3 52 03 PM" src="https://user-images.githubusercontent.com/59638727/177135886-8d6b2d70-4858-46ed-a9e9-d450d3ccd34d.png">

**Comment by aloksinha3110** [comment]
```
php bin/console akeneo:batch:job csv_import
14:12:45 CRITICAL  [console] Error thrown while running command "akeneo:batch:job csv_import". Message: "Could not find job instance "csv_import"." ["exception" => InvalidArgumentException { …},"command" => "akeneo:batch:job csv_import","message" => "Could not find job instance "csv_import"."]
```

**Comment by timonburkard** [comment]
Hi @aloksinha3110,

Did you configure a valid path on the server?

![image](https://user-images.githubusercontent.com/54314495/181018942-262599e4-3536-473e-830d-e2e4e18684cf.png)

Alternatively, you can choose "UPLOAD A FILE" instead of "IMPORT NOW" and upload a file by drag and drop.

**Comment by aloksinha3110** [comment]
I am getting an error of 
`[2022-08-05 04:05:53] console.CRITICAL: Error thrown while running command "console 'messenger:consume' ui_job import_export_job data_maintenance_job --env=prod -vv". Message: "Command "console" is not defined." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"console\" is not defined. at /var/www/html/akeneov6/pim-community-standard/vendor/symfony/console/Application.php:718)","command":"console 'messenger:consume' ui_job import_export_job data_maintenance_job --env=prod -vv","message":"Command \"console\" is not defined."} []`
