### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by grzech1991** [akeneo/pim-community-dev#17641]
Hi

I have a problem with install. After use `make prod` i see error:

Error: EACCES: permission denied, mkdir '/home/node/.cypress/6.9.1'

----------

Platform: linux (Debian - 10)
Cypress Version: 6.9.1
The Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at

https://github.com/cypress-io/cypress/issues

----------

Error: EACCES: permission denied, mkdir '/home/node/.cypress/6.9.1'

I use debian 11, clean install for akeneo. Any one can help me?

**Comment by rsoulard-prolaser** [comment]
Hi,

I had the same problem.
The directory "~/.cache/Cypress" did not have the right user rights.

**Comment by grzech1991** [comment]
Thank you, after use chmod 777 is working :)
