### ISSUE TITLE
[Question] Overriding css

### ISSUE THREAD

**Issue by aRn0D** [akeneo/pim-community-dev#1839]
Hi there,
I wanted to change the pim colors. I created my own variable.less with my custom colors. I put it in my bundle which extends the PimUIBundle but nothing changed... Snif... Does overriding assets work same as template ? Thus I needed to override pim.less for including my variable.less

Is it the right way? I ask this question because with this solution I had to copy paste the whole of the pim.less in my bundle... 

Thanks

**Comment by chicodasilva** [comment]
Hi there,

I am trying to acomplish the same goal. Is this a problem with bootstrap?

Regards,
Francisco

**Comment by jmleroux** [comment]
Closed as there is a similar resolevd topic on the forum : http://www.akeneo.com/forums/topic/custom-ui/
