### ISSUE TITLE
Fixtures - using csv and/or yml

### ISSUE THREAD

**Issue by BatsaxIV** [akeneo/pim-community-dev#1878]
Hi,

Following the document for creating new fixtures (http://docs.akeneo.com/1.2/cookbook/setup_data/customize_installer.html#add-your-own-data), it's written that *All fixtures can be created in CSV or YAML* ; but it's natively impossible (I suppose) to insert a specific fixture in a different format that the one defined in **fixtures_jobs.yml**  (_InstallerBundle/Resources/config/_).

Unless overriding **fixtures_jobs.yml**, is there something plan to insert fixtures in csv or yml ?
Like this :

    fixtures_attribute_options_yml:
        order: 50
        connector: Data fixtures
        alias:     fixtures_attribute_options_yml
        label:     Attribute options data fixtures
        type:      fixtures
        configuration:
            filePath: attribute_options.yml
            multiple: false

    #NEW
    fixtures_attribute_options_csv:
        order: 51
        connector: Data fixtures
        alias:     fixtures_attribute_options_csv
        label:     Attribute options data fixtures
        type:      fixtures
        configuration:
            filePath: attribute_options.csv
            multiple: false
    #END NEW

    fixtures_family_yml:
        order: 60
        connector: Data fixtures
        alias:     fixtures_family_yml
        label:     Families data fixtures
        type:      fixtures
        configuration:
            filePath: families.yml
            multiple: false

Thanks,
Jérémy.

**Comment by panploenes** [comment]
Is there any answer on this? Just try to load fixtures from csv files but they wont get used.
