### ISSUE TITLE
Fresh Install issue

### ISSUE THREAD

**Issue by vlad-dc** [akeneo/pim-community-dev#18923]
Hello,

I have a trouble with a fresh install, after:
docker run -ti -u www-data --rm -e COMPOSER_MEMORY_LIMIT=2G -v $(pwd):/srv/pim -v ~/.composer:/var/www/.composer -w /srv/pim akeneo/pim-php-dev:6.0 php /usr/local/bin/composer create-project akeneo/pim-community-standard /srv/pim "6.0.*@stable"

I have the next output:
symfony/flex contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "symfony/flex" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
Creating a "akeneo/pim-community-standard" project at "./"

In CreateProjectCommand.php line 371:

  Project directory "/srv/pim" is not empty.

=========
and with:
docker run -u www-data -v $(pwd):/srv/pim -w /srv/pim --rm akeneo/pim-php-dev:8.1 \
     php /usr/local/bin/composer create-project --prefer-dist \
     akeneo/pim-community-standard /srv/pim "dev-master@dev"

I have the next message:

Status: Downloaded newer image for akeneo/pim-php-dev:8.1
Creating a "akeneo/pim-community-standard" project at "./"
Info from https://repo.packagist.org: #StandWithUkraine
Installing akeneo/pim-community-standard (dev-master d1e20eeaf8bbcd4bfd08737596a04087e5ce68b5)
    Failed to download akeneo/pim-community-standard from dist: /srv/pim/vendor/composer does not exist and could not be created.
    Now trying to download from source
  - Syncing akeneo/pim-community-standard (dev-master d1e20ee) into cache
  - Installing akeneo/pim-community-standard (dev-master d1e20ee): Cloning d1e20eeaf8 from cache
    Install of akeneo/pim-community-standard failed

In Filesystem.php line 314:
  Could not delete /srv/pim:

=========
Debian 10.13
docker-compose version 1.25.3
docker version
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:20 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:12 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

How can i solve this?

Regards.

**Comment by vlad-dc** [comment]
Solved with permission settings.

**Comment by vijayrana-99** [comment]
@vlad-dc can you please explain how you solved it? I am facing the same issue
