### ISSUE TITLE
docker compose && make down after this akeneo get 500 error code

### ISSUE THREAD

**Issue by eroxunn** [akeneo/pim-community-dev#18991]
Hello,
can someone explain me how to propertly shutdown the docker compose stack because, after i make the installation from guide 

like 
`docker run -ti -u www-data --rm \
    -e COMPOSER_MEMORY_LIMIT=4G \
    -v $(pwd):/srv/pim -v ~/.composer:/var/www/.composer -v ~/.ssh:/var/www/.ssh -w /srv/pim \
    akeneo/pim-php-dev:6^C php /usr/local/bin/composer install
`
and then i do 
make dev or make prod 

after this my docker-compose stack is up and running - but if i do docker-compose down to shutdown and then docker-compose up -d 
and go to mysite:8080 i get 500 error page..

what i need to change or do to make this stack working?

thanks!

**Comment by Abraxas-365** [comment]
you need to run "make down" to stop and socker compose up -d to start

**Comment by LevFlavien** [comment]
After a successful setup with `make up`, use `docker-compose stop` and `start` instead of down/up.

**Comment by LevFlavien** [comment]
The MySQL database because it is not stored in a volume, so removing the container with `docker-composer down` will also remove the database itself. Otherwise you'll need to build it again with [this kind of command](https://github.com/akeneo/pim-community-dev/blob/master/Makefile#L157).
