### ISSUE TITLE
Unable to search for products in the API on parent when using the operator =

### ISSUE THREAD

**Issue by andrew-smart** [akeneo/pim-community-dev#19084]
:bug: **I'm reporting a Bug** :bug:

Currently using version 6.0.66

Since version 6.0.65 it looks like you can no longer find products using the following search parameter;
`{{url}}/api/rest/v1/products?search={"parent":[{"operator":"=","value":"some_top_level_model"}]}`

This is the postman response;

`{
    "code": 422,
    "message": "Filter on property \"parent\" is not supported or does not support operator \"=\""
}`

The following commit seems to stop you doing that; https://github.com/akeneo/pim-community-dev/commit/71bc8d538b6a71651cf3e529c3477415ee0049ac

As per the documentation (https://api.akeneo.com/documentation/filter.html#on-their-parent) we use this to fetch child products using the root product model code.

**Comment by MystikReasons** [comment]
I'm experiencing the same issue after updating past version 6.0.65
And I can also confirm that the pull request which was mentioned above causes the issue.

**Comment by chpnt** [comment]
Hi, this shall be resolved with patch v6.0.69 :)

**Comment by andrew-smart** [comment]
Thanks @chpnt 
This has fixed the issue reported.
