### ISSUE TITLE
Invalid Doctrine mapping

### ISSUE THREAD

**Issue by ramon-nijman-webstores** [akeneo/pim-community-dev#19387]
:bug: **I'm reporting a Bug** :bug:

Version - Akeneo PIM v7.0
Symfony Webprofiler shows invalid entity: The association Akeneo\Pim\Enrichment\Component\Product\Model\Product#groups refers to the inverse side field Akeneo\Pim\Enrichment\Component\Product\Model\Group#products which does not exist. on Akeneo\Pim\Enrichment\Component\Product\Model\Product:

In a Group.orm.yml missed inverse side mapping:

>     manyToMany:
>         products:
>             targetEntity: Akeneo\Pim\Enrichment\Component\Product\Model\ProductInterface
>             mappedBy: groups

**Comment by ramon-nijman-webstores** [comment]
Hi!

Have already created a pull request with the change, see also: https://github.com/akeneo/pim-community-dev/pull/19389.

**Comment by ghoussard** [comment]
Hello!
Thank you for reporting this issue @ibs83278 😃
I handle this issue on my https://github.com/akeneo/pim-community-dev/pull/20349
