### ISSUE TITLE
Pim installer

### ISSUE THREAD

**Issue by aRn0D** [akeneo/pim-community-dev#1951]
I started a new project which follows the Symfony best practices (I try...). I wanted to put my fixtures into `app/Resource/fixtures` but it is impossible because Akeneo excepts something like MyBundle:fixture_dir. It should be useful to configure a path too. What do you think ?

Edit : The code used to calculate that path is "copied/pasted" at 2 places (into `PimInstallerExtenstion` and `FixtureJobLoader`)

**Comment by aRn0D** [comment]
@nidup I close it because it is impossible to follow the SF best practice but the second post is a real bug but what I do, create a new issue or not?

**Comment by nidup** [comment]
Hi ! New issue please, thx !

**Comment by aRn0D** [comment]
done by #2006

**Comment by aRn0D** [comment]
@nidup perhaps something like that can use (I don't test it I just saw it few minutes ago)
```
$kernel->locateResource('@PimCatalogBundle/Resources/fixture');
```
