### ISSUE TITLE
Imports unable to read the uploaded file when customizing the local_storage_adapter path

### ISSUE THREAD

**Issue by Rafelder** [akeneo/pim-community-dev#19688]
:bug: **I'm reporting a Bug** :bug:

Akeneo Version: 7.0.14

When customizing the location of the `local_storage_adapter` storage adapter, the import can not read the uploaded file anymore.
```
oneup_flysystem:
  adapters:
    local_storage_adapter:
      local:
        location: '%kernel.project_dir%/var/file_storage_local'
```

![image](https://user-images.githubusercontent.com/2484846/236221604-95056b65-a598-47a3-8aa2-7ee0f8a8658a.png)

How to reproduce:
- Change the location of the `local_storage_adapter`
- Import a file (for example import a attribute csv with a default csv attribute import profile)

Technical example for an csv attribute import:

The uploaded file is moved to the `local_storage` file system here:
https://github.com/akeneo/pim-community-dev/blob/a2d1bb63e34c7b42a44a4f52550fe7a7e8c7505a/src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/DownloadFileFromStorage.php#L32-L46

The info about the file system and the path is stored in the job execution parameters (`file_path` and `type`):
https://github.com/akeneo/pim-community-dev/blob/a2d1bb63e34c7b42a44a4f52550fe7a7e8c7505a/src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/DownloadStep.php#L62-L66

The charset validator does not take the file storage (`type`) into account (only reads `file_path` from the parameters):
https://github.com/akeneo/pim-community-dev/blob/a2d1bb63e34c7b42a44a4f52550fe7a7e8c7505a/src/Akeneo/Tool/Component/Connector/Item/CharsetValidator.php#L51-L53

The csv reader also does not take the file storage (`type`) into account (only reads `file_path` from the parameters):
https://github.com/akeneo/pim-community-dev/blob/a2d1bb63e34c7b42a44a4f52550fe7a7e8c7505a/src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php#L70-L78

**Comment by Rafelder** [comment]
Is it possible to get any feedback to this? The bug prevents us from hosting Akeneo on a shared hosting system because the only working configuration is the default configuration which points to the root directory (which does not work because of permissions - the adapter tries to check if the directory is writeable).

**Comment by ghoussard** [comment]
Hello @Rafelder, it is now possible to customize the root location of local storage adapter by overriding the `local_storage_root` parameter!
