### ISSUE TITLE
Incorrect documentation for scheduled jobs

### ISSUE THREAD

**Issue by aistis-** [akeneo/pim-community-dev#19972]
:bug: **I'm reporting a Bug** :bug:

[Documentation states](https://docs.akeneo.com/7.0/install_pim/manual/scheduled_job.html) to enable `pim:job-automation:push-scheduled-jobs-to-queue` cron for v7.

However, such command **does not seam to exist under v7.0.19.**

**Comment by StevenVAIDIE** [comment]
Hello aistis, 

You are right this command is only available in Enterprise Edition, I'm going to made the change. 

Thanks for you feedback !

**Comment by danielbeardsley** [comment]
This should be re-opened as this job is mentioned is being available in CE in at least one place:
https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html

**Comment by amirhmoradi** [comment]
@StevenVAIDIE  please re-open this issue and fix the docs. @danielbeardsley  is right, i have the same issue.

**Comment by almostanengnineer** [comment]
This is still showing in the install docs as a required job for the Akeneo CE Edition ~ https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html
