### ISSUE TITLE
Yarn Error 2 installing Akeneo & Webkul using Bitnami Instance

### ISSUE THREAD

**Issue by MudGreg** [akeneo/pim-community-dev#19991]
I'm trying install a Webkul plugin but I'm getting a Yarn error 2. With debugging on and reading the logs, the error looks to be in Akeneo itself, but I can't figure out how to resolve it. Any pointers would be massively appreciated! Below is the error log:

`yarn run v1.22.19
$ yarn workspace pim-community-dev packages:build
$ yarn dsm:build && yarn shared:build && yarn measurement:build && yarn catalog-volume-monitoring:build && yarn category:build && yarn config:build && yarn process-tracker:build && yarn import-export:build && yarn catalogs:build && yarn identifier-generator:build
$ yarn --cwd=front-packages/akeneo-design-system install --frozen-lockfile && yarn --cwd=front-packages/akeneo-design-system lib:build
[1/4] Resolving packages...
success Already up-to-date.
$ tsc -p ./tsconfig.build.json
$ yarn workspace @akeneo-pim-community/shared lib:build
$ tsc -p ./tsconfig.json
src/components/page/PageHeader.tsx:86:11 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ showPlaceholder: boolean | undefined; }' is not assignable to parameter of type 'Partial<unknown> & Attributes'.
      Object literal may only specify known properties, and 'showPlaceholder' does not exist in type 'Partial<unknown> & Attributes'.

86           showPlaceholder,
             ~~~~~~~~~~~~~~~

  ../../../../../node_modules/@types/react/index.d.ts:325:14
    325     function cloneElement<P>(
                     ~~~~~~~~~~~~
    The last overload is declared here.

src/tests/utils.tsx:12:37 - error TS2322: Type 'React.ReactNode' is not assignable to type 'import("/opt/bitnami/akeneo/node_modules/@types/styled-components/node_modules/@types/react/ts5.0/index").ReactNode'.
  Type '{}' is not assignable to type 'ReactNode'.

12     <ThemeProvider theme={pimTheme}>{children}</ThemeProvider>
                                       ~~~~~~~~~~

  ../../../../../node_modules/@types/styled-components/index.d.ts:349:5
    349     children?: React.ReactNode | undefined;
            ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemeProviderProps<any, any>, any, any>> & Readonly<...>'


Found 2 errors in 2 files.

Errors  Files
     1  src/components/page/PageHeader.tsx:86
     1  src/tests/utils.tsx:12
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /opt/bitnami/node/bin/node
Arguments: /opt/bitnami/akeneo/.yarn/releases/yarn-1.22.19.cjs lib:build
Directory: /opt/bitnami/akeneo/vendor/akeneo/pim-community-dev/front-packages/shared
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /opt/bitnami/node/bin/node
Arguments: /opt/bitnami/akeneo/.yarn/releases/yarn-1.22.19.cjs packages:build
Directory: /opt/bitnami/akeneo/vendor/akeneo/pim-community-dev
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Reaping losing child 0x556600218f70 PID 4129 
make[1]: *** [Makefile:29: front-packages] Error 2
Removing child 0x556600218f70 PID 4129 from chain.
make[1]: Leaving directory '/opt/bitnami/akeneo'
make: *** [vendor/webkul/bigcommerceconnector/src/Webkul/BigCommerceBundle/install/Makefile:67: wk_install] Error 2
Script vendor/webkul/bigcommerceconnector/src/Webkul/BigCommerceBundle/install/config.sh COMPOSER=true NO_DOCKER=true handling the post-update-cmd event returned with error code 2`

I've tried upgrading all the components including Yarn with no joy.

**Comment by oefterdal** [comment]
I am getting the same error on an upgrade of Akeneo 6 to 7, but are not using webkul

**Comment by oefterdal** [comment]
`$ tsc -p ./tsconfig.json
src/components/page/PageHeader.tsx:86:11 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ showPlaceholder: boolean | undefined; }' is not assignable to parameter of type 'Partial<unknown> & Attributes'.
      Object literal may only specify known properties, and 'showPlaceholder' does not exist in type 'Partial<unknown> & Attributes'.

86           showPlaceholder,
             ~~~~~~~~~~~~~~~

  ../../../../../node_modules/@types/react/index.d.ts:325:14
    325     function cloneElement<P>(
                     ~~~~~~~~~~~~
    The last overload is declared here.

src/tests/utils.tsx:12:37 - error TS2322: Type 'React.ReactNode' is not assignable to type 'import("/var/www/cblys/node_modules/@types/styled-components/node_modules/@types/react/ts5.0/index").ReactNode'.
  Type '{}' is not assignable to type 'ReactNode'.

12     <ThemeProvider theme={pimTheme}>{children}</ThemeProvider>
                                       ~~~~~~~~~~

  ../../../../../node_modules/@types/styled-components/index.d.ts:349:5
    349     children?: React.ReactNode | undefined;
            ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemeProviderProps<any, any>, any, any>> & Readonly<...>'


Found 2 errors in 2 files.

Errors  Files
     1  src/components/page/PageHeader.tsx:86
     1  src/tests/utils.tsx:12`

**Comment by MudGreg** [comment]
> I am getting the same error on an upgrade of Akeneo 6 to 7, but are not using webkul

Interesting. Reading the error I have, it's in the Akeneo code, not Webkul so definitely related. Just at my wits end.
Reading it, it seems to point to Typescript and Webpack as the issue from my research.

Might try updating that in the package.json.

There are some minor version updates too. Might see if I can persuade them to install and if that fixes it:
https://github.com/akeneo/pim-community-dev/blob/master/CHANGELOG-7.0.md
