### ISSUE TITLE
Impossible to override AttributeOption Entity

### ISSUE THREAD

**Issue by aRn0D** [akeneo/pim-community-dev#2000]
I extended and overrided the doctrine mapping but doctrine was bot able to generated the `attribute_id` column in my database. I don't know why! I copied/pasted the whole of the entity into mine, I did the same for the mapping and it works... 

Did I do something wrong? Adding a abstract model should solve the problem even if it is not the right solution. Interested by a PR!?

**Comment by nidup** [comment]
Hi @aRn0D 

In fact, I already met this kind of issue there is some time now (older version of doctrine) with MappedSuperClass which manages to generate fields only but not relations except when copy / paste. As you said, introduce an Abstract does the job but it's not a really clean way to do so.

Why do you need to override the AttributeOption ? You add some fields inside ?

FYI, in 1.3, we're adding interfaces for models to prepare the future :)

**Comment by aRn0D** [comment]
@nidup I wanted to create a new attribute, a kind custom select (HTML). Each options will depend on the value of another attribute. For example : I have two attributes City and Postal code, the second one depends on the first one. When you select a city the options of postal code will be updated, we will only display the options which depend on the selected city. So I need to override AttributeOption. I don't like to copy code too... Julien told me that he created those interfaces but DoctrineEntityResolver does not use them ;)

**Comment by nidup** [comment]
Ok, I understand, we prepare the ground with interfaces but you're right we need to go further on this topic, I've seen some related PR proposal somewhere ;)

**Comment by jmleroux** [comment]
@aRn0D ,
is this issue still relevant ?

**Comment by aRn0D** [comment]
@jmleroux old issue, it can be closed!
