### ISSUE TITLE
Double Scroll on the product edition

### ISSUE THREAD

**Issue by aRn0D** [akeneo/pim-community-dev#2007]
When your product edition is too large, a double scroll appears on FireFox 34 but il work for Chromium. Please see a sceenshot below:

![double_scroll](https://cloud.githubusercontent.com/assets/3585922/5761148/b96cd3e0-9cd9-11e4-965d-3f96a94a3025.png)

**Comment by aRn0D** [comment]
@nidup cf. last tweet ;)

**Comment by nidup** [comment]
@aRn0D forwarded to the team ;)
