### ISSUE TITLE
Akeneo CE 5.0 pim_catalog_image and thumbnail generation

### ISSUE THREAD

**Issue by nadialf** [akeneo/pim-community-dev#20107]
:question: **I'm asking a Question** :question:

Akeneo Community version 5.0 generates thumbnails based on a pim_catalog_image attribute for product model?

I have read that when an image is uploaded to an attribute of type pim_catalog_image, a thumbnail is generated, and this thumbnail is used in the product grid view and product detail view if you set this attribute as the main image.

The problem is that I have my pim_catalog_image attribute, I upload an image and the thumbnail is not visible in the details view and neither in the grid.

Could someone help me to know how to do this or if it is only for the Enterprise edition, guide me in the documentation where it is mentioned?

![image](https://github.com/akeneo/pim-community-dev/assets/12315568/0bf3a8c6-1f89-4303-827e-2c59b9170dba)

**Comment by EEmlan** [comment]
Hi,
I'm using Version 7 and don't know if its the same way as in Version 5
but gernerally it is possible in the Community Edition

After adding your image attribute you have to create a family.
Then add the attributes you wish to the family.
After that go to properties tab (still within the create family menu) and assign label attribute (text) and the attribute used as the picture.

After that add your products to this Family and then the picture should be visible.

Hope this helps :)
