### ISSUE TITLE
Javascript error on the dashboard

### ISSUE THREAD

**Issue by aRn0D** [akeneo/pim-community-dev#2019]
On my dashboard I got the following error : `Error: The route "pim_dashboard_widget_data" does not exist.` (router.js, line 9). I searched it in the core and this route exists.

Did I break something or is it a known problem on the dev-master?

**Comment by vbnet3d** [comment]
We have the same error on production. app_dev.php is functioning properly. This is a 1.3.3 upgrade from 1.2.

**Comment by jmleroux** [comment]
Hello @vbnet3d ,

Did you regenerate your assets ?

`php app/console pim:installer:assets --env=prod`


Note : you can also clean your browser cache after.

Regards,

JM Leroux

**Comment by vbnet3d** [comment]
I did when I installed, but there must have been an issue before because it worked now. Here is the procedure I had to follow:

php app/console pim:installer:assets --env=prod
php app/console cache:clear --env=prod
php app/console cache:warm --env=prod

+ clear browser cache.

**Comment by riconeitzel** [comment]
That problem occured to me as well … I solved it by removing the directories in /web/* (kept the files!) – then did the steps, @vbnet3d did … then it worked like a charm.

Just installing the assets and even dumping the requireJS config didn't help.
