### ISSUE TITLE
cannot install apps from the store - Internal Server Error 500

### ISSUE THREAD

**Issue by EEmlan** [akeneo/pim-community-dev#20399]
I want to test some apps from the store.
Unfortunately the installation is not working.
I can click on connect with the app and then the authorization dialog is shown where I can grant the app permissions.
I confirm all permissions needed and then when I click on confirm there is a error from the remote server of the app.
"The server returned a "500 Internal Server Error".
We have tried with several apps and with every app it is the same.
There seems to be something wrong with the API call which is made after clicking on connect.
We are using Version 7.0 of Akeneo.
We have no idea what we should do now.
The logs show nothing helpful and the domain which responds the 500 Error is always the remote domain of the app.
Can anybody help?
many thanks in advance.

**Comment by Nan-dri-an** [comment]
Hello, did you manage to find a solution for this, please? I have the same issue.

**Comment by EEmlan** [comment]
@Nan-dri-an Yes the reason for that was that the system needs to be accessible from the Internet with the configured domain.
The API needs to connect backwards to your system so that without external domain the apps won't work.

**Comment by Nan-dri-an** [comment]
For me the domain was okay but this solved it:
bin/console akeneo:connectivity-connection:openid-keys:create

Thanks for the help.
