### ISSUE TITLE
Can't bulk delete products

### ISSUE THREAD

**Issue by zegmaarmanu** [akeneo/pim-community-dev#20408]
1. I select 1, multiple or all products using the checkboxes to select them
2. I use the bulk action to delete these products
3. nothing happens
4. When checking processes running, the mass deletion process stays in the status "starting"

Here's a screen recording: https://photos.app.goo.gl/4DqXrxBBh7BY7i1x6

**Comment by StevenVAIDIE** [comment]
Hello @zegmaarmanu,

It's normal you should start the job queue process in order to handle thé asynchonous task (import/export/mass edit...)

Here the documentation https://docs.akeneo.com/latest/install_pim/manual/daemon_queue.html

**Comment by zegmaarmanu** [comment]
Thanks, that did the thing indeed! Cheers!
