### ISSUE TITLE
EACCES Permission denied Make command

### ISSUE THREAD

**Issue by andreschmitten94** [akeneo/pim-community-dev#20415]
Hello I need help installing akeneo pim with docker on Ubuntu 22.04.
following error:
error An unexpected error occurred: "EACCES: permission denied, mkdir '/home/node/.yarn/v6'".

Can not create directory, permission denied. Also got following warning:
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.
Cannot create cache directory /var/www/.composer/cache/repo/flex/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.

Before the installation i gave the directory full permission. Also User is in Docker group.

Can anybody help?
Thanks in advance.

**Comment by StevenVAIDIE** [comment]
Hello @andreschmitten94,

You need to made the following command on your server/computer:
```
chown $USER:$USER ~/.cache/yarn
```

**Comment by andreschmitten94** [comment]
thank you very much. This solved the problem, I needed to do the same, with Cyprus. But now i have following error:
In StaticNoPingConnectionPool.php line 64:
                                        
  No alive nodes found in your cluster  
 
Can you also help with this?
@StevenVAIDIE
