### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by andreschmitten94** [akeneo/pim-community-dev#20416]
In StaticNoPingConnectionPool.php line 64:

No alive nodes found in your cluster.

After i tried the installation with docker and using the make command. I got this error.

Can someone help me with that?

**Comment by navneetbhardwaj** [comment]
@andreschmitten94 

Check the elasticsearch (elastic/elasticsearch) process status/container should be running.

> sudo docker ps

**Comment by andreschmitten94** [comment]
when i start the make command it is running but after the command reached the error. Elasticsearch Status is inactive. When I try the installation without docker. I got the same error

**Comment by andreschmitten94** [comment]
Could solve my problem, with a workaround. I used Version 6 and with docker there are no problems with elasticsearch. So could be a problem with the configuration of version 7.

This was driving me crazy.
