### ISSUE TITLE
image import in demo product

### ISSUE THREAD

**Issue by techtic-naman** [akeneo/pim-community-dev#20432]
I successfully imported a zip file containing an image, but despite the successful import, I can only see the default image instead of mine. Can anyone assist me in resolving this issue?

**Comment by StevenVAIDIE** [comment]
Hello @techtic-naman,

On your xlsx/csv file did you give the image path in the right column ?

**Comment by techtic-naman** [comment]
hello @StevenVAIDIE 
yes my zip was correct and I also see my image in var/file_storage/catalog folder.
in database I will see in pim_catalog_product table with these value 
 "additional_images": {"<all_channels>": {"<all_locales>": "0/2/0/a/020afb420d3959151d8b523b21b14dc14e1a5e30_NX_25_cad.jpg"}}
 but I am not getting image in product detail page 
 see this screenshot: [https://prnt.sc/MD9p9mPmZ7gA]
