### ISSUE TITLE
Identity Server connector

### ISSUE THREAD

**Issue by peter-burger** [akeneo/pim-community-dev#20457]
:question: **I'm asking a Question** :question:

Is there an option to connect the login process of akeneo with a identity server instance to use SSO approach and integrate akeneo PIM into business architecture?

**Comment by StevenVAIDIE** [comment]
Hello peter, 

It's only possible on Growth Edition and Enterprise edition, this feature is not available in community edition (https://www.akeneo.com/fr/compare-editions/)

Link to the documentation to configure it: https://help.akeneo.com/serenity-user-management/serenity-configure-the-saml-based-single-sign-on

**Comment by peter-burger** [comment]
Hello Steven, 
thanks for the fast reply. Will take that into consideration. Will close the topic.
