### ISSUE TITLE
Unable to modify Product Categories inside a product - MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by nbarxma** [akeneo/pim-community-dev#20484]
**I'm reporting a Bug** :
 When navigating into the Category section of a product that has Categories already assigned, there will always be a loading icon and
 as a result categories are unable to get modified for a product once set.
 
Error message:
`No route found for "GET https://myakeneo.com/enrich/product/list-categories/product/030c4ecb-f03e-46d9-b7e6-0d86de77674f/parent/4910": Method Not Allowed (Allow: POST)`
`MethodNotAllowedHttpException`

![image](https://github.com/user-attachments/assets/2d633dcd-4f16-43d4-bdd3-67e467b8f1c9)

:paperclip: **I'm using the Community Edition** :paperclip:

**Comment by ETEML17** [comment]
Thank you, i fixed the issue by replacing [POST] by [GET] method :
pim_enrich_product_model_listcategories:
    path: /list-categories/product-model/{id}/parent/{categoryId}
    defaults: { _controller: pim_enrich.controller.product_model:listCategoriesAction, _format: json }
    requirements:
        id: '[0-9a-f]+'
        categoryId: \d+
    methods: [GET]
