### ISSUE TITLE
resolvedFilePath should be protected instead of private in FileWriter.php (BaseConnectorBundle)

### ISSUE THREAD

**Issue by alafon** [akeneo/pim-community-dev#2063]
This prevents anyone to extend the class without also re-defining the `setFilePath()` method in order to correctly manage the `resolvedFilePath` property. Not sure if this should be considered as a bug or a non-feature :smile: But if it does not break anything on your side, then it would be more convenient to change the visibility of this property.

More explanations :

- `setFilePath()` initializes the `filePath` (which is protected) and set `resolvedFilePath` to null
- in our case we have a class `B` extended (among other things) the getFilePath() method to add a `%jobid%` placeholder (because we can't rely on the date to export our medias)
- `getFilePath()` uses lazy loading to retrieve the `resolvedFilePath` : if it's null, then the value is computed with the `strtr` stuff, if it's not null then the value is directly loaded from the object property
- part of our business code is unit tested and I discovered that multiple calls to `setFilePath` on our `B` class won't actually update the `resolvedFilePath` property, and finally `getPath` will always return the same string which is not what one can expect.

PR incoming

**Comment by nidup** [comment]
As discussed on your PR, our policy is to never use private as visibility, don't hesitate to do other PRs if you encounter other issue with a private visibility. Thx.

**Comment by alafon** [comment]
Will do :+1:
