### ISSUE TITLE
Image field in product form

### ISSUE THREAD

**Issue by BatsaxIV** [akeneo/pim-community-dev#2153]
Hello,

Is it plan to increase the size of the image field in the product form ?
To see the entire name (when it's long), you have to click the image.

See screenshot below :

![picture-name](https://cloud.githubusercontent.com/assets/1379286/6107413/fa4ce3e2-b06a-11e4-804f-de772c5a983b.png)

Thanks.

**Comment by nidup** [comment]
Hello,
Thank you for the feedback.
we plan to enhance the product form in the coming 1.4
Best regards

**Comment by nidup** [comment]
has been fixed in 1.4 (stable version will be release soon)
