### ISSUE TITLE
Datagrid Configuration shows only [object Object]

### ISSUE THREAD

**Issue by couda** [akeneo/pim-community-dev#2174]
I was reading the new features of the version 1.3 and testing them in the demo application. 

While testing the feature "Add filters for image and file attributes" I saw, that the attributes in the Datagrid Configuration were shown only as [object Object]. The localization of the system is set to default "English".

![2015-02-13 09_07_50-products](https://cloud.githubusercontent.com/assets/3909042/6184257/deac6778-b35f-11e4-90e4-0d1aa3d7835b.png)

**Comment by filipsalpe** [comment]
This looks nothing like the new awesome UI. Could you try clearing your browser cache?

**Comment by sumbobyboys** [comment]
Hello @couda,

It seems that you still have some old javascript in your browser cache :)

After a cache clear everything should work as expected.

Regards,

Julien

**Comment by couda** [comment]
After clearing the browser cache, the new ui looks great!

Best regards,
couda
