### ISSUE TITLE
Upgrade LiipImagineBundle to branch 1.2.x

### ISSUE THREAD

**Issue by alafon** [akeneo/pim-community-dev#2181]
Would be nice to upgrade the bundle to its last version.
It provides excellent improvements such as DataLoaders : http://symfony.com/doc/master/bundles/LiipImagineBundle/data-loaders.html

I know that it can be tricky since it's a "hardcoded" dependency in the OroPlatform but leaving outdated dependencies in Akeneo PIM is not much good either for integrators who wants to build rich bundles on top of Akeneo PIM.

**Comment by nidup** [comment]
Hello Arnaud,
You're right. FYI, since the 1.3 we moved all deps in our own composer.json cf https://github.com/akeneo/pim-community-dev/blob/master/composer.json
We plan to do some bumps and cleanup for the 1.4.

**Comment by alafon** [comment]
Just a word : perfect :+1:
