### ISSUE TITLE
Import localizable attribute option issue 

### ISSUE THREAD

**Issue by scivray** [akeneo/pim-community-dev#2222]
Hi,
With version 1.3.1 on Ubuntu 14.04, when I try to import attribute option values from a csv, the values act weird.
For instance, I create a attribute simple select localizable named test.
I create a import job and try to import a simple csv like this : 

attribute;code;sort_order;label-fr_FR;label-en_US;label-de_DE
test;test_A04;3;04FR;04US;04DE
test;test_A05;2;05FR;05US;05DE
test;test_A06;1;06FR;06US;06DE

The execution shows no error. But in database (mysql) in table pim_catalog_attribute_option_value I got the following : 

'73', '73', 'fr_FR', '04DE'
'74', '74', 'fr_FR', '05DE'
'75', '75', 'fr_FR', '06DE'

The DE values are in FR column and DE and US values aren't present.

**Comment by sumbobyboys** [comment]
Hi @scivray,

Thanks for your bug report. We aware of this bug and currently working on it.

Regards,

Julien

**Comment by skeleton** [comment]
Bug has been fixed in 1.3.2.
