### ISSUE TITLE
[BUG] Completeness calculation error

### ISSUE THREAD

**Issue by cjanody** [akeneo/pim-community-dev#2262]
Hi,

We found a bug in completeness calculation. You can reproduice it on the demo site.
Here are the steps to reproduce the calculation error:
- Edit a family, add an attribute and set it as required;
- Save your changes;
- Remove your new attribute without unsetting the requirement;
- Go to a product and save it to calculate the completeness;

=> The removed attribute appeared as missing which is not correct. In fact, the requirement has not been removed on attribute deletion. Saving the family solves the error.

I have seen the fix #1662 but it does not solved that problem.

Thanks for reading.

**Comment by Nuscly** [comment]
Thanks for the report, we create a ticket about it in our internal tracker https://akeneo.atlassian.net/browse/PIM-3848. It will be fixed soon.

**Comment by sumbobyboys** [comment]
Hi @cjanody,

I don't manage to reproduce your scenario. We fixed an completeness bug last week so it maybe fixed this one too.

If you still can reproduce the bug on demo, could you please give us a more detailed scenario or a screencast ?

Regards,

Julien

**Comment by jmleroux** [comment]
#2475 
#2523
