### ISSUE TITLE
Localised fields on overridden Category.

### ISSUE THREAD

**Issue by emileswarts** [akeneo/pim-community-dev#2321]
Hi 

Thanks for all the work you guys have done on this project.

I have a custom category, set up as described here:
http://docs.akeneo.com/latest/cookbook/category/add-properties-to-category.html

Is there any easy way to make these new properties translatable?

**Comment by jmleroux** [comment]
Hello,

You could use the Twig `trans` fiter.

Something like this : 
```{{ form_row(form.customCategory, , { 'label': 'custom.category.label'|trans }) }}```

Regards,

JM

**Comment by emileswarts** [comment]
Thanks for the quick response.

The attribute that needs to be translatable is a new 'Description' field that I added to the extended entity (as per the example).
 I need to give the user a number of inputs in the category admin for this field that they can fill in (Same as the node values currently does).

Is there an easy way to do this right now that you know of?

**Comment by emileswarts** [comment]
I am trying to overwrite the CategoryTranslation class in the same way that I did with Category.

I have this in my entities.yml file:
    pim_catalog.entity.category.class: Foo\ProductBundle\Entity\FooCategory
    pim_catalog.entity.category_translation.class: Foo\ProductBundle\Entity\FooCategoryTranslation

Both these custom entities exist.

However, when I create a new Category with translated fields in the admin, I get the following:

Found entity of type Foo\ProductBundle\Entity\FooCategoryTranslation on association Pim\Bundle\CatalogBundle\Entity\Category#translations, but expecting Pim\Bundle\CatalogBundle\Entity\CategoryTranslation

I try overwrite the relationship in FooCategory (which extents Category) with the following but it has no effect.

    /**
     * @ORM\OneToMany(targetEntity="Foo\ProductBundle\Entity\FooCategoryTranslation", mappedBy="foreignKey")
     */
    protected $translations;

I am wondering if that has something to do with the fact that its STI, and I am using subclasses?

**Comment by emileswarts** [comment]
I managed to solve this by replacing the translation class entirely in my own code, and not just extending category translation.  Thanks

**Comment by danalloway** [comment]
you need to implement the `getTranslationFQCN` method on your `Category` class if you are creating your own `CategoryTranslation` class

```
    /**
     * {@inheritdoc}
     */
    public function getTranslationFQCN()
    {
        return 'Acme\Bundle\CatalogBundle\Entity\CategoryTranslation';
    }
```
