### ISSUE TITLE
[BUG] Number attribute exports always with decimals

### ISSUE THREAD

**Issue by panploenes** [akeneo/pim-community-dev#2333]
When exporting a number attribute that has “allow decimals” set to No, the export module still exports the value with decimals.

**Comment by skeleton** [comment]
Hi,

Thanks for your bug report. We aware of this bug and currently working on it.

**Comment by skeleton** [comment]
Finally, it's not a bug. 
"allow decimals" option is only for validation, not to define format in export.

**Comment by panploenes** [comment]
Thank you.
Makes sense.
I
