### ISSUE TITLE
CSV Import - deleting medias

### ISSUE THREAD

**Issue by BatsaxIV** [akeneo/pim-community-dev#2397]
Hi guys,

How can I delete medias (pictures in my case) from a product with a standard csv product import?

I tried with an empty/null/'' column, doesn't remove the file.

We had a bad media import, to reimport everything and clear the wrong pictures I had to modify the **CatalogBundle/Manager/MediaManager.php** in **handle()** function and add **$this->delete($media);** at the beginning (which is not a very clean solution :smiley:)

Do you have a good solution ?

Thanks
Jérémy.

**Comment by nidup** [comment]
If it's to clean up wrong media data, i would write a symfony command, imho, the easier way to have access to all the service and quickly write a script.

**Comment by masmrlar** [comment]
Writing an additonal command is no real soluton for this.
If you use a regular csv import for the product data from foreign systems and that foreign system changes images or drops images of a gallery there must be a possiblitity to remove the images in the PIM by the import.

**Comment by akosglue** [comment]
is it solved already ?
