### ISSUE TITLE
Product list select box filter problem

### ISSUE THREAD

**Issue by s0ps** [akeneo/pim-community-dev#2433]
If you choose filter parameters from select box and press enter, then all the page becomes not clickable.
This does not happen when I click Update button instead of pressing enter.

**Comment by grena** [comment]
Hi @s0ps , thank you for the report :)
On **which version** of the PIM do you have this issue, and on **which page** ?
Thanks !

Regards,

**Comment by s0ps** [comment]
Hi @grena!
Version: 1.3.5 and on product list page.

**Comment by grena** [comment]
Thank you !
The bug has been reported internally, we'll do our best to fix it ! :)
