### ISSUE TITLE
Mass edit - image attribute

### ISSUE THREAD

**Issue by masev** [akeneo/pim-community-dev#2477]
When doing a mass edit on an image attribute, after confirmation we are redirected to the product list but there is no modification made on the products (no image added).

If there was an image on the product it removes it. 

The post parameters are :
pim_enrich_mass_edit_action: {"operation":{"locale":"90","values":{"visuel_1":{"id":"","media":{"id":"","copyFrom":""}}}},"_token":"63630f9f870417953deff71c14ffeb4bae060a45"}

**Comment by aRn0D** [comment]
Sir @jjanvier, Can you have a look plz?

**Comment by jmleroux** [comment]
@masev ,
do you still have the issue ?
on which version ?

Thx,
JM

**Comment by masev** [comment]
It's now ok on 1.3.x
I close the issue
