### ISSUE TITLE
Support to documentation

### ISSUE THREAD

**Issue by chicodasilva** [akeneo/pim-community-dev#2502]
Hi,

I've been trying to test some feature of "pim-community-dev" but the documentation is not always complete. 

What is the best channel to have some questions/documentation problems replied?

Regards,
Francisco

**Comment by grena** [comment]
Hello @chicodasilva, sorry for the late response and thank you for your interest!
GitHub is used by the team for bug reports and pull requests.

For any technical questions (technical or not), we'll try to do our best to answer you on http://www.akeneo.com/forums/.
For documentation, http://docs.akeneo.com/ (we try to improve it :wink: )

Kind regards
