### ISSUE TITLE
Completeness isn't recalculated when a family is updated.

### ISSUE THREAD

**Issue by squaresurf** [akeneo/pim-community-dev#2511]
We found a bug with regards to a family's completeness. After changing a family's required attributes all products within that family no longer have any completeness calculated. It is expected that all products have their completeness recalculated when that criteria changes for a family.

This is reproducible on the demo site. Here are the steps to reproduce it:

1. Add a required attribute to a family that has products with completeness calculated.
1. Save your changes.
1. Go to a product within that family and see that no completeness has been calculated.

Thank you for your time.

**Comment by fitn** [comment]
Hi @squaresurf 

This is a "normal" behavior today. Completeness calculation should be done with a CRON so we just remove the already calculated value (if existing) to flag products when we change a family or mass edit products.

Regards,

**Comment by squaresurf** [comment]
Hi @fitn,

Thank you for your response. Will this always be the norm or are there plans on removing the dependency on a CRON job?

**Comment by sumbobyboys** [comment]
Hi @squaresurf,

In fact, this is just a symfony2 command so you can use anything you want as long as it can launch the command :)

Regards,

Julien

**Comment by squaresurf** [comment]
The point to my questions was that it is truly unfortunate that it requires a command to regenerate completeness. I would expect that this should be done automatically whenever product's completeness has been cleared (i.e. a family is updated).

**Comment by sagikazarmark** [comment]
The biggest problem is that competeness is not invalidated after family update, so the calculate command does not regenerate completeness, as there is no missing completeness.

**Comment by sagikazarmark** [comment]
It seems that it is actually invalidated and recalculated. Maybe there were some problems, as I was mass editing lots of families. However, it is still a problem, that cases like this, there is no possibility to recalculate wrong completeness, only missing can be calculated.

**Comment by grena** [comment]
Hello @sagikazarmark, 

If you want to purge completeness (eg. when you had your problem for "fully completed product that will not be recalculate"), you can run the command `pim:completeness:purge` that will invalidate all completenesses for all families.

```
➜  ce-1.4 git:(1.4) php app/console pim:completeness:purge
Purging completenesses of the family "webcams"...
Purging completenesses of the family "mugs"...
Purging completenesses of the family "camcorders"...
Purging completenesses of the family "tshirts"...
Purging completenesses of the family "digital_cameras"...
Purging completenesses of the family "headphones"...
Purging completenesses of the family "led_tvs"...
Purging completenesses of the family "tablets"...
Purging completenesses of the family "mp3_players"...
Purging completenesses of the family "laser_led_printers"...
Purging completenesses of the family "pc_monitors"...
Purging completenesses of the family "scanners"...
Purging completenesses of the family "loudspeakers"...
Purging completenesses of the family "multifunctionals"...
Completenesses purged.
➜  ce-1.4 git:(1.4) php app/console pim:completeness:calculate
Generating missing completenesses...
Missing completenesses generated.
➜  ce-1.4 git:(1.4) 
```

**Comment by peleq-smile** [comment]
Hi there,

Thanks for this thread, which confirms my idea on it.
By the way, I discovered a little **tip** to cause the regeneration of the completeness : by **mass editing** the **status** from products grid (at least on Akeneo 1.6)
It can be useful for our customers who don't use CLI command ;-). All they have to do is select products with same status and mass edit them without...  changing the value ^^.

Regards,
Perrine
