### ISSUE TITLE
findOneBy... methods should not return false, but null if product is not found

### ISSUE THREAD

**Issue by alafon** [akeneo/pim-community-dev#2517]
See : src/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepository.php

```php
    public function findOneByIdentifier($identifier)
    {
        $pqb = $this->queryBuilderFactory->create();
        $qb = $pqb->getQueryBuilder();
        $attribute = $this->getIdentifierAttribute();
        $pqb->addFilter($attribute->getCode(), Operators::EQUALS, $identifier);
        $result = $qb->getQuery()->execute();

        return reset($result);
    }
```

My suggestion is that it should be implemented like this :

```php
return !empty($result) ? reset($result) : null;
```

BTW, the interface implemented by the repository seems to be correct.
If you agree that this is an issue I can provide the PR

**Comment by jmleroux** [comment]
Hi @alafon ,

You're totally right and a PR is of course welcome.

Regards,

**Comment by alafon** [comment]
I think that this one can be closed since it has been patched in the new version.
I was too slow to provide the PR... :D
