### ISSUE TITLE
[BUG] Custom view : columns sorting

### ISSUE THREAD

**Issue by cjanody** [akeneo/pim-community-dev#2589]
Hi,

When a user edits one of his views, columns sorting has been lost. If this is not the expected behavior, we have fixed it on our 1.3 installation and could submit a pull request soon if you wish.

Thanks for reading.

**Comment by jmleroux** [comment]
Hi @cjanody ,

Keeping columns sort order could be interesting.
Feel free to submit a PR and we will review it.

Regards

**Comment by cjanody** [comment]
Hi @jmleroux ,

We will do it as soon as possible.

Sincerely
