### ISSUE TITLE
Cannot import category names with "-"

### ISSUE THREAD

**Issue by vbnet3d** [akeneo/pim-community-dev#2638]
We are integrating an existing Magento solution, and by default Magento creates category names with dashes in place of spaces. However, the category import in Akeneo disallows the dash character. I thought about modifying the filter, but was not certain that this would be a safe change. We will be moving to PIMGento, but I believe the category names still must match?

PIM version 1.3.5

**Comment by Nuscly** [comment]
Hello,

I think you can create a filter in the import that convert the category name from the magento format to the pim format to solve your problem.
You need to customize the batch bundle job to add your step filter.

Regards,

**Comment by vbnet3d** [comment]
Would this filter remain after updates to the application?
