### ISSUE TITLE
Mass edit - Updated At

### ISSUE THREAD

**Issue by s0ps** [akeneo/pim-community-dev#2644]
Updated at value is not updated on mass edit

**Comment by grena** [comment]
Hello @s0ps, thank you for your report.
On which version of the PIM do you have this issue?

**Comment by s0ps** [comment]
Version: 1.3.5

**Comment by phaseinducer** [comment]
Hi @s0ps, I can't reproduce the behaviour on the latest stable version (which is currently 1.3.16), maybe you could upgrade and try again ?

Regards
