### ISSUE TITLE
Traduc in product edit page

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#2882]
When i'm editing the product lots of text are not translated in french or english.

![akeneo](https://cloud.githubusercontent.com/assets/4558101/8303658/aff76396-199f-11e5-9a99-4d9abb126712.png)

**Comment by sumbobyboys** [comment]
Hello @Philippe-M,

Your are using a development version of the PIM (master branch) which is still in active development. This version is currently only translated in english and will be translated at least in french before the release.

To use a fully translated PIM, you can use our last stable version of the PIM: https://github.com/akeneo/pim-community-dev/releases

By the way, you are greatly encouraged to help use translate Akeneo PIM in french using our crowdin project !

Regards,

Julien

**Comment by Philippe-M** [comment]
Ok thanks
