### ISSUE TITLE
PHP Fatal error in DefaultRepositoryFactory.php in 1.3.16

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#2885]
Hello,

After fresh install the 1.3.16, when i go to login page i've this error in apache log :

> PHP Fatal error: Class 'Pim\\\Bundle\\\CatalogBundel\\\Doctrine\\\ORM\\\Repository\\\AttributeRepository' not found in /var/www/pim-community-dev/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php in line 75

I'm testing with 1.3.15 version and the error is :

> PHP Fatal error: Class 'Oro\\Bundle\SecurityBundle\\OroSecurityBundle' not found in /var/www/pim-community-dev/app/AppKernel.php on line 186

I'm using debian 7.8, apache 2.2.22, php 5.4.41-0+deb7u1

**Comment by grena** [comment]
Hello @Philippe-M , thank you for the feedback and sorry for the delay.
Can you test these commands and tell me if it fixes your problem please?

```sh
# Go in the root of your PIM installation
rm -Rf app/cache vendor composer.lock
composer install
sudo service apache2 restart
```

Kind regards,

**Comment by Philippe-M** [comment]
Hello @grena , it's ok with 3.15 and 3.16.

Thanks.
