### ISSUE TITLE
Error in TranslateFlashMessagesSubscriber when Session is not started

### ISSUE THREAD

**Issue by vpetrovych** [akeneo/pim-community-dev#2912]
I'm using Nelmio Cors package to support cross reference calls, but because it's an OPTIONS call you don't have a session started. So you get the following error:
> FatalErrorException: Error: Call to a member function getFlashBag() on null in /vendor/akeneo/pim-community-dev/src/Pim/Bundle/EnrichBundle/EventListener/TranslateFlashMessagesSubscriber.php line 58

The issue is this line:
```
$bag = $event->getRequest()->getSession()->getFlashBag();
```

This can be easily fixed by adding a check:
```
if (!$event->getRequest()->hasSession()) {
    return;
}
```

**Comment by phaseinducer** [comment]
Hi @vpetrovych,

Thanks for your feedback, feel free to send a PR. ; )

Regards
