### ISSUE TITLE
NormalizeConfigurationExtension issue

### ISSUE THREAD

**Issue by srascar** [akeneo/pim-community-dev#2938]
Hello,

I've just created a custom reader for an export job. 
It appears that defining an option with a multiple select will raise an exception in 
\Pim\Bundle\ImportExportBundle\Twig\NormalizeConfigurationExtension.php
cause normalizeValueFilter method does not handle array.

Is that on purpose, or could you add an other line like
    
    if (is_array($value)) {
        return implode(', ', $value);
    }

More informations:
version => "akeneo/pim-community-dev": "~1.3.11"
how to reproduce =>

    class Dummy extends AbstractConfigurableStepElement
    {
         //...
         public function getConfigurationFields()
         {
             return [
                 'foo' => [
                     'type'    => 'choice',
                     'options' => [
                         'choices'  => ['foo' => 'Foo', 'bar' => 'Bar'],
                         'multiple' => true,
                     ]
                 ],
             ];
         }
    }

**Comment by skeleton** [comment]
Hi srascar,

Thanks a lot for your contributing. Can you send a pull request to purpose your fix ? 
We will launch our CI to check if this fix does not break something.

**Comment by srascar** [comment]
hi @skeleton ,
Thank you for your quick answer. 
Please see my PR
