### ISSUE TITLE
Problem with image upload on Variant Group 

### ISSUE THREAD

**Issue by cwakim** [akeneo/pim-community-dev#3014]
If I add an attribute of type Image on a Variant Group and reload the page the inage link becomes broken.

When we try to resave the product we get the below error on a development installation:
File not found [temp_file_name] 

Or on a production instalation:
Page not loaded correctly.
Also we have noticed that in the catalog_product_template table the image link is that of the temporary file upload.
And in the twig template the filename variable is not the uploaded image name such is the case with the product but the temp name.

Any help is appreciated.

**Comment by BitOne** [comment]
Thanks @cwakim , I got a broken image, and when I want to add a product after having put an image, I got the "Page was not loaded correctly" error. So I confirm the bug on our demo environment.

It seems this bug only occurs when the variant group has no product attached.

So as a temporary workaround, just after creating a variant group, please first attach a product *then* add the image attributes. It should work better.

In the meantime, we will push this ticket to our product team.

Thanks again for the report !

**Comment by cwakim** [comment]
Hello @BitOne I can't seem to make it work on our end but the workaround seems to work on the demo. Is the demo using Mongo as db ?

**Comment by cwakim** [comment]
@BitOne I just tried a MySQL installation and the workaround works fine, but still on the Mongo installation it does not work.

**Comment by jmleroux** [comment]
Ticket created in JIRA : PIM-4976
