### ISSUE TITLE
Get full product with only some attributes

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3028]
I'm a Symfony/Doctrine/Akeneo beginner ;-) and try to get the full data of a product with only some attributes. 

I've seen that `Pim\Bundle\DataGridBundle\Controller\ProductExportController` use for the export this line to get all attributes:

        $results = $this->productRepository->getFullProducts($productsList, $attributeIds);

I've tried the same only with some attribute ids as second parameter of `getFullProducts`, but this doesn't work: I always get all attributes instead of only some of them. (I'm using MySQL.)

I looked down to this line in ProductRepository https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php#L250 :

            ->leftJoin('v.attribute', 'a', $qb->expr()->in('a.id', $attributeIds)) 

Shouldn't be the condition the fourth instead of the third parameter here?

**Comment by ClementGautier** [comment]
Hello,

It looks like you are right. Thank you for pointing that out !

I'll fix that on the 1.3 branch but we'll probably mark this function as deprecated in the master branch as it is not used in the PIM itself anymore.

**Comment by ClementGautier** [comment]
Fixed in 1.3, will be merged in master soon.
We will bump the 1.3.19 today btw.
