### ISSUE TITLE
Switch from serialize() in DB fields to json_encode()

### ISSUE THREAD

**Issue by dimitri-koenig** [akeneo/pim-community-dev#3071]
Hi Guys

How much effort would be needed to change the usage of serialize() in DB fields, e.g. changeset/snapshot fields in versioning table, to json_encode?

Why? E.g. if you want to alter attribute code, which is not directly possible, only via raw queries, you can do it perfectly in the attributes table, but then versioning will be broken. And a simple mysql REPLACE() operation is not possible because then unserialize() won't work anymore. But if you store arrays/objects via json_encode it still would work.

**Comment by ClementGautier** [comment]
Hello Dimitri,

It looks like we use serialize on few spaces so it wouldn't take long. 
I found references to serialize in:

```
src/Pim/Bundle/BaseConnectorBundle/EventListener/InvalidItemsCollector.php
60:        return md5(serialize($item));

src/Pim/Bundle/DataGridBundle/Extension/Pager/Orm/Pager.php
65:        return serialize($vars);

src/Pim/Bundle/DataGridBundle/Extension/Pager/AbstractPager.php
308:        return serialize($vars);
316:        $array = unserialize($serialized);

src/Pim/Bundle/VersioningBundle/Doctrine/ORM/PendingMassPersister.php
114:                $fieldValue = serialize($fieldValue);

src/Pim/Bundle/EnrichBundle/Mailer/MailRecorder.php
42:        file_put_contents($this->filename, serialize($contents));
56:        $contents = unserialize(file_get_contents($this->filename));
```

The tricky part is the data migration.

Feel free to make a pull request about this (with the data migration script) and we will be happy to merge it.

Regards

**Comment by gplanchat** [comment]
Wouldn't a serlializer as a DI service be more appropriate?

as long as each installation has its own constraints, choosing your serialization format would be a great enhancement
