### ISSUE TITLE
delete all attributes or families

### ISSUE THREAD

**Issue by tschroeter** [akeneo/pim-community-dev#3109]
hey, i am installed a fresh akeneo installation and try do delete all demo attributes and families but unable do select all and click on any delete button !?

**Comment by willy-ahva** [comment]
Hi @tschroeter, to avoid to remove all data by hand you can install akeneo with the minimal dataset moving this param https://github.com/akeneo/pim-community-dev/blob/master/app/config/pim_parameters.yml#L24

Regards,
Willy
