### ISSUE TITLE
Family mass edit problems with the filtered records by label (akeneo 1.3.*).

### ISSUE THREAD

**Issue by tadcka** [akeneo/pim-community-dev#3114]
http://demo.akeneo.com/#url=/enrich/mass-edit-action/choose?gridName=family-grid&actionName=mass_edit&inset=1&values=3%2C4%2C7&family-grid%5B_sort_by%5D%5Bcode%5D=ASC&filters%5Blabel%5D%5Bvalue%5D=m&filters%5Blabel%5D%5Btype%5D=1&dataLocale=%2Fdatagrid%2Ffamily-grid%3Ffamily-grid%5BlocaleCode%5D%3Den_US

I see don't set locale code.

From profilter:
```
SELECT 
  p0_.id AS id0, 
  p0_.code AS code1, 
  p0_.created AS created2, 
  p0_.updated AS updated3, 
  p0_.id AS id4, 
  p0_.code AS code5, 
  p0_.created AS created6, 
  p0_.updated AS updated7, 
  (
    CASE WHEN p1_.label IS NULL THEN p0_.code ELSE p1_.label END
  ) AS sclr8, 
  p1_.label AS label9, 
  p0_.label_attribute_id AS label_attribute_id10 
FROM 
  pim_catalog_family p0_ 
  LEFT JOIN pim_catalog_family_translation p1_ ON p0_.id = p1_.foreign_key 
  AND (p1_.locale = ?) 
  LEFT JOIN pim_catalog_attribute p2_ ON p0_.label_attribute_id = p2_.id 
WHERE 
  p1_.label LIKE ? 
  AND p0_.id IN ('3', '4', '7') 
ORDER BY 
  p0_.code ASC
```
Parameters: [null, '%m%']

**Comment by nidup** [comment]
Hello tadcka,

Thank you for the feedback!

I think that issue has been fixed here https://github.com/akeneo/pim-community-dev/blob/1.3/CHANGELOG-1.3.md#1317-2015-07-07

The demo was not up to date when you reproduced it, we re-deployed it few days ago.

**Comment by tadcka** [comment]
This issue not fixed in PIM-1.3.7. I use PIM-1.3.8 and has this bug.

**Comment by nidup** [comment]
Sorry, i maybe misunderstood the issue, may you test with the very last patch deployed on our demo http://demo.akeneo.com?

If you don't reproduce the bug on this environment, I advise you to update your installation with the last patch v1.3.24 (we do our best to never do BC Break in patches and you should be able to apply it easily).

**Comment by tadcka** [comment]
Fixed, thanks :+1:
