### ISSUE TITLE
akeneo with anyother database

### ISSUE THREAD

**Issue by kekin-chheda** [akeneo/pim-community-dev#3188]
Hi, first of all i would like to tell akeneo is awesome application developed, as i am really looking forward to use akeneo, my main question is can i use akeneo completely with nosql databases such as orientDB is there any configuration changes required? plz suggest if not orientDB please suggest any solution for mongoDB.

**Comment by nidup** [comment]
Hi kekin-chheda ,

Thank you!

Natively Akeneo can use 2 methods to store data:
 - simple storage, means all data in Mysql (through DoctrineORM, should work with other RDBMS but not tested)
 - polyglot storage, means product data in MongoDB and other data in Mysql (through DoctrineMongoDBODM and DoctrineORM)

There is a tech doc which describes how to install different storage http://docs.akeneo.com/latest/developer_guide/installation/installation_workstation.html

The application rely on some abstractions (as repository interfaces and product query builder) added to handle the native double storage, these interfaces may be implemented to add another storage but it's a big work and maybe you'll be face of missing extension points depending on the storage you would introduce :)
