### ISSUE TITLE
Product import variant group key?

### ISSUE THREAD

**Issue by linslin** [akeneo/pim-community-dev#3265]
Hey Guys, whats the key to import products into a variant group? I tried a lot but did not found any information in the documentation. Hint: Variants already exists in Akeneo, I just want to link my product into via product import.

#### Example without variant group:

sku;family;categories;
1;test;test
2;test;test

THX

**Comment by nidup** [comment]
Hi linslin!

The key is 'groups', a good approach is to complete some products and export the csv file to see the format (this format can be used to import products too).

sku;family;categories;groups;
1;test;test;my_variant_group_code
2;test;test;

**Comment by linslin** [comment]
Thanks, works like a charm. :+1:
