### ISSUE TITLE
Add "hide" feature for attributes

### ISSUE THREAD

**Issue by dimitri-koenig** [akeneo/pim-community-dev#3279]
You should be able to hide an attribute. Currently the only way of disabling an attribute is to delete it. Temporarily hiding (or even disabling) is not possible.

**Comment by nidup** [comment]
FYI, in Enterprise Edition, you can use advanced permissions to hide/readonly/edit each attribute.

**Comment by dimitri-koenig** [comment]
Good to know, thx.
