### ISSUE TITLE
Installer fails on 1.4 RC1

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#3287]
I just launched a `app/console pim:install` and went through an error :

Error message : `The function "oro_windows_restore" does not exist in "::base.html.twig" at line 32 `

Errored file is located in **app/Resources/views/base.html.twig**, seems to be a TwigExtension missing or failing to be loaded

**Comment by nidup** [comment]
i don't reproduced this issue, it was after a re-install? with a clean cache?

**Comment by gplanchat** [comment]
It was after a hard cleaned cache (`rm -rf app/cache/*`), on an empty DB, with the application's sources freshly merged from master (commit from akeneo/pim-community-standard@65905f4f8ca7024b26797965db0e0db9c43fa6a2) and updated composer dependencies.

It is not an empty project, I have 2 bundles in the src directory : a custom connector and a custom fixtures installer

I am running php 5.6.9 as cli on osx :

```
PHP 5.6.9 (cli) (built: Jun  3 2015 16:43:00) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

I was previously using version 1.2

**Comment by jmleroux** [comment]
hi @gplanchat ,

is this issue still relevant ?

**Comment by gplanchat** [comment]
I'll test it again with the latest 1.4 release this evening.

**Comment by gplanchat** [comment]
The error does not seem to appear again

Grégory
