### ISSUE TITLE
Email address with an '+' marked as invalid

### ISSUE THREAD

**Issue by darryla** [akeneo/pim-community-dev#3337]
Email addresses with an '+' are marked as invalid in the interface but this conforms to the standard. For us we widely use this to good effect with Gmail inbox filters, as per the post here: http://gmailblog.blogspot.co.uk/2008/03/2-hidden-ways-to-get-more-from-your.html

**Comment by jmleroux** [comment]
Hi @darryla ,
Thank you for the feedback, this feature will be discussed with the core team ASAP.

Regards

**Comment by LaureBro** [comment]
Hello @darryla, 

Sorry for the delay, I have informed our Product team of your request, but this improvement will not be part of our Roadmap.

If you feel like, you can still open a pull request, we'll be glad to help you to merge it.

Thanks, best regards, 

Laure
