### ISSUE TITLE
Allow full numeric entities codes

### ISSUE THREAD

**Issue by FrankStappers** [akeneo/pim-community-dev#3371]
Since the commit of "PIM-4443", full numeric entities code are forbidden. According to the author, the patch "solves" an error when exporting attribute codes, by preventing them from being used. 

For a client we are performing a data migration. To model the data correctly in Akeneo, we require variant group codes with full numeric values (> 0).  Due to restriction posed by "PIM-4443", we cannot do so.

Is het possible to revert the patch and provide an alternative fix to export attribute codes? 

Kind regards,
Frank Stappers

**Comment by nidup** [comment]
Hi FrankStappers,
Thank you for the feedback, it has been raised by different customers / users.
The Core Team is studying an alternative patch.
BR,

**Comment by jmleroux** [comment]
Ticket PIM-4977

**Comment by phaseinducer** [comment]
Hi Frank,

We reverted that behavior in the last patch (1.4.3), it should solve your problem. ; )

Regards,
Yohan

**Comment by FrankStappers** [comment]
Hi Yohan,

Thank you for the revert! Will check it out today!

Kr,
FS
