### ISSUE TITLE
Rule Engine error

### ISSUE THREAD

**Issue by hungpq12** [akeneo/pim-community-dev#3378]
i used akeneo1.4 that defined :
1 - vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml
* pim_catalog.repository.category.class:         Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\CategoryRepository
* pim_catalog.repository.category:
        class: %pim_catalog.repository.category.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.category.class%]
        tags:
            - { name: 'pim_repository' }
2 - vendor/akeneo-labs/classification-rule-bundle/PimEnterprise/Bundle/ClassificationRuleBundle/Resources/config/engine.yml
pimee_catalog_rule.applier.product.updater:
        class: %pimee_catalog_rule.applier.product.updater.class%
        arguments:
            - '@pim_catalog.updater.product_property_setter'
            - '@pim_catalog.updater.product_property_copier'
            - '@pim_catalog.updater.product_template'
            - '@pim_catalog.repository.category'
but on file "vendor/akeneo-labs/classification-rule-bundle/PimEnterprise/Bundle/ClassificationRuleBundle/Engine/ProductRuleApplier/ProductsUpdater.php" using Pim\Bundle\CatalogBundle\Repository\CategoryRepositoryInterface for "pim_catalog.repository.category", so has an error 
[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                                       
  Catchable Fatal Error: Argument 4 passed to PimEnterprise\Bundle\ClassificationRuleBundle\Engine\ProductRuleApplier\ProductsUpdater::__construct() must be an instance of Pim\Bundle\CatalogBundle\Repository\  
  CategoryRepositoryInterface, instance of Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\CategoryRepository given, called in /home/dev/www/pim_14branch/app/cache/dev/appDevDebugProjectContai  
  ner.php on line 23026 and defined 

Regards,

Hung

**Comment by nidup** [comment]
Hello Hung,

As you're using the Enterprise Edition you should have access to our HelpDesk that allow us to provide Enterprise Edition support, thank you to use your account to create a ticket.

Thank you,
