### ISSUE TITLE
Rule Engine on Pim enterprise 1.4 has an error.

### ISSUE THREAD

**Issue by hungpq12** [akeneo/pim-community-dev#3379]
rules:
    assign_dwtree_calculate:
        conditions:
            - field:    categories.code
              operator: NOT IN CHILDREN
              value:
                - dw
        actions:
            - type:      set_value
              field:     dw_flag
              value:     '0'
i used above yaml's config to import rule engine but has an error 
An error occured during the import execution.
Error #0 in class Symfony\Component\Debug\Exception\ContextErrorException: Warning: Missing argument 1 for Symfony\Component\Validator\Validator\RecursiveValidator::getMetadataFor(), called in /home/dev/www/pim141/vendor/akeneo/pim-enterprise-dev/src/PimEnterprise/Bundle/CatalogRuleBundle/Connector/Processor/Denormalization/RuleDefinitionProcessor.php on line 76 and defined

Regards,

Hung

**Comment by nidup** [comment]
Hello Hung,

As you're using the Enterprise Edition you should have access to our HelpDesk that allow us to provide Enterprise Edition support, thank you to use your account to create a ticket.

Thank you,
