### ISSUE TITLE
No filters in product grid for attribute groups that contain an underscore

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3406]
When the key of an attribute group contains an underscore character `_`, the filters panel ("Manage filters ...") in the product grid will not get displayed.

Example attribute group:

    attribute_groups:
        my_group1:
            sort_order: 1
            labels:
                en_US: "My group"

Example attributes.csv:

    "type";"code";"label-de_DE";"label-en_US";"group";"unique";"useable_as_grid_filter";"allowed_extensions";"metric_family";"default_metric_unit";"reference_data_name";"localizable";"scopable"
    "pim_catalog_identifier";"SKU";"SKU";"SKU";"general";1;1;;;;;0;0
    "pim_catalog_text";"MATNR";"Material";"Material";"my_group1";0;1;;;;;0;0

=> No filters get displayed.

**Comment by grena** [comment]
Hello @Hocdoc,
Thank your for your feedback!

On which version of the PIM did you have this?
I'll try to reproduce it.

Kind regards,
Adrien.

**Comment by Hocdoc** [comment]
I just tried it again in 1.4.20 where it now works without any problems. 
It seems that the bug got already fixed somewhere in the last versions. Thanks.
