### ISSUE TITLE
User group fixtures: all does not necessarily exist

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3409]
When loading data into the database using fixtures, groups are added to users. Groups are identified by name (since Oro user groups does not have such option as code) with one exception: all.

https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/InstallerBundle/DataFixtures/ORM/LoadUserData.php#L100

This hard coding requires to have a group called all (the name property must be all, not just the 'code'). It should either be declared as a requirement somewhere (is it already?) or should be fixed some other way.

**Comment by nidup** [comment]
Thank you for the feedback!
We would like to introduce code in the group entity to be consistent with all other entities (unique code, readonly once created).
You're right, it should be defined as a requirement in the doc http://docs.akeneo.com/latest/cookbook/setup_data/customize_installer.html (as the fact to have at least a root category and an identifier attribute)
Feel free to do a Pull Request on the documentation to add details https://github.com/akeneo/pim-docs/blob/1.4/cookbook/setup_data/customize_installer.rst
Thanks!

**Comment by damien-carcel** [comment]
Closing this issue as non relevant anymore. Fixtures have reworked as only CSV and YAML since 1.5.
