### ISSUE TITLE
Package separation

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3419]
As I can see, currently everything is in one repository. Will this be changed in the future? Separate packages, etc?

Two things that brought this question up:

- Developing web service: I am going to serve content directly from PIM using webservice and full page caching (at least that's the plan for now instead of using exports)
- Not using webservice: Currently I need it. But what if someone doesn't? Sure, it can be removed from the kernel....

**Comment by nidup** [comment]
Good question!
As you can see most of our pull requests concern several components / bundles, so work in a single repository is really easier.
For now, we don't expose these components and bundles in dedicated repositories but if we would to do so, we would use the same strategy than symfony/symfony, ie do sub tree split in readonly repositories.
You can try to disable several bundles in your AppKernel but depending on cross dependencies between these bundles you can encounter issues.
We're trying to decouple more and more our architecture to be able, for instance, to have different AppKernel with a subset of bundles, for instance, a dedicated kernel for the import/export (without all the UI part).
We would like to expose several separate packages but we still have some work to reach this goal!

**Comment by sagikazarmark** [comment]
Thanks for your response. Actually during early phases, this might not be the most important thing.

Another question: is there any fix/work in progress for installation? Currently it requires about 1.5G RAM to run an update with composer. (Removing VCS repositories from the application and using composer would probably be a bit more lightweight?)

**Comment by nidup** [comment]
I imagine that you encounter this issue with the Enterprise Edition which retrieves community edition sources from vcs.
It's a known issue without fix in progress, in the future, we would put the community bundles on packagist (only the bundles, not the full stack, to do so we need to update and write some scripts), i don't have any ETA for this change.

**Comment by willy-ahva** [comment]
A ticket has been created with the description of your need. Thank you for your feedback :)

**Comment by nidup** [comment]
(btw, we started to do some tests of subtree split + readonly repo with our batch component + bundle, still very experimental for now)
