### ISSUE TITLE
Attribute group sort_order is ignored in the product form

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3424]
In Akeneo 1.4 the attribute group sort order (defined in the field `sort_order` in `attribute_groups.yml`) is ignored when displaying the groups in the product form on the left sidebar.

Instead, the attribute groups are displayed in the definition order. This is also fine, but when the field is ignored please remove the confusing `sort_order` field from the example installation data (minimal+icecat_demo).

**Comment by Afroger** [comment]
Is this bug solved in the Akeneo Version 1.4.11 ?

**Comment by alexisfroger** [comment]
Thank you for your correction ! That works perfectly in version 1.4.13
