### ISSUE TITLE
Non-ascii characters are not displayed in generated PDF

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3428]
Letters like őűúó are replaced with a question mark (?).

**Comment by Hocdoc** [comment]
Maybe this is related to https://github.com/dompdf/dompdf#about-fonts--character-encoding

I haven't tested it, but you may use the parameter `pim_pdf_generator_font` to set a different font (f.ex. DejaVu Sans )

**Comment by sagikazarmark** [comment]
Thanks for the hint, will try it out.

**Comment by jmleroux** [comment]
Thank you to both of you for the feedback.
We're looking forward to hear about this issue.

JM
