### ISSUE TITLE
Attributes are not sorted in "Manage filters" select box

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3435]
Users could add filters with the "Manage filters" link in the product grid. The attributes in the select box are grouped by the attribute groups in the right order. Unfortunately inside of the attribute groups the attributes seem to be unsorted.
It would be easier for the user if they have the same order as in the product form.

**Comment by jmleroux** [comment]
Hi @Hocdoc ,
we will test your issue and integrate it on our tracker if we can reproduce.
Thanks for the feedback.

JM

**Comment by willy-ahva** [comment]
Reproduced in 1.5.1. Easy pick ! Contributors are welcome :)

**Comment by a2xchip** [comment]
What is the current status of this issue @phaseinducer?

**Comment by LaureBro** [comment]
Hello @a2xchip, 

Sorry for the late feedback!
It has been fixed on our Master version that will be released beginning of September.

Best regards, 

Laure

**Comment by nidup** [comment]
Oops, we misunderstood with @LaureBro, this improvement has not been done in our upcoming v1.6.0.

**Comment by a2xchip** [comment]
:-) Could be fixed during #5573

**Comment by Hocdoc** [comment]
Seems to be also fixed in 1.7 :-).
