### ISSUE TITLE
Symfony 3 directory structure

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3436]
As of sensio distribution bundle 4.0, the new directory structure is supported (see it [here](https://github.com/symfony/symfony-standard/tree/master)). I think it would be good to move to that structure right now. It is possible and it will be the new structure anyway (which is much better IMO).

**Comment by jmleroux** [comment]
hello @sagikazarmark ,
this point is on our raodmap for future versions, but not right away because we don't want to break compatibility with existing Akeneo installations.

Thanks for the feedback,
JM
