### ISSUE TITLE
Installation with parameter `--force` fails, if temporary `file_storage`directory doesn't exist

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3448]
A installation with `php app/console pim:install --env=prod --force` fails with Akeneo 1.4.4 if the directory `/tmp/pim/file_storage` doesn't exist (f.ex. after a reboot).

Error message:

    Error during PIM installation. Failed to remove directory "/tmp/pim/file_storage".

I have to restart the installation without the `--force` argument, which works. 
Errors removing the `file_storage` directory should get ignored.

**Comment by Hocdoc** [comment]
Oops. I was wrong, the fault wasn't the `--force` parameter.
There were some problems with the permissions on the `/tmp/pim` directory.
I will close this issue again until I know exactly why I got the error message during the installation.

**Comment by simplenotezy** [comment]
Running `sudo rm -rf /tmp/pim` fixed the issue for me
