### ISSUE TITLE
Broken site following commit 4d079d3d (PIM-4683: fix attribute requirements in updater)

### ISSUE THREAD

**Issue by paulclarkin** [akeneo/pim-community-dev#3461]
My Akeneo Community Dev is broken following a Pull. I've tracked it down to @solivier's commit 4d079d3d5b9acc23a82188ea09b893f5b30fa97c

The site loads with a 500 error, and this in the log.

`
[Sun Oct 25 10:08:54.786814 2015] [:error] [pid 21310] [client 127.0.0.1:59309] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Catchable Fatal Error: Argument 6 passed to Pim\\Component\\Catalog\\Updater\\FamilyUpdater::__construct() must be an instance of Pim\\Bundle\\CatalogBundle\\Doctrine\\ORM\\Repository\\AttributeRequirementRepository, instance of Doctrine\\ORM\\EntityRepository given, called in /home/paul/code/pim-community-dev/app/cache/prod/appProdProjectContainer.php on line 4804 and defined' in /home/paul/code/pim-community-dev/src/Pim/Component/Catalog/Updater/FamilyUpdater.php:69\nStack trace:\n#0 /home/paul/code/pim-community-dev/src/Pim/Component/Catalog/Updater/FamilyUpdater.php(69): Symfony\\Component\\Debug\\ErrorHandler->handleError(4096, 'Argument 6 pass...', '/home/paul/code...', 69, Array)\n#1 /home/paul/code/pim-community-dev/app/cache/prod/appProdProjectContainer.php(4804): Pim\\Component\\Catalog\\Updater\\FamilyUpdater->__construct(Object(Pim\\Bundle\\CatalogBundle\\Doctrine\\ORM\\Repository\\FamilyRepository), Object(Pim\\Bundle\\CatalogBundle\\Fac in /home/paul/code/pim-community-dev/src/Pim/Component/Catalog/Updater/FamilyUpdater.php on line 69, referer: http://akeneo-pim.local/
`

(I've run `rm -rf app/cache/*`)

Is there something I need to do to make this work? Clear/reset something?

**Comment by solivier** [comment]
Hi @paulclarkin,

Sometime the apc cache is not cleared. Could you try to restart Apache and see if it solve the problem ?

**Comment by paulclarkin** [comment]
Looks like that might have sorted it, thanks.

Maybe add a note to the readme?
