### ISSUE TITLE
Creating a new node in the category tree is complicated

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3465]
1. Right click on the parent element
2. Click Create
3. Enter the **category code** (not the label) in the node name (After that the tree becomes unresponsive, you can only modify the newly created element, after that the page refreshes itself)
4. Edit the label

Not sure if it is documented at all.

**Comment by LaureBro** [comment]
Hello, 

The category tree freezes because you need to fill in the properties of the new category. Once you edit the label (and code) and save the category properties, you can edit other categories.
Maybe we'll add a note in our user guides.
Thanks for your feedback.

Best regards, 

Laure

**Comment by sagikazarmark** [comment]
> Once you edit the label (and code)

I think the code is read only at that time. Probably it would be better, if clicking the create would bring up the category editor instead of requiring the code first. Currently you have to input something for the new node, which then is saved as the code. But it seems to be a bit illogical to me: if something, then passing the label there is logical IMO.

**Comment by erfanimani** [comment]
Wow.. Only after 4 hours of Googling/experimenting I finally figured out you need to right click the master category tree to create a subcategory.

**Comment by LaureBro** [comment]
Hello @erfanimani, sorry to read that :/ 
We'll improve the UX in the coming version.
Don't hesitate to check our documentation ([forum](https://www.akeneo.com/forums/), our [user guides](https://www.akeneo.com/user-guide/)) or to get help from the Community [Slack user group](https://akeneopim-ug.slack.com/) for instance.
Kind regards, 
Laure

**Comment by erfanimani** [comment]
Thanks for your response @LaureBro! Much appreciated. I did read the user guide (CE version), but it didn't explicitly show how to add subcategories.

It seems almost silly now, but I think because nowhere in the app the right click command is used, it's something that you don't expect - especially for web-apps. Looking forward to the new changes. Thanks.

**Comment by LaureBro** [comment]
Hi @erfanimani, we'll improve the documentation part too! 
Thanks again for your feedback, can we close this issue? 
I cannot tell you when we'll improve the category node creation, but it will be done. Stay tuned!

**Comment by erfanimani** [comment]
Not a problem. Issue can be closed imo. Thanks.

**Comment by LaureBro** [comment]
Ok thanks!
