### ISSUE TITLE
Category images

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3491]
Do you think it is possible with the current Doctrine/Form types to add an image field to categories?

I am aware of this page:

http://docs.akeneo.com/latest/cookbook/category/add-properties-to-category.html

However I haven't started researching whether this is possible at all.

**Comment by willy-ahva** [comment]
Hi,

If you only want to add an image field in the category I don't see pb to do it. You just have to follow the guide you linked and then custom form to be able to receive/display an image. I think you can use our FileStorage component to link FileInfo to your Category.
You'll have to custom category export if you want to be able to export images.

Regards, Willy
