### ISSUE TITLE
Family attributes

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3492]
Can I add custom attributes to families as well?

Based on this guide, I can in case of Categories:

http://docs.akeneo.com/latest/cookbook/category/add-properties-to-category.html

**Comment by willy-ahva** [comment]
Hi !

I see no pb to do it but I'm pretty curious to know your use case. Could you explain which type of attribute you want to add to the Family ?

Thank you :)
Willy

**Comment by aRn0D** [comment]
Yes it is possible! I close this issue, if you need more information do not hesitate to re open it!
