### ISSUE TITLE
Better WYSIWYG editor

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3507]
The current HTML editor is not really featureful. Is it possible to replace it? (Either per application, or globally in akeneo)

**Comment by jmleroux** [comment]
The WYSIWYG integration is done in just one file, so i'd say yes.

You can find the instantiation in this file : https://github.com/akeneo/pim-community-dev/blob/9bc4e089f25f9cfd3e26a22681713cfd278a407e/src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js#L31

Regards,
JM
