### ISSUE TITLE
Uploaded picture not showing

### ISSUE THREAD

**Issue by clicktrend** [akeneo/pim-community-dev#3553]
After uploading an image file the thumbnail is not working. You see only the default "?" (question mark picture). After saving the product it's visible.

The uploaded picture is saved in "tmp" directory correctly. But it cannot be shown because of the query in FileController.php line 83

    $file = $this->fileInfoRepository->findOneByIdentifier($filename);

This is NULL because the file is not saved yet.

My PIM version is 1.4.5

**Comment by jmleroux** [comment]
Hi @clicktrend 

Thanks for your report, we will integrate this issue in our internal bug tracker.

Regards,
JM

**Comment by userz58** [comment]
the same problem with a missing thumbnail in varian groups

**Comment by nidup** [comment]
Hi,

Thank you for raising this issue!

@clicktrend this improvement has been done by @pierallard in the v1.5.4 for the product edit form :tada: 

@userz58 this improvement has been applied for the variant group edit form in the upcoming v1.6.0 :tada: 

Have a good day!
