### ISSUE TITLE
where i can disable removing media file after removing field?

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#3572]
i would like use HASH parameter to upload and save only unique files Akeneo\Component\FileStorage\Model\FileInfo
Akeneo\Component\FileStorage\File\FileStorer

i have problem: when i click on media field on trash icon - file will saved in DB.

when i will add to product additional field "PDF description" (and upload file).
if i will remove additional field - file will be deleted from DB.

where i can disable removing file when field removing?

**Comment by userz58** [comment]
Pim\Bundle\CatalogBundle\Model\ProductValue:
    type: entity
    table: pim_catalog_product_value
    changeTrackingPolicy: DEFERRED_EXPLICIT
    indexes:
        value_idx:
            columns:
                - attribute_id
                - locale_code
                - scope_code
        varchar_idx:
            columns:
                - value_string
        integer_idx:
            columns:
                - value_integer
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        varchar:
            type: string
            length: 255
            nullable: true
            column: value_string
        integer:
            type: integer
            nullable: true
            column: value_integer
        decimal:
            type: decimal
            scale: 4
            precision: 14
            nullable: true
            column: value_decimal
        boolean:
            type: boolean
            nullable: true
            column: value_boolean
        text:
            type: text
            nullable: true
            column: value_text
        date:
            type: date
            nullable: true
            column: value_date
        datetime:
            type: datetime
            nullable: true
            column: value_datetime
        locale:
            type: string
            length: 20
            nullable: true
            column: locale_code
        scope:
            type: string
            length: 100
            nullable: true
            column: scope_code
    manyToOne:
        attribute:
            targetEntity: Pim\Bundle\CatalogBundle\Model\AttributeInterface
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
        option:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AttributeOption
            cascade:
                - persist
                - refresh
            joinColumns:
                option_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        entity:
            targetEntity: Pim\Bundle\CatalogBundle\Model\ProductInterface
            inversedBy: values
            joinColumns:
                entity_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        media:
            targetEntity: Akeneo\Component\FileStorage\Model\FileInfoInterface
            cascade:
                #- remove
                - persist
                - refresh
                - detach
            joinColumns:
                media_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    manyToMany:
        options:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AttributeOption
            cascade:
                - refresh
            joinTable:
                name: pim_catalog_product_value_option
                joinColumns:
                    value_id:
                        referencedColumnName: id
                        nullable: true
                        onDelete: CASCADE
                inverseJoinColumns:
                    option_id:
                        referencedColumnName: id
                        nullable: true
                        onDelete: CASCADE
    oneToOne:
        metric:
            targetEntity: Pim\Bundle\CatalogBundle\Model\MetricInterface
            cascade:
                - remove
                - persist
                - refresh
                - detach
            inversedBy: value
            joinColumns:
                metric_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    oneToMany:
        prices:
            targetEntity: Pim\Bundle\CatalogBundle\Model\ProductPriceInterface
            cascade:
                - remove
                - persist
                - refresh
                - detach
            mappedBy: value

**Comment by juliensnz** [comment]
Hello @userz58,

What you try to achieve is already the normal behaviour on Akeneo PIM:
When a media is removed from a product field, we keep it in the media table and keep it on the file system. We only break the relation between the product value and the media in database.

Did I miss something ?

Regards,

Julien

**Comment by userz58** [comment]
when you detele additional field - file will be deleted too.

**Comment by juliensnz** [comment]
Which version of the PIM are you using ?

**Comment by userz58** [comment]
1.4.8

**Comment by juliensnz** [comment]
I just checked on 1.4.12:

I go to a product with a media attached to it. I remove it and save the product.

The media is still on the mysql table and on the file system.

Could you update to try it ?

**Comment by userz58** [comment]
1 you open saved product.
2 add new media field
3 upload image or pdf
4 save product
----
5 remove FIELD (don't click trash icon)
6 save
file will be deleted from DB

**Comment by userz58** [comment]
![scr](https://cloud.githubusercontent.com/assets/2612186/13501267/053824c2-e177-11e5-9f6d-bb243595d5b6.jpg)

**Comment by willy-ahva** [comment]
Hi userz58 !

I reproduced a part of the behaviour you described in the 1.5.1. When I remove the custom media attribute from the product the file is not removed from the file storage but it is removed from the database.

I added a ticket for this. Thanks for your feedback :)

**Comment by willy-ahva** [comment]
I labelized this issue to Bug. You're very welcome to contribute and fix this bug, if you need help or if you have question don't hesitate to ask :)

Regards, Willy

**Comment by damien-carcel** [comment]
Hello.

This bug has just been fixed on our 1.5 branch. It will be out with our next 1.5 patch coming this week.

Regards,
Damien
