### ISSUE TITLE
Product grid: Columns order lost

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3591]
The order of the columns in the product grid gets lost (Akeneo 1.4.9):

1. Click the "Columns" button in the product grid and change the order of the displayed columns
2. Click "Apply"
3. Click the "Columns" button again => the columns are in the old order again

**Comment by LaureBro** [comment]
Hello Hocdoc, 

Thanks for your message, we have noticed this bug and are currently working on it, we'll keep you updated.

Best regards, 

Laure

**Comment by Hocdoc** [comment]
Fixed in Akeneo 1.4.11.
