### ISSUE TITLE
Race condition while editing product associations

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3594]
1. Edit the associations of a product: On the left sidebar click on the second (or third...) association group and check a product to associate it.
2. Save the product
3. After the `Product successfully updated.` message you will get "redirected" to the first association group again. Quickly click on the second association group again **before** the grid is rendered (this doesn't work in the Akeneo Icecat demo because there are so few products, but for our system the rendering takes about 5 seconds).

=> The saved associations of the second group get not displayed. Only after reloading the whole page the associations will appear again. 

(Akeneo 1.4.9 with 150,000 products)

**Comment by LaureBro** [comment]
Hello Hocdoc, 
Do you still have the issue on the 1.4.12? 
I'm not sure I understand the issue, is it a performance issue: the page is long to load and associated products are not displayed, am I right?

Thanks!

**Comment by juliensnz** [comment]
Hello @Hocdoc,

This is definitely a bug. I create a bug in our bug tracker right away.

Regards,

Julien

**Comment by Hocdoc** [comment]
The issue is still there in 1.4.12. Thanks for the bug tracking.

**Comment by nidup** [comment]
Reproduced on upcoming 1.6.0 too.

**Comment by LaureBro** [comment]
Hi @Hocdoc, I could not reproduce this issue on the current 1.6 (1.6.9) can you confirm me it's working fine on your side too?

Thanks a lot, 

Laure

**Comment by Hocdoc** [comment]
We're still using Akeneo 1.5, so unfortunately I cannot test it. 
We may switch next month to 1.6, then I will test the issue again with our big&slow ;-) product database.

**Comment by LaureBro** [comment]
Ok thanks for your quick feedback, I hope you'll switch soon on 1.6 :) ! 
We've really improved the context on Associations on 1.6. Now when you save a new product association or group association you remain on the association type selected, the filters also remain.. The user experience is much better!

**Comment by Hocdoc** [comment]
Seems to be fixed (tested on 1.7). Thanks for the fix.
