### ISSUE TITLE
Cannot assign product to categories that have a whole number as the category code

### ISSUE THREAD

**Issue by DrewK289** [akeneo/pim-community-dev#3686]
If category code is a whole number, javascript parses it as an integer when submitting the POST, and causes the CategoryFieldSetter class to throw the following exception:

`500 Internal Server Error - InvalidArgumentException
Attribute or field "categories" expects an array with a string value for the key "1", "integer" given (for setter category).`

This is being thrown on line 89 of "Pim\Component\Catalog\Updater\Setter\CategoryFieldSetter"

**Comment by juliensnz** [comment]
Hello @DrewK289,

It's definitely a problem. I add it to our bug tracker.

Thanks a lot for the report.

Regards

**Comment by LaureBro** [comment]
Hello, 

FYI, we are now working on a fix for this issue.
A patch should be available shortly, we'll keep you updated.

Best regards, 

Laure

**Comment by LaureBro** [comment]
Hello @DrewK289,

This issue has been fixed in the 1.4.16 version, issue ref. PIM-5331

Best regards, 

Laure

**Comment by a2xchip** [comment]
@juliensnz Can't we close it?
