### ISSUE TITLE
Order attributes are ignored in the product form

### ISSUE THREAD

**Issue by alexisfroger** [akeneo/pim-community-dev#3698]
I believe is the same problem that akeneo's forum (http://www.akeneo.com/forums/topic/attributes-order-2/) but there was no solution ! Or similar at this issue #3424 about the attribute groups order.

Version akeneo : 1.4.11

Indeed when I sort my attributes (with the drag and drop in the right column) in Settings/Attribute Groups 

*Attribute groups screenshot*
![image](https://cloud.githubusercontent.com/assets/15442639/11557458/163b669c-99ad-11e5-8b9f-22851ee34737.png)

and I add this attribut in my families, the attributes order are not respected in the families form and in the product form (All my attributes are added in my families).

*Families screenshot*
![image](https://cloud.githubusercontent.com/assets/15442639/11557992/3ec85d10-99b0-11e5-886e-627f361bf8d8.png)

When I created a product, it's the order of the attributes creation in Akeneo ! 

*Products screenshot*
![image](https://cloud.githubusercontent.com/assets/15442639/11557529/69bfb52a-99ad-11e5-9250-c0d3e6336b45.png)

Thank you in advance for your answer.

**Comment by LaureBro** [comment]
Hello Alexis, 

Thanks your message! We have noticed this issue too, sorry for that, it should be fixed in the next patch - that will be released this week. I'll keep you updated.

Best regards, 

Laure

**Comment by juliensnz** [comment]
Here is the related pull request: https://github.com/akeneo/pim-community-dev/pull/3721 

I close the issue, thanks a lot for this report !
