### ISSUE TITLE
Doctrine\ORM\AbstractQuery "use" statement missing in Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\AbstractItemCategoryRepository

### ISSUE THREAD

**Issue by DrewK289** [akeneo/pim-community-dev#3704]
The getItemIdsInCategory() function uses "AbstractQuery::HYDRATE_ARRAY" (line 86), but the AbstractQuery class is missing the "use" statement in the AbstractItemCategoryRepository class, causing PHP to throw a fatal error:
`PHP Fatal error:  Class 'Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\AbstractQuery' not found in /opt/data/apps/pim-dev/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/AbstractItemCategoryRepository.php on line 86`

The AbstractItemCategoryRepository class should include "`use Doctrine\ORM\AbstractQuery;`"

**Comment by juliensnz** [comment]
Hello @DrewK289,

Definitely a bug, I propose  a bug fix right away. 

Regards,

Julien

**Comment by nidup** [comment]
Thank you for your valuable feedback, it has been fixed in v1.4.13.
