### ISSUE TITLE
How to create custom data grid using Akeneo

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3719]
Hi there, I want to add some custom page to Akeneo, and render there grid with some custom data, but I faced problem. I am including macros.html.twig to my page, then calls macro to build grid, path there name of route for fetch my data from. But I getting error about required parameter `locale_code`. So I trying to fix that but didnt get any results. So can somebody help me? I know that not issue as well. But on Akeneo forum my question was ignored. So I decide to ask developers directly. :smiley: 

Best, regards.

**Comment by juliensnz** [comment]
Responded on the forum: http://www.akeneo.com/forums/topic/create-grid-base-on-akeneo-components/#post-6412
