### ISSUE TITLE
Classes implementing ArchivableWriterInterface consumes too much resources

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#3783]
I created a connector that exports to CSV using `Pim\Bundle\BaseConnectorBundle\Writer\File\CsvWriter` and its descendents for variant group and products.

When I'm exporting my products with images, a zip file seems to be generated, due to the implementation of interface `Pim\Bundle\BaseConnectorBundle\Writer\File\ArchivableWriterInterface`. This file generation seems to generate the file in-memory in the first place. I currently have an export of ~2200 products with an average of 3 HD images for each product.

The images folder weights 13Gb, the server does not have this amount of RAM and nevertheless it should not consume that much. If I remove the interface from the `CsvWriter` class, everything works fine (I do not need this zip file).

By quickly reading the sources, I can see that the zip file generation uses `thephpleague/flysystem`, with a lot of calls to `file_get_contents`. Maybe using streams interface of Flysystem instead of string interface make the memory consumption much lower.

Gregory

**Comment by gplanchat** [comment]
Seems like there is the same issue here :

http://www.akeneo.com/forums/topic/issues-when-running-job-via-terminal/#post-6519

**Comment by nidup** [comment]
This is a known issue, we're discussing with product owner to decide what is the best approach to better handled this case (we're preparing a set of features to enhance the export part).

It could be an extra step which zip (or copy files to a configured server), from design point of view, it should not come from the implementation of an interface (at least not natively).

**Comment by gplanchat** [comment]
Maybe an optional `Job` item named `archive`, in addition to `reader`, `processor` and `writer` could do the trick, be very explicit and be easy to implement

**Comment by willy-ahva** [comment]
We are currently working on refactoring the Archiver on the master branch. It'll fix your problem. More information later ;)
Thank you for the feedback !

**Comment by willy-ahva** [comment]
@gplanchat can you give me the version you're working on please ? You can check this documentation to disable the archiver or create your own one : http://docs.akeneo.com/1.4/reference/scalability_guide/more_than_1GB_of_product_media_to_export.html Available since v1.4 :)
Thank you for your feedback !

**Comment by gplanchat** [comment]
Hello @willy-ahva,

Did the 1.6 changes in the `AkeneoBatchBundle` fixed this issue ?

Grégory

**Comment by gplanchat** [comment]
This seems to be a bit outdated now
