### ISSUE TITLE
Akeneo shows 500 internel server error while connect with MongoDb

### ISSUE THREAD

**Issue by ewallteam** [akeneo/pim-community-dev#3786]
Hi,
I have installed Akeneo and MongoDb by using Bitnami stack with two different instance on Google cloud. The Akeneo perfoming well with MySql connection but dose work and show the Internal server error with MongoDb connection moreover the Installation was completed successfully with MongoDb. Don't know why its shows the internal server error after the installation, Can anyone help me to resolve the issue?
Below is the error what I got from error log
>[Mon Dec 21 04:47:08.509983 2015] [ssl:warn] [pid 21089:tid 140465885460224] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the 
server name [Mon Dec 21 04:47:08.552914 2015] [ssl:warn] [pid 21090:tid 140465885460224] AH01909: localhost:443:0 server certificate does NOT include an ID which
matches the server name [Mon Dec 21 04:47:08.553033 2015] [lbmethod_heartbeat:notice] [pid 21090:tid 140465885460224] AH02282: No slotmem from mod_heartmonitor
[Mon Dec 21 04:47:08.569298 2015] [mpm_event:notice] [pid 21090:tid 140465885460224] AH00489: Apache/2.4.17 (Unix) OpenSSL/1.0.1q configured -- resuming normal 
operations [Mon Dec 21 04:47:08.569333 2015] [core:notice] [pid 21090:tid 140465885460224] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -f
/opt/bitnami/apache2/conf/httpd.conf' [Mon Dec 21 04:47:23.430368 2015] [proxy_fcgi:error] [pid 21098:tid 140465256888064] [client 103.242.236.163:58529] AH01071:
Got error 'PHP message: PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to write cache file
"/opt/bitnami/apps/akeneo/htdocs/app/cache/prod/classes.php".' in
/opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0
/opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122):
Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/opt/bitnami/ap...', '<?php \\nnamespac...')\n#1
/opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2557): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/opt/bitnami/ap...',
'classes', false, false, '.php')\n#2 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2392):
Symfony\\Component\\HttpKernel\\Kernel->doLoadClassCache('classes', '.php')\n#3 /opt/bitnami/apps/akeneo/htdocs/app/bootstrap.php.cache(2426):
Symfony\\Component\\HttpKernel\\Kernel->boot()\n#4 /opt/bitnami/apps/akeneo/htdocs/web/a...\n'
[Mon Dec 21 06:15:29.778054 2015] [proxy_fcgi:error] [pid 21097:tid 140465600988928] [client 103.242.236.163:315
19] AH01071: Got error 'PHP message: PHP Fatal error:  Class 'Mongo' not found in /opt/bitnami/apps/akeneo/htdoc
s/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php on line 284\n'
[Mon Dec 21 06:20:19.264281 2015] [proxy_fcgi:error] [pid 21096:tid 140465223317248] [client 103.242.236.163:329
18] AH01071: Got error 'PHP message: PHP Fatal error:  Class 'Mongo' not found in /opt/bitnami/apps/akeneo/htdoc
s/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php on line 284\n'

**Comment by nidup** [comment]
Hi,
It looks like the PHP Mongo driver is not even installed, i guess there is an installation problem.
How did you installed Akeneo PIM with MongoDB storage with bitnami?
Are you able to connect to your MongoDB server to check if there is any data in the product collection?

**Comment by ewallteam** [comment]
Hi @nidup ,

Thanks for your response, yes you are correct, issue is related to "Mongo" PHP driver but I have installed the same and enabled it on php.ini but my phpinfo() dose not show anything about Mongo driver. I have used the Bitnami Akeneo stack on Google Debian instance, moreover the Database and some collections are created during the installation but it's not working after the installation. Do have any idea?

**Comment by nidup** [comment]
Hi,
If installation properly works but application does not work via a browser i would say Mongo is enabled for PHP cli in /etc/php5/cli/php.ini and not enabled for PHP apache in /etc/php5/apache2/php.ini. If mongo is well enabled in this php.ini, it should appear in phpinfo, have you restarted/reloaded apache to refresh the apache configuration ?

**Comment by ewallteam** [comment]
Hi @nidup 
I have seen the "Loaded Configuration File" is "opt/bitnami/php/etc/php.ini" in the browser and I have added the Mongo driver extension on the same and restart the apache but still I got the same error.
Thanks.

**Comment by nidup** [comment]
Hi @ewallteam,

Weird, I don't really know how to work the Bitnami stack, could you ask to the Bitnami support why the driver is not properly loaded, maybe there is some custom conf in their stack ?
I think other users may have the same issue than you and will be interested to know what is the change to apply.

Thank you!

**Comment by ewallteam** [comment]
Thanks @nidup 
I have raised same question on Bitnami forum and waiting for their response. Moreover thanks for your great support and quick response. Thanks :-)
