### ISSUE TITLE
Multiselect field type for item step getConfigurationFields()

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3797]
Hello, I am working on creation one batch job. And I want to make some configuration parameter as multiselect option. So, I configured field like in the example below:

```php
 public function getConfigurationFields()
    {
        return [
            'deliveries' => [
                'type'    => 'choice',
                'options' => [
                    'choices'      => ['test1', 'test2'],
                    'required'     => true,
                    'select2'      => true,
                    'expanded'  => true,
                    'multiple'     => true,
                    'label'          => 'deliveries.label',
                    'help'           => 'deliveries.help'
                ]
            ],
        ];
    }
```
I configured my job, and save it with both selected parameters. But when went to Job view page, I got exception:

```
An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in PimImportExportBundle:JobProfile:_show_form.html.twig at line 13.
```

So after some debugging process I found that you handle `choice` field type in your Twig filter `normalizeFieldValue` only when `data`  of `element.vars` is equal to string. But in that case it is equal to array. So I decided to override template with a bit of custom logic. But I don't know what items are selected, because `data` returns me an array that looks like:

```twig
array:2 [
  1 =>1
  0 =>0
]
```
So can somebody help me to find place where that array is preparing? Or give some advice how this should be handled? Thanks!

**Comment by gplanchat** [comment]
Wouldn't it be this configuration for `options` attribute?

```php
    public function getConfigurationFields()
    {
        return [
            'deliveries' => [
                'type'    => 'choice',
                'options' => [
                    'choices'      => [
                        'test1' => 'Test 1',
                        'test2' => 'Test 2',
                    ],
                    'required'     => true,
                    'select2'      => true,
                    'expanded'  => true,
                    'multiple'     => true,
                    'label'          => 'deliveries.label',
                    'help'           => 'deliveries.help'
                ]
            ],
        ];
    }
```

**Comment by NovikovViktor** [comment]
@gplanchat , yes that is the point about returned array, thanks. But I still need to add custom logic to output data, if it in array format. So this thing I suppose should be handled by Akeneo.

**Comment by gplanchat** [comment]
I don't understand your need, what do you mean by "But I still need to add custom logic to output data, if it in array format."?

**Comment by NovikovViktor** [comment]
@gplanchat , I mean that I still need override `_show_form.html.twig` template, as it is expects that data will be in string formmat, not in array.

**Comment by gplanchat** [comment]
Why do you need an array? I think you are trying to solve the problem with the wrong solution.

Your option selector can help you to pick a service in the DI, which will be much effective than trying to hack Akeneo's templates. To do this, you may have to create a new compiler pass in your bundle and use service tags in your select values : http://symfony.com/doc/current/components/dependency_injection/tags.html#create-a-compilerpass

**Comment by gplanchat** [comment]
Maybe this change in a previous tweet could also be a response to your issue :

https://twitter.com/gplanchat/status/674617531009794048

https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/ImportExportBundle/Twig/NormalizeConfigurationExtension.php#L71

**Comment by NovikovViktor** [comment]
@gplanchat , thanks for last note. I am used older version so need to update right now :+1:

**Comment by nidup** [comment]
Great, thx @gplanchat for the support :)
