### ISSUE TITLE
Accessing private property in child class

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3803]
Hello, found a little strange issue in both adapters [here](https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/FilterBundle/Datasource/Orm). There you are trying access property `$expressionBuilder`. How this working?

**Comment by nidup** [comment]
Hi,

It's a legacy override of an old version of OroOrmFilterDatasourceAdapter, the ExpressionBuilder is instanciated here https://github.com/akeneo/pim-community-dev/blob/master/src/Oro/Bundle/FilterBundle/Datasource/Orm/OrmFilterDatasourceAdapter.php#L87 

What is the issue you encountering?

**Comment by NovikovViktor** [comment]
@nidup, hello, thanks for reply. It is not isssue as well, but it seems strange, that you "override" this property. It is unclearly how it is working, I mean that `expressionBuilder` is defined as private, so it cannot be accessed from children classs.

**Comment by pierallard** [comment]
Hi @NovikovViktor 
As there was no new activity on this post since more than 1 year, I permit myself to close the card ;)
Please feel free to re-open this issue if you have issues using this code classes :)

Regards
Pierre
