### ISSUE TITLE
Custom filtering products by scope code

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3807]
Hello, I am building grid with custom products output. I want to filter my products in all existing channels. So I went to documentation and found this [article](http://docs.akeneo.com/latest/cookbook/catalog/product/query.html#build-a-query), I tried to add scope filter:
```php
$grid->getDatasource()->getProductQueryBuilder()->addFilter('scope ', 'IN', ['channel1', 'channel2']);
```
But I got exception with message: `Filter on field "scope" is not supported`.
The same happened on `scope_code` etc. So I went deeper and found that there is no filter for scope. So could you please clarify how can I solve this and add custom multi-scope filter?

Regards, Victor.

**Comment by NovikovViktor** [comment]
When grid is rendering  it fetches product values for all scopes, but when I try to filter values by some attribute, it fetches data (attribute values) only per current grid scope. So the main problem is to find endpoint where this action performs. Could somebody clarify how it works please?

**Comment by NovikovViktor** [comment]
@nidup , we have solved this by creating custom filter type and custom ValueJoin for it. So this issue-question can be marked as closed. Thanks for attention :laughing:

**Comment by nidup** [comment]
Hi @NovikovViktor, thank you for the feedback and sorry for the no answer :(
