### ISSUE TITLE
Redundant dataLocale parameter in JavaScript route generation

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3817]
Hello, I have question. What is the reason to pass dataLocale as parameter for route [here](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/configure-columns-action.js#LC231), if in route definition dataLocale doesn't mentioned?
[routingDefinition](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/DataGridBundle/Resources/config/routing/datagrid_view.yml#LC9)
[controller action](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/DataGridBundle/Controller/DatagridViewController.php#LC145)

Regards, Victor.

**Comment by nidup** [comment]
I would say to localize the attribute label by using the locale selected in the locale switcher of the grid.
I do agree, it looks weird from routing point of view :)

**Comment by NovikovViktor** [comment]
@nidup , so is it made as "look to the future" ?

**Comment by nidup** [comment]
In the popin, the attribute labels are already translated depending on the selected data locale in the switcher (passed as dataLocale). The UI (titles, labels, buttons) is translated depending on the language selected in system / config (BTW, we reworked the localization part in the upcoming 1.5 to allow a different UI language per user).

So, it's an inconsistency in the code, dataLocale should be specified in the routing too.

By the way, I would thank you for creating the organisation https://github.com/FriendsOfAkeneo and by contributing new bundles! That's great!

Would you be interested to contribute to pim-community-dev repository? I would be glad to count you as our contributors, if you're interested, I will be happy to discuss with you to ease the merge of your PRs, I would ask you to read and sign our contributor agreement http://www.akeneo.com/contributor-license-agreement :)

**Comment by NovikovViktor** [comment]
Hello, @nidup , sorry for such long term answer. Sure, I would be glad to help.

**Comment by NovikovViktor** [comment]
I consider this issue as not relevant anymore, so mark it as Closed.
