### ISSUE TITLE
Decimal fields should respect locale

### ISSUE THREAD

**Issue by mathielen** [akeneo/pim-community-dev#3828]
We are using the german translation of akeneo. So the user is also expecting the system to accept german number notation. i.e. "1.234,56" in the relevant fields (numbers, prices, metrics, etc).
Right now, the system forces the user to input us-style numbers, i.e. 1234.56 (the "," seems to be forbidden).

**Comment by skeleton** [comment]
Hi @mathielen ,

this functionality is on track for 1.5 version :)

Regards, 

Skeleton

**Comment by LaureBro** [comment]
Hello @mathielen, 

The 1.5 is now out, and the numbers, prices, metrics are now localised depending on the UI locale set in your user account. 

This feature cannot be backported in lower versions.

Best regards, 

Laure

**Comment by mathielen** [comment]
Works fine with 1.5. Thank you.
