### ISSUE TITLE
Product Export always shows empty

### ISSUE THREAD

**Issue by ewallteam** [akeneo/pim-community-dev#3841]
Hi all,

I have used the Akeneo latest version, and imported products more than 12000  into it. But when I have export the products it show empty result. Can anyone help me resolve the same.

Thanks

**Comment by skeleton** [comment]
Hi @ewallteam ,

Export products exports only products by a channel and with a 100% completeness (if you want to know more about it, you can read the [documentation](http://docs.akeneo.com/latest/userguide/keyconcepts.html?highlight=completeness#what-is-completeness)). 
You can check how many products are complete in the product datagrid with the filter "complete".

Regards, 

Skeleton

**Comment by ewallteam** [comment]
Hi @skeleton 

Thanks for your quick reply,
All my products having the 100% completeness but no luck.Do you Have any Idea to resolve this?

**Comment by skeleton** [comment]
Is there any informations in your logs (symfony and apache) ?
Do you use the standard export or do you have a customization ?

**Comment by ewallteam** [comment]
Hi @skeleton 

I have found only the batch log from the location app/log/ which have the below details,
>[2016-01-07 09:54:49] batch.DEBUG: Job execution starting: startTime=, endTime=, updatedTime=, status=2, exitStatus=, exitDescription=[],
job=[export_product_after_upgrade] [] [] [2016-01-07 09:54:49] batch.INFO: Step execution starting: id=0, name=[pim_enhanced_connector.export.product.title],
status=[2], exitCode=[EXECUTING], exitDescription=[] [] [] [2016-01-07 09:54:49] batch.DEBUG: Step execution success: id= 734 [] [] [2016-01-07 09:54:49]
batch.DEBUG: Step execution complete: id=734, name=[pim_enhanced_connector.export.product.title], status=[1], exitCode=[EXECUTING], exitDescription=[] [] []
[2016-01-07 09:54:49] batch.DEBUG: Upgrading JobExecution status: startTime=2016-01-07T09:54:49+00:00, endTime=, updatedTime=, status=3, exitStatus=,
exitDescription=[], job=[export_product_after_upgrade] [] []


apache and other error logs has no details.

Also we have installed and used the Enhanced Connector Bundle but native connector also not working.

**Comment by erfanimani** [comment]
@ewallteam did you manage to solve this issue? My exports also show up empty.. 0 bytes

**Comment by guillaume-netapsys** [comment]
@erfanimani 
Following Akeneo's documentation and my experience, there are 4 requirements for correct product exports : 
- enabled
- categorised in the channel's category tree
- completion (following export profile config)
- product must have a family
