### ISSUE TITLE
Suggestion about Akeneo attributes

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3873]
Hello, to my point of view it would be great, if there was mechanism to add custom extra attribute properties. For example, some boolean flag to make product attribute disabled on edit screen. I know it might be complicated in providing, and can seriously touch existent database schema.

**Comment by mathewrapid** [comment]
@NovikovViktor have you made any progress yourself with this?

We've been workin on readonly flags for attributes, not nearly ready to open source it though.

**Comment by NovikovViktor** [comment]
@mathewrapid we didn't work on this

**Comment by LaureBro** [comment]
Hello @NovikovViktor, did you check out our 1.6 feature on read-only attributes?
You can now define in the attribute property that an attribute is read-only, meaning it cannot be edited but only viewed.
If this matches your request, please let me know if we can close this issue :)

Regards, 

Laure

**Comment by NovikovViktor** [comment]
Hello @LaureBro 
First I would like to say that updated design of 1.6 looks really awesome!
I have checked the demo page (attribute config page) but I didn't find an option for making attribute read-only, or this could be done from some other page?

Best regards, Viktor

**Comment by LaureBro** [comment]
Hello @NovikovViktor, 
Thanks for your feedback! 
I'm sorry because it's actually an Enterprise Edition feature :/
It looks like this in the attribute edit form (bottom of the page).
![screen shot 2017-01-26 at 16 51 40](https://cloud.githubusercontent.com/assets/13367999/22338496/d1f993d8-e3e7-11e6-8d54-e83886b3c22e.png)

Kind regards, 

Laure

**Comment by LaureBro** [comment]
Hi @NovikovViktor, since this feature already exists (but in the licensed Edition), do you agree to close this issue? 
It's not planned to report it in the CE version, we'll keep you updated if we do.

Kind regards, 
Laure

**Comment by NovikovViktor** [comment]
Hello @LaureBro sure, you can close this issue.

**Comment by LaureBro** [comment]
Hi @NovikovViktor, 
thanks for your feedback, I'll close this issue.
