### ISSUE TITLE
Add a new group directly in the product form

### ISSUE THREAD

**Issue by alexisfroger** [akeneo/pim-community-dev#3892]
Hi,

If my product doesn't have group, is it possible to add a new group directly in the product form ?

![image](https://cloud.githubusercontent.com/assets/15442639/12389312/20217b34-bdd8-11e5-9c86-7dfbd3aeb312.png)

Today, there is not group attribute when I create a new product :

![image](https://cloud.githubusercontent.com/assets/15442639/12389361/748524d2-bdd8-11e5-9dad-f2e5d38bc6ab.png)

**Comment by LaureBro** [comment]
Hello,

thanks for your message, unfortunately, it is not possible: you have to add a product to a group in Enrich/Groups (or Variant groups) menu. 
Please note that a group is not considered as an 'attribute' but as a feature that allows to gather products. The Group information is only displayed when a product already belongs to a group.

Best regards, 

Laure
