### ISSUE TITLE
Associations products not saved

### ISSUE THREAD

**Issue by lpxavi** [akeneo/pim-community-dev#3918]
Hello,

when I try to associate a product with another product, the association isn't always saved.

I noted when this problem occured, if I load the home page and I refresh browser cache, the association's products backup run at new.

Someone noted this problem yet ?

Thank's !

**Comment by LaureBro** [comment]
Hello Xavier, 

I have tried to reproduce your issue on demo.akeneo.com, but could not succeed into.

Could you give us more details about the step taken? 
Did you make some specific customisation on the PIM?

Thanks a lot, 

Laure

**Comment by lpxavi** [comment]
Hello Laure,

thank's you for your assistance.

We have find the problem.

First, we had a corrupted database.

Second, the association does't work when we don't wait the end of ajax loading before select the product to associate.

Thank's !
