### ISSUE TITLE
ProductQueryBuilder and default_locale & default_scope

### ISSUE THREAD

**Issue by mathielen** [akeneo/pim-community-dev#3931]
Hi there,

When I am using the ProductQueryBuilder with the default_locale and default_scope options I would expect that these defaults are in effect when using the ->getValue(...) methods of the resulting products. But obviously its not. Do I misunderstood something or is it a bug?

```php
$products = $this->getContainer()->get('pim_catalog.query.product_query_builder_factory')->create([
    'default_locale' => 'de_DE',
    'default_scope' => 'ecommerce'
])->execute();

foreach ($products as $product) {
    echo $product->getValue('description', 'de_DE', 'ecommerce')->getData()."\n"; //works
    echo $product->getValue('description')->getData()."\n"; //does not work as the value is null
}
```

Best regards
Markus

**Comment by jmleroux** [comment]
Hi @mathielen ,

This is not a bug, the default context is used to fulfil locale and scope parameter when we filter on a attribute without providing locale and scope, in the query in fact. It does not affect the objects hydration (the product values) after the filtering.

Regards,
JM

**Comment by mathielen** [comment]
Ok, just thought it would make sense to use the defaults while hydrating, too. Nevermind :)
