### ISSUE TITLE
1.5.0 Alpha1 -  PHP Fatal error:  Class 'Oro\Bundle\UserBundle\Form\Type\UserType' not found in 'Oro\Bundle\UserBundle\Form\Type\UserApiType'

### ISSUE THREAD

**Issue by mathielen** [akeneo/pim-community-dev#3950]
...after installing akeneo 1.5.0A1 via composer

**Comment by jmleroux** [comment]
Hello @mathielen ,

did your clear all your caches ?
Symfony chaches, but also APC cache (an apache restart will clean it automatically).

Regards,
JM

**Comment by mathielen** [comment]
Hi @jmleroux,

Yes, I think so. Not sure if I got everything right, but if you have a look at https://github.com/akeneo/pim-community-dev/tree/master/src/Oro/Bundle/UserBundle/Form/Type you won't find a class UserType there, as in the previous 1.4 versions. I think the class is just missing...

Regards
Markus

**Comment by mathielen** [comment]
Same with BETA1

**Comment by mathielen** [comment]
I kind of fixed this problem in #4039. Not sure if the imported UserType class is the right one, though.

The reason why I was the only one getting this error was: I also used the JMSDiExtraBundle which in turn scans all the classes for annotations when building its cache. So it scanned the UserApiType class and did not find the base class => Exception.

Works with #4039.
