### ISSUE TITLE
Question : check all categories above ?

### ISSUE THREAD

**Issue by alexisfroger** [akeneo/pim-community-dev#3959]
Hi,

I have a question about categories. When I check a category box in the product form, is it possible to check all categories above ?

![image](https://cloud.githubusercontent.com/assets/15442639/12744159/f4bcbeba-c992-11e5-9b7f-9d7d9e6fa1c0.png)

![image](https://cloud.githubusercontent.com/assets/15442639/12744192/23fc319c-c993-11e5-8d45-0593d72a776b.png)

**Comment by pierallard** [comment]
Hi @alexisfroger 

Of course it's possible, with some development ;) But, before starting it, what's your use case? If you do this at each time, you will complexify the data attached to the products, and lost the first interest of the tree representation.

Pierre

**Comment by a2xchip** [comment]
@alexisfroger It is anti-category usage.

**Comment by LaureBro** [comment]
Hello @alexisfroger, 
Thanks for your feedback, but this behaviour will not be changed in the PIM. 
I am closing this issue.

Kind regards, 

Laure
