### ISSUE TITLE
After import product history displays that all changes were made by default admin user 

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3971]
Hello,
I found that when I run import from any user, in product history it displays that all changes were made by default admin user. Even when I delete admin user it continues to mark all import updates as from "admin - Removed user". So I have few questions regarding this:
1) Is it done intendently?
2) What class is responsible for setting version author? Is it `VersionManager` class? (I would to know some details, cause jump from class to class is a little bit confusing)

Regards, Viktor.

**Comment by NovikovViktor** [comment]
Hello, @nidup ,
after more investigation I found that [here](
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/VersioningBundle/EventSubscriber/AddUserSubscriber.php#L59), getToken() always return null, so it seems like always all versions on import will be applied from admin user.  And it seems like not very simple issue to solve, possible this could be fetched from job instance that running, but it sound like bad idea. Maybe you have some suggestions regarding this issue?

**Comment by nidup** [comment]
Hi @NovikovViktor,
Yes, this default hard-coded admin is part of our legacy / work as not well designed ;)
When running cli commands (what happens for any backend processes, import, mass edit, etc), there is no authenticated user, so the token storage does not allow to identify a user.
In the Enterprise Edition we have some backend processes (as the mass edit) that need to authenticate a user to properly apply permissions (refuse some changes for instance). We do this in the processor item step to authenticate the user from the job exec:
```
    /**
     * Initialize the SecurityContext from the given $stepExecution
     *
     * @param StepExecution $stepExecution
     */
    protected function initSecurityContext(StepExecution $stepExecution)
    {
        $username = $stepExecution->getJobExecution()->getUser();
        $user = $this->userManager->findUserByUsername($username);

        $token = new UsernamePasswordToken($user, null, 'main', $user->getRoles());
        $this->tokenStorage->setToken($token);
    }
```

**Comment by NovikovViktor** [comment]
Hello, @nidup,  thanks for your repply. So as I understand import is not part of thoose jobs where `initSecurityContext(StepExecution $stepExecution)` method is used right? I am not quite good familiar with Akeneo architecture but in my humble opinion is looks like user can be fetched from job in [AddContextSubscriber](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/VersioningBundle/EventSubscriber/AddContextSubscriber.php#L53) and passed to context. Cause from current disposition `AddUserSubscriber` looks irrelevant (I am not sure maybe somewhere is needed). But I am not sure that this is architectural correct solution.

Best regards, Viktor.

**Comment by LaureBro** [comment]
Hello @NovikovViktor, 

To let you know this issue is linked to a feature request having the reference IM-480 on our side.
Ideally we'd like to have the name of the user that ran the import, like it is displayed under the Process Tracker page.

We'll keep you updated.
Kind regards, 
Laure

**Comment by NovikovViktor** [comment]
Hello @LaureBro thanks for info.
I believe that this was covered in some of Akeneo versions higher than 1.5 , so I close this issue.

Best regards, Viktor.

**Comment by NolwennP** [comment]
Indeed, it was covered in the 2.0 version.

**Comment by omolto** [comment]
+1

Please, this is a basic feature for CE version. Its a must to have logged the user that ran the import job.

**Comment by danielbeardsley** [comment]
We're still running into this and it's still a bug. See #9055
