### ISSUE TITLE
All old (empty) attributes are retained when changing the family of a product

### ISSUE THREAD

**Issue by DrewK289** [akeneo/pim-community-dev#3974]
When we change the family of a product, we expect any empty attributes that do not exist in the new family to be removed, but that does not happen; all the attributes from the old family are retained, and a delete option shows up next to them.

Would it make more sense to only retain attributes that have values, and remove any of the attributes that do not exist in the new family if they are empty?

**Comment by jmleroux** [comment]
Hello @DrewK289 ,

Thanks for this improvement proposal. We will submit it to our product owner and give you some feedback ASAP.

Regards,
JM

**Comment by nidup** [comment]
Hi,
We'll not change this behavior for now, we added a ticket in our idea manager board (number IM-469) to take it in account when we'll re-work the optional attributes topic.
Thank you again for your feedback.
