### ISSUE TITLE
Problems with selecting first channel from dropdown on product grid

### ISSUE THREAD

**Issue by alexandrzhulev** [akeneo/pim-community-dev#4001]
Hello,  @nidup !
While working with Akeneo as a user I have found following issue:
- after selecting from drop-down some channel - and then trying to return to the first channel from dropdown - it doesn't work, the state of grid is not swichted.
It occurs under following condition:
- from product grid go to product detailed view - then return back to product grid.
Browser Console displays following error: "Uncaught TypeError: Cannot read property 'locale' of undefined".

![select_issue](https://cloud.githubusercontent.com/assets/6017132/13104431/bec52aac-d565-11e5-8ba0-c82ecd5bb6c3.png)

Conclusion after quick review:
- this error occurs because of previously interpreted product detailed view template (in our case - "textarea.html" with calling "value.locale" for "data-locale" attribute value) which is also tried to be taken on product grid view (but there is no such variable `value` for grid).

Do you have any thought how can be solved this issue?

Regards, Alexandr & Viktor

**Comment by TonioxXx** [comment]
We also notice that issue on the solution we deployed.
Moreover, when it occurs, the forms behaviours are quite strange then. Saving associations seams to fail and JS erros apears in console.

I subscribe to notifications on this thread

Regards

**Comment by NovikovViktor** [comment]
@alexandrzhulev and I use Akeneo 1.4, and we are getting error above.
But when I installed Akeneo 1.5.0-ALPHA1, I found that error is similar but it has another context.
![selection_001](https://cloud.githubusercontent.com/assets/8058373/13214571/1ef9a140-d959-11e5-92a5-ec03b719ac3e.png)

**Comment by alexandrzhulev** [comment]
After we investigated this issue deeper we have found that error was caused because of following two cases:
1. after visiting detailed product view page and going back to product grid - templates and javascript of detailed view are somehow also included to the page;
2. on product detailed view first channel select option doesn't consist "value" attribute.

Case 1 - not covered, for now we don't have any suggestions how to fix it .

Case 2. Description and solution: 
During switching between channels - with value that is hold in "value" attribute of channel select option product data is got for detailed view. 
But as value for the first channel select option doesn't exist - it further causes error on scopable product attribute.
ScopeFilter (used for channels selection) differs from other similar filters as it has no "All" default option selection.
It is populated with default channel (taken from user context, [ScopeFilter.php](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/FilterBundle/Filter/Product/ScopeFilter.php#L80)).
Further select option of default channel is populated with blank value ([select-filter.js](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select-filter.js#L149)).

So, we'll prepare PR for solving Case 2 issue.

**Comment by nidup** [comment]
Hi @alexandrzhulev and @NovikovViktor 
Thank you for this detailed feedback and for the Pull Request, i reproduced on our demo and investigating.

**Comment by NovikovViktor** [comment]
Hello @nidup, according to @juliensnz comment [here](https://github.com/akeneo/pim-community-dev/pull/4032) and this [pull request](https://github.com/akeneo/pim-community-dev/pull/4278/files#diff-7a2db57888ca2f83bb89d72cf09b70abL82), this issue should be marked as Closed.

Regards, Viktor

**Comment by nidup** [comment]
Hello @NovikovViktor 
Ok, thx.
