### ISSUE TITLE
Checkbox state issue in association grid 

### ISSUE THREAD

**Issue by TonioxXx** [akeneo/pim-community-dev#4009]
Hi everybody,

It seems that there’s a problem with association grid in product edit form.
The case occurs on demo site too.

Here are steps of our test case :

1.	Login
2.	Enrich > Products
3.	Select one product in the list
4.	Go to association tab
5.	Select the second sub-tab to display the second association grid
6.	Click to select all checkbox
7.	Click back button [<]
8.	Confirm [ok] to leave without saving
9.	Select another product in the list
10.	The association tab is directly displayed, on the first association grid, with all checkbox checked => **KO**!

11.	Uncheck some lines : the 4 first in our case
12.	Click (save] button
13.	The first association grid is refresh with now our 6 associated lines “Yes” checked
14.	Go to the second sub-tab to display the second association grid
15.	The second association grid is displayed with all but the 4 previous checkbox checked : the 6 last in fact
16.	Click (save] button
17.	The page is refresh on the first association grid with still now our 6 associated lines “Yes” checked
18.	Go to the second sub-tab to display the second association grid
19.	The 6 lines are still checked but not really associated “No” => **KO** : save fail !

20.	Uncheck some lines : the 2 first checked in our case
21.	Click (save] button
22.	The page is refresh on the first association grid with still now our 6 associated lines “Yes” checked
23.	Go to the second sub-tab to display the second association grid
24.	The 4 lines are still checked but not really associated “No” => **KO** : save fail !

Seems there’s a problem with the state of checkbox in session/navigation.

Is that issue known ?

Many thanks for your feedback

**Comment by LaureBro** [comment]
Hello TonioxXx,

Thanks a lot for your detailed message with all the steps taken to generate the issue. I could reproduce it on my side too. 

I've asked our dev team to take a look and fix it as soon as possible, we'll keep you updated.

Best regards, 

Laure

**Comment by TonioxXx** [comment]
Hello Laure,

Do you have details to share me about solving this problem?
Or maybe a possible delay from the dev team ?

Best regards

TonioxXx

**Comment by LaureBro** [comment]
Hello TonioxXx, 

The fix is ready and will be available in the next patch.

We plan to release it by the beginning of the week. I'll keep you updated, 

Best regards, 

Laure

**Comment by LaureBro** [comment]
Hello TonioxXx, 

The 1.4.21 has been released this morning, it includes the fix for the association tab.

Best regards, 

Laure
