### ISSUE TITLE
EventDispatcher property not declared in ProductBuilder

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#4011]
It is dynamically added in https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/CatalogBundle/Builder/ProductBuilder.php#L80
but it's not declared in the class.

**Comment by nidup** [comment]
Hi @mathewrapid 
Thank you for the feedback! We would love to count you as our contributor, don't hesitate to open a Pull Request to fix this glitch.
To be able to merge the PR, i'll need that you read and sign our contributor agreement http://www.akeneo.com/contributor-license-agreement/
If not interested, let us know and we'll fix.
Thank you

**Comment by mathewrapid** [comment]
#4016

**Comment by nidup** [comment]
your related PR has been merged, thank you for your contribution! don't hesitate if you encounter any other issues!
