### ISSUE TITLE
LoadUser addGroup data fixtures bug, prevents to load custom data

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4065]
**I'm reporting a Bug**
The line of code linked above have to be deleted because it prevents to load users own fixtures where threre is no such group. 
[addGroup('All')](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/InstallerBundle/DataFixtures/ORM/LoadUserData.php#L98)

**Comment by nidup** [comment]
Hi @a2xchip 
The group "All" is mandatory, the PIM can't work properly without this default user group.
You can fix your data set by adding this user group https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/user_groups.yml#L8
Don't hesitate if you need any further information.

**Comment by a2xchip** [comment]
Where does akeneo use it?

**Comment by nidup** [comment]
You can find the list by looking at the classes calling this method https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/UserBundle/Entity/Repository/GroupRepository.php#L56

**Comment by a2xchip** [comment]
@nidup I think the problem is that code relies on local specific name ```All``` instead of its key. For example my implementation uses russian as default language and i also have user group ```all``` but its name is ```Все``` and there is no english locale. I made thing you proposed and installation works fine but i can's see group ```All``` in group listing.

**Comment by nidup** [comment]
The group "all" never appears in the user management UI, neither in group list, neither in user edit, it's a system group added for any users created in the PIM. cf http://demo.akeneo.com/#url=/user/group 

It's mainly used in Enterprise Edition to grant permissions to any users and appears in "permissions" tabs of "locale", "attribute", "category", etc (in the Enterprise Edition only).

For legacy reasons, the PIM does not provide a field named "code" for any of UserBundle entities which is not consistent with all other entities of the PIM for which we provide a code (we would improve this but it requires some work to provide simple migration path).

**Comment by a2xchip** [comment]
Thanks for your answer @nidup. Things became clear. I'm curious if it is possible to document it as "note" in ```Cookbook -> How to Customize Import / Export``` section? Detailed project documentation sometimes is much important than projects stability and features.

**Comment by nidup** [comment]
Thank you for the feedback and agree with you that our documentation could mention this, don't hesitate to open a pull request on https://github.com/akeneo/pim-docs to add this information.

**Comment by a2xchip** [comment]
Coming soon )) @nidup

**Comment by nidup** [comment]
Great! we'll be glad to help and merge :)
