### ISSUE TITLE
JS validation is not run when creating product through the GUI

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#4066]
[akeneo-pim-system-info_2016-02-29_12-15.txt](https://github.com/akeneo/pim-community-dev/files/150666/akeneo-pim-system-info_2016-02-29_12-15.txt)

When creating a product through the GUI the attached JS callback is not run on clicking the **Save** button.

Twig template `akeneo/pim-community-dev/src/Pim/Bundle/JsFormValidationBundle/Resources/views/JsFormValidation.js.twig`

``` javascript
jsfv.onFirstEvent(form, 'submit', function(e) {
    var gv, submitForm = true;
    submitForm = jsfv.check_pim_product_create_values_puuilo_id_varchar() && submitForm;
    if (!submitForm) {
        e.stopImmediatePropagation();
        showFirstTabWithErrors();
        $(form).trigger('validate');
    }
    return submitForm;
});
```

The callback is run if the jQuery's submit method is called on the form

``` javascript
$('#formId').submit();
```

Tested with Chrome `Version 48.0.2564.116 m (64-bit)` and FireFox `44.0.2`

**Comment by mathewrapid** [comment]
This is due because the form's submit is never run. The product creation dialog serializes the form without checking the JS-validation. Any suggestions how to fix this?

https://github.com/akeneo/pim-community-dev/blob/v1.4.20/src/Pim/Bundle/UIBundle/Resources/public/js/pim-dialogform.js#L50

```javascript
if (submitButton) {
    formButtons.push({
        text: submitButton,
        'class': 'btn btn-primary',
        click: function () {
            showLoadingMask();
            $.ajax({
                url: url,
                type: 'post',
                data: $(formId).serialize(),
                success: function (data) {
                    processResponse(data);
                    mediator.trigger('dialog:open:after', this);
                }
            });
        }
    });
}
```

**Comment by pierallard** [comment]
Hi @mathewrapid 

Thanks for the bug report! Unfortunately, I can not reproduce it in 1.4.23 version or 1.5.1. Can you update your current installation to 1.4.23 ? If the issue is still here, can you send us a complete step by step scenario to reproduce it ?
And, last question, what's your OS ?

Regards

Pierre

**Comment by mathewrapid** [comment]
I'll test it on 1.4.23 when I get the chance.

What I found out from the code is that the forms submit method is never called, the form is just serialized and sent through ajax on a click event (no submit event).

My OS Windows 10, browser Chrome.

**Comment by mathewrapid** [comment]
@a2xchip Same with IE, no difference. I haven't had any problems with Akeneo+Windows 10+lates Chrome (64-bit)

The thing is that the JsFormValidation is never run on the product create form as the form submit event is never triggered, or am I wrong.

**Comment by a2xchip** [comment]
@mathewrapid Thx, for reply! We use the same PIM version as You, i'll debug js checking if it is called in our implementation.
