### ISSUE TITLE
Integrity constraint violation updating products

### ISSUE THREAD

**Issue by buttash** [akeneo/pim-community-dev#4069]
I'm trying to update my products with price information from a csv file.  The file is of the format:

![image](https://cloud.githubusercontent.com/assets/4323877/13396296/bc4e0412-deeb-11e5-9954-b19a390d3a18.png)

Strangely, the output says that 25 products have been created (no items in the csv file are new as they refer to existing products) and then I get a contraint violation.

<img width="987" alt="screen shot 2016-02-29 at 13 50 43" src="https://cloud.githubusercontent.com/assets/4323877/13396340/ef200f20-deeb-11e5-9363-a048cf543520.png">

The constraint seems to be something to do with the image of the base product, although the product images are not being referenced.

Any idea what might be causing this?

Thanks
Martin
[akeneo-pim-system-info_2016-02-29_13-51.txt](https://github.com/akeneo/pim-community-dev/files/150999/akeneo-pim-system-info_2016-02-29_13-51.txt)

**Comment by buttash** [comment]
I've managed to get round this by working out which variant is being accessed and then removing all products associated to that product.

**Comment by nidup** [comment]
Thank you for raising this issue, this message seems very close to this issue https://github.com/akeneo/pim-community-dev/issues/4298.

**Comment by damien-carcel** [comment]
Closing as it seems fixed in 1.7, as the #4298 issue.
