### ISSUE TITLE
Can't view/access to catalog tree bottom entries

### ISSUE THREAD

**Issue by gmacaire** [akeneo/pim-community-dev#4070]
Hello,

Using Akeneo without Google Chrome AND a screen resolution under 1280x1024px, it is impossible to view/access catalog tree bottom entries (including "Unclassified products" and "All products" entries).

![catalog](https://cloud.githubusercontent.com/assets/574706/13396223/b41ce012-def3-11e5-9d28-64b9101c1352.jpg)

Here is the result of a little test I did today with BrowserStack :

| OS | Browser | Screen resolution | Result |
| --- | --- | --- | --- |
| Windows 7 | Internet Explorer 11 | 1280x1024 | **OK** |
| Windows 7 | Internet Explorer 11 | 1280x800 | KO |
| Windows 7 | Internet Explorer 11 | 1024x768 | KO |
| Windows 7 | Firefox 44 | 1280x1024 | **OK** |
| Windows 7 | Firefox 44 | 1280x800 | KO |
| Windows 7 | Firefox 44 | 1024x768 | KO |
| Windows 7 | Chrome 48 | 1280x1024 | **OK** |
| Windows 7 | Chrome 48 | 1280x800 | **OK** |
| Windows 7 | Chrome 48 | 1024x768 | **OK** |

**Comment by grena** [comment]
Hello @gmacaire and thank you for the report!

We recommend a resolution of 1280 x 960 for a better experience (see [the official doc](http://docs.akeneo.com/1.4/reference/technical_information/client_side_compatibilities.html#browsers) for more information).

As we try to do our best to support more & more configurations and resolutions, **your benchmark will sure help us** to improve this part, so thanks again :)

Kind regards,
Adrien.

**Comment by gmacaire** [comment]
Hey,

Thank you for the link ! I was looking for this information before opening the issue.

Since the UI isn't completely usable with a 1280x600px resolution, shouldn't you update the docs with 1280x960 pixels as minimal screen size ? It would be more appropriate don't you think ?

**Comment by LaureBro** [comment]
Hello @gmacaire, 
Sorry for the late reply :) I've submitted this update to our Product team, min. screen size to 1280x800 pixels. We should update the documentation very soon! 
Regarding the categories that were not displayed, that was a bug, it's fixed in 1.5 and higher versions.

Thanks!

Laure

**Comment by LaureBro** [comment]
Hello @gmacaire, 
We've updated our documentation (https://docs.akeneo.com/1.5/reference/technical_information/client_side_compatibilities.html#screen-resolution)

Minimal Resolution: 1280x800px
Recommended Resolution: 1440x900px

This display issue is fixed in all our current versions (1.5, 1.6 and 1.7) so I'll close this issue.
I hope you managed to update/upgrade your installation on one of these versions.

Kind regards, 
Laure
