### ISSUE TITLE
Attributes options values translation /  Current edit locale  (display mismatch in Product form)

### ISSUE THREAD

**Issue by TonioxXx** [akeneo/pim-community-dev#4110]
Hi,

We noticed a problem with the translations of attributes options values, that don't correspond dynamically to the current edit locale selected.

The following screenshots have ben made on demo site (1.4.21) :
- Attribute configuration
  ![image](https://cloud.githubusercontent.com/assets/17314147/13569047/d93df7ce-e465-11e5-95ae-f8b13fca50a6.png)
- Go to a digital camera product sheet
  ![image](https://cloud.githubusercontent.com/assets/17314147/13569087/1b578c4c-e466-11e5-87ac-15505e95891f.png)
- see the attribute value for current locale
  ![image](https://cloud.githubusercontent.com/assets/17314147/13569091/261acacc-e466-11e5-96b1-d8c8425ab32b.png)
- select another locale 
  ![image](https://cloud.githubusercontent.com/assets/17314147/13569160/a0dcd052-e466-11e5-9855-3853a4e4fc94.png)
- see the inconvenience 
  ![image](https://cloud.githubusercontent.com/assets/17314147/13569185/c915e9d2-e466-11e5-8b35-e5e3107c5887.png)

If the problem seems to be only a display inconvenience (since the code behind stay the right), (international-)users are therefore disturbed by this behaviour.
We expected there rather to be displayed/refreshed the option value translation according to the locale selected (like it is done for the list).
Is this issue already known ? And is there some fix planned ?

Best regards,

**Comment by grena** [comment]
Hello @TonioxXx , thank you for reporting this :bug:! 

We didn't know about it, so thanks again :+1: 
I added this bug to our _known-bugs-board_ (PIM-5629) to prioritize it, so no ETA yet for a fix.

You can monitor changes on this GitHub ticket, we'll close it once fixed.
Kind regards,

**Comment by nidup** [comment]
FYI, also referenced as PIM-5777 in our internal bug tracker and has been highly prioritized.

**Comment by ikwattro** [comment]
Still occur on EE 1.6.7, any update about an ETA of a fix ?

**Comment by tamarasaurus** [comment]
Hi @ikwattro - is this still an issue for you on the latest 1.6.x?

Regards,
Tamara

**Comment by grena** [comment]
Hello @ikwattro , I close this issue due to inactivity, if it's still a problem, don't hesitate to re-open it.
