### ISSUE TITLE
Product PDF export doesn't work in the demo V. 1.5.0

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4122]
Exporting a product to PDF in the PEF doesn't work in the demo http://demo.akeneo.com/ (Akeneo 1.5.0)
> The server returned a "500 Internal Server Error".

But the PDF feature works for my local installation.

PS: Congratulations for the new 1.5 release :-) ! It would be cool, if you could add more details in the CHANGELOG. At the moment it just contains technical changes (BC breaks, bug fixes...) but no details from a user's point of view.

**Comment by LaureBro** [comment]
Hello Hocdoc, 

Thanks a lot for your message, I could not reproduce the error on demo.akeneo.com. Can you test again? If the error appears, can you send me the ID of the product on which you are testing?

We'll publish a release note on the 1.5 this afternoon on our blog, I'll send you the link when it's posted.

Best regards

**Comment by Hocdoc** [comment]
It still doesn't work for me.

F.ex.: http://demo.akeneo.com/enrich/product/1043?dataLocale=en_US
PDF-URL: http://demo.akeneo.com/enrich/product/1043/download-pdf?dataLocale=en_US&dataScope=ecommerce

=> Internal Server Error

**Comment by LaureBro** [comment]
Thanks for your quick feedback, could you retry now (before 11.42am French Time) so we can check all our logs? We reset the demo every hour, and previous logs are not available anymore.

**Comment by LaureBro** [comment]
Hello Hocdoc, 

Do not take into account my previous message, we do keep logs, but could not find anything related to your issue. 
If you still could reproduce the issue one more time and let me know at what precise time you tried, we'll check again our logs.

Here are the taken steps:
- Go to the product grid
- Click on one product
- Click on PDF button,
- PDF is downloaded and I can open it without any issue.

Do you have the same steps to reproduce the issue?

Thanks!

**Comment by Hocdoc** [comment]
Now the PDF export works perfectly for me, thanks for your effort.

**Comment by Hocdoc** [comment]
I still have problems with the product PDF export in Akeneo 1.5.1:

This is still in the Akeneo demo, f.ex.when creating the PDF for the propduct with the SKU `10699783` (13:20).

I think the problem is creating a PDF for products that contains an image.

The `ImageExtension` still use the old Akeneo 1.4 paths for `AttributeInterface` and `ProductInterface`:

https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/PdfGeneratorBundle/Twig/ImageExtension.php#L5

**Comment by nidup** [comment]
Thank you a lot for the related PR!, we'll merge it next week (we're first merging few 1.4 fixes to 1.5). \cc @grena @solivier

**Comment by Hocdoc** [comment]
Thanks, the issue is fixed in 1.5.2

**Comment by tintusumith** [comment]
We used eikona/pdf-generator-bundle for pdf generation in akeneo application. After redirecting site to HTTPS, PDF export functionality is not working properly. Pdf with blank page generated in this case. Without HTTPS its working fine

**Comment by tintusumith** [comment]
How to fix broken pdf issue while exporting product pdf in akeneo using eikona/pdf-generator-bundle after redirecting site to https?
