### ISSUE TITLE
Cannot install Akeneo 1.5.1

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4144]
Since some days I cannot install a clean Akeneo 1.5.1.

I have:
- created a fresh clone of https://github.com/akeneo/pim-community-standard
- installed the dependencies (`composer install`) 
- run `pim:install` with the default `PimInstallerBundle:icecat_demo_dev` data
- I've cleared the cache several times.

When I open the PIM in the browser it renders the login screen. But after clicking the "Login" button I get this error message:

> An exception has been thrown during the rendering of a template ("Error during translations file generation for locale "en_US"") in OroTranslationBundle::requirejs.config.js.twig at line 4.

I think, that 1.5.0 worked for me last week.

Is it just me, or isn't a fresh Akeneo 1.5.1 installation from the pim-community-standard repository not working?

**Comment by grena** [comment]
Hello @Hocdoc ! Thank you for your feedback :+1: 
Unfortunately, I can't reproduce.

- When you clone the pim-community-standard, do you checkout the `v1.5.1`  tag or are you still on the 1.5 branch?
- Does your server have write permission on the folder `web/*`?

Kind regards,

**Comment by Hocdoc** [comment]
Thanks for your hints. 
So it's just me, which is important to know for me.

(I have checkout `v1.5.1` and checked the write permissions but still get the same error. I will continue trying to install 1.5 and will write here if I get it running again.)

**Comment by grena** [comment]
Thanks.

Can you try to run these commands in the root of your project please:
```
rm -Rf ./app/cache/* ./web/bundles/* ./web/css/* ./web/js/*
php app/console pim:install:asset -e=prod
php app/console assets:install --symlink web
```

Tell me if it helps :)

**Comment by Hocdoc** [comment]
Unfortunately these commands don't change my installation problem.

**Comment by bxnxg** [comment]
Hi,

Same here, I started to install Akeneo today, respectively following the [installation process](http://docs.akeneo.com/1.5/developer_guide/installation/installation_workstation.html).

I downloaded the 1.5.1 version, installation whitout problem and block witeh the same error after login admin/admin.

`An exception has been thrown during the rendering of a template ("Error during translations file generation for locale "en_US"") in OroTranslationBundle::requirejs.config.js.twig at line 4. `

` WARNING - Translation not found.
WARNING - Translation not found.
DEBUG - Translation use fallback catalogue.
WARNING - Translation not found.
CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Error during translations file generation for locale "en_US"") in "OroTranslationBundle::requirejs.config.js.twig" at line 4." at /var/www/akeneo/vendor/twig/twig/lib/Twig/Template.php line 396 `

**Comment by jmleroux** [comment]
I just made a fresh installation at home, with no existing database : 

```
git clone git@github.com:akeneo/pim-community-standard.git
cd pim-community-standard/
git checkout v1.5.1
composer install --prefer-dist
app/console pim:install -e prod
```

I can log in as admin and see the product grid without error.
Sorry to not reproduce.

**Comment by Hocdoc** [comment]
I get the installation of Akeneo 1.5.1 now running on my system.

It seems to be just a permission problem, Akeneo needs write permissions to `web/js/translation/` otherwise the [creation of the translation](https://github.com/akeneo/pim-community-dev/blob/1.5/src/Pim/Bundle/EnrichBundle/Twig/TranslationsExtension.php#L69) fails.

I'm not sure why it works now, because I really have checked the write permissions before as @grena has already hinted. Anyway I'm happy that it works now and I can explore Akeneo 1.5 ;-) . 

Thanks for your advice.

@bxnxg: You may want to check if you could run the translation creation from the console:
`php app/console --env=prod oro:translation:dump en_US`

**Comment by bxnxg** [comment]
OK, i will check later and confirm if the problem is solved or not.
Thanks everyone :+1:

**Comment by bxnxg** [comment]
OK that was just a permission problem for me, thanks

**Comment by clicktrend** [comment]
I use `pim:installer:assets` command in composer to finish my deployment.

The problem is here:

`https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php#L54`

"en_US" is missing.

**Comment by grena** [comment]
Hello guys,

Indeed the thing is, we generate only "common" locales on install. The one you list @clicktrend .
When switching locale in the PIM, the related .js translation file is generated on-the-fly (en_UK.js, fr_CH.js, and so on).

We're currently reviewing this to generate all localization files when dumping assets, it's currently WIP and will be available in an upcomping patch on 1.5.

**Comment by LaureBro** [comment]
Hello Guys, 

The issue still occurs and we should not have to launch this command after a fresh install
```php app/console --env=prod oro:translation:dump en_US```

**Comment by imranhasan871** [comment]
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Installing akeneo/pim-community-standard (v4.0.90)
  - Installing akeneo/pim-community-standard (v4.0.90): Downloading (100%)         
Downloading (100%)         
Downloading (100%)    Failed to download akeneo/pim-community-standard from dist: Could not delete /srv/pim/: 
    Now trying to download from source
  - Installing akeneo/pim-community-standard (v4.0.90): Cloning 861a14f17d from cache


[RuntimeException]           
  Could not delete /srv/pim/:
