### ISSUE TITLE
Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_cow_1042.oro_config' doesn't exist' in 

### ISSUE THREAD

**Issue by emaan-zepcom** [akeneo/pim-community-dev#4152]
I am facing issue while installing akeneo steps i followed :

-Unzip downloaded project
-changed database and user setting with custom database 
-changed mode as prod 
now its throwing following error :
 Base table or view not found: 1146 Table 'akeneo_cow_1042.oro_config' doesn't exist in /var/www/akeneo.cow.pttde.de/vhosts/www/src/pim-community-standard-v1.4.18-icecat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 695

how i suppose to add this oro_config table when i do not have its database schema.

**Comment by nidup** [comment]
Hi @emaan-zepcom 

Did you follow this installation documentation http://docs.akeneo.com/latest/developer_guide/installation/installation_workstation.html ?
