### ISSUE TITLE
Critical issue on binding events / Cumulative bind events on association tab

### ISSUE THREAD

**Issue by TonioxXx** [akeneo/pim-community-dev#4156]
Detected on v1.4.21
Reproduced on demo site 1.5.1

In product edit form, under "Associations" tab :

If you click on another association type to change the current one, the datagrid is refreshed by the two next calls :
- http://demo.akeneo.com/datagrid/association-product-grid?association-product-grid...
- http://demo.akeneo.com/datagrid/association-group-grid?association-group-grid...

=> OK

`events: {
                'click .nav-tabs li':                'changeAssociationType',
                'click #association-buttons button': 'changeAssociationTargets'
            }`

But if you switch to an other main tab "Attributes" and go back then to "Associations" tab : the datagrid is reloaded with duplicate calls of the two previously listed actions :
- http://demo.akeneo.com/datagrid/association-product-grid?association-product-grid... x2
- http://demo.akeneo.com/datagrid/association-group-grid?association-group-grid... x2

=> KO

You can even play with main tabs : going to "Attributes" and go back "Associations" tab : each time, we rebind the event and cumulate as many additional calls 

=> KO

Moreover, Akeneo is then becoming slower and slower because of the multiple http requests sent...

WORSE : 
- if you exit the current product edit form (by the "<" action button), 
- and go back to products main datagrid, 
- and then visit another product sheet

ALL the events previously binded are still triggered, and whereas in more they concern another product id with the risk maybe of inconsistent data in addition to the global downturn :
=> That missing unbind causes association issue, since the event triggered on selection of a product in association datagrid is multiple and duplicated too 
=> That causes problems in saving associations since selected states are not correctly sent (after clicking "Save" form is relaoded with success message information but the "Is associated" state stay to "NO" : the selection has failed)

Could you please work on a quick fix for that issue, and confirm us it can be done on 1.4.x too.

Best regards,

TonioxXx

**Comment by grena** [comment]
Hello @TonioxXx,

Thank you for this report! I reproduced it on our server. I created a major ticket on our board, we'll prioritize this ticket and close this GitHub issue once fixed.

If you want to contribute to this project and see how it could be fixed, you're welcome to open a Pull Request, we'll be glad to help you to merge it :)

Thanks again.

**Comment by TonioxXx** [comment]
Hello Akeneo team,

Could you give us a feedback about that issue ?

Thanks you

TonioxXx

**Comment by LaureBro** [comment]
Hello TonioxXx, 

We have raised a ticket internally, we'll let you know when it will be handled.
It will be fixed on the 1.5, you will be able to backport this fix on the 1.4.

Best regards, 

Laure

**Comment by LaureBro** [comment]
Hello TonioxXx! 

I hope you're doing well, the 1.5.2 has been released, and this issue is now fixed in this version.

Thanks again for spotting this out, 

Best regards, 

Laure
