### ISSUE TITLE
Upgrade to 1.5.1 product history missing

### ISSUE THREAD

**Issue by s0ps** [akeneo/pim-community-dev#4158]
**I'm reporting a Bug**

After upgrade to 1.5.1 product history is missing.
It is missing probably because pim_versioning_version resourceName is "Pim\Component\Catalog\Model\Product" in new version, but "Pim\Bundle\CatalogBundle\Model\Product" in older versions.

**Comment by grena** [comment]
Hello @s0ps !

Thank you for reporting this. Indeed, it's a sad oversight on our part!
Hopefully we have a incredible community, so thanks again for pointing this :family: 

I created a ticket on our board to track this down and fix it, this GitHub issue will be closed once merged.
Thanks again!

**Comment by s0ps** [comment]
Hi, is there any progress on this issue?

**Comment by a2xchip** [comment]
Thinking about upgrade to 1.5 branch too.

**Comment by willy-ahva** [comment]
Hi guys !

We merged on 1.5 a bug fix you can find here : https://github.com/akeneo/pim-community-dev/pull/4292
The fix will be available in the next v1.5.2. We'll tag as soon as possible.

Thank you for reporting and for your feedback !
Willy

**Comment by LaureBro** [comment]
Hello, the 1.5.2 has been released. It contains the fix for this issue.
Can you confirm me it's ok for you @a2xchip?
Thanks!

**Comment by a2xchip** [comment]
@LaureBro Let us upgrade first! I'll report if something will go wrong

**Comment by nidup** [comment]
As we tested the fix on other projects, I close the issue, don't hesitate to re-open one if not properly fixed in your case. Thx again for the report!
