### ISSUE TITLE
"Quick Export/CSV (All attributes)" menu stays after click

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4168]
In Akeneo 1.5.1 when I click in the product grid on the "Quick export" button, and then "CSV (All attributes)", the menu item doesn't disappear.
So it is very tempting to start the QuickExport another time as nothing seems to happen.
Only with a click outside the menu item the item hides.

You can test this with the Akeneo Demo http://demo.akeneo.com/enrich/product/ .
 
In Akeneo 1.4 the menu item disappeared.

**Comment by grena** [comment]
Hello @Hocdoc !
You're right, I reproduced it too on the demo env.

I've created an internal ticket to follow & fix the issue. We'll close this GitHub issue once merged.

Thanks again!

**Comment by LaureBro** [comment]
Hello @Hocdoc, 

This issue is fixed in the CE 1.5.3 that have been released few hours ago!

Best regards, 

Laure

**Comment by Hocdoc** [comment]
Thanks, it works now. :-)

**Comment by ankit-sf** [comment]
I think quick export menu should not stay visible after click in Akeneo 2.0.x and later.
[https://image.prntscr.com/image/Bo74mTHjTD_ri9HhoJTL0w.png](https://image.prntscr.com/image/Bo74mTHjTD_ri9HhoJTL0w.png)

**Comment by grena** [comment]
Hello @ankit-sf , don't hesitate to open a new GitHub issue to report this UI behavior, it will be easier to follow :)
