### ISSUE TITLE
User actions erroneously attributed to incorrect account

### ISSUE THREAD

**Issue by sammarcus** [akeneo/pim-community-dev#4249]
When I first set up Akeneo I used the default account and did not customize it with the correct users. I performed many actions and then changed this later, adding my own name to a user account. The actions I previously performed would show like this:

![image](https://cloud.githubusercontent.com/assets/8689264/14155760/14d125da-f691-11e5-9bb5-10f400542733.png)

This makes sense. For a period of time, my correct account would display next to each new action. However, it now continues to display like the image above. I've checked my `oro_user` table and it is correct:

![image](https://cloud.githubusercontent.com/assets/8689264/14155824/6962f826-f691-11e5-9747-a7c12072e075.png)

So why are new actions still appearing like this?

![image](https://cloud.githubusercontent.com/assets/8689264/14155850/8f72e58a-f691-11e5-8fff-4b261e96e020.png)

I am using 1.4.17, I know this is not the newest version but I had other issues that necessitated me rolling back. If it is fixed in 1.5 please disregard this issue.

**Comment by sammarcus** [comment]
It seems it is only doing this on actions done via an imported job. If I make an edit on an item directly in the web interface, the correct user is recorded in the history log. Is this expected behavior for when importing things?

**Comment by LaureBro** [comment]
Hello Sammarcus, 

Thanks for your message. The import jobs are ran by the default admin user, so it is an expected behavior - I have suggested our Product Team to improve it, I've created an improvement feature.
We will keep you updated.
Best regards, 
Laure

**Comment by sammarcus** [comment]
Interesting, thanks for clarifying. At the very least I do not think "removed user" is the best choice of language, as it seems it will display this phrasing for any installations where the initial user has customized the user list (and hence removed the first user). 

But, I do think it is important to identify precisely who ran the import job. Since this is expected behavior I'll close the issue, but feel free to reopen if you want to use it for tracking on this enhancement request. Thanks @LaureBro!

**Comment by NolwennP** [comment]
Some updated news!
Since 2.0, in Entreprise Edition, when modifying entities using the import feature, the entities history will show the user that ran the import job.
