### ISSUE TITLE
Product attributes tab rendering fails with Internet Explorer

### ISSUE THREAD

**Issue by jkajasrisoikea** [akeneo/pim-community-dev#4255]
Reproducible in demo.akeneo.com 1.5.1

Steps:
- With IE11 (10.0.9600.18204):
- Log In
- Open any product

Expected behavior:
Attributes are shown

Current behaviour:
Attributes tab is empty. JS error:
`Zone "other-actions" does not exist`
`File: form.js, Line: 232, Column: 21`

Page Refersh -> attributes are rendered until the problem repeats after next login.

**Comment by willy-ahva** [comment]
Hi jkajasrisoikea !

Sorry but Internet Explorer browser is not supported with Akeneo. You can find client side configuration and compatibilities list on this documentation : http://docs.akeneo.com/latest/reference/technical_information/client_side_compatibilities.html?highlight=chrome#browsers.
However, you're very welcome to contribute to Akeneo and fix this bug on IE. We'll be happy to review your fix and run tests on your PR. Don't hesitate if you need more information :)

Thank you for your feedback !
Willy
