### ISSUE TITLE
Attribute form "refresh" bug.

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4266]
**I'm reporting a Bug**

Version: master

I open attribute edit form and it is ok. I refresh the page and UI crashes. 

![image](https://cloud.githubusercontent.com/assets/6627334/14222633/82ab3f78-f87b-11e5-8fb0-7171386d3196.png)

It does not in firefox

![image](https://cloud.githubusercontent.com/assets/6627334/14222681/2eed9a4c-f87c-11e5-95b4-3558ba77ed10.png)

May be it is only linux Yandex browser specific, but there are no errors in dev console

UPDATE: The same bug in google-chrome for linux 64 it may be same for all webkit family

**Comment by pierallard** [comment]
Hey @a2xchip 
Thanks for the report.
For me it's not reproductible in http://demo.akeneo.com/configuration/attribute/48/edit with Chrome 49.0.2623.87 (64-bit) on Ubuntu 14.04 LTS
We will see from our side in other system configuration if it's reproductible and correctable. What are exacly your system infos ?

**Comment by a2xchip** [comment]
![image](https://cloud.githubusercontent.com/assets/6627334/14227238/a2a8d49e-f901-11e5-8333-11c221ac9138.png)

![image](https://cloud.githubusercontent.com/assets/6627334/14227247/cf6b0f1a-f901-11e5-951a-751f97cc782f.png)

![image](https://cloud.githubusercontent.com/assets/6627334/14227255/fd468ebe-f901-11e5-8e74-42a8ca6146e4.png)

The Ubuntu version and browsers are the same. I will try to play with extensions.

**Comment by a2xchip** [comment]
I disabled all active extensions in google-chrome and checked it again. The same *glitch*

**Comment by jmleroux** [comment]
I do not reproduce on demo neither.
@a2xchip do you have the same glitch when you use the same version (1.5.1) than demo.akeneo.com ?

**Comment by a2xchip** [comment]
@jmleroux there is no such on demo.akeneo.com

**Comment by a2xchip** [comment]
@jmleroux @pierallard  It happens only in dev environment. So you may close this issue or left it in low priority.

**Comment by juliensnz** [comment]
Thank you for your feedback ! I close this issue as it seems linked to too much variables and not reproduced on prod env. I keep it in mind in case I work on this section of the pim again.

Regards,

Julien

**Comment by a2xchip** [comment]
@juliensnz It is ok.
