### ISSUE TITLE
Families Sequencial edit

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4271]
**I'm submitting a Feature Request**

Our akeneo's users expirience need in families sequential edit. 

### Use case:

In our implementation initial families and their attributes are scrapped from different third party sources and there are no initial required attributes. Before starting to setup families to product our users need to manually check all families and set up required attributes according to our own needs. They must be checked one-by-one and mass edit doesn't helps in such task.

### Request 

To add sequential edit with the same behaviour we have in products sequential edit.

**Comment by a2xchip** [comment]
@pierallard @nidup I checked product sequential ativity is done. Now it is sticked to product entity. May be we are able to start this issue by abstracting and refactoring "product sequential services"?

**Comment by nidup** [comment]
Interesting use case, agree that mass edit will not help here. Something doable is to export families as csv, complete the file then re-import to iteratively add attributes and requirements in each family.
Our product owners have already prepared some topics to ease the setup process, these topics have not yet been developed, I'm not sure it was through the sequential edit.

@Delphineray what do you think about using the sequential edit on other entities than the product?

PS: technically speaking, the product edit form architecture is very different than the family edit form so I think that abstracting this will not be that easy. By the way, i'm not convinced at all that we need to store the SequentialEdit selection in the database, could be maybe done in browser session storage.

**Comment by a2xchip** [comment]
@nidup It is possible to implement using different storage, as i understand it is used only to know certain object that will be edited next. Families export/import flow fails with error, it gives constraint violation error (i didn't checked it, but seems it is because of flush), that doesn't happen when families edited one-by-one.

**Comment by Delphineray** [comment]
Hello @a2xchip,

Thank you for your feature request. It's an interesting use case. How many families do you manage in your project?
As suggested by @nidup, our customers who manage a lot of families use the import to initialize and update them easily, but ease the input of the families by screen is also important.

Delphine

**Comment by a2xchip** [comment]
Hello @Delphineray 

Now it is 1000+ but we started by filling info of about ~25% of all assortment company sells. I used the import to create families, but it is hard to explain how to use codes from attributes xls with families xml to non technical users. And how i mentioned before there were some errors during import i simply ignored and will come back to it later.

**Comment by juliensnz** [comment]
Hello @a2xchip,

First, technical point of view:
The sequential edition process is implemented on the product edit form with a kind of dirty architecture (front and backend mixed). This is due to some legacy stuff and tight deadline last summer.
Also the current family edit form is made of twig/Symfony forms which is completely different from the product edit form.

So to achieve what you need, steps are:
- Full rework of the sequential edit functionality to only have it frontend
- Full rework of the family form to use our new form component.

Quick huge work but doable I think :)

About @Delphineray suggestion, I think it's the simplest way to achieve it: export your families in csv, edit them in open office and import them back.

As we are working on xlsx import and export for 1.6 this will be even easier in the coming 1.6 !

Regards,

Julien

**Comment by a2xchip** [comment]
@juliensnz Thank you for your answer. I did some research about current product form and sequential edit, but never thought that family form works different. It seems really huge work ))) But double. May be I will be able to learn more around backbone in such way. )

**Comment by juliensnz** [comment]
Yeah, it could a great experience. You can also take a look the 1.3: at the time product edit form and family edit form where on the same system (twig) so you could maybe reuse this to port the sequential edit on the family screen

I close this issue as we will not work on it directly.

We can continue to discuss it even after closing it though.

Best regards,

Julien

**Comment by a2xchip** [comment]
@juliensnz Ok! Thank you! I keep it in mind and return back to this topic later.
