### ISSUE TITLE
config_prod.yml hardcodes apcu cache for doctrine

### ISSUE THREAD

**Issue by Xobb** [akeneo/pim-community-dev#4300]
We're having a beautiful selection of cache drivers for doctrine, why would we hardcode any of them?

Maybe it should be moved to become one of the parameters in ```parameters.yml``` for the application. The pull request is pretty obvious, but let's have a discussion on this before I submit one.

Edit: clarifying my English.

**Comment by jmleroux** [comment]
Hello Xobb,

Memcached should not be a hard dependency.
This customization is quite easy and should maybe be documented, but not set by default.
To be honest, if doctrine metadata were cached in array in place of APC, i'm not sure it would have great impacts on perfs.

**Comment by ClementGautier** [comment]
I totally agree with @Xobb , this is configuration is basically an environment variable and should be moved to the parameters.yml file.

**Comment by Xobb** [comment]
@jmleroux thanks for a quick update. Sorry, maybe I was not that clear in my statement, I do not want Memcached to be the default option. I would love to have that configurable, not hardcoded.

**Comment by juliensnz** [comment]
Hello @xobb,

After little discussion internally, we think that this variable is more related to project configuration than Akeneo PIM needs. You can add it to your `parameters.yml` in your project but I don't think we should add it to every projects. Moreover adding parameters to our `parameters.yml` file, will make them appear in our post composer install interactive command which can be confusing to new users. Last, a lot of parameters are like this one and adding it to our `parameters.yml` could kind of open the door to a lot of parameters.

As those files are versioned in your project, you can easily do it to fulfil your needs.

I hope that my answer is clear and not too "No way Jose" :)

Best regards,

Julien

**Comment by Xobb** [comment]
@juliensnz 

Thanks for your answer. We definitely found our way through this. Some things are not worth happening and this is one of them, that's why I never made a pull request. Thanks for insight and an awesome product you're creating.

Regards,
Paul Chubatyy
