### ISSUE TITLE
Akeneo\Component\Batch\Job\Job bad dependency

### ISSUE THREAD

**Issue by jmleroux** [akeneo/pim-community-dev#4310]
Batch Job seems to depend of StepInterface but it really depends of [AbstractStep](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Component/Batch/Step/AbstractStep.php) because of this line:
https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Component/Batch/Job/Job.php#L395

Also, it maybe show a missing spec, because it should have been detected by unit tests.

**Comment by skeleton** [comment]
Can we close this issue @jmleroux ?
