### ISSUE TITLE
Broken link on upload icon

### ISSUE THREAD

**Issue by JulienDotDev** [akeneo/pim-community-dev#4319]
Hi,

i'm using akeneo pim-community-standard 1.5. 
I have a test environment with an url like http://www.myurl.com/akeneo/.

Most of image links are ok but i noticed that on media field, the upload icon link was : 
"http://www.myurl.com/bundles/pimui/images/upload.png" instead of "http://www.myurl.com/akeneo/bundles/pimui/images/upload.png"

Best regards,

**Comment by a2xchip** [comment]
Hello @JulienDotDev. As i remember it had to be fixed by #759 @willy-ahva may know the story about subdir installations better.

**Comment by JulienDotDev** [comment]
Hi a2xchip,

thanks for these informations. 
I do understand the best pratice to use a different virtualhost but i think there will be many people who, like me, are not allowed/able to manage virtualhost etc on development/production servers.
I hope that Oro will allow this oneday and that in the end, akeneo will support it to.

Should i close ?

**Comment by juliensnz** [comment]
Hello,

I just checked with our product owner and we have a card in our backlog.

I will let you know here when it will be prioritized.

I close the issue if it doesn't bother you
