### ISSUE TITLE
Quick search on the family field in the product creation popin doesn't search in labels

### ISSUE THREAD

**Issue by RonanL** [akeneo/pim-community-dev#4321]
Reported in 1.5.1
Tested on Akeneo PIM online demo.

When creating a product, the quick search does not pass the current locale to the ajax request, so the controller only searches in the family codes and not the family labels.

To reproduce on the online demo, create a product and search for a part of a family label that is not in this family code, for instance "Hauts" with the FR locale. Then it doesn't return the expected result ("Hauts Parleurs").

With the english locale the problem is mitigated on the online demo as the code are transcriptions of the labels.

**Comment by juliensnz** [comment]
Hello Ronan,

This issue is already reported: [here](https://github.com/akeneo/pim-community-dev/issues/4306) And will be fixed soon (this week I hope).

Regards,

Julien

**Comment by a2xchip** [comment]
))) Yeah #4306 and #4302 PR duplication
