### ISSUE TITLE
Attribute option : char " is removed when edit option

### ISSUE THREAD

**Issue by jcpla** [akeneo/pim-community-dev#4353]
Hi Akeneo Team,

we encounter a specific bug when we update an attribute option.

We have an attribute for screen resolution (in inch - char ").
We create the option, eg. 19" and save the option => no problem it s saved.
I now want to edit the option : the char " is removed - eg. I have only 19 and I have to add " for each locales.

Tested in your demo.akeneo.com

Best regards
JC

**Comment by LaureBro** [comment]
Hello JC,
Thanks for your message!
 
What is the type of the attribute you have created?

Thanks,

Laure

**Comment by jcpla** [comment]
Simple select or multi select

Test with Clothing size on demo.akeneo.com
http://demo.akeneo.com/#url=/configuration/attribute/32/edit

JC

**Comment by LaureBro** [comment]
Hello, 

Thanks, I have created a bug in our bug tracker system. We'll let you know once it's fixed.

Best regards, 

Laure

**Comment by a2xchip** [comment]
@jcpla May be this one can help you 

http://docs.akeneo.com/latest/cookbook/catalog_structure/overriding_the_orm_product_value.html#linking-the-productvalue-to-a-collection-of-objects

**Comment by jcpla** [comment]
Hi @a2xchip 
I'm sorry but I don't understand how overriding a product value is linked this attribute option bug.

JC

**Comment by a2xchip** [comment]
@jcpla You may not only override but create new option types. Also it is possible to create new attribute types and fields according to your needs extending from metric.

**Comment by jcpla** [comment]
OK I see
Thanks
JC

**Comment by LaureBro** [comment]
Hi @jcpla, 
this issue has been fixed in 1.5 (from 1.5.14) and higher versions! If you're still on the 1.4, I recommend you to upgrade on one of our latest versions to benefit from this fix. 

Best regards, 

Laure
