### ISSUE TITLE
[Feature Request] : mass edit families : add new attributes

### ISSUE THREAD

**Issue by jcpla** [akeneo/pim-community-dev#4354]
Hi,

After using the PIM, we might have an enhancement for mass edit families : 
**be able to add same attributes to different families at once.**

For now there is only "choose required attributes"

Best regards
Jcpla

**Comment by pierallard** [comment]
Hi @jcpla 

If I understand your feature request, I'm proud to answer this feature already exists ;)

- Go to the families page
- Select your families
- Click on edit
- Set attribute requirements
- Select your attributes
- Next

And that's it! The "choose required attributes" is optional, the added attributes are added to all the families without be required.

If this is not what you need, please come back to me ;)

Pierre

**Comment by jcpla** [comment]
Hi @pierallard,

indeed it's exactly that !

Thank you very much
