### ISSUE TITLE
datetimepicker dropdown not visible if too many attributes

### ISSUE THREAD

**Issue by tebinu** [akeneo/pim-community-dev#4511]
If there are too many attributes (which means you have a scrollbar) in the product edit view and the last attribute is a datetimepicker, the popup will open below the input field which makes it invisible. It should open above the input field.

**Comment by tebinu** [comment]
<img width="871" alt="screen shot 2016-05-25 at 12 58 57" src="https://cloud.githubusercontent.com/assets/18256789/15537064/2060127c-227d-11e6-8b85-bfab3661fc46.png">

**Comment by LaureBro** [comment]
Hello, 
Thanks for reporting this, I'll create a ticket in our bug tracker. 

If you feel like fixing it yourself and need any assistance for this, we will be glad to help you :) 
Otherwise we'll let you know when this bug will be fixed.

Best regards, 

Laure

**Comment by tebinu** [comment]
Possible way to fix: use latest bootstrap datepicker and set orientation to auto in the datepicker options

**Comment by a2xchip** [comment]
@aRn0D This one is not easy pick. We already discussed this with @nidup as this one was fixed in one of integration projects, but fix itself presumes date picker source update that, as i understood is not acceptable for pim-community-dev. Another way is mentioned by @tebinu and is time consumable.

**Comment by Doodoune** [comment]
Hi! 
Do you still have this issue?
Regards,

**Comment by Doodoune** [comment]
I close this issue,
Feel free to reopen it if you still have a problem.
Regards,
