### ISSUE TITLE
UI Performance suggestions: Reduce assets file size

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4616]
Our users often complains the GUI performance of our Akeneo installation.
One small &easy improvement could be reducing the file size of the assets.

Here are some suggestions for an open discussion (I'm not a frontend performance guru):
- GZip: Enable GZip compression in the `.htaccess`. A call of the product grid `/enrich/product/` needs for us 3.7 MB (cache disabled). With enabled GZip compression it is just 1.2 MB! The time to finish the request reduce about 0.5s.
- Fonts:  Why is the `Lato-Regular.ttf` (in `UIBundle/Resources/public/fonts`) so big (642K)? The [original font from Google](https://www.google.com/fonts#UsePlace:use/Collection:Lato) seems to need only 118K.
- Is there a good reason that most of the Javascript and CSS isn't compressed?
- Maybe it would help to outsource some static assets to a CDN like [Google Hosted Libraries](https://developers.google.com/speed/libraries/#jquery) for JQuery so the browser can handle more concurrent connections?

**Comment by aRn0D** [comment]
Thank you Hocdoc to raise those problems. We should work on it as soon as possible but if you want to contribute, every contributions are very welcome. Some core team devs like @juliensnz, @loicguillois and @phaseinducer can help or speak with you about this topic.

**Comment by a2xchip** [comment]
@Hocdoc About fonts. As i remember it is known that google shorts fonts pallete. Their version often excludes extended latin and cyryllic symbols. But it must be tested for their Lato font to be sure.

**Comment by jmleroux** [comment]
Hello,

The UI changed drastically since this issue and i will close it. Feel free to reopen it if you think it is still relevant.

Regards
