### ISSUE TITLE
Yes/No attribute filter doesn't work in product grid

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4629]
In the product grid when filtering for a Yes/No attribute, the No-filter doesn't work as expected: When the attribute has the value "No" the product gets not displayed when filtering for this.

Steps to reproduce on http://demo.akeneo.com/ (Akeneo 1.5.5):
1. Create a new product with the "Digitals camera" family
2. The attribute "Auto focus lock" in the Attribute group "Technical" is "No" in this new product. Return to the product grid.
3. Filter the attribute "Auto focus lock" for the value "No"

=> No results found, which is confusing.

The filter only works, if you save the product with the attribute value "Auto focus lock = Yes" and switch after that again to "Auto focus lock = No".

I think this is because the Yes/No attribute has initial an empty value but is displayed with a "No" value.

By the way, a lot of our users wishes a filter for non-empty values (f.ex. for select attributes).

**Comment by aRn0D** [comment]
Hi Hocdoc,

Thank you for raising this issue, there is a bug indeed. The product are not created their empties values, I guess that the product value are not created for boolean attribute by default and it should be.

**Comment by aRn0D** [comment]
@Hocdoc it will be fix in the next version,  the javascript component will be updated. You will able to set it to `Yes`, `No` or `No value`.

**Comment by Hocdoc** [comment]
Thanks for the news.

(I am not sure if the `No value` filter isn't confusing here for the user, as also empty Yes/No attributes will be displayed with a `No` value in the PEF.)

**Comment by LaureBro** [comment]
Hello @Hocdoc, I've checked with our Product Team and they also planned to change the attribute used in the Product Edit Form to manage this 3rd state, to avoid any misleading.
Thanks.

**Comment by AFBElektronik** [comment]
This bug is not resolved. Any schedule to fix the bug?

**Comment by LaureBro** [comment]
Hello @AFBElektronik, sorry for the late reply. 
We will fix this issue by releasing a new boolean attribute that will manage 3 states: Yes, No and no value.
Like @Hocdoc said, when you first add the attribute to a product/family, the default value is 'no value', even if value 'no' is displayed. What you need to do is edit the product, set the boolean to Yes, save and then set it to the desired value (you can mass edit the attribute if you have several products to edit). 
We know it's not an ideal behaviour, but we'll improve it!

thanks!

**Comment by damien-carcel** [comment]
Hello.

This bug is fixed in 1.7 and 2.x now. Closing this issue.

Feel free to reopen it if you have more questions.

Regards,
Damien.

**Comment by juskor-mt** [comment]
Hello @LaureBro, is that 3 states boolean attributes already released? Or if not, are there any estimate?

> We will fix this issue by releasing a new boolean attribute that will manage 3 states: Yes, No and no value - unfortunately I cannot give you a precise date.
> Like @Hocdoc said, when you first add the attribute to a product/family, the default value is 'no value', even if value 'no' is displayed. What you need to do is edit the product, set the boolean to Yes, save and then set it to the desired value (you can mass edit the attribute if you have several products to edit).
> We know it's not an ideal behaviour, but we'll improve it!
> 
> thanks!

**Comment by LaureBro** [comment]
Hello @juskor-mt, no unfortunately, it has not been released and it is not yet prioritised, but it's still on the Product team's pipe. 
I have informed our Product team of your feedback, we'll keep you posted.

Kind regards, 
Laure
