### ISSUE TITLE
"Are you sure you want to leave this page?" for Categories

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#4715]
**I'm reporting a Bug**
you forgot about warning for changed forms

http://demo.akeneo.com/#url=/enrich/product-category-tree/1/edit

**Comment by aRn0D** [comment]
I am not sure you mean, there is that popup when you try to leave category edition page.

**Comment by userz58** [comment]
yes, i speak about popup window
![- -1](https://cloud.githubusercontent.com/assets/2612186/16781563/86a473fc-4884-11e6-9990-df4007b06f7d.jpg)

**Comment by aRn0D** [comment]
Strange I got **You will lose changes to the (category|tree) if you leave the page.** which category did you try to edit?

**Comment by userz58** [comment]
can you open your demo site?
http://demo.akeneo.com/#url=/enrich/product-category-tree/6/edit

i will lose changes when i click on other category
but when i will close browser window (tab), i will see modal window

**Comment by Hocdoc** [comment]
By the way, when editing an attribute there is also no popup warning.
(I have just lost 30s by browsing to another URL while editing an attribute ;-) )

**Comment by nidup** [comment]
Thank you for the bug report ! I reproduced on 1.5 and master (upcoming 1.6).

Yes, we should display the "Are you sure you want to leave this page?" popup when we click on another category in the tree (if a data has been updated in the form, ie the "There are unsaved changes." is displayed).

If someone want to pick and fix this issue, feel free !

**Comment by tamarasaurus** [comment]
This issue has been fixed in v1.6
