### ISSUE TITLE
Product grid: Pagination labels on a small screen

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4716]
A small GUI bug in the product grid (Akeneo 1.5.6, Chrome 51).

When resizing the browser window to a smaller size than 1200px (which isn't that small) the position of the "Page:" label or the totalPages / totalRecords - Labels move to a second row which is confusing:

![screenshot](https://cloud.githubusercontent.com/assets/3492813/16724451/0d3daaf6-4753-11e6-8acf-410f848a79bd.png)

This issue can get reproduced on http://demo.akeneo.com/ .

**Comment by aRn0D** [comment]
Thank you @Hocdoc for raising this problem.

**Comment by nidup** [comment]
Hi!

Akeneo PIM does not support smaller size that 1280 px cf https://docs.akeneo.com/latest/reference/technical_information/client_side_compatibilities.html#browsers

Have a good day!

**Comment by Hocdoc** [comment]
Thanks for your comments to my issues.

Well when the browser font was set big enough (which you cannot control)... the described problem still appears on my 1920px screen.
 
But it's really only a minor problem, so we can live without a fix ;-).
