### ISSUE TITLE
Import product merge new attributes/categories/family of existing product

### ISSUE THREAD

**Issue by ILinKI** [akeneo/pim-community-dev#4730]
Hello,
I am new to Akeneo, and have some problems with import products.

I have imported some products with a certain product named "Rod01", this product is in the categorie "Carp rod".

Few days laters, I decide to import others products, and "Rod01" again with now the categorie "Trout rod".

I have noticed that my categorie "Carp rod" was deleted.

So I suppose that he delete my product and create the new one or something like that.

Is it possible to merge informations of existing product for not loosing our informations cause I need "Rod01" is in the categories "Carp rod" and "Trout rod"?

Thanks !

**Comment by aRn0D** [comment]
Hi ILinKI,

This is normal, the product is updated (not created) with the latest provided data. It is not possible to merge information, every categories should be in the CSV file. It looks like:
```csv
identifier; catagories
Rod01;carp_rod,trout_rod
```

**Comment by ILinKI** [comment]
Hi aRn0D,

Thanks for your answer, I thought it existed a method or a configuration to merge information but okay !
