### ISSUE TITLE
Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException'

### ISSUE THREAD

**Issue by saulhudson** [akeneo/pim-community-dev#4742]
**I'm reporting a Bug**

I have just updated from 1.4.18 to the latest version 1.4.26 and I've seeing the following error.

I've cleared the caches, restarted apached as per #3461 https://github.com/akeneo/pim-community-dev/issues/3461 but I'm still seeing the error.

Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 6 passed to Pim\Component\Catalog\Updater\FamilyUpdater::__construct() must be an instance of Pim\Component\Catalog\Repository\AttributeRequirementRepositoryInterface, instance of Doctrine\ORM\EntityRepository given

**Comment by aRn0D** [comment]
Hi Rich,

Do you overwrite that service?

**Comment by saulhudson** [comment]
No nothing is changed from the default installation.

**Comment by saulhudson** [comment]
I've sorted this. Rebooting the VM that Akeneo was on resolved the issue.
