### ISSUE TITLE
Add/Edit family forgets Properties after adding Attributes

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4772]
**I'm reporting a Bug**

When adding an attribute to a family, the PIM forgets about the changes in the Properties tab.

Akeneo 1.5.7, reproducible on http://demo.akeneo.com/ :
1. Edit or add a family, f.ex. http://demo.akeneo.com/configuration/family/6/edit
2. Change some values in the "Properties" tab f.ex. change some locale values
3. Click into the "Attributes" tab and add some attributes
4. When you switch back to the "Properties" tab you will see that the changes from step 2 are lost.

**Comment by aRn0D** [comment]
@Hocdoc Thank you for raising this issue. Indeed the page is reloaded after adding a attribute, thus you lost the properties. I will create a issue in our bug tracker.

**Comment by LaureBro** [comment]
Hello @Hocdoc, 

this issue is fixed in the upcoming 1.7 🎉  

Kind regards, 

Laure

**Comment by Hocdoc** [comment]
It works now :-).
