### ISSUE TITLE
Number attribute field validation in product edit

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#4806]
**I am reporting a Bug**

There is no way to set Max. digits in number attribute field. for e.g. UPC (12 characters) or EAN (13 characters)

[Edition]
CE

[Version]
1.5.7

[Storage]
doctrine/orm

[Environment]
prod

[Install time]
2016-07-28T10:50:54+04:00

[Registered bundles]
Registered bundles APY\JsFormValidationBundle\APYJsFormValidationBundle
Acme\Bundle\DummyConnectorBundle\AcmeDummyConnectorBundle
Akeneo\Bundle\BatchBundle\AkeneoBatchBundle
Akeneo\Bundle\BufferBundle\AkeneoBufferBundle
Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle
Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle
Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle
Akeneo\Bundle\SpreadsheetParserBundle\AkeneoSpreadsheetParserBundle
Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle
Doctrine\Bundle\DoctrineBundle\DoctrineBundle
Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle
Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle
Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle
FOS\JsRoutingBundle\FOSJsRoutingBundle
FOS\RestBundle\FOSRestBundle
JMS\SerializerBundle\JMSSerializerBundle
Knp\Bundle\MenuBundle\KnpMenuBundle
Liip\ImagineBundle\LiipImagineBundle
Nelmio\ApiDocBundle\NelmioApiDocBundle
Oneup\FlysystemBundle\OneupFlysystemBundle
Oro\Bundle\AsseticBundle\OroAsseticBundle
Oro\Bundle\ConfigBundle\OroConfigBundle
Oro\Bundle\DataGridBundle\OroDataGridBundle
Oro\Bundle\FilterBundle\OroFilterBundle
Oro\Bundle\FormBundle\OroFormBundle
Oro\Bundle\NavigationBundle\OroNavigationBundle
Oro\Bundle\RequireJSBundle\OroRequireJSBundle
Oro\Bundle\SecurityBundle\OroSecurityBundle
Oro\Bundle\TranslationBundle\OroTranslationBundle
Oro\Bundle\UIBundle\OroUIBundle
Oro\Bundle\UserBundle\OroUserBundle
Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle
Pim\Bundle\BaseConnectorBundle\PimBaseConnectorBundle
Pim\Bundle\CatalogBundle\PimCatalogBundle
Pim\Bundle\CommentBundle\PimCommentBundle
Pim\Bundle\ConnectorBundle\PimConnectorBundle
Pim\Bundle\DashboardBundle\PimDashboardBundle
Pim\Bundle\DataGridBundle\PimDataGridBundle
Pim\Bundle\EnrichBundle\PimEnrichBundle
Pim\Bundle\ExcelConnectorBundle\PimExcelConnectorBundle
Pim\Bundle\FilterBundle\PimFilterBundle
Pim\Bundle\ImportExportBundle\PimImportExportBundle
Pim\Bundle\InstallerBundle\PimInstallerBundle
Pim\Bundle\JsFormValidationBundle\PimJsFormValidationBundle
Pim\Bundle\LocalizationBundle\PimLocalizationBundle
Pim\Bundle\NavigationBundle\PimNavigationBundle
Pim\Bundle\NotificationBundle\PimNotificationBundle
Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle
Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle
Pim\Bundle\TransformBundle\PimTransformBundle
Pim\Bundle\UIBundle\PimUIBundle
Pim\Bundle\UserBundle\PimUserBundle
Pim\Bundle\VersioningBundle\PimVersioningBundle
Pim\Bundle\WebServiceBundle\PimWebServiceBundle
Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
Symfony\Bundle\AsseticBundle\AsseticBundle
Symfony\Bundle\FrameworkBundle\FrameworkBundle
Symfony\Bundle\MonologBundle\MonologBundle
Symfony\Bundle\SecurityBundle\SecurityBundle
Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
Symfony\Bundle\TwigBundle\TwigBundle

**Comment by LaureBro** [comment]
Hello @wakqasahmed, 

Thanks for raising this issue, you cannot add validation parameters on the number of character for a number attribute.

If you want to add a validation for your EAN or UPC codes, we advise you to create a text attribute and add a validation with a Regular Expression. You'll find more information about the RegEx formula to use in this Knowledge Base article: [(https://www.akeneo.com/knowledge-base/how-do-i-create-an-ean13-barcode-attribute-type-in-the-pim/)]

Hope this information will be useful for you!

Best regards, 

Laure

**Comment by wakqasahmed** [comment]
Thanks. yep it did help :)
