### ISSUE TITLE
Add the Mysql 5.7 support (support the "only_full_group_by" mode)

### ISSUE THREAD

**Issue by nidup** [akeneo/pim-community-dev#4855]
Akeneo PIM does not support Mysql 5.7, cf https://docs.akeneo.com/latest/developer_guide/installation/system_requirements/system_requirements.html

When using MySQL 5.7, you need to deactivate the "only_full_group_by" mode to make the PIM works.

This enhancement is referenced in our internal ticketing system as TIP-425 and has been reported in several issues,
- https://github.com/akeneo/pim-community-dev/issues/4748
- https://github.com/akeneo/pim-community-dev/issues/4829

If someone is interested to pick up this task, please post a comment in this issue before to open a pull request on the master.

**Comment by erfanimani** [comment]
Got bitten by this one as well, wouldn't run out of the box.]=

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` will sort it out, but a more permanent fix should be done as more people will run on Ubuntu 16.04 which includes MySQL 5.7 by default.

**Comment by mickaelandrieu** [comment]
Hello,

`master` branch is now fully compatible with MySQL 5.7.

Thanks @nidup !

**Comment by ahocquard** [comment]
@mickaelandrieu we still need to deactivate "only_full_group_by" with Mysql 5.7

**Comment by mickaelandrieu** [comment]
@ahocquard ok, sorry. Should I reword the issue? In your opinion, is it something a community member could do?

**Comment by ahocquard** [comment]
@mickaelandrieu Not easily. Actually, without the CI, it's almost impossible to know where it's failing. And it implies to customise the CI to activate the option (it's deactivated by default in the docker) and see what is failing. 

So, *imho*, it's hardly doable by a community member (but not impossible ;) ).
And moreover, I believe that we have some Oro stuff using some request with bad use of GROUP BY (= only_full_group_by off), and I don't know if it's in our code our in a dependency. If it's in our dependency, pretty hard to fix that without fixing the dependency version (that can impact a lot of things).
