### ISSUE TITLE
Collapsed Sidebar has non-clickable floating button (Minor UI bug)

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#4859]
**I'm reporting a Bug**

When the div.separator has the class .collapsed, div.sidebar-controls has this non clickable "+" button lingering.

<img width="1279" alt="screen shot 2016-08-18 at 2 44 50 pm" src="https://cloud.githubusercontent.com/assets/4486133/17771191/ea181098-6552-11e6-9b07-cb1b9127708a.png">

In my opinion, this "+" button should be display:none on separator.collapsed and display:block on separator.expanded

[Edition]
CE

[Version]
1.5.7

[Storage]
doctrine/orm

[Environment]
prod

**Comment by Doodoune** [comment]
Hi @wakqasahmed,
Did you solve your issue? 
Regards,

**Comment by wakqasahmed** [comment]
Nopz, it wasn't critical. I moved to v1.6 soon after. Though the problem persists in v1.6 as well.

**Comment by jmleroux** [comment]
Hello,

This version is not supported anymore and we probably won't fix this issue.
Do not hesitate to ask the community if you still need a fix on this version.

Regards
