### ISSUE TITLE
Multiselect in filter bar not behaving appropriately (UI bug)

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#4950]
**I'm reporting a Bug**

In attribute grid page or any such other grid page, when selecting any filter other than "all", it doesn't show the resulting grid (as the "all" checkbox is still selected).

<img width="1277" alt="screen shot 2016-08-31 at 12 53 53 pm" src="https://cloud.githubusercontent.com/assets/4486133/18122362/0766b72c-6f7a-11e6-9d39-21587f02f910.png">

<img width="1277" alt="screen shot 2016-08-31 at 12 41 01 pm" src="https://cloud.githubusercontent.com/assets/4486133/18122271/a52d4580-6f79-11e6-9d57-19dc220438e3.png">

**Suggestion:**
"all" checkbox should get unchecked as soon as any other filter is selected

[Edition]
CE

[Version]
1.6.0

[Storage]
doctrine/orm

[Environment]
prod

**Comment by LaureBro** [comment]
Hello @wakqasahmed, thanks for your feedback.

I have created a suggestion of improvement under the reference: IM-619, you will be informed when this behaviour will be changed.

Regards,

**Comment by wakqasahmed** [comment]
I am willing to contribute, if provided guidelines about front end structure.

**Comment by LaureBro** [comment]
Hi @wakqasahmed, that's great! thanks! From the 1st infos my team gave me, it can be a bit tricky, but I'll ask one of our developer if we have such guidelines.
Thanks!

**Comment by LaureBro** [comment]
Hi @wakqasahmed, we have changed this behaviour in the 1.7. 
I'll close this issue.

Kind regards,

Laure
