### ISSUE TITLE
Akeneo 1.6 update info missing

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#4959]
**I'm reporting a Bug**

Akeneo 1.6.0 http://demo.akeneo.com/

Trying to query https://updates.akeneo.com/CE-1.6.json for update info.
Expect to get similar result as with Akeneo 1.5.x https://updates.akeneo.com/CE-1.5.json
```
{
    last_patch: {
        name: "v1.5.8"
    }
}
```
Actually get 404

**Comment by LeoBenoist** [comment]
Hello @mathewrapid !
Thank you for reporting this missing file.

It has been fixed!

Kind regards,
Léo
