### ISSUE TITLE
GUI: Touch events

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#4971]
**I'm reporting a Bug**

Akeneo 1.4 (maybe 1.5) with Chrome

If a user has a touchscreen (e.g. some laptops) then the mouse clicks are not propagated correctly.

![image](https://cloud.githubusercontent.com/assets/1784672/18195501/7d59f888-70f4-11e6-8e2f-d4fbdb6d4df5.png)

With Chromes touch events enabled (chrome://flags/#touch-events), those buttons cannot be clicked. Same applies to the save button dropdown on the product page.

**Comment by mathewrapid** [comment]
Tested it on demo.akeneo.com which runs version 1.6.1 of Akeneo. There the problem seems to be corrected.

**Comment by nidup** [comment]
Hi @mathewrapid 

Thank you for the report and the qualification, I don't see what we've changed that could improve this issue (FYI, we don't test the PIM on touch screen).

Don't hesitate to open another ticket if you encounter any other issue.

Have a good day!

**Comment by mathewrapid** [comment]
@nidup Please, don't close the ticket. You recommend the latest Chrome as the browser, but this causes a problem with any device with a touchscreen e.g. some business laptops have them; mouse as the pointing medium. Caused by this bug/feature of chrome https://bugs.chromium.org/p/chromium/issues/detail?id=332397

You've probably done some changes to the ui in 1.6 that circumvents this; updated underlying JS components maybe.

Nevertheless, this is still an issue to many of our customers, as they're using touchscreen capable laptops.

**Comment by nidup** [comment]
Hi @mathewrapid 

Sorry, my bad, I re-open the ticket :)

Thank you very much for the detail, I tag the issue it as "contribution welcome", don't hesitate to give more details or to open a pull request if you manage to find a workaround, I'll be happy to help by reviewing and merging.

Have a good day.

**Comment by Doodoune** [comment]
Hi @mathewrapid,
Did you solve your issue?
Regards,

**Comment by mathewrapid** [comment]
Ho @Doodoune ,
This has turned out to be a minor issue, so we haven't looked into it any further
