### ISSUE TITLE
Currencies missing data

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#4986]
**I'm reporting a Bug**

In **version 1.5** number of currencies are **197**, in **version 1.6** it is **101**
<img width="1279" alt="screen shot 2016-09-04 at 12 09 29 pm" src="https://cloud.githubusercontent.com/assets/4486133/18229844/9cf07366-7298-11e6-9c8a-ec2be7d630dc.png">

<img width="1277" alt="screen shot 2016-09-04 at 12 29 24 pm" src="https://cloud.githubusercontent.com/assets/4486133/18229902/4410e458-729b-11e6-89e2-0844c3aa0a05.png">

[Edition]
CE

[Version]
1.6.0

[Storage]
doctrine/orm

[Environment]
prod

**Comment by LaureBro** [comment]
H

**Comment by nidup** [comment]
Hi @wakqasahmed 

Thank your for the report! This issue will be soon fixed with this pull request https://github.com/akeneo/pim-community-dev/pull/5033 by @ahocquard 

Have a good day.

**Comment by nidup** [comment]
Hi @wakqasahmed 

Thanks again for this bug report, the fix has been released in the v1.6.3 https://github.com/akeneo/pim-community-dev/blob/1.6/CHANGELOG-1.6.md#163-2016-09-22

Have a good day.
