### ISSUE TITLE
Exception while saving a customer with Product grid filters

### ISSUE THREAD

**Issue by Pacolu** [akeneo/pim-community-dev#4988]
Hello,
I have encountered a bug while saving a customer.

If you use the Product grid filters (for example status) and call the save action, this exception occurs:

> An exception has been thrown during the rendering of a template ("You have requested a non-existent service "pim_datagrid.datagrid.product.filters_configurator". Did you mean this: "pim_datagrid.datagrid.configuration.product.filters_configurator"?") in vendor/akeneo/pim-community-dev/src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig at line 110.
500 Internal Server Error - Twig_Error_Runtime
1 linked Exception: ServiceNotFoundException »

here my system info:

[akeneo-pim-system-info_2016-09-07_10-48.txt](https://github.com/akeneo/pim-community-dev/files/458675/akeneo-pim-system-info_2016-09-07_10-48.txt)

**Comment by Mathieudewet** [comment]
/**
     * @return FiltersConfigurator
     */
    final protected function getFiltersConfigurator()
    {
        return $this->container->get('pim_datagrid.datagrid.configuration.product.filters_configurator');
    }

**Comment by nidup** [comment]
Hello @Mathieudewet 

Exact, this is the problem :tada: 

FYI, this issue has been fixed on the 1.6 branch 2 days ago via this PR https://github.com/akeneo/pim-community-dev/pull/5027

The fix will be released tomorrow with the upcoming v1.6.3 before to be merge in master branch (the future v1.7).

Have a good day!
