### ISSUE TITLE
1.6 Upgrade Property Pim\Bundle\CatalogBundle\Entity\Channel::$color does not exist

### ISSUE THREAD

**Issue by saulhudson** [akeneo/pim-community-dev#4990]
After upgrading from 1.5 to 1.6.2 Akeneo is throwing a 500 Internal Server and I am seeing the following error in the prod.log.

`[2016-09-07 10:47:09] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Property Pim\Bundle\CatalogBundle\Entity\Channel::$color does not exist" at /var/www/www-akeneo/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php line 82 {"exception":"[object] (ReflectionException(code: 0): Property Pim\\Bundle\\CatalogBundle\\Entity\\Channel::$color does not exist at /var/www/www-akeneo/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:82)"} []
`

I followed the instructions (https://github.com/akeneo/pim-community-standard/blob/1.6/UPGRADE-1.6.md#migrate-your-standard-project) and we don't have any custom code in our installation.

I'm a bit confused as to why our installation is looking for the colour of a channel. I can see from your migration that you have dropped the column from the database so maybe some part of installation is still looking for color.

`  ++ migrating _1_6_20160530174030_remove_channel_color

     -> ALTER TABLE pim_catalog_channel DROP color`

Can you please advise as to how we can get back into our Akeneo installation please?

Many Thanks

**Comment by solivier** [comment]
Hi @saulhudson,

Did you cleared the cache ? Could you try to execute this command: `rm -rf app/cache`
If it doesn't work you could also try to restart apache2 sometimes it comes from the APC cache.
Tell me if it works

Thank for raising the issue.

Have a good day,
Olivier

**Comment by saulhudson** [comment]
Yes I tried that. It's OK though we did a full reinstall from scratch and re-imported our data. Long process but we are sorted

**Comment by Hocdoc** [comment]
I've also seen this error when upgrading one of our Akeneo installations from 1.6 to 1.7.
Restarting apache2 helped, thanks for the suggestion.
