### ISSUE TITLE
Duplicate products after CSV product import

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4992]
**I'm reporting a Bug**
- Updating products with the `csv_product_import`
- The `product.csv` contains two equal lines with the same product update  
- => Instead of one updated product, there will be a new product created with a duplicated SKU

This bug is rather critical for us, as we get new ghost products without unique values in our PIM system.

We are using Akeneo 1.5.8, but the issue is also in 1.6.2: I can reproduce it on http://demo.akeneo.com/ :

Import this file with the `csv_product_import`:

```
sku;name
20126;"An update"
20126;"An update" 
```

=> After that, there should be two products with the SKU `20126`.

If the product already has a media, there will be another error message during product import.

Maybe the cause of the problem is detaching a product when `product_skipped_no_diff`?

**Comment by fabienlem** [comment]
Hello @Hocdoc,

SKU duplication issue can happen when you are using MySQL, it is linked to doctrine's object detacher. We are currently thinking about the best way to prevent this. We will keep you updated.

Regards,
Fabien

**Comment by a2xchip** [comment]
@Hocdoc @fabienlem Workaround is to create validation step that will check duplication.

**Comment by Hocdoc** [comment]
This seems to be fixed in 1.7, hooray!
