### ISSUE TITLE
XLSX product import numeric value for simpleselect codes

### ISSUE THREAD

**Issue by naolis** [akeneo/pim-community-dev#4993]
Hi, in Akeneo 1.6 with the product XLSX import job. I have the following issue. 

If my excel cells = 40 for an attribute type simpleselect i get an ignore when i process the job. 
`Attribute or field "diam_verin" expects a string as data, "integer" given (for setter simple select).` 

Even if i configure the cells in format = text in Excel

[akeneo-pim-system-info_2016-09-08_16-40.txt](https://github.com/akeneo/pim-community-dev/files/461891/akeneo-pim-system-info_2016-09-08_16-40.txt)

**Comment by LaureBro** [comment]
Hello @naolis, thanks for reporting this. This behaviour has been reproduced on our side too.

Would you be interested into investigating this and contribute to fix it? 

We will be happy to help you to review and merge your pull request. If you are interested into fixing it, please read and sign our contributor agreement https://www.akeneo.com/contributor-license-agreement/.

Best regards, 

Laure

**Comment by solivier** [comment]
Hello @naolis,

I think the error comes from the `Pim\Component\Catalog\Updater\Setter\SimpleSelectAttributeSetter::checkData` where we check if the data is a string you could add something like `&& !is_numeric($data)` line 88 to prevent the raise of the exception in case the value is a numeric and create a pull request if you are interested to contribute :)

Feel free to ask any questions if you need more help, I would be happy to help you.

Have a nice day.
Olivier

**Comment by solivier** [comment]
Fixed on 1.6 branch
