### ISSUE TITLE
console oro:requirejs:build  show dependencies error

### ISSUE THREAD

**Issue by danielpoe** [akeneo/pim-community-dev#4998]
When running 

Missing dependencies are claimed

In 
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml

There are JS and HTML referenced that do not exist in filesystem:

  pim/filter/text:                       pimenrich/js/filter/text
  pim/filter/simpleselect:               pimenrich/js/filter/simpleselect
  pim/template/filter/text:                       pimenrich/templates/filter/text.html

Why is that? And how do you compile / build the oro.min.js then?

**Comment by solivier** [comment]
Hi @danielpoe,

I think something went wrong when you installed your assets. Maybe you could try to run this command to fix this: `rm -Rf ./app/cache/* ./web/bundles/* ./web/css/* ./web/js/*; ac pim:install:ass -e=env;ac assets:install --symlink web`

Best regards,
Olivier.

**Comment by akazik** [comment]
Same problem here.
Steps to reproduce:

1. download 1.6.2 standard archive file: https://www.akeneo.com/download/
2. app/console oro:requirejs:build

OR

1. download https://github.com/akeneo/pim-community-standard/releases/tag/v1.6.0
2. composer install
3. app/console oro:requirejs:build

Executing the steps above does not help.

**Comment by masmrlar** [comment]
Hi, 
even with the command above we get this error:

```
[RuntimeException]
  Tracing dependencies for: /var/www/fraport-web/devbox/pim/releases/fraport-pim_1.0.0-659/web/js/oro.min.js
  Error: Error: ENOENT, no such file or directory '/var/www/fraport-web/devbox/pim/releases/fraport-pim_1.0.0-659/web/bundles/pimenrich/js/produc
  t/form/back-to-grid.js'
      at Object.fs.openSync (fs.js:432:18)
```

ls shows this:
```
ls web/bundles/pimenrich/js/product/form/
associations.js  attributes.js  delete.js        locale-switcher.js  meta   product-label.js  save.js            sequential-edit.js
attributes       categories.js  download-pdf.js  mass-edit           panel  save-and-back.js  scope-switcher.js  status-switcher.js
```

**Comment by masmrlar** [comment]
Ah, I found the answer here: https://github.com/akeneo/pim-community-dev/issues/5072

**Comment by fabienlem** [comment]
I'm closing this issue.
