### ISSUE TITLE
Getting error while importing and exporting

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#5013]
**I'm asking a Question**

**PRODUCT IMPORT  [Semantical Error] line 0, col 125 near 'attribute = 29': Error: Class Pim\Component\Catalog\Model\ProductValue has no field or association named attribute**

**PRODUCT EXPORT  No mapping found for field 'attribute' on class 'Pim\Component\Catalog\Model\ProductValue'.**

While investigating, i found out that my identifier (sku) is the one causing problem for some reason. Tried to delete and recreated the attribute but no luck. Any idea what might be wrong?

BTW, product creation from UI is fine but producing the same error while exporting.

Please help. Thanks

**Comment by wakqasahmed** [comment]
CustomEntityBundle was the culprit. Was i doing something wrong trying to make CustomEntityBundle work with akeneo v1.6?

**Comment by fitn** [comment]
Hi @wakqasahmed 

Could you give me more explanation about your error? The CustomEntityBundle is already compatible with Akeneo PIM 1.6 but we maybe missed to tests some features.

Regards,

**Comment by wakqasahmed** [comment]
Well, its not in my requirement list so will check it out once i get some free time. If you have tested it and want me to close the issue, I am happy to do that (will reopen if could reproduce).

Thank You
