### ISSUE TITLE
Unused / Dead Code for creating new Products

### ISSUE THREAD

**Issue by danielpoe** [akeneo/pim-community-dev#5017]
Hey

It seems some Backend based Forms that have been used in older PIM Versions are replaced by Javascript based forms and calling Rest APIs.

For example:
\Pim\Bundle\EnrichBundle\Form\Type\ProductCreateType  seems not to be used anymore?
(+ related ProductCreateTypeSpec)

Is that true? Then its maybe better to delete all the unused code?

Cheers,
Daniel

**Comment by nidup** [comment]
Hi @danielpoe !

Exact, thank you for raising this issue, we forget to drop it! :tada: 

FYI, we don't drop any existing code on already released versions to avoid any issue when applying patches on projects, however we should drop it in the upcoming 1.7 version (master branch).

Are you interested to drop these classes and the related symfony service through a pull request? I'll be happy to help you by reviewing and merging this PR.

If you're interested, I'll need that you read and sign our contributor agreement to merge the pull request https://www.akeneo.com/contributor-license-agreement/

Thank you!

**Comment by pierallard** [comment]
Thanks @a2xchip  for your fix !
