### ISSUE TITLE
Wrong default filepath in product export (csv and xlsx)

### ISSUE THREAD

**Issue by gohartonyan** [akeneo/pim-community-dev#5037]
There is a missing directory separator in the default export filepath. Executing the export without adapting the defalut path runs into an error.

Tested with the current Master

**Comment by nidup** [comment]
Hi @gohartonyan 

Thank you very much for raising this issue and for contributing a pull request :)

This issue has already been fixed and merged yesterday in the 1.6 branch via the following pull request https://github.com/akeneo/pim-community-dev/pull/4941 and the fix will be available in the upcoming v1.6.3 (will be released tomorrow).

FYI, in our workflow, each time we fix something in an older branch, for instance, v1.6, we release then we merge the fix in more recent versions, with this example, fix in v1.6 then merge the fix in v1.7 (master). So, the fix will be available on master tomorrow just after the v1.6.3 release.

Sorry to not be able to merge your related PR to avoid conflict with the merge of the 1.6 fix. Don't hesitate to open any other issues or pull request, we'll be glad to review and help.

Have a good day.
