### ISSUE TITLE
Product not found - Parsing part of product ID - MongoDB

### ISSUE THREAD

**Issue by janssensjelle** [akeneo/pim-community-dev#5043]
**I'm reporting a Bug**

While browsing through products in the grid, some product results in a 500 error. If I manually check the product id from the URL, in MongoDB, it exists.

When looking in the logs it says the product does not exist, so it returns a 500 error. But however, logging the request, the request parses the correct id. However, it is only searching for a part of the product id

> [2016-09-21 14:14:26] request.INFO: Matched route "pim_enrich_product_rest_get". {"route_parameters":{"_controller":"pim_enrich.controller.rest.product:getAction","_format":"json","id":"57d2b88b58ebec84268b4567","_route":"pim_enrich_product_rest_get"},"request_uri":"http://akeneo.pim/enrich/product/rest/57d2b88b58ebec84268b4567"} []
> [2016-09-21 14:14:26] request.CRITICAL: Uncaught PHP Exception Doctrine\ODM\MongoDB\DocumentNotFoundException: "The "MongoDBODMProxies__CG__\Pim\Component\Catalog\Model\Product" document with identifier "57d2b9d258ebeccd268b4584" could not be found." at /var/www/akeneomongo/src/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php line 33 {"exception":"[object](Doctrine\ODM\MongoDB\DocumentNotFoundException: The "MongoDBODMProxies\__CG__\Pim\Component\Catalog\Model\Product" document with identifier "57d2b9d258ebeccd268b4584" could not be found. at /var/www/akeneomongo/src/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php:33)"} []

For an unapartent reason it is searching for ID: 57d2b9d258ebeccd268b4584

Mongo document ID: 57d2b88b58ebec84268b4567
ID in URL: 57d2b88b58ebec84268b4567

It's missing the last bit, 268b4567, however it parses this in the url?

Akeneo version: 1.5.8
PHP version: 5.6.25

**Comment by solivier** [comment]
Hi @janssensjelle,

Thanks for raising the issue, do you have an example of product (sku) that gives a 500 ? I tried on my side I couldn't find a product that raised a 500. 

Have a nice day.

Olivier.

**Comment by janssensjelle** [comment]
Hi @solivier 

Thanks for replying. 
This is on a live production database on our servers. Basically the SKU is like any other, 3 letters and 4 numbers. I can't see anything wrong in the data. 

The only thing I see is that the document/product ID is being sent correctly, in the URL. As you can see the error log sends an incorrect document ID back, only a part of it. So it seems to be getting trimmed somewhere? Even though this is just in a product load

**Comment by janssensjelle** [comment]
@solivier After doing some debugging, I found the issue, when an association went missing it will throw this error. 

No idea what caused this. Perhaps some error handling here could be added to show people that this is the case.

**Comment by mathewrapid** [comment]
Copy&paste from Akeneo's slack

> I've got a problem with removing attributes. Akeneo 1.4, MongoDB 2.6, products in db 100K+.
> 
> When deleting few attributes from the system (over 80K products have this) the Mongo connection times out (60s). Some/most of the products are left with references to non existing attributes. This'll yeld an exception
> `request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\EntityNotFoundException: "Entity was not found." at .../vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php line 177`

Basically when using MongoDB and removing an attribute, it might leave these associations to said attributes behind.

**Comment by janssensjelle** [comment]
This is still an issue. Will look into a function to perhaps clear out ghost associations instead of throwing a 500 error. Anyone have any thoughts?
