### ISSUE TITLE
[v1.6.3] Pim\Bundle\EnrichBundle\Form\Type\ImageType missing (possible dead code)

### ISSUE THREAD

**Issue by eheuje** [akeneo/pim-community-dev#5048]
Since 1.6.1, the form type **Pim\Bundle\EnrichBundle\Form\Type\ImageType** have disappeared however the parameters is still **pim_enrich.form.type.image.class** is still affected to **Pim\Bundle\EnrichBundle\Form\Type\ImageType** and the **pim_enrich_image** is still declared.

**Comment by nidup** [comment]
Hi @eheuje !

Exact, thank you for raising this issue, we forgot to drop it! :tada:

FYI, we don't drop any existing code on already released versions to avoid any issue when applying patches on projects, however we should drop it in the upcoming 1.7 version (master branch).

Are you interested to drop these parameters and services through a pull request? I'll be happy to help you by reviewing and merging this PR.

If you're interested, I'll need that you read and sign our contributor agreement to merge the pull request https://www.akeneo.com/contributor-license-agreement/

Thank you!

**Comment by nidup** [comment]
Fixed! thank you @a2xchip !

**Comment by aistis-** [comment]
Hey guys, what is the new replacement for `Pim\Bundle\EnrichBundle\Form\Type\ImageType` ? Is there any other FormType which could be used for an image?

**Comment by a2xchip** [comment]
@aistis- ImageType is not used any more, and all symfony forms are going to be deprecated. attribute fields functionality is based on js/rest/updaters/savers/removers... You can check docs about it: https://docs.akeneo.com/1.6/cookbook/ui_customization/create_a_new_field_type.html#create-the-form-field there are architecture explanations
