### ISSUE TITLE
Associations disappearing during import with compare values set to no (MongoDB only)

### ISSUE THREAD

**Issue by janssensjelle** [akeneo/pim-community-dev#5061]
**I'm reporting a Bug**

Version: 1.5.8 and 1.5.9

When importing a CSV file, and not providing any associations in the CSV file, associations disappear when you set the setting "Compare values" to no. 

Example 

sku;name
CLR1667;"Test product"

This would make all associations disappear from product CLR1667.

**Comment by LaureBro** [comment]
Hello @janssensjelle, 

This issue will be fixed in the next 1.5 patch. We will keep you updated.
It's fixed in 1.6.7.

Thanks again for raising this!

Laure
