### ISSUE TITLE
Problem with generating javascript files, some files are missing

### ISSUE THREAD

**Issue by akazik** [akeneo/pim-community-dev#5072]
Steps to reproduce:

1. get akeneo from
   - clone https://github.com/akeneo/pim-community-dev.git
   - download https://github.com/akeneo/pim-community-standard/releases/tag/v1.6.0
   - download 1.6.2 standard archive file: https://www.akeneo.com/download/
2. composer install (not required with the 1.6.2 standard archive)
3. app/console oro:requirejs:build

Output:
```
  [RuntimeException]                                                                                                                                   
  Tracing dependencies for: .../pim-community-dev-master/web/js/oro.min.js                                                                    
  Error: Error: ENOENT: no such file or directory, open '.../pim-community-dev-master/web/bundles/pimenrich/js/product/form/back-to-grid.js'  
      at Error (native)                                                                                                                                

```

**Comment by fabienlem** [comment]
Hi @akazik !

Thank you for raising this issue. This oro command isn't supported by the PIM so I strongly recommend to not use it.

The assets deployment, including javascript files, is performed by the following command : 
php app/console pim:install --env=prod

You can find further information about the PIM installation on our documentation : 
https://docs.akeneo.com/latest/developer_guide/installation/installation_ee_archive.html

Kind regards

**Comment by akazik** [comment]
We've written some Bundles with added assets and js-files.
After updating from 1.5 to 1.6 which script do I call instead of oro:requirejs:build to create a new require-js file with all files (including those we wrote)?

**Comment by juliensnz** [comment]
Hello @akazik,

As @fabienlem said, this command is not supported and does not work at all since 1.3.

You don't need this command to have your files available in require on in we/bundles.

All you have to do is run this list of commands once the pim is installed:

```bash
rm ./web/js/oro.min.js
rm -rf ./app/cache/*
app/console pim:install:asset --env=prod
app/console assets:install --symlink web
```

Regards,

Julien

**Comment by fabienlem** [comment]
Hello @akazik,

I'm closing this issue, feel free to reopen it if you need further information!

Regards
