### ISSUE TITLE
[v1.6.3] Price - splitPrices logic incompatible with (float) parsing

### ISSUE THREAD

**Issue by eheuje** [akeneo/pim-community-dev#5081]
During the standard product import, if there is a price attribute, the PriceConverter use the following **splitPrices** function of **Pim\Component\Connector\ArrayConverter\FlatToStandard\ProductFieldSplitter**

``` php
    public function splitPrices($value)
    {
        $prices = [];
        if ('' !== $value) {
            preg_match_all('/
                (?P<prices>
                    (-?[a-z0-9]+)  # int or blank (if there is no price defined)
                    (?:[^0-9]\d+)? # decimal separator and decimal
                    [a-z\s]+       # currency
                )/ix', $value, $matches);

            if (empty($matches['prices'])) {
                if (!is_array($value)) {
                    return [$value];
                }

                return $value;
            }

            $prices = $matches['prices'];
            array_walk($prices, function (&$price) {
                $price = trim($price);
            });
        }

        return $prices;
    }
```

A price imported as a string is casted as float. If I have the string '.82000000', PHP caste a string as a float like 0.82. 

``` php
$price = '.8200000000';
$price = (float) $price;
echo $price;
// print 0.82
```

However, if I have a string representing a price like ".82000000 EUR" (which is like 0.82), the preg_match_all call return 8200000 EUR.

**Comment by nidup** [comment]
Hi @eheuje !

Thank you for raising this issue, I reproduced it on our demo.

Are you interested to contribute a fix through a pull request on the 1.6 branch? I'll be happy to help you by reviewing and merging this PR.

If you're interested, I'll need that you read and sign our contributor agreement to merge the pull request https://www.akeneo.com/contributor-license-agreement/

Thank you!

**Comment by eheuje** [comment]
I have signed your contributor agreement.
Pull request is coming.

Thank you.

**Comment by nidup** [comment]
Hi @eheuje 

Great! :tada:

Don't hesitate to ping me on the PR, I would help by reviewing / merging it!

Didn't checked too much but I guess the issue may comes from the "+" of "(-?[a-z0-9]+)" which imply to have at least one char before the seprator.

**Comment by eheuje** [comment]
> Didn't checked too much but I guess the issue may comes from the "+" of "(-?[a-z0-9]+)" which imply to have at least one char before the separator.

Yes, it is. 👍

**Comment by fabienlem** [comment]
Hello @eheuje,

Do you need any assistance to fix this issue? If so don't hesitate to ping me :)

Thank you!

**Comment by eheuje** [comment]
Hi @fabienlem,

No problem. It's already fixed properly on my projects.
I just need a extended day with more than 24 hours, more coffee and no needs to sleep. :stuck_out_tongue_winking_eye:

I try to pull request it before the end of week (an the few others fix too).
Cheers.

**Comment by fabienlem** [comment]
Thank you for your quick feedback. I fully understand! Let us know if you find the recipe of extending days, that could be very useful!

It will be great if you could submit your contributions by the end of the week, but no worries! And if so I will arrange one Ziggy to be sent over :)
