### ISSUE TITLE
Grid filters UI (quick-fix)

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#5103]
**I'm reporting a Bug**

For version = 1.5

UI glitch. Behat's update. When you open grid filter, then another, then another previously clicked grid filters options boxes are not closed. Picture attached. Chrome. 

![image](https://cloud.githubusercontent.com/assets/6627334/19317900/38aa93e8-90af-11e6-818d-b7ee180bf3aa.png)

**Comment by fabienlem** [comment]
Hello @a2xchip,

I well reproduced this on our environments, and even on the latest versions of the PIM. Are you interested to contribute a patch for this on the **master** branch?

By the way, thank you a lot for your other pull requests :+1: 

Regards

**Comment by a2xchip** [comment]
I will work in this part of code base soon. @fabienlem

**Comment by fabienlem** [comment]
Sounds great! Don't hesitate to ping me. Thank you again.

**Comment by a2xchip** [comment]
:/ forgot about this issue

**Comment by Doodoune** [comment]
Hi!
Did you solve your issue?
Regards,

**Comment by jmleroux** [comment]
Closed after long inactivity
