### ISSUE TITLE
**/navigation.yml/oro_menu_config/items/*/extras/position missing

### ISSUE THREAD

**Issue by danielsan80** [akeneo/pim-community-dev#5105]
**I'm reporting a Bug**
As a Dev
When I extend Akeneo
When I add an item to the menu
Then I'd like to put it in any position of the menu.
But not all items have the extras/position property, so it's not possible.

The attached navigation.yml is modified to fix this problem but is only one of all navigation.yml files in Akeneo.

Thanks, Danilo.

[akeneo-pim-system-info_2016-10-13_12-25.txt](https://github.com/akeneo/pim-community-dev/files/526836/akeneo-pim-system-info_2016-10-13_12-25.txt)

[src/Pim/Bundle/EnrichBundle/Resources/config/navigation.yml](https://github.com/akeneo/pim-community-dev/files/526838/navigation.yml.txt)

**Comment by a2xchip** [comment]
@danielsan80 Any position - is abstraction. What exactly is wrong in your case. If you want your menu item to be first give it posion 5 or 1. If you want it to be second: 11-19, third: 21-29. It is all.

**Comment by danielsan80** [comment]
@a2xchip Ok, I'll be less abstact to better explain the problem:

> ...
> Then I'd like to put it in the **Settings** submenu between **Attribute Groups** and **Attribute**
> So I give it position 11-19
> But the subitems of Settings has not a position set ( this is the current [navigation.yml](https://github.com/akeneo/pim-community-dev/blob/1.6/src/Pim/Bundle/EnrichBundle/Resources/config/navigation.yml))
> So it doesn't work
> And my custom item will be placed in the first position.
> 

[this](https://github.com/akeneo/pim-community-dev/files/526838/navigation.yml.txt) was the suggested file to fix this problem.

**Comment by a2xchip** [comment]
@danielsan80 Thx for your reply.

If we are talking about sub items of menu item: these are ordered alphabetically (asc). If you ask to order them in ```yml``` config - that would be **feature request** not **bug report**. And will depend mostly on core team and project owner i think. However i'm sure independent on their decision you can override this in your own project as you need.

P.S
You may include yml source this way  \`\`\`yml \`\`\`

```yml
parameter:
    item: ~

```

**Comment by danielsan80** [comment]
@a2xchip 
Yes, I'm talking about sub items of menu item.

> these are ordered alphabetically (asc)
>

It should be good but this is not true (neither in franch language). I'm not sure there is this feature in Oro Menu Component at all (the sorting should change on the localized item labels... a mess) .

The subitems of **Settings** have not the position properties and take the registering order:

```yml
pim_configuration_tab:
    children:
        pim_enrich_attributegroup: ~
        pim_enrich_attribute: ~
        pim_enrich_family: ~
        pim_enrich_associationtype: ~
        pim_enrich_grouptype: ~
        pim_enrich_currency: ~
        pim_enrich_locale: ~
        pim_enrich_channel: ~
```

The subitems of **Enrich** have the position properties and are reordered on them.

So I think it's not a **feature request**, maybe is not a **bug**, only a **little imprecision**.
Anyway it is better to fix it at the source, isn't it?

best reguards,

Danilo

**Comment by danielsan80** [comment]
Ok @fabienlem,

I'll do with a pull request linking it to this issue. :)

Thanks guys.

Regards

**Comment by fabienlem** [comment]
@danielsan80,

Great! Feel free to ping me if you need help with your pull request.

Kind regards

**Comment by Doodoune** [comment]
Hi!

I close this issue. Feel free to re-open it if you're interested to contribute this improvement.

Regards,
