### ISSUE TITLE
Remove debug js code in 1.5 [Quick fix]

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#5119]
**I'm reporting a Bug**

https://github.com/akeneo/pim-community-dev/blob/1.5/src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js#L203

JS contains logging line. That writes both in dev and prod.

**Comment by nidup** [comment]
The improvement will by released in upcoming v1.5.11 :tada:

**Comment by a2xchip** [comment]
@nidup not so big approvement :) but anyway!
