### ISSUE TITLE
Optionally use an arbitrary precision library in the AkeneoMeasuresBundle

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#5137]
Currently, the AkeneoMeasureBundle uses PHP's native operators. PHP at its internals uses `long int` or `double` native types for storing numbers, depending on the value. When the number is greater than the `INT_MAX` or smaller than `INT_MIN`, it is automatically casted to a `double`.

OroCommerce is using `brick/math` for high-precision taxes calculations.

Would it be reasonable to make the AkeneoMeasuresBundle use this library, either by migrating the `Akeneo\Bundle\MeasureBundle\Convert\MeasureConverter`, or by making an interface and letting live 2 implementations altogether ?

**Comment by fabienlem** [comment]
Hi @gplanchat,

Thank you for this improvement suggestion. The precision issue when storing numeric values concerns   the whole PIM technical scope. We are pondering these questions but for now, we don't plan to use brick/math.

Kind regards

**Comment by gplanchat** [comment]
In this case, why not create a `Akeneo\Bundle\MeasureBundle\Convert\MeasureConverterInterface` and let the integrators choose the implementation they desire ?

**Comment by nidup** [comment]
Hi @gplanchat 

This is a very interesting approach, the MeasureConverter class is referenced less than 10 times in the PIM itself, so introduces an interface and rely on it should be pretty easy.

We could keep the default implem in the PIM that could be replaced in project.

Would you be interested by this contribution? (I know that you already have a lot in your plate ;) )

**Comment by gplanchat** [comment]
After some thoughts, the `DECIMAL(24,12)` fields in the `pim_catalog_metric` may also have to be changed on project-specific implementations.

**Comment by nidup** [comment]
Regarding decimal fields, that's why @fabienlem talked about a global topic which has large impacts regarding rounding values / storage precision, etc. Precision of the measure bundle library is a part of this big topic :)

**Comment by gplanchat** [comment]
It seems to be solved in 2.0, isn't it ?

**Comment by Doodoune** [comment]
I close this issue, it seems solved in 2.3.
If you still have this error, feel free to reopen it.

Regards,
