### ISSUE TITLE
[v1.5] Custom view overwrite filters

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#5158]
**I'm reporting a Bug**

The bug is in Akeneo 1.5.9 and 1.5.10:

* Go to the Product grid and select a custom view (not the default view)
* Change some filters or select a different category
* When you refresh the page (or click on a product and go back...) your filters/categories are overwritten again from the custom view. Also the URL changes. 

With V. 1.5.8 or 1.6 this works as expected.

The bug is rather annoying for our users, as they often click on a product, go back and then expect to have the same filters and categories again.

The cause of the problem is the commit 329ddde. When I deactivate the line `activateView(activeViewId);` the filter/categories works again with a custom view.

**Comment by fabienlem** [comment]
Hello @Hocdoc,

I well reproduced this on our environments. The point is the commit you mentioned fixes a major bug that prevents from loading data properly in the product grid in some cases. So the fix cannot only remove the "activateView" method call.

I understand it can be very annoying for users. As a workaround, it's possible to save others custom views after editing the filters.

Are you interested to investigate on this issue? If yes, we will help you to review your fix :)

Regards

**Comment by Hocdoc** [comment]
Thanks for your explanations!

As our users don't complain about the grid-loading-bug I still just comment the line out in our code base, so our users are happy again.

We plan to update to Akeneo 1.6 (which doesn't contain this bug) in some months and have few development resources to investigate more into this issue, so a fix isn't important for us.
