### ISSUE TITLE
GUI: Upload file Cancel button

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#5165]
**I'm reporting a Bug**

Akeneo 1.5 + 1.6, a minor GUI bug:

The Cancel-Button in the file dialog removes an old updated file. I would expect that the old file stays untouched (until I hit the trash icon).

Steps to reproduce:
- Choose an import profile
- Upload a file
- Click again on the gray file upload field but choose then the `Cancel` button in the file dialog => The old uploaded file will get removed.

**Comment by fabienlem** [comment]
Hello again @Hocdoc!

I see what you mean. When you select a file via the upload field, the file is not uploaded yet, but just ready to be uploaded (clicking "Upload and import now" triggers the upload). What you describe is the native behavior of the HTML5 file input. You can reproduce this behavior here: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_accept

The PIM upload field is based on the native HTML5 file input, so it's not possible to change this behavior.

Regards

**Comment by Hocdoc** [comment]
Hm the HTML5 demo works as expected for me, the Cancel-button of the file dialog doesn't remove the previous selected file (Chrome with MacOS).
As far as I can see the PIM also doesn't use the HTML5 file input.

I think the problem is in the first `else` part in https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/UIBundle/Resources/public/js/pim-fileinput.js which unnecessary removes the old file.

**Comment by fabienlem** [comment]
I reproduced the issue like that:
- Click on drop zone area
- Select a file
- Click "open" button on the file dialog
- Click again on the drop zone area
- Click "cancel" button on the file dialog
Is that ok?

I can confirm that the <input type="file"> element is hidden but used for file selection on the import profile screen. The else block ensure the displayed selected file is consistent with the input field's content that is automatically cleared when user clicks on file dialog cancel button. (Reproduced on Chrome with both ubuntu and MacOS).

Regards

**Comment by Hocdoc** [comment]
Yes, the steps to reproduce my problem are correct.

**Comment by LaureBro** [comment]
Hello @Hocdoc, I can reproduce this issue on 1.6 but this behaviour is not anymore reproducible on the 1.7. Do you agree to close this issue?

Kind regards,
Laure

**Comment by Hocdoc** [comment]
This is fixed in 1.7 as you cannot update an uploaded file without removing it.

Thanks for the fix.
