### ISSUE TITLE
[1.6.3] NumberFormatValidator and NumberLocalizer won't allow only decimals

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#5169]
Not sure if bug or just an enhancement request

If you try to pass e.g. `.16` as a number into a numeric field during import the regex in both `Akeneo\Component\Localization\Validator\Constraints\NumberFormatValidator::validate` and `Akeneo\Component\Localization\Localizer\NumberLocalizer::getMatchesNumber` won't allow this.

The current regex `\d+((?P<decimal>\D+)\d+)?` requires that there is an integer before the decimal separator i.e. `0.16` will do but not `.16`.

If the regex is changed to `\d*((?P<decimal>\D+)\d+)?` then both `0.16` and `.16` will be accepted.

Similar issue as in #5081

**Comment by fabienlem** [comment]
Hello @mathewrapid,

I would like to know more about your use case. Do the "without zeros formatted values" come from a specific software of your information system? Do you have a big amount of data formatted like this or just some values? 

Thank you in advance for your feedback!

Regards

**Comment by mathewrapid** [comment]
Hi @fabienlem,

> Do the "without zeros formatted values" come from a specific software of your information system?

Yes, when customers ERP exports their data (utf-8 csv) it strips out leading zeros from numeric fields. That means that instead of giving `0.43` as a value to us (Akeneo import) we get `.43`.

> Do you have a big amount of data formatted like this or just some values?

All numeric values (x) which fall between `0 < x < 1`

**Comment by fabienlem** [comment]
Hi @mathewrapid,

I checked with our product team. It's not a behavior we plan to change. Unfortunately, we cannot check and reformat all data coming into the PIM. 

You can edit it on your project or create a custom connector to implements some data reformatting rules.

Best regards,
Fabien

**Comment by mathewrapid** [comment]
Hi @fabienlem,

interesting choice from your product team, as according to #5081 a string `.82000000` can be used as an input parameter, PHP casting it to a float `0.82`.

Why would number field formatting not allow this?

**Comment by fabienlem** [comment]
Hello @mathewrapid,

Sorry for my late reply. You pointed rightly that the expected number format aren't harmonized all over the PIM. We are aware of that, but the harmonization work isn't prioritized for now. Be sure I took the time to test many cases with imports, exports and on the product sheet. The results aren't homogenized and we need to clearly determine the accepted format before changing the PIM behavior. I will keep you updated.

Regards,
Fabien

**Comment by mathewrapid** [comment]
Hi @fabienlem.

No worries and thanks for your reply.

All in all this is not an issue as the required classes/services are easily overridden. This is more of a small nuisance and a fyi for others that might encounter similar _obstacle_.
