### ISSUE TITLE
Fatal error: Allowed memory size of bytes exhausted

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [akeneo/pim-community-dev#5170]
Hi,

I'm getting the following error when I try to install.

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in ../pim-community-standard/app/bootstrap.php.cache on line 2727`

Could you please look into this issue?

Thanks,
Unnikrishnan B.

**Comment by a2xchip** [comment]
Hello @UnnikrishnanBhargavakurup 

Take a look on this page: https://docs.akeneo.com/latest/developer_guide/installation/system_requirements/system_requirements.html

and this one: https://github.com/composer/composer/issues/1898

If it is VPS try to add swap before running script: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by fabienlem** [comment]
Hello @UnnikrishnanBhargavakurup,

Did you solved your memory issue? 

Regards

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi fabienlem,

Yes, now that issue got resolved but got another issue on clearing the cache

` [PDOException]                                                                                
  SQLSTATE[HY000] [1045] Access denied for user 'akeneo_pim'@'localhost' (using password: YES)`

**Comment by UnnikrishnanBhargavakurup** [comment]
Could you please look into these issues

`Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_4_20150512133600_pim_session" was found in both "$baseDir . '/upgrades/1.3-1.4/Version_1_4_20150512133600_pim_session.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.3-1.4/Version_1_4_20150512133600_pim_session.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_4_20150602173830_discr_category_table" was found in both "$baseDir . '/upgrades/1.3-1.4/Version_1_4_20150602173830_discr_category_table.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.3-1.4/Version_1_4_20150602173830_discr_category_table.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_4_20150819143301_user" was found in both "$baseDir . '/upgrades/1.3-1.4/Version_1_4_20150819143301_user.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.3-1.4/Version_1_4_20150819143301_user.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_4_20150922153314_drop_oro_tables" was found in both "$baseDir . '/upgrades/1.3-1.4/Version_1_4_20150922153314_drop_oro_tables.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.3-1.4/Version_1_4_20150922153314_drop_oro_tables.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_4_20150922153314_misc" was found in both "$baseDir . '/upgrades/1.3-1.4/Version_1_4_20150922153314_misc.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.3-1.4/Version_1_4_20150922153314_misc.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_4_20150922153325_versioning" was found in both "$baseDir . '/upgrades/1.3-1.4/Version_1_4_20150922153325_versioning.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.3-1.4/Version_1_4_20150922153325_versioning.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\schema\Version_1_5_20151005132540_oro_user" was found in both "$baseDir . '/upgrades/1.4-1.5/Version_1_5_20151005132540_oro_user.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.4-1.5/Version_1_5_20151005132540_oro_user.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\schema\Version_1_5_20151006132723_notifications" was found in both "$baseDir . '/upgrades/1.4-1.5/Version_1_5_20151006132723_notifications.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.4-1.5/Version_1_5_20151006132723_notifications.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\schema\Version_1_5_20151102131708_default_view" was found in both "$baseDir . '/upgrades/1.4-1.5/Version_1_5_20151102131708_default_view.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.4-1.5/Version_1_5_20151102131708_default_view.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\schema\Version_1_5_20151121110000_index_logged_at" was found in both "$baseDir . '/upgrades/1.4-1.5/Version_1_5_20151121110000_index_logged_at.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.4-1.5/Version_1_5_20151121110000_index_logged_at.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\schema\Version_1_5_20151202101336_metric_precision" was found in both "$baseDir . '/upgrades/1.4-1.5/Version_1_5_20151202101336_metric_precision.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/1.4-1.5/Version_1_5_20151202101336_metric_precision.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\schema\Version_1_5_20160405165700_versioning" was found in both "$baseDir . '/upgrades/schema/Version_1_5_20160405165700_versioning.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_5_20160405165700_versioning.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_201603100000_batch_jobs" was found in both "$baseDir . '/upgrades/schema/Version_1_6_201603100000_batch_jobs.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_201603100000_batch_jobs.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160312201959_batch_mapping" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160312201959_batch_mapping.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160312201959_batch_mapping.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160403110147_remove_job_configuration" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160403110147_remove_job_configuration.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160403110147_remove_job_configuration.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160526173325_remove_warning_name" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160526173325_remove_warning_name.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160526173325_remove_warning_name.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160530174030_remove_channel_color" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160530174030_remove_channel_color.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160530174030_remove_channel_color.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160616102218_mass_edit" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160616102218_mass_edit.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160616102218_mass_edit.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160627194118_jobinstance_alias_to_jobname" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160627194118_jobinstance_alias_to_jobname.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160627194118_jobinstance_alias_to_jobname.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160714195239_jobinstance_rawConfiguration_to_raw_parameters" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160714195239_jobinstance_rawConfiguration_to_raw_parameters.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160714195239_jobinstance_rawConfiguration_to_raw_parameters.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160722155535_quick_export" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160722155535_quick_export.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160722155535_quick_export.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160726103445_update_product_export_parameters" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160726103445_update_product_export_parameters.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160726103445_update_product_export_parameters.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\Schema\Version_1_6_20160804181154_versioning_index" was found in both "$baseDir . '/upgrades/schema/Version_1_6_20160804181154_versioning_index.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/schema/Version_1_6_20160804181154_versioning_index.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\SchemaHelper" was found in both "$baseDir . '/upgrades/SchemaHelper.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/SchemaHelper.php", the first will be used.
Warning: Ambiguous class resolution, "Pim\Upgrade\UpgradeHelper" was found in both "$baseDir . '/upgrades/UpgradeHelper.php" and "/Library/WebServer/Documents/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/upgrades/UpgradeHelper.php", the first will be used.`

Thanks,

**Comment by a2xchip** [comment]
@UnnikrishnanBhargavakurup look at ```app/config/parameters.yml``` check db name and password

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi a2xchip,

I am following this [Installing Akeneo PIM Community Edition (CE) with the Archive](https://docs.akeneo.com/latest/developer_guide/installation/installation_ce_archive.html) is it the right document I should follow?

**Comment by a2xchip** [comment]
@UnnikrishnanBhargavakurup Yes! But there is no straight roads in development... You might miss some settings during installation. Also there was composer issue causing ```Ambiguous class resolution``` error. May be you will have to ```composer self-update``` first and then ```rm -Rf vendor/* && composer update``` to fix it, if you composer is not the latest one.

**Comment by UnnikrishnanBhargavakurup** [comment]
@a2xchip - Thanks for the help! everything working fine, please close this ticket.

Thanks,
Unnikrishnan B.

**Comment by a2xchip** [comment]
@UnnikrishnanBhargavakurup You can close it yourself, or @fabienlem can do it.

**Comment by UnnikrishnanBhargavakurup** [comment]
Can we make this installation document helpful for non developers also? How can I help in this?

**Comment by fabienlem** [comment]
@UnnikrishnanBhargavakurup,

It's great to know that everything works as expected! You can suggest documentation improvements directly by clicking on the "edit on github" link on the top right hand corner. Our team will be happy to review your changes!

Feel free to reopen this issue if you need further information.

Have a nice day!
