### ISSUE TITLE
1.6 Export filter by simple select

### ISSUE THREAD

**Issue by janssensjelle** [akeneo/pim-community-dev#5193]
**I'm reporting a Bug**

Local Akeneo version: 1.6.4
Demo Akeneo version: 1.6.4

When adding a simple select attribute to filter products in the product export, the export completes instantly. 

To reproduce in demo:

1. Open a product, select a value in any simple select box.
2. Go to export product
3. Select this attribute and value as a filter
4. Make sure that the other filters apply so that your product should be exported
5. Click export

Result: export finishes instantly
Expected result: export to finish with at least 1 product in it (your product)

Can reproduce this on both ORM and MongoDB. If you need more info, I'm on slack :)

**Comment by a2xchip** [comment]
Pretty strange @janssensjelle

**Comment by janssensjelle** [comment]
Yeah. It works fine for category filter or entities filter. But not simple select 😓

**Comment by fabienlem** [comment]
Hello @janssenjelle,

I did successful exports on our demo with a digital camera product and the "sensor type" simple select attribute. It's also work when I create a simple select attribute and follow your steps. 

Can you provide me further information?
- The product and the simple select attribute you used.
- The complete product export job configuration.

Thank you in advance for our feedback!

Regards

**Comment by janssensjelle** [comment]
@fabienlem this does seem to be due to the default completeness filter setting. I completely overlooked this in the demo. 

I will test this on our production (MongoDB) and get back :)

**Comment by a2xchip** [comment]
@fabienlem used colors in the way @janssensjelle described and did not get results, even headers. May be i'm doing smth wrong as i have no experience working with 1.6 connectors but result is so

**Comment by janssensjelle** [comment]
@a2xchip it is probably the completeness setting in this case. It is default set to must be complete

**Comment by fabienlem** [comment]
Hi @a2xchip,

I have tried with main color attribute with both MySQL and MongoDB and everything worked fine. As @janssensjelle said, I think it's linked to the completeness setting.

Regards

**Comment by a2xchip** [comment]
@fabienlem Means devs doesn't know how to use PIM's new exporter :smiley:

**Comment by janssensjelle** [comment]
I'm sorry @a2xchip , but that's like a sneaky default setting they put in there :D

**Comment by a2xchip** [comment]
I think if we would record protected screencast and present it to @fabienlem it could make things much clearer. :eyes: @janssensjelle

**Comment by janssensjelle** [comment]
It's a setting that was causing this, it is not really a bug. However changing this setting on my production does not solve it. It solves it on the demo environment. So I am looking what is wrong on my end, so I can comment it here :)

**Comment by janssensjelle** [comment]
Right, so I've got an update, and was able to reproduce it on the demo

Steps

1. Create a new product
2. Do not assign this product to any category
3. Create/edit an export profile
4. Make sure the settings will match your product. Even defining your sku in the export list won't make your product export

I was able to reproduce this on demo

**Comment by fabienlem** [comment]
Hello @janssensjelle!

The products have to be categorized to be exported. This prerequisite also exists in 1.5 version and our product team confirmed me that is a normal behavior.

To sum up, these are the conditions to export products:

PIM 1.5 | PIM 1.6
----|----
complete | match with export builder "Completeness" filter
enabled | match with export builder "Status" filter
categorized | match with export builder "Category" filter, "all products" option only works for categorized ones


Regards,
Fabien

**Comment by janssensjelle** [comment]
@fabienlem okay, thank you. Could the label "All products" be changed to "All categorised products", so this will be less confusing?

**Comment by fabienlem** [comment]
@janssensjelle you're right, a submitted a improvement suggestion to our product team.

Thank you for your feedback!  :+1:

**Comment by janssensjelle** [comment]
I could submit a PR if you'd like :-)

**Comment by fabienlem** [comment]
Thank you @janssensjelle! As wording could be a sensitive topic, I think it's better to wait for a product team feedback. I will let you know ;)

**Comment by jmleroux** [comment]
Hello guys,

1.7 is not supported anymore and this issue is almost 4 years old now. That's why i'm closing it, but do not hesitate to reopen it if needed.

Regards,
JM
