### ISSUE TITLE
Lock wait timeout during csv import

### ISSUE THREAD

**Issue by AFBElektronik** [akeneo/pim-community-dev#5195]
Hi guys, am currently doing a big csv import > 400.000 lines
After 1 hour we get this massage

QLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
We set innodb_lock_wait_timeout from 50 to 120.. but that does not help

or 

PRODUKT IMPORT  An exception occurred while executing 'INSERT INTO pim_catalog_product_value (value_string, value_integer, value_decimal, value_boolean, value_text, value_date, value_datetime, locale_code, scope_code, metric_id, attribute_id, option_id, entity_id, media_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["4018242239405", null, null, null, null, null, null, null, null, null, 1, null, 202036, null]: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

PRODUKT-EXPORT ALS CSV-DATEI  The EntityManager is closed.

Anyone have any ideas on how we can resolve this

**Comment by fabienlem** [comment]
Hello @AFBElektronik,

Can you ensure you don't have a cronjob for completeness calculation that could be launched concurrently to your import?

As said in slack user group, it seems to be the most probable cause. We had similar reports from other PIM users.

Regards

**Comment by AFBElektronik** [comment]
@fabienlem yes you are right. There was a job. Now it works. thanks

**Comment by fabienlem** [comment]
Good to know!
Thank you for your feedbacl :+1:

Regards

**Comment by hostep** [comment]
@fabienlem: we also just ran into this very same problem.

I think this bug report should be reopened until it is fixed, right?
