### ISSUE TITLE
PimEnterprise\Bundle\WorkflowBundle\Doctrine\Common\Saver\DelegatingProductSaver doesn't dispatch events

### ISSUE THREAD

**Issue by iulyanp** [akeneo/pim-community-dev#5208]
**I'm reporting a Bug**
Hello @nidup,

While testing the mass edit functionality I noticed that on the EE bundle in the DelegatingProductSaver there are no events dispatched. Any reason for that? 

Best regards

**Comment by nidup** [comment]
Hi @iulyanp !

Sorry for the late answer, I was on holidays :sunglasses: 

StorageEvents::PRE_SAVE and StorageEvents::POST_SAVE are well dispatched in the DelegatingProductSaver for both unitary saving of product and product draft.

You're right StorageEvents::PRE_SAVE_ALL and StorageEvents::POST_SAVE_ALL are not dispatched, when we save a bulk of products we don't yet know if each product is a working copy or a draft (depending on user's permissions). I think we need to first iterate on objects and check permissions to dispatch pre_save_all for both bulk of drafts and bulk of products before to call saveProduct and saveProductDraft in a second iteration.

Would you like contribute a patch through a gist, I will be happy to apply it on 1.6? (sorry for now the contribution on enterprise edition is not easy but we'll try to improve this point).

Have a good day!

**Comment by Doodoune** [comment]
Hi @iulyanp,
Did you found a solution? Can we close this issue?
Regards,

**Comment by iulyanp** [comment]
Hi @Doodoune,

I think so, this could be closed.

Thank you,

**Comment by Doodoune** [comment]
Thanks for your answer :)
Have a nice day,
