### ISSUE TITLE
SimpleJobLauncher uses kernel.root_dir parameter for logs instead of kernel.logs_dir

### ISSUE THREAD

**Issue by rolebi** [akeneo/pim-community-dev#5212]
Hello,

When running commands via [SimpleJobLauncher](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php#L77) the logs are created in the kernel root directory, expecting a `logs` directory to be present instead of using the `kernel.logs_dir` parameter. This cause problem on installation where the logs don't reside in the application directory. To bypass this you'll have to overwrite a whole method definition slowing down the upgrading process.

What about using the right parameter (`kernel.logs_dir`) ? Or for backward compatibility, add a protected `getLogDir` method that can be overwritten when needed. The change is trivial and PR will follow if this seems right.

**Comment by fabienlem** [comment]
Hello @rolebi,

It could be a good improvement! Don't hesitate to submit a PR, we will be happy to help you by reviewing it. Here is our contribution guide: https://docs.akeneo.com/master/contributing/contribution_guide.html

You are right it's important to ensure backward compatibility as Akeneo PIM can be extended by users. So the second solution seems to be the good one.

You can ping me if you need some assistance. Thank you!

Regards,
Fabien

**Comment by mickaelandrieu** [comment]
Hello @rolebi, this has been fixed by @xElysioN => https://github.com/akeneo/pim-community-dev/commit/622c6833c6f822e54d17be63200086f3263032b7

Thanks for the report.
