### ISSUE TITLE
Fixtures: families.yml

### ISSUE THREAD

**Issue by tkn98** [akeneo/pim-community-dev#5213]
**I'm reporting a potential Flaw**

I wanted to import/load fixtures for which I choosed the YAML format.

I created the file `families.yml`.

That file was not imported/loaded despite the importer/fixture-loader wrote "DONE." in green letters.

Example:

    $ app/console pim:installer:load-fixtures path/to/families.yml

First of all: Obviously there is no importer for the fixture (families.yml) specified.

I have two issues here with it:

- The program does not communicate so. It would be easy to say that for file X.Y no importer (or however that is called) is not available and exit with a non-zero exit code.
- The missing importer should be considered a flaw.

References:

- #1878
- NETZ98#29434

(I'm new to the software, so please bear with me if I don't use the right terms; I could easily convert my YAML serialized structure into a CSV file in a generic fashion, so right now I can work-around the missing importer issue, but better output on fixutre loading would have saved me many question marks)

---

~~~
[Edition]
CE

[Version]
1.5.9

[Storage]
doctrine/orm

[Environment]
prod

[Install time]


[Registered bundles]
APY\JsFormValidationBundle\APYJsFormValidationBundle
Akeneo\Bundle\BatchBundle\AkeneoBatchBundle
Akeneo\Bundle\BufferBundle\AkeneoBufferBundle
Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle
Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle
Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle
Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle
Doctrine\Bundle\DoctrineBundle\DoctrineBundle
Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle
Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle
Doctrine\Bundle\MongoDBBundle\DoctrineMongoDBBundle
Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle
FOS\JsRoutingBundle\FOSJsRoutingBundle
FOS\RestBundle\FOSRestBundle
JMS\SerializerBundle\JMSSerializerBundle
Knp\Bundle\MenuBundle\KnpMenuBundle
Liip\ImagineBundle\LiipImagineBundle
N98\Pimgento\RestCsvExportBundle\N98PimgentoRestCsvExportBundle
N98\Tx24\AttributesBundle\N98Tx24AttributesBundle
Nelmio\ApiDocBundle\NelmioApiDocBundle
Oneup\FlysystemBundle\OneupFlysystemBundle
Oro\Bundle\AsseticBundle\OroAsseticBundle
Oro\Bundle\ConfigBundle\OroConfigBundle
Oro\Bundle\DataGridBundle\OroDataGridBundle
Oro\Bundle\FilterBundle\OroFilterBundle
Oro\Bundle\FormBundle\OroFormBundle
Oro\Bundle\NavigationBundle\OroNavigationBundle
Oro\Bundle\RequireJSBundle\OroRequireJSBundle
Oro\Bundle\SecurityBundle\OroSecurityBundle
Oro\Bundle\TranslationBundle\OroTranslationBundle
Oro\Bundle\UIBundle\OroUIBundle
Oro\Bundle\UserBundle\OroUserBundle
Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle
Pim\Bundle\BaseConnectorBundle\PimBaseConnectorBundle
Pim\Bundle\CatalogBundle\PimCatalogBundle
Pim\Bundle\CommentBundle\PimCommentBundle
Pim\Bundle\ConnectorBundle\PimConnectorBundle
Pim\Bundle\DashboardBundle\PimDashboardBundle
Pim\Bundle\DataGridBundle\PimDataGridBundle
Pim\Bundle\EnhancedConnectorBundle\PimEnhancedConnectorBundle
Pim\Bundle\EnrichBundle\PimEnrichBundle
Pim\Bundle\FilterBundle\PimFilterBundle
Pim\Bundle\ImportExportBundle\PimImportExportBundle
Pim\Bundle\InstallerBundle\PimInstallerBundle
Pim\Bundle\JsFormValidationBundle\PimJsFormValidationBundle
Pim\Bundle\LocalizationBundle\PimLocalizationBundle
Pim\Bundle\NavigationBundle\PimNavigationBundle
Pim\Bundle\NotificationBundle\PimNotificationBundle
Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle
Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle
Pim\Bundle\TransformBundle\PimTransformBundle
Pim\Bundle\UIBundle\PimUIBundle
Pim\Bundle\UserBundle\PimUserBundle
Pim\Bundle\VersioningBundle\PimVersioningBundle
Pim\Bundle\WebServiceBundle\PimWebServiceBundle
Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
Symfony\Bundle\AsseticBundle\AsseticBundle
Symfony\Bundle\FrameworkBundle\FrameworkBundle
Symfony\Bundle\MonologBundle\MonologBundle
Symfony\Bundle\SecurityBundle\SecurityBundle
Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
Symfony\Bundle\TwigBundle\TwigBundle
~~~

**Comment by fabienlem** [comment]
Hello @tkn98, and welcome to the Akeneo community!

Thank you for reporting this. Indeed our documentation isn't clear enough and doesn't precise which format is expected for which import type. The message provided by the fixtures load command is unclear as well, I reproduced the behavior you report. 

You can use the demo fixtures as example, they can be found here: https://github.com/akeneo/pim-community-dev/tree/1.5/src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev.

We usually offer our PIM users to contribute a fix by pushing a pull request on the master branch. So if you are interested, all you need to know can be found here:

- Enhance the Documentation: https://docs.akeneo.com/master/contributing/documentation.html
- Submit a Patch to the Core: https://docs.akeneo.com/master/contributing/contribution_guide.html

We will be happy to help you by reviewing your changes. Other community users that are interested by this issue can also contribute.

Best regards,
Fabien

**Comment by tkn98** [comment]
Hi and thanks a lot for the prompt and detailed feedback. Next to a PR against master what can I do for a backport in 1.5 as we currently still need to use it and have the problem with?

**Comment by tkn98** [comment]
@fabienlem: I checked out master and it looks like that for the issue I have (and can provide a patch for), this is not so much the issue with master but of benefit for 1.5. 

Would it be OK to file a patch against HEAD of 1.5? I'll just do so in a PR, but please let me know what the correct workflow is.

**Comment by fabienlem** [comment]
Hello @tkn98,

Thank you a lot for your contribution! :+1: 

Except in some cases, we accept contributions only on the master branch. I will discuss with the team and I will let you know if it's better or not to rebase the pull request. We will also review it soon!

Best regards,
Fabien

**Comment by nidup** [comment]
Hi @tkn98 

This improvement has already been done in 1.6, cf this comment https://github.com/akeneo/pim-community-dev/pull/5216#issuecomment-260383944

Have a good day,
