### ISSUE TITLE
Exception when writing invalid item xlsx file after product import

### ISSUE THREAD

**Issue by JulienDotDev** [akeneo/pim-community-dev#5227]
**I'm reporting a Bug**

Local Akeneo 1.6.4

When importing a product using the XLSX product importer, if a line is invalid and that it contains a date, when the invalid item file is written, the Worksheet throw a InvalidArgumentException because Akeneo send the line to write with a date as an array (and an array can't be written in a xlsx cell).

Box\Spout\Writer\XLSX\Internal\Worksheet.php line 156

I know that the invalid item file is written by reading the initial file, i suppose that by reading the initial file, the date is converted to a datetime object and send as an array to the xlsx writter. It shouldn't convert a date into a datetime / array when the aim is to write a invalid file.

Let me know if you can't understand what i'm saying.

Regards,

**Comment by fabienlem** [comment]
Hello @JulienDotDev,

Can you provide me an example of an invalid line you try to import?

Thank you in advance!

Regards,
Fabien

**Comment by mickaelandrieu** [comment]
Hello @JulienDotDev,

if you come back to provide a reproducible test case, I'll re-open the issue.

Thanks for your understanding.
