### ISSUE TITLE
Importing Variant Group attribute(s) fails

### ISSUE THREAD

**Issue by Melleschepers** [akeneo/pim-community-dev#5234]
I'm reporting a Bug

Akeneo version: 1.6.4

When updating an Variant group attribute with the same data that already exists the import fails.

To reproduce in demo:

1. Add an attribute to a variant group (for example with the demo data; add the attribute name to the variant group "akeneo_mug") and give it the name "Mug".
2. Go to Import Profiles and select the job Akeneo CSV Connector ->"csv_variant_group_import" with the Akeneo CSV Connector. Let the switch "Copy variant group values to products" stay on the default "yes".
3. Start the import with the file:
`
code;type;axis;name
`
`
akeneo_mug;VARIANT;main_color,secondary_color;Mugtest
`
You will see that the import is completed and that name of the products are updated to Mugtest.
4. Run the import again with the same file:
`VARIANT GROUP IMPORT IN CSV  A new entity was found through the relationship 'Pim\Component\Catalog\Model\Product#groups' that was not configured to cascade persist operations for entity: [akeneo_mug]. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).`

Result: The import fails.

**Comment by wakqasahmed** [comment]
Looks to me similar to the issue that i faced #5231

**Comment by pierallard** [comment]
@Melleschepers and @wakqasahmed 
I reproduced your issue, and fixed it in this Pull Request: https://github.com/akeneo/pim-community-dev/pull/5261

Can you ping me if the fix does not work for you ?
(Warning: this feature is broken in 1.5 too, so the fix is on the 1.5 version, and will be deployed to 1.6 in the next days)

Regards

**Comment by Melleschepers** [comment]
Hi @pierallard,

Thanks for fixing 👍 
I've only version 1.6 installed. When it's deployed to 1.6 I will test it and let you know my findings.

**Comment by pierallard** [comment]
@Melleschepers The fix is currently going up to 1.6 ;) https://github.com/akeneo/pim-community-dev/pull/5264

**Comment by Melleschepers** [comment]
Hi @pierallard !

Thanks for the update.
I've tested it and it works great! 👍

**Comment by dbijuduval-wiko** [comment]
Hello @pierallard and @wakqasahmed 

I'm using version 1.7 after migration from 1.6 and i still have this bug when trying to Importing Variant Group attribute.

After running the job import i got error:
A new entity was found through the relationship 'Pim\Component\Catalog\Model\Product#groups' that was not configured to cascade persist operations for entity: ..... To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

Best regards
