### ISSUE TITLE
UI refresh bug after saving product associations

### ISSUE THREAD

**Issue by apaananen** [akeneo/pim-community-dev#5263]
**I'm reporting a Bug**

Akeneo Community edition version 1.5.5. Multiple association types configured.

Open up a product for enriching the data. Open associations tab. Select an association type from the left column, but not the first one. Add an association. Save the changes by clicking the "Save" button in the right top corner.

Expected result:
The data is saved. The grid on the right is updated. The left column stays on the selected tab.

Actual outcome:
The data is saved ok, and the grid on the right gets updated ok. But the left column shows that the first association type tab is selected. That is a quite bad UX bug, the user may very well think that the system added the association link(s) also for the first association type.

**Comment by fabienlem** [comment]
Hello @apaananen,

Thank you for reporting this. This behavior doesn't exist anymore on the 1.6 version. You can test it on demo.akeneo.com. (Here is the pull request of this improvement: https://github.com/akeneo/pim-community-dev/pull/4210). 

Best regards,
Fabien

**Comment by fabienlem** [comment]
I'm closing this issue.

Regards,
Fabien
