### ISSUE TITLE
Product grid 

### ISSUE THREAD

**Issue by andrelecomte** [akeneo/pim-community-dev#5283]
**I'm reporting a Bug**
[akeneo-pim-system-info_2016-11-29_21_13.txt](https://github.com/akeneo/pim-community-dev/files/620084/akeneo-pim-system-info_2016-11-29_21_13.txt)

**Expected behavior**
After creating a custom view in the PIM, it should be possible to apply a different selection of columns. 

**Encountered behavior**
Applying a different selection of columns fails when testing on demo.akeneo.com immediately after creating a custom view. 

**Steps to reproduce**
1. Log in to demo.akeneo.com
2. Click the + icon to create a custom view
3. Enter any label for the view and click OK
4. Click the Columns button
5. Try to apply a new list of selected columns

**Comment by fabienlem** [comment]
Hello @andrelecomte,

Thank you for reporting this. We are aware of this issue and we are currently working on the fix.

I will let you know when the patch will be available!

Kind regards,
Fabien

**Comment by fabienlem** [comment]
Hello @andrelecomte,

This issue has been fixed (in both 1.6.6 and 1.5.14 version). You can update your PIM.

Best regards,
Fabien
