### ISSUE TITLE
[<=1.6.5] AttributeOptionSearchableRepository - Missing attribute option when no translation in my locale

### ISSUE THREAD

**Issue by eheuje** [akeneo/pim-community-dev#5284]
When I enrich a product, I cannot fill all Single and Multi Select fields with an attribute option without translation set on the attribute option that I search. 

The waiting behavior is the following : if the attribute_option isn't translated in the contextual locale,  it returns the attribute code.

```php
'['.$attribute->getCode().']';
```

It's due to the way to write the add of query options.

```php
class AttributeOptionSearchableRepository implements SearchableRepositoryInterface
{
    ...
    ...
    public function findBySearch($search = null, array $options = [])
    {
        $qb = $this->entityManager->createQueryBuilder();

        $qb->select('o')
            ->addSelect('v')
            ->from($this->entityName, 'o')
            ->leftJoin('o.optionValues', 'v')
            ->leftJoin('o.attribute', 'a')
            ->andWhere('a.code = :attributeCode')
            ->orderBy('o.sortOrder')
            ->setParameter('attributeCode', $options['identifier']);

        if ($search) {
            $qb->andWhere('v.value like :search OR o.code LIKE :search')
                ->setParameter('search', '%' . $search . '%');
        }

        $qb = $this->applyQueryOptions($qb, $options);

        return $qb->getQuery()->getResult();
    }

    protected function applyQueryOptions(QueryBuilder $qb, array $options)
    {
       ...
        if (isset($options['locale']) && null !== $options['locale']) {
            $qb->andWhere('v.locale = :locale');
            $qb->setParameter('locale', $options['locale']);
        }
       ...
        return $qb;
    }
}
```

Something like that may works.

```php
    protected function applyQueryOptions(QueryBuilder $qb, array $options)
    {
       ...
        if (isset($options['locale']) && null !== $options['locale']) {
            $qb
                ->leftJoin('o.optionValues', 'v', 'WITH', 'v.locale = :locale')
                ->setParameter('locale', $options['locale']);
        }
       ...
        return $qb;
    }
```

**Comment by fabienlem** [comment]
Hello @eheuje,

I'm not sure to understand. I'm able to add attribute options without translations on both multi-select and simple-select attribute types. When you type the first characters of the option you are looking for, the search is performed on current locale label as well as on attribute option code.

![attroptcodes](https://cloud.githubusercontent.com/assets/19775001/20791471/7a774804-b7bd-11e6-8cc4-e490cdbdb27c.png)

Can you be more specific about the steps to reproduce? Which PIM version are you using?

Regards,
Fabien

**Comment by willy-ahva** [comment]
Hi @eheuje !

Do you have any update about your potential bug ? Can I close this issue ?

**Comment by mickaelandrieu** [comment]
Hi @eheuje,

if you can provide a reproducible test case, don't hesitate to do it and I'll reopen the issue.

Regards,
