### ISSUE TITLE
Object "category" with code .... does not exist, when editing and export profile

### ISSUE THREAD

**Issue by siegfried1e** [akeneo/pim-community-dev#5302]
**I'm reporting a Bug**
If the schema changes and a category is removed , then an export profile created with the deleted category can not be edited (to remove the category but keep the rest of the configuration)

**Comment by fabienlem** [comment]
Hello @siegfried1e,

I reproduced this issue on our environments. It's a bad design which also exists in some other PIM functionalities. We will not fix it on the current version but we plan to improve this in a future release of the PIM.

You can access the profile in edition mode by clicking the edit icon and then, save to update it. The problem will be solved.

![editexportprofile](https://cloud.githubusercontent.com/assets/19775001/20975571/2f9a8bf6-bca0-11e6-9d8a-9140487c35e3.png)

Best regards,
Fabien

**Comment by LaureBro** [comment]
Hello @siegfried1e, this issue is still not fixed, we have created a bug ticket in our internal bug tracker, here is the reference: PIM-6430
We'll keep you updated.
Regards.
