### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by JBleijenberg** [akeneo/pim-community-dev#5344]
I'm following the instructions on this page to install Akeneo:
https://docs.akeneo.com/1.6/developer_guide/installation/installation_ce_archive.html

I've met all the requirements, but after running ```composer install --optimize-autoloader --prefer-dist``` succesfully, everything comes to a grinding halt.
Every other command i try to execute throws errors about not being able to connect to the database.
It's right about that, i've never been asked to configure database credentials, nor are there instructions to create/edit a config file.

After sniffing through the files i've found some configuration files in app/config and i've got it working after a while.
But it would be nice if there would be some kind of configuration wizard for my DB credentials, OR instructions in the installation manual about where to edit the config files.

**Comment by fabienlem** [comment]
Hello @JBleijenberg,

When missing, the `composer install` command automatically ask user to fill the databases parameters (by generating or updating the app/config/parameters.yml).

Regards,
Fabien

**Comment by JBleijenberg** [comment]
@fabienlem but it's not missing when installing with the archive. And this is not documented in the install manual. That's why the documentation is incomplete, i had to figure this out myself :)

**Comment by fabienlem** [comment]
@JBleijenberg,

You're absolutely right! I think it's better to not provide the parameters.yml file in our archives instead of adjusting our documentation. I will submit this improvement to our product team and keep you updated.

Best regards,
Fabien
