### ISSUE TITLE
Import does not sterilize data if system attributes are included

### ISSUE THREAD

**Issue by sammarcus** [akeneo/pim-community-dev#5349]
This may be obvious (or even more of a feature request), but if system attributes are mistakenly included as a part of data that is imported, there is no warning to the user and that data will become corrupt. Further, when trying to debug, the error was very ambiguous and was not obvious what the actual issue was.

## Steps to reproduce:
Import a CSV with a standard `csv_variant_group_import` job profile with the necessary minimum columns as required, but also include one that is a core system one, such as `categories`, for example.

| code | axis  | type    | label-en_US | categories | 
|------|-------|---------|-------------|------------| 
| 1A1A | axis1 | VARIANT | 1A1A        | magnetic   | 

The variant group is indeed created as corrupt right off the bat:

![image](https://cloud.githubusercontent.com/assets/8689264/21200856/c89a3ad8-c216-11e6-864d-9b0baacc9f54.png)

That message itself is not clear and does not suggest what happened. After some digging and guidance from @gplanchat (thank you!) I learned it was a product value denormalization that was causing the issue. When clicking through to load the respective variant group, a blank page just loads instead.

In this state, a standard variant export job would also fail as well:

![image](https://cloud.githubusercontent.com/assets/8689264/21201144/cd034384-c217-11e6-9034-1451e87d31d4.png)

## Expected behavior:
Not create a corrupt group and possibly more clearly alert the user instead that this is not a permissible column to have on import, or fail more gracefully.

When I was working with hundreds of groups and many many columns on this import job, it was very difficult to debug this. There were many times when importing that it didn't even complain of an error and just imported the corrupt group silently as well.

**Comment by fabienlem** [comment]
Hello @sammarcus,

The import profiles expect only the columns that are available when using the corresponding export profiles. If you want add custom columns, you have to create your own import profile by following our cookbook: https://docs.akeneo.com/latest/cookbook/import_export/index.html

Regards,
Fabien

**Comment by sammarcus** [comment]
@fabienlem Thanks, I appreciate the reply. I still see an advantage to more clear language in these cases, but I understand why it is doing what it is doing.
