### ISSUE TITLE
[CLEANUP] parameter pim_catalog.constraint.product_identifier.class is not used anymore

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#5359]
It looks like the `pim_catalog.constraint.product_identifier.class` is no longer used on 1.6+ (neither CE or EE) and the class it declares doesn't exist neither.

**Comment by fabienlem** [comment]
Hello Grégory!

Yes you're right, good catch! I made a PR on the master branch, we will merge it very soon!

Regards,
Fabien

**Comment by fabienlem** [comment]
Hello @gplanchat!

I confirm you the class declaration has been removed on the master branch.

Thank you again!

Fabien
