### ISSUE TITLE
Product status permission issue

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#5403]
**I'm reporting a Bug**

Disabling/Disallowing the permission of the "Changing state of the product" behaves improperly in some cases.

Case 1: Product grid still have toggle icon and changing status is allowed still
Case 2: Product detail page has the button hidden (seems partially right as there should be an indicator (label/badge) telling the status of the product but non editable)

Steps to reproduce

1) System > User Management > Roles > Permissions Tab > Change state of the product > disallow

![screen shot 2016-12-26 at 1 07 27 pm](https://cloud.githubusercontent.com/assets/4486133/21479369/4af04130-cb6d-11e6-8362-d7b13b87693a.png)

2) Go to product grid and you still see toggle status icon and can even disable/enable the product (wrong behavior in my opinion)

![screen shot 2016-12-26 at 1 07 56 pm](https://cloud.githubusercontent.com/assets/4486133/21479374/52e9d586-cb6d-11e6-8043-e9c47bad6783.png)

3) Go to product detail and you don't see the Enabled/Disabled button (partially right behavior in my opinion)

![screen shot 2016-12-26 at 1 08 15 pm](https://cloud.githubusercontent.com/assets/4486133/21479382/5b9719b4-cb6d-11e6-9d5e-fcfb1df5c7be.png)

Thank You

**Comment by LaureBro** [comment]
Hi @wakqasahmed, 

Thanks for your ticket, I could reproduce the same behaviours.

For case 1, it's a bug. 

For case 2, what would you expect on the Product Edit Form: a button Enabled/Disabled visible but not clickable?

Thanks a lot, 
Laure

**Comment by BatsaxIV** [comment]
This [PR](https://github.com/akeneo/pim-community-dev/pull/6098) fixes the first bug described.

For the second issue, it's not really a bug so I'll let the Akeneo team decided the best way to handle that case.

**Comment by phaseinducer** [comment]
Case 1 is fixed, thanks :wink: 
@wakqasahmed If you really want to have the disabled button, it's possible to do it in your project. Don't hesitate to ask for help on the slack UG.
