### ISSUE TITLE
Bug on pop-in Add a family or add an association type

### ISSUE THREAD

**Issue by matthieuhelary** [akeneo/pim-community-dev#5423]
When I try to create a new family, the pop-in seems broken. There is no way to close the pop-in or save the code. 

When you move the pop-in with the mouse, there is a purple rectangle behind the pop-in.

I try in Chrome. 
In Safari, we can't even see the pop-in.
In Firefox, I'm not able to launch Akeneo (loading bar after the log-in)

I use Bitnami and Google Cloud Platform.

[akeneo-pim-system-info_2016-12-29_04-10.txt](https://github.com/akeneo/pim-community-dev/files/677038/akeneo-pim-system-info_2016-12-29_04-10.txt)

![capture d ecran 2016-12-29 a 12 57 06](https://cloud.githubusercontent.com/assets/7225618/21543626/8568fc32-cdc8-11e6-900d-eb234b626ae0.png)

**Comment by matthieuhelary** [comment]
<form id="pim_enrich_family_form" method="post" action="/configuration/family/create" data-title="Create a new family" data-button-submit="Save" data-button-cancel="Cancel" class="form-inline ui-dialog-content ui-widget-content" style="display: block; width: auto; min-height: 82px; max-height: none; height: auto;" novalidate="novalidate">

**Comment by LaureBro** [comment]
Hello @matthieuhelary, 

That's strange...
Can you clear all your caches and check if your assets (CSS, JS files etc.) are well deployed?
You will find the commands to run on this link:
https://docs.akeneo.com/latest/troubleshooting/first_aid_kit/index.html#step-7-are-your-assets-properly-deployed

Thanks, 

Laure

**Comment by matthieuhelary** [comment]
@LaureBro Actually it works now. I was on a guest network with weird configuration. Thanks !
