### ISSUE TITLE
Component akeneo/batch is missing dependencies

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#5448]
The component `akeneo/batch` is missing a dependency to `symfony/filesystem` :

The class `Akeneo\Component\Batch\Job\Job` instanciates a `Symfony\Component\Filesystem\Filesystem` and catches a `Symfony\Component\Filesystem\Exception\IOException`

This does not affect the main app, but affects those requiring the batch component

**Comment by pierallard** [comment]
Checked ! You're right, the `composer.json` of batch does not contains require to `symfony/filesystem`.

If someone want to contribute, it's an extra-easy-pick ;)

Thanks @gplanchat !

**Comment by gplanchat** [comment]
I made a fix with PR #5570

**Comment by pierallard** [comment]
Thanks for the fix @gplanchat !
