### ISSUE TITLE
Redo the family edit screen

### ISSUE THREAD

**Issue by nidup** [akeneo/pim-community-dev#5573]
**Goal:**
Discover the current stack and give a feedback of what could be improved as a newcomer.
**How:**
Redo a simple edit page of the PIM and update the doc if needed.

**The program:**
You will work on the family edit form to redo it using backbone and REST API. You will discover the javascript architecture (if it's not already the case) and create a internal api controller. We also would like to get the maximum amount of feedback about your experience during this process to improve the documentation and our tools. It will help contributors and newcomers to onboard on the product more easily. Of course we will be available on slack ug for questions and small training sessions and we will update the doc according to your feedbacks.

PS1: bonus, this improvement will allow to handle the scalability limitation regarding the amount of attributes directly loaded in the attribute selector by using the same selector than in product edit form (loading 10 first attributes + search capability). The attribute selector is the same component that we use in the product mass edit common attributes.

PS2: bonus, we'll also add a selector to add all attributes of an attribute group to stay iso-functional with the current attribute popin which allow to select all attributes when clicking on an attribute group (we can't keep this behavior in the attribute selector as we only load few attributes).

![akeneo add by group](https://cloud.githubusercontent.com/assets/2104359/22333495/cacbd140-e3d6-11e6-9655-53acf4b84ae3.jpg)

PS3: also known as PIM-6095 in the internal tracker

**Comment by LaureBro** [comment]
Will fix this issue #4772

**Comment by nidup** [comment]
closed in favor of https://github.com/akeneo/pim-community-dev/pull/5791
