### ISSUE TITLE
Translation errors after updating to 1.6

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#5580]
Finally we are updating Akeneo from 1.5.13 to 1.6.9. :-)

Most of our users have set the interface language "de_DE".
With our shiny new 1.6.9 installation the user gets an exception after logging in:

    Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Error during translations file generation for locale "de_DE"")."

I've already done step 6 from `UPGRADE-1.6.md`, but this only generates `de.js`:

    rm $PIM_DIR/web/js/translation/ -rf
    php app/console pim:installer:assets

When I manually copy the translation file to `de_DE` everything works fine:

    cp web/js/translation/de.js web/js/translation/de_DE.js

**Comment by a2xchip** [comment]
```app/console oro:trans:dump de_DE```

**Comment by Hocdoc** [comment]
Thx this also works, I was just wondering why this doesn't work with the instructions from the UPDATE guide.

**Comment by a2xchip** [comment]
@Hocdoc You are welcome, i'm remember that almost same issue was raised before ~6m ago, with more explanations about why it happens, but not sure who was reporter :/
