### ISSUE TITLE
JS fetchers, cache & reference

### ISSUE THREAD

**Issue by grena** [akeneo/pim-community-dev#5600]
## Explanation
- JS Fetchers are used to fetch resources, as Locale, Attributes, etc.
- Fetchers do cache by returning the `deferred.promise()` object to avoid multiple requests on already fetched resources.

**Problem:** If I fetch a resource A, then edit the object, then later re-fetch the resource A, the cache gives me the modified object, which does not represent the server state! Code example:

```js
FetcherRegistry.getFetcher('datagrid-view').fetch(666).then(function(obj) {
   console.log(obj);  // {name: 'FooBar', columns: ['name', 'sku']}
   obj.columns = ['name']; // now I update the object
});

// Then later in the same script, without reload, without saving the entity

FetcherRegistry.getFetcher('datagrid-view').fetch(666).then(function(obj) {
   console.log(obj);  // {name: 'FooBar', columns: ['name']}
});
```

Here, on the second call, the fetcher should return the cache object from the initial request, cf: `{name: 'FooBar', columns: ['name', 'sku']}`, but we see it has been impacted by the modification by reference.

## Solution?
The file who manages this is mainly the base-fetcher (https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js).

Fetchers **should return a deep clone of the resolved resource**.

---
_Notes:_
- The PR https://github.com/akeneo/pim-community-dev/pull/5599 has been resolved by bypassing the cache, but we should be able to re-use the cache once this issue will be fixed.

**Comment by a2xchip** [comment]
@grena Where do we update fetched object directly? As i know general practice is that we set as form data modifiable object gotten through fetcher and then use it via `getFormData` `setData` `BaseForm`'s methods. In case for example when fetched objects list was modified we can set listener to fetch updated items using fetcher with `cache: false` param set.

Like example 

Here we [trigger event](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/Resources/public/js/channel/form/properties/general/locales.js#L111) and here [we listen for event](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/properties/translation.js#L125)
