### ISSUE TITLE
[FRequest] Product attribute as label settings

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#5649]
**I'm submitting a Feature Request**

**Description** 

In some cases users filling in product info have need in `Attribute as label`+`SKU` labeled PEF. This way they can understand what product is by "Product name" and search info they need from other companies sources linking to `SKU`. As example: Philips A2.310 20W RMS high Power (20126)

**Feature**

To add additional *Yes/No* switch on *Family* edit page's *Properties* tab form labeled as "Attribute as label with identifier", and show product label according to this settings with/without `pim_catalog_identifier` postfix.

Ideas, offers and suggestions are WELCOME! :slightly_smiling_face:

**Comment by Delphineray** [comment]
Hello Alexandr,

Thank you for your feature request, we have in our backlog an improvement like this (idea IM-741), but we would like to give more possibilities to our users, because often they would like to have a more complex label, to compose their label by concatenating several attributes (ex: name + color or name + brand or name + SKU as you suggest)
We are thinking about something like this:
![keynote-ivb_key](https://cloud.githubusercontent.com/assets/10232850/22691058/ea057adc-ed38-11e6-9ba0-fccce0bee0ee.png)

Delphine

**Comment by a2xchip** [comment]
Thx! Good to know! IM-741 sounds even better.

It is also possible to use attribute select with sortable list, like this 

![image](https://cloud.githubusercontent.com/assets/6627334/22691192/e539ccb6-ed41-11e6-9690-08aef4e9626e.png)

**Comment by Delphineray** [comment]
Yes, you're right the order is important.

**Comment by a2xchip** [comment]
:-) Cool! I think it is great feature!

**Comment by mickaelandrieu** [comment]
Hello @a2xchip,

would you like to contribute to this feature? Do you need help?

Regards

**Comment by a2xchip** [comment]
Hello!!! @mickaelandrieu

From talk with @Delphineray i understood that there is `IM` created, such ticket means it is just idea and no decision was taken about it. And of course ;-) I would like to participate in this feature development when `TIP` or `PIM` based on this `IM` will be created.

**Comment by Delphineray** [comment]
Hello @a2xchip, it's great if you could contribute to this feature, I will create a PIM ticket for this, I keep you informed (CC @mickaelandrieu).

**Comment by a2xchip** [comment]
:) :) :) Thx! @Delphineray

**Comment by Delphineray** [comment]
Hello @a2xchip,

About this feature request on products labels, we would like to work on another solution which will cover more use cases, by having a rule to concatenate attributes (in EE). But perhaps you could contribute this solution as a CE bundle in our marketplace?

Regards,
Delphine
