### ISSUE TITLE
ProductEvents in EnrichBundle 

### ISSUE THREAD

**Issue by jon92** [akeneo/pim-community-dev#5663]
Hello,
I found in the application multiple events (which were not mentioned in the documentation) that appear to be inactive.
For example, i was trying to subscribe to **PRE_EDIT** product event (_EnrichBundle/Event/ProductEvents_) but it seems that it is never triggered. Nevertheless, there are still native subscribers based on this event : _SecurityBundle/EventSubscriber/Enrich/ProductSubscriber.php_

Am I missing something ?

**Comment by willy-ahva** [comment]
Hi,
This issue is related to Enterprise Edition and has been answered in Jira. Just for information, those events are legacy and will be removed in next release.

Thanks :)
