### ISSUE TITLE
ODMProductReader reads disabled products

### ISSUE THREAD

**Issue by Mostafa1695** [akeneo/pim-community-dev#5748]
**I'm reporting a Bug**

`ORMProductReader` does not read disabled products due to a check that happens in `Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\ProductRepository`.
However, `ODMProductReader` does not have the same check, therefore disabled products are exported only when using `doctrine/mongodb-odm` as the `pim_catalog_product_storage_driver`.

**Comment by momoss** [comment]
Hello @Mostafa1695 ,

Please have a look to [your pull request](https://github.com/akeneo/pim-community-dev/pull/5749#issuecomment-285092865).

Best regards,

Philippe.
