### ISSUE TITLE
[1.6.11] Category Delete button rendered even if role does not allow category remove

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#5752]
**I'm reporting a Bug**

The category _Delete_ button gets rendered even it the users role does not allow _category remove_. This happens _if_ the amount of products in the category _exceeds the product limit for removal_.

How to reproduce:

1. User _Foo_ with role which does not allow category removal.
2. Category _A_ with less than _X_ products. _X_ comes from parameter _pim_enrich_max_products_category_removal_, which again comes from parameter _max_products_category_removal_. Defaults to 100.
3. Category _B_ with over _X_ products.
4. Go to category _A_ as user _Foo_. No _Delete_ button.
5. Go to category _B_ as user _Foo_. _Delete_ button exists (does not allow to delete though).

The logic is applied in https://github.com/akeneo/pim-community-dev/blob/v1.6.11/src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig#L30-L54

The _deleteLink_ macro checks for the _acl_, whereas the _link_ macro does not. https://github.com/akeneo/pim-community-dev/blob/v1.6.11/src/Pim/Bundle/UIBundle/Resources/views/Default/page_elements.html.twig#L76-L95

**Comment by mickaelandrieu** [comment]
Hello @mathewrapid,

I can reproduce the bug, thank you! I agree with you on the suggest you did, would you link to contribute a patch in `1.6.x` branch? I'll be glad to help you if needed.

Regards,

**Comment by Doodoune** [comment]
Hi!

I close his ticket, feel free to reopen it if you still have the issue.

Regards,
