### ISSUE TITLE
[1.6.11] Variant group data import throws an ORMInvalidArgumentException if no prior product attributes set

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#5772]
**I'm reporting a Bug**

Importing product attributes to variant group via csv importer (probably same result with xlsx), _if_ no prior attributes set to variant group, causes an exception to be thrown.

settings:
```
    installer_data: 'PimInstallerBundle:icecat_demo_dev'
    pim_catalog_product_storage_driver: doctrine/orm
```
How to reproduce:
1. Run a clean PIM install `php app/console --env=prod pim:install --force` with `PimInstallerBundle:icecat_demo_dev` as installer_data
2. Run variant group export to csv
3. Add a new column to the csv e.g. `name` and add some data into it
4. Import the modified file through the `csv_variant_group_import` job
5. Voilà
```
An error occurred during the import execution.
Error #0 in class Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Pim\Component\Catalog\Model\Product#groups' that was not configured to cascade persist operations for entity: [akeneo_mug]. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
```

**If** the variant groups already have _any_ product attributes set, then this exception is not thrown.

Test csv file inside zip.

[variant_group.zip](https://github.com/akeneo/pim-community-dev/files/799256/variant_group.zip)

**Comment by mickaelandrieu** [comment]
To me sounds like correct that we have to import attributes before importing the variant groups... what do you think @Delphineray?

**Comment by mathewrapid** [comment]
@mickaelandrieu Did you look into the test file I attached?

perhaps I should have clarified the setup a bit.

> Add a new column to the csv e.g. name and add some data into it

I mean that add any existing attribute, as in a valid attribute created in Akeneo that is still not set to said variant groups.

**Comment by mickaelandrieu** [comment]
Hello @mathewrapid, thank you for your report.

For now, I try to confirm this is wrong from a behavior point of view. I trust you about your issue and we need to fix it, I want to add more "product" context to help: this is why I didn't even tried to reproduce the problem, yet ;)

We were very late to answer you on this issue, so you may have fixed it from your own? Do you want to contribute a patch for this specific issue?

**Comment by mickaelandrieu** [comment]
Hello again, I've confirmed with the product team 2 things:

* it's a bug, and it should behave the way you think
* it's working on 1.7 with the csv file you provided

So it's probably a patch we need to apply on `1.6.x` branch from `1.7.x`.

Regards

**Comment by jmleroux** [comment]
Closed after 2 years of inactivity
