### ISSUE TITLE
Enhance documentation to explain how to create config form

### ISSUE THREAD

**Issue by smalot** [akeneo/pim-community-dev#5786]
Hi,

I'm trying to find a way to enrich the `system_configuration` form or to create a new one.
My goal is to share a setup property between multiple jobs and event listeners.

Thanks,

**Comment by nidup** [comment]
Hi @smalot 

You can find an example in the following pull request https://github.com/akeneo/pim-community-dev/pull/4991

Have a good day,

**Comment by smalot** [comment]
Hum, quite complexe ...

**Comment by nidup** [comment]
Hi @smalot 

Regarding documentation don't hesitate to open a discussion in the dedicated repository https://github.com/akeneo/pim-docs and to help by contributing a cookbook. FYI, we re-working the upcoming 1.7 doc to add the most expected cookbooks (as how to create a CRUD for a reference data or how to add a menu entry \cc @mickaelandrieu), the use case you're describing is definitely missing even if it's not the most common customization.

Have a good day,
