### ISSUE TITLE
[BUG] Product mass edit - common attributes

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#5805]
**I'm reporting a Bug**

At least on 1.7, and master

Select some products, bulk actions, change product information, edit common attributes.
Select some attributes, fill in or not fill in some data, press next.
Expected - confirm button, attributes disabled (read only). 
Now select one more attribute. Hah! Attributes editable again! 

Expected: attributes read only; add attribute select disabled.

![image](https://cloud.githubusercontent.com/assets/6627334/23447830/3d09221e-fe56-11e6-8703-0dd054992167.png)

**Comment by LaureBro** [comment]
Hi Alex, 
As you know we have created an internal ticket (PIM-6199) for this :) 
I'll assign this one to myself to ease the follow up. Thanks!

**Comment by a2xchip** [comment]
Is fixed in latest PR
