### ISSUE TITLE
Attribute Group sorting is wrong if attribute group code is numeric

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#5827]
**I'm reporting a Bug**

If the attribute group code is a number, PEF ignores the sort_order of the group and sorts the groups based on their code.

*Attribute Group sorted as a last member:*
<img width="1280" alt="screen shot 2017-03-03 at 1 24 27 am" src="https://cloud.githubusercontent.com/assets/4486133/23527645/44c48cfe-ffb0-11e6-9488-2bd910e382f4.png">

*PEF showing the group as first member (doesn't mind the sort_order of the group):*
<img width="1277" alt="screen shot 2017-03-03 at 1 28 21 am" src="https://cloud.githubusercontent.com/assets/4486133/23527701/6fdd30e4-ffb0-11e6-855d-8dfeee616b13.png">

*Attribute Group Code*
<img width="1277" alt="screen shot 2017-03-03 at 1 29 26 am" src="https://cloud.githubusercontent.com/assets/4486133/23527755/a6b8a30a-ffb0-11e6-9d03-77f6217c9978.png">

*The Reason*
<img width="1276" alt="screen shot 2017-03-03 at 1 31 02 am" src="https://cloud.githubusercontent.com/assets/4486133/23527843/ec28cef6-ffb0-11e6-8488-c703736148bb.png">

**Comment by a2xchip** [comment]
Nice catch! Like it!

**Comment by LaureBro** [comment]
Hello @wakqasahmed, 
it's fixed in the latest 1.7 (the 1.7.5) released this morning :)
Kind regards, 
Laure
