### ISSUE TITLE
Product mass edit - common attributes and validation on SKU

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#5846]
**I'm reporting a Bug**

If your product identifier, that is SKU, has an regex validation on it, for an example `/^\d+$/` then the Mass edit common attributes will fail with a validation error.

This is because in https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/EditCommonAttributes.php#L229 the temp product, that gets validated, gets a fake SKU which might not match the given regex for the identifier.

**Comment by aistis-** [comment]
I confirm we have the same issue on v1.6.12 CE

**Comment by LaureBro** [comment]
Hello @mathewrapid @aistis- , 

This issue on 1.7.2, here's the commit if you need it for 1.6 version: https://github.com/akeneo/pim-community-dev/pull/6009/commits.

Kind regards, 

Laure
