### ISSUE TITLE
Prevent export disabled products when using MongoDB

### ISSUE THREAD

**Issue by thisisandrew** [akeneo/pim-community-dev#5851]
1.5 latest - When exporting products when using MongoDB for product storage. ORMProductReader does not read disabled products due to a check that happens in Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\ProductRepository.
However, ODMProductReader does not have the same check, therefore disabled products are exported only when using doctrine/mongodb-odm as the pim_catalog_product_storage_driver

PR to fix is here if this is a bug and not deliberate. 

https://github.com/akeneo/pim-community-dev/pull/5749

**Comment by momoss** [comment]
Hello @thisisandrew,

Please have a look to this [pull request](https://github.com/akeneo/pim-community-dev/pull/5749#issuecomment-285092865)

We only accept contributions on master version, therefore we won't fix it in 1.5 version

Best regards,

Philippe.
