### ISSUE TITLE
Disallow multiple category selection within a tree and select parent automatically on child selection

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#5858]
**I'm submitting a Feature Request**

There are two minor features i would like to request.

1) Disallow multiple parent/child selection within a category tree
2) Select the parent node on child node selection

The first behavior is available in latest version of jstree but since akeneo is still using *v1 rc3* we don't have this behavior available. Let me know if this requires explanation. 

**Ready to contribute**

Thank You

**Comment by aistis-** [comment]
We have also a demand on the same feature. At the moment, we have implemented a custom validation for that. But it is dirty and has some problems: for example, if you change the categories via mass editor - it will not work.

**Comment by Delphineray** [comment]
Hello @wakqasahmed, thank your for your submitting a feature request, I am product owner in the Akeneo product team and I have some questions about your 2 features.

1. Feature 1: Within a category tree, we allow the multiple selections because in an e-commerce website a product can belong to several categories (for example a product "jean Levi's" could be in the categories "Men > Jeans", "Jeans > Mens" and a dedicated category for the brand "Levi's",  What is your use case?

2. Feature 2: In the product grid, if you click on a parent node, all the products from the children nodes are displayed. Why do you need to select the parent node on child node selection? 

Regards,
Delphine

**Comment by wakqasahmed** [comment]
Hi @Delphineray 

1) In my case, for each channel there is a dedicated category tree. The whole selected node is shown in breadcrumb. Having multiple nodes selected, the channel can't decide which one to show in the breadcrumb (Check in icecat for example). The products that belongs to multiple areas are handled in navigation.

The best way in my opinion would be to provide a configuration "Allow multiple nodes" in category properties (at the root).

2) Again, it is used to export the complete branch (e.g. Home Appliances > Laundry > Washer & Dryers > Washing Machines). In order to reduce product listing time, its better to select the parent on selection of child (but not vice versa of course)

3) (Suggestion) Moreover, in my opinion each category tree should also be exported separately in product export. (Right now, its only exported as a single column "categories" without any sequence and without any clue of the tree it belongs to)

Let me know if my understanding is wrong or you have any further query.

Thank You

**Comment by Delphineray** [comment]
Hello @wakqasahmed,

Sorry for the delay, I've missed the notification.

1. I understand your use case and I've seen some customization for this on projects. But to keep our actual behaviour, I prefer to add a parameter "Allow single category selection" (in the categories for the root category).

2. About this use case, perhaps it's just a requirement at the export? To export the products with its categories and parents categories?

3. Thank your for the suggestion, we have to think how we can improve this, we export all the categories in a single column to ease the import/export of the categories.

Regards,
Delphine

**Comment by mickaelandrieu** [comment]
Hello,

as @Delphineray have answered, I close.

I will re-open if needed, thanks for your report @wakqasahmed :)
