### ISSUE TITLE
Shows console error in case of missing flash message

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#5897]
**I'm reporting a Bug**

As shown in the snapshot, we keep getting a javascript error whenever we click on any import/export profile, in my opinion:

1) Either it should be a simple warning OR
2) If it is really critical (I don't really know why?) we should fix this by sending some message (e.g. empty string) to stop showing error on profile click.

Steps to reproduce:

1) Click Import profiles/Export profiles from Collect/Spread links in the menu.
2) Click any profile and check chrome console for error

![javascript_error](https://cloud.githubusercontent.com/assets/4486133/23820917/78918738-063d-11e7-8fad-2840da1db53c.jpg)

**Comment by wakqasahmed** [comment]
Submitted a PR, please have a look and merge.
https://github.com/akeneo/pim-community-dev/pull/5898

**Comment by solivier** [comment]
Thanks @wakqasahmed you PR has been merged. :+1:
