### ISSUE TITLE
Mcrypt is deprecated

### ISSUE THREAD

**Issue by gquemener** [akeneo/pim-community-dev#5937]
Hello :wave: ,

I'm using Akeneo CE 1.7 and I've noticed that somehow you still rely on mcrypt which has been unmaintained since 2007.

https://github.com/akeneo/pim-community-dev/blob/master/app/OroRequirements.php#L43

http://php.net/manual/en/intro.mcrypt.php#117606

I've removed this requirement and will let you know if I notice any impact.

**Comment by gquemener** [comment]
so far so good

**Comment by a2xchip** [comment]
Hello! Global searched project and it looks like mcrypt really never used. Do not hesitate to submit PR. cc @nidup

**Comment by aRn0D** [comment]
Thank you Gildas for reporting this issue! I am glad you're using Akeneo! Feel free to send a PR ;)

**Comment by NicoHaase** [comment]
Is there any reason this hasn't made its way into Akeneo 2.x? Does this still require mcrypt to be installed, as stated in https://github.com/akeneo/pim-community-dev/blob/2.3/app/PimRequirements.php?
