### ISSUE TITLE
VariantGroupWriter Memory Leak on 1.5

### ISSUE THREAD

**Issue by nei** [akeneo/pim-community-dev#5941]
**I'm reporting a Bug**

Version: 1.5.20 
Version: 1.6 (fixed already)

The variant group import wasn't detaching the objects and the memory usage was going up to 1Gb with just 100 variant groups being imported.

I've managed to run 4k variant groups and the memory kept in 218Mb.

@nidup helped to solve this issue where I will be PR soon.

**Comment by nidup** [comment]
Fix will be available with upcoming v1.5 patch release, thank you @nei ! :tada:

**Comment by LaureBro** [comment]
Hello, the 1.5.21 has been released this morning! 
I'm closing this issue.
Thanks again @nei for this contribution!
