### ISSUE TITLE
Error on product updating with association type code as integer

### ISSUE THREAD

**Issue by dobru** [akeneo/pim-community-dev#5951]
Hello,
I'm reporting a bug on Akeneo CE 1.6.11 !

We currently use integer as association type code but it seems not to be allowed :/
The checkAssociationData method of AssociationFieldSetter class has a condition to not accept no string association type code. 
That's why we can't update product since we update Akeneo version from 1.3 to 1.6.

Is there a fix or should we change the codes ?

**Comment by aRn0D** [comment]
Hi @dobru 

Since the 1.4 and changes made in the UI, integer association codes do not work in the PIM anymore. We have an internal ticket to prevent the creation of numeric association codes in the PIM. So you should change your codes.

Sorry for the inconvenience.

**Comment by dobru** [comment]
Hi @aRn0D ,

Thanks for the answer !
