### ISSUE TITLE
SQL error while importing products

### ISSUE THREAD

**Issue by malteSchultz-redteclab** [akeneo/pim-community-dev#5954]
When importing a CSV-file with products via the "Akeneo CSV Connector" sometimes Akeneo returns the following error message: 
![bildschirmfoto 2017-03-20 um 14 28 39](https://cloud.githubusercontent.com/assets/26544985/24101698/9c0569f8-0d79-11e7-9286-60ec55504f98.png)

The same import profile with other import data produces no problems. The CSV-files imported don't contain the number 1264 and the message seems to be the same in several instances of the error.

**Comment by aRn0D** [comment]
Hi @malteSchultz-redteclab ,

You want to import `4250201202413`, what did you configure as `min` and `max` for that attribute?

**Comment by malteSchultz-redteclab** [comment]
The min and max values were not set. But since the attribute should have been a text to begin with, we fixed the problem this way. But the error message could give some clue about this.

**Comment by mickaelandrieu** [comment]
Hello @malteSchultz-redteclab,

can you please provide your PIM information? (You can export a txt file from System > System informations)

Also, would you mind to test using an updated version of Akeneo: we need a reproducible test case to fix the issue.

Thanks for your help :)

**Comment by mickaelandrieu** [comment]
Hello @malteSchultz-redteclab,

we close the issue right now, if you still have a question or an issue about Products import feel free to open a new issue.

Thank you for your understanding
