### ISSUE TITLE
Negative values are not "normalized" from the ui

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#5962]
**I'm reporting a Bug**

Exists in 1.6, tested even in 1.7

Use case:

- Have a numeric attribute with negative values allowed
- Change your users locale to fi_FI (Finnish)
- Go to product edit page
- Enter a negative value, for example `-4`
- Save
- Output it now `−4`
- Save - get error, not a number

As we can see the `-4` and `−4` are not the same.

The transformation happens in https://github.com/akeneo/pim-community-dev/blob/v1.7.0/src/Akeneo/Component/Localization/Localizer/NumberLocalizer.php#L45-L72

Why then is there not a "normalization" phase in the product update action in https://github.com/akeneo/pim-community-dev/blob/v1.7.0/src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php#L257-L298 ?

**Comment by mathewrapid** [comment]
Is there a reason to not utilize the `$numberFormatter->parse($number, \NumberFormatter::TYPE_DOUBLE);` in `NumberLocalizer::delocalize`?

**Comment by mickaelandrieu** [comment]
Hello @mathewrapid,

I could reproduce the issue, I agree this is probably not the expected behavior.

Can you contribute a pull request with your proposal? I think it's the right think to do, but this need to be reviewed by a core team member.

Thanks for your help!

**Comment by mickaelandrieu** [comment]
Hello @mathewrapid,

I've added your issue to our board of "Wanna contribute". Feel free to contribute a patch, if you don't maybe someone from the community will take it.

Thanks for your help :)

**Comment by dnd-tyler** [comment]
Hi, this is not only on product value.
The problem appear on the attribute too.
If you try to edit an numeric attribute which allow negative value and got a negative value, the negative values are display with − and not a -
- Create a new numeric attribute
- Allow negative value
- Set min value in negative like -100
- Save
- Change your users locale to fi_FI (Finnish)
- Reload the attribute page
- The min value display `−100` and not `-100`

**Comment by dnd-tyler** [comment]
I tried to fix the problem with the solution given by @mathewrapid, but it's make some bord effect for decimal numbers :
- The negative number is well formatted
- Then the decimals of numbers disappear
I'm trying to find another way.
