### ISSUE TITLE
Channel without translation doesn't show up on channel field of Export profile

### ISSUE THREAD

**Issue by nei** [akeneo/pim-community-dev#6004]
**I'm reporting a Bug**

When the channel have no translation,  (table pim_catalog_channel_translation is empty) the Channel dropdown on the export profile stay empty.

<img width="535" alt="screen shot 2017-03-29 at 6 15 22 pm" src="https://cloud.githubusercontent.com/assets/33385/24467717/7eb39128-14ad-11e7-8d18-452157106c0e.png">

I believe it should show the code or something but not empty. 

My details:

PIM 1.7.1
PIM EE

**Comment by nei** [comment]
Hi, 

I found the issue, it is actually on the initBundle since the connector https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Channel.php#L83 expect label prefix.

Init example file says that:
<img width="219" alt="screen shot 2017-03-30 at 3 33 39 pm" src="https://cloud.githubusercontent.com/assets/33385/24509559/9053a128-155e-11e7-9983-74a19dff6071.png">

But to have the translation fixed you must use the prefix like this.
<img width="475" alt="screen shot 2017-03-30 at 3 33 49 pm" src="https://cloud.githubusercontent.com/assets/33385/24509598/ab3f4dd4-155e-11e7-994a-ba2f2e7ca319.png">

@jmleroux

**Comment by jmleroux** [comment]
Thx @nei , i've made a PR for your fix: https://github.com/akeneo/ExcelInitBundle/pull/36

I think we can continue on it and close this one.

**Comment by mickaelandrieu** [comment]
Hello,

I agree with @jmleroux.

Thank you for your feedback @nei!
