### ISSUE TITLE
Products doesn't get exported on variant group update

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#6007]
**I'm reporting a Bug**

If the variant group (which has products linked) is modified, it doesn’t get exported in the export profile (FILTER: “Time condition”: “Updated products since last export”).

**Comment by wakqasahmed** [comment]
any considerations on this?

**Comment by mickaelandrieu** [comment]
Hi @wakqasahmed,

your report is uncomplete and I'm unable to answer you. Would you mind to complete your bug report with your system informations? (You can export a txt file from your Akeneo application in "System > System information" menu.

Thank you.

**Comment by mickaelandrieu** [comment]
Hi @wakqasahmed,

any considerations on this? which version is concerned by the bug? Is the bug still exists on the latest 1.7.5?

Mickaël

**Comment by wakqasahmed** [comment]
I am on v1.6.6 and this bug exists in that. Don't really know about the new version but most likely it would be there in the latest one too as i don't see any mentioning of it in ChangeLogs.

**Comment by wucherpfennig** [comment]
This bug exists also in 1.7 and we are looking for an solution on that. Any suggestions?

**Comment by jmleroux** [comment]
CE 1.7 and variant groups are not supported anymore.
