### ISSUE TITLE
Sku column values are not visible on Products Tab in Variant Group

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#6020]
**I'm reporting a Bug**

Sku (code) column values in the product grid of variant group are not visible (basically disappears after being loaded).

*Steps to reproduce:*

1) Click on "Enrich > Variant Groups" from the menu
2) Click on any variant group

The sku column values disappear after being loaded.

Note: Using `Cmd + R` (on Mac) brings the sku back.

<img width="1274" alt="screen shot 2017-04-01 at 3 49 04 pm" src="https://cloud.githubusercontent.com/assets/4486133/24578543/1482086e-16f3-11e7-9b7a-0249032a5035.png">
 
<img width="1274" alt="screen shot 2017-04-01 at 3 49 25 pm" src="https://cloud.githubusercontent.com/assets/4486133/24578547/1d967f7a-16f3-11e7-868c-54c5e434bd88.png">

**Comment by xElysioN** [comment]
I can reproduce the bug in the demo, but when i try in local with the latest version, i have the sku every times

**Comment by LaureBro** [comment]
Hello @wakqasahmed and @xElysioN,

This problem has been fixed in the 1.7.2! So I'll close this issue.

Thanks!

Kind regards, 
Laure
