### ISSUE TITLE
1.7 CSS Sub-menu size

### ISSUE THREAD

**Issue by naolis** [akeneo/pim-community-dev#6061]
Please adapt the menu size for bigger Text in the new CSS. 
Ping @pierallard 
<img width="306" alt="capture d ecran 2017-04-13 a 12 01 03" src="https://cloud.githubusercontent.com/assets/6884638/25003921/005e4bf0-2052-11e7-820d-ddd20cd599c4.png">

**Comment by pierallard** [comment]
Thanks for raising this glitch Aymeric ! PR is done, waiting for reviews ;)

**Comment by pierallard** [comment]
Merged ! Thanks again!
