### ISSUE TITLE
Upload of a file broken URL and breaks PNG

### ISSUE THREAD

**Issue by ekussberg** [akeneo/pim-community-dev#6078]
Hi guys,

maybe it's the misconfiguration on my side, but when i upload a file to the system, it breaks PNGs and when i try to download the path looks like this:

http://XXX/media/download/%252Ftmp%252Fpim%252Ffile_storage%252F1%252F5%252F8%252F4%252F%252F15842de4242df0ef4187d02c6e597a0f63d02197%252Fflying-men%25402x.png

Any ideas?

Edition	CE
Version	1.7.2
Umgebung	prod
Installationszeit	2017-04-17T14:32:56+02:00
Server-Version	Apache
Anzahl der Kanäle	5
Anzahl der Gebietsschemas	3
Anzahl der Produkte	1121
Anzahl der Attribute	43
Anzahl der Familien	14
Anzahl der Benutzer	3
OS-Version	Linux srv-ubuntu 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64
PHP-Version	5.6.30-10+deb.sury.org~xenial+2
PHP-Erweiterungen	Core
date
ereg
libxml
openssl
pcre
zlib
filter
hash
Reflection
SPL
session
standard
apache2handler
mysqlnd
PDO
xml
apcu
calendar
ctype
curl
dom
mbstring
fileinfo
ftp
gd
gettext
iconv
intl
json
exif
mcrypt
mongo
mongodb
mysql
mysqli
pdo_mysql
Phar
posix
readline
shmop
SimpleXML
sockets
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xmlreader
xmlwriter
xsl
zip
mhash
apc
Zend OPcache
Registrierte Bundles	APY\JsFormValidationBundle\APYJsFormValidationBundle
Akeneo\Bundle\BatchBundle\AkeneoBatchBundle
Akeneo\Bundle\BufferBundle\AkeneoBufferBundle
Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle
Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle
Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle
Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle
Doctrine\Bundle\DoctrineBundle\DoctrineBundle
Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle
Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle
Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle
FOS\JsRoutingBundle\FOSJsRoutingBundle
FOS\OAuthServerBundle\FOSOAuthServerBundle
FOS\RestBundle\FOSRestBundle
JMS\SerializerBundle\JMSSerializerBundle
Knp\Bundle\MenuBundle\KnpMenuBundle
Liip\ImagineBundle\LiipImagineBundle
Oneup\FlysystemBundle\OneupFlysystemBundle
Oro\Bundle\AsseticBundle\OroAsseticBundle
Oro\Bundle\ConfigBundle\OroConfigBundle
Oro\Bundle\DataGridBundle\OroDataGridBundle
Oro\Bundle\FilterBundle\OroFilterBundle
Oro\Bundle\NavigationBundle\OroNavigationBundle
Oro\Bundle\RequireJSBundle\OroRequireJSBundle
Oro\Bundle\SecurityBundle\OroSecurityBundle
Oro\Bundle\TranslationBundle\OroTranslationBundle
Oro\Bundle\UserBundle\OroUserBundle
Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle
Pim\Bundle\ApiBundle\PimApiBundle
Pim\Bundle\CatalogBundle\PimCatalogBundle
Pim\Bundle\CommentBundle\PimCommentBundle
Pim\Bundle\ConnectorBundle\PimConnectorBundle
Pim\Bundle\DashboardBundle\PimDashboardBundle
Pim\Bundle\DataGridBundle\PimDataGridBundle
Pim\Bundle\EnrichBundle\PimEnrichBundle
Pim\Bundle\FilterBundle\PimFilterBundle
Pim\Bundle\ImportExportBundle\PimImportExportBundle
Pim\Bundle\InstallerBundle\PimInstallerBundle
Pim\Bundle\JsFormValidationBundle\PimJsFormValidationBundle
Pim\Bundle\LocalizationBundle\PimLocalizationBundle
Pim\Bundle\NavigationBundle\PimNavigationBundle
Pim\Bundle\NotificationBundle\PimNotificationBundle
Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle
Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle
Pim\Bundle\UIBundle\PimUIBundle
Pim\Bundle\UserBundle\PimUserBundle
Pim\Bundle\VersioningBundle\PimVersioningBundle
Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
Symfony\Bundle\AsseticBundle\AsseticBundle
Symfony\Bundle\FrameworkBundle\FrameworkBundle
Symfony\Bundle\MonologBundle\MonologBundle
Symfony\Bundle\SecurityBundle\SecurityBundle
Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
Symfony\Bundle\TwigBundle\TwigBundle
Speicher	doctrine/orm
MySQL-Version	mysqlnd 5.0.11-dev - 20120503

**Comment by ekussberg** [comment]
When i upload also a PNG it breaks an image. See attached images.
<img width="1179" alt="screen shot 2017-04-18 at 16 26 00" src="https://cloud.githubusercontent.com/assets/5912520/25135868/d2a78824-2453-11e7-82f6-67f86be79298.png">
<img width="1185" alt="screen shot 2017-04-18 at 16 26 12" src="https://cloud.githubusercontent.com/assets/5912520/25135870/d3534b6e-2453-11e7-9007-5b2be020af4f.png">

**Comment by BatsaxIV** [comment]
Hi @ekussberg,

I think this [PR](https://github.com/akeneo/pim-community-dev/pull/6097) will solve your first problem. Could you try and tell me?

**Comment by mickaelandrieu** [comment]
Hi @ekussberg,

did you try the patch suggested by @BatsaxIV? Can you confirm this fixes your issue?

Regards,

**Comment by SamirBoulil** [comment]
Hello @ekussberg !

Not being able to download an image right after having uploaded it is a known bug. The fix we want to see regarding this button is to hide it when the PIM is in that state.

I'm not sure why the PNG is broken, can you copy/paste the following parameters from your app/config/pim_parameters.yml:
- upload_dir
- archive_dir
- catalog_storage_dir
- tmp_storage_dir

To see if anything is wrong with it ?

**Comment by mickaelandrieu** [comment]
Hello @ekussberg ,

any update regarding this issue? do you want to contribute to a patch?

Mickaël

**Comment by ekussberg** [comment]
Sorry for delay, we have checked it and the error appears when just selecting a file without uploading. After the image is uploaded, i can normally download the file, but preview has problems with PNG and black background.

**Comment by mickaelandrieu** [comment]
Thank you for additional information @ekussberg.

Did you fix it? Do you want to contribute a patch and become part of Akeneo core contributors? :)

Mickaël

**Comment by Doodoune** [comment]
Hi!

After one year without feedback, I close this issue.
Feel free to reopen it if you still have this issue.

Regards,
Elodie
