### ISSUE TITLE
ImmutableValidator has dead code in it

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#6089]
**I'm reporting a Bug**

`public function getTargets()` is a method of the `Constraint` class, not `ConstraintValidator`
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Catalog/Validator/Constraints/ImmutableValidator.php#L64-L67

**Comment by nidup** [comment]
Hi @mathewrapid !

Thank you for opening the issue :tada: 

Don't hesitate to open a pull request on the master to remove this method.

Cheers.
