### ISSUE TITLE
Wrong formating at WYSIWYG attribute

### ISSUE THREAD

**Issue by krafas** [akeneo/pim-community-dev#6101]
After upgrade to the newest 1.7 version we have problem with text formating at wysiwyg editor. The same issue exists in demo (http://demo.akeneo.com/#url=/enrich/product/1101?dataLocale=en_US)

When formating list no bullets and no numbers are shown:
![image](https://cloud.githubusercontent.com/assets/3889275/25316984/06942524-2879-11e7-849c-2e3c4cf1e701.png)

But the code have correct styling:
![image](https://cloud.githubusercontent.com/assets/3889275/25317004/3866a7ac-2879-11e7-8e6b-91392e96ebc8.png)

**Comment by pierallard** [comment]
Hi !

It's a bug introduced by this:
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/UIBundle/Resources/public/less/base/general.less#L53

We have to override this rule in the wysiwyg context, in this file
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/UIBundle/Resources/public/less/lib/summernote.less
to match original browser rules
https://www.w3schools.com/cssref/css_default_values.asp

by adding something like this...
```.note-editable ol { list-style-type: decimal; margin-left: 1em; }
note-editable ol > li { list-style-type: decimal }```

Feel free to do a pull request, it's an easy pick :)

**Comment by pierallard** [comment]
Fixed! Thanks a lot @xElysioN !
