### ISSUE TITLE
HTML title double encoded

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#6106]
**I'm reporting a Bug**

When a SKU contains f.ex. quotes, they are encoded in the HTML title again (V. 1.7.3 CE).

Steps to reproduce:

1. Create a product with quotes in the SKU like `My "Test"`.
2. Edit this product. In the tab title (HTML `<title>`-Tag) you will see `Products My &quot;Test&quot;` instead of the expected `Product My "Test"`

**Comment by mickaelandrieu** [comment]
Hello @Hocdoc,

you're right. This is valid HTML so I'm wondering why is it a bug for you: does some search engine display "&quot;" as it?

I can also confirm the values are stored without encoding in the database.

Thanks for your feedback

**Comment by Hocdoc** [comment]
The title that the *user* sees in his browser tab is `Products My &quot;Test&quot;`.

The title-HTML-tag must be doubble-encoded, maybe something like `Products My &amp;quot;Test&amp;quot;`

**Comment by SamirBoulil** [comment]
Nice catch @Hocdoc ! This is definitely a minor bug. 

I'll label this issue and add it to the github project.

**Comment by mickaelandrieu** [comment]
Indeed, I'm not sure about the best way to fix it, what do you think @SamirBoulil ?

Also, @Hocdoc, do you want to contribute to a patch?

**Comment by Hocdoc** [comment]
I've add an PR #6176; 
but I haven't tested it and I'm not sure if `navTitle.params` should get escaped.

**Comment by mickaelandrieu** [comment]
@Hocdoc thank you for your pull request, we'll review it as soon as possible :)

Mickaël

**Comment by SamirBoulil** [comment]
The fix @Hocdoc provided has been successfully merged in 1.7 !

Thanks everyone for your help !
