### ISSUE TITLE
PHP Fatal error in installation

### ISSUE THREAD

**Issue by prodes** [akeneo/pim-community-dev#6116]
Hi,

I just tried to install the latest version of Akeneo. 
I downloaded the latest version. Unzipped it and runned; 
php app/console pim:installer:check-requirements <-- This was all good
php app/console pim:install --env=prod <-- This is giving a Fatal error 

The last screen output is;
```
Prepare database schema (driver: doctrine/orm)
Dropped database for connection named `akeneo_pim`
Created database for connection named `akeneo_pim`
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
Database schema created successfully!
Nothing to update - your database is already in sync with the current entity metadata.
Create session table
Load jobs for fixtures. (data set: PimInstallerBundle:icecat_demo_dev)
PHP Fatal error:  Declaration of Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\ChannelRepository::findBy(array $criteria, array $orderBy = Array, $limit = NULL, $offset = NULL) must be compatible with Doctrine\Common\Persistence\ObjectRepository::findBy(array $criteria, ?array $orderBy = NULL, $limit = NULL, $offset = NULL) in /Users/jurgenbosch/sites/pim/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ChannelRepository.php on line 19
```

I'm running Apache 2.4.25 on a Macbook Pro with PHP 7.1.

**Comment by Hocdoc** [comment]
Unfortunately the PIM only supports PHP 7.0 at the moment.

But: You can run also the PIM with PHP 7.1 in production with no problems, with just some small changes:
https://github.com/akeneo/pim-community-dev/pull/5613/commits/38c3845d96d1766263dad7316bb81fe8db43b168

I hope these PR gets to the Akeneo releases soon.

**Comment by mickaelandrieu** [comment]
Hello @prodes, thanks for your feedback.

As @Hocdoc said, we don't support PHP 7.0 for 1.7.x release but we accept the contributions which improve this support.

The patch described (which is mine ^^) is available since the latest ``1.7.4`` so you should be able to install your PIM using PHP 7.1 right now.

Regards,

**Comment by NitishChauhan1991** [comment]
HI,
I have change the port 9200 to 80 in parameters.yml but after that i am getting this error: 

In Connection.php line 615:

  <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
  <html><head>
  <title>405 Method Not Allowed</title>
  </head><body>
  <h1>Method Not Allowed</h1>
  <p>The requested method PUT is not allowed for the URL /akeneo_pim_product.
  </p>
  <hr>
  <address>Apache/2.4.29 (Ubuntu) Server at localhost Port 80</address>
  </body></html>


The command terminated with an error code: 405.
Error during PIM installation. The command terminated with an error code: 405.

is anyone can help me in this??

**Comment by prodes** [comment]
Deze mailbox wordt niet gelezen. Excuus voor het ongemak. Kijk op prodes.nl voor meer informatie.

**Comment by NitishChauhan1991** [comment]
> HI,
> I have change the port 9200 to 80 in parameters.yml but after that i am getting this error:
> 
> In Connection.php line 615:
> 
> <title>405 Method Not Allowed</title>
> # Method Not Allowed
> The requested method PUT is not allowed for the URL /akeneo_pim_product.
> 
> Apache/2.4.29 (Ubuntu) Server at localhost Port 80
> The command terminated with an error code: 405.
> Error during PIM installation. The command terminated with an error code: 405.
> 
> is anyone can help me in this??
