### ISSUE TITLE
Group edit triggers 414 Request URI too large with 81 selected (?) products in group

### ISSUE THREAD

**Issue by wimvds** [akeneo/pim-community-dev#6153]
**I'm reporting a Bug**

Expected behavior : When I go to the edit view of a group (via Enrich, Groups, eye icon), I should see the datagrid.

Encountered behavior : When I go to the edit view of a group, I don't see the datagrid. Checking the console, I see that a call to **datagrid/product-group-grid/load** triggers a **414 Request-URI Too Large** error.

Payload of the request is the following : 
`GET /datagrid/product-group-grid/load?locale=en_GB&currentGroup=1&id=1&selection%5B%5D=1583&selection%5B%5D=2546&selection%5B%5D=2547&selection%5B%5D=2548&selection%5B%5D=2549&selection%5B%5D=2550&selection%5B%5D=2551&selection%5B%5D=2552&selection%5B%5D=2553&selection%5B%5D=2554&selection%5B%5D=2555&selection%5B%5D=2556&selection%5B%5D=2557&selection%5B%5D=2558&selection%5B%5D=2559&selection%5B%5D=2560&selection%5B%5D=2561&selection%5B%5D=2562&selection%5B%5D=2563&selection%5B%5D=2564&selection%5B%5D=2565&selection%5B%5D=2566&selection%5B%5D=2567&selection%5B%5D=2568&selection%5B%5D=2569&selection%5B%5D=2570&selection%5B%5D=2571&selection%5B%5D=2572&selection%5B%5D=2573&selection%5B%5D=2574&selection%5B%5D=2575&selection%5B%5D=2576&selection%5B%5D=2577&selection%5B%5D=2578&selection%5B%5D=2579&selection%5B%5D=2580&selection%5B%5D=2581&selection%5B%5D=2582&selection%5B%5D=2583&selection%5B%5D=2584&selection%5B%5D=2585&selection%5B%5D=2586&selection%5B%5D=2587&selection%5B%5D=2588&selection%5B%5D=2589&selection%5B%5D=2590&selection%5B%5D=2591&selection%5B%5D=2611&selection%5B%5D=2880&selection%5B%5D=2881&selection%5B%5D=2882&selection%5B%5D=2883&selection%5B%5D=2884&selection%5B%5D=2885&selection%5B%5D=2886&selection%5B%5D=2887&selection%5B%5D=2936&selection%5B%5D=2937&selection%5B%5D=2938&selection%5B%5D=2939&selection%5B%5D=2940&selection%5B%5D=2941&selection%5B%5D=2942&selection%5B%5D=2943&selection%5B%5D=2944&selection%5B%5D=2945&selection%5B%5D=2946&selection%5B%5D=2947&selection%5B%5D=2948&selection%5B%5D=2949&selection%5B%5D=2950&selection%5B%5D=2951&selection%5B%5D=2952&selection%5B%5D=2953&selection%5B%5D=2954&selection%5B%5D=2955&selection%5B%5D=2956&selection%5B%5D=2958&selection%5B%5D=2959&selection%5B%5D=2960&selection%5B%5D=2961&params%5Blocale%5D=en_GB&params%5BcurrentGroup%5D=1&params%5Bid%5D=1&params%5Bselection%5D%5B%5D=1583&params%5Bselection%5D%5B%5D=2546&params%5Bselection%5D%5B%5D=2547&params%5Bselection%5D%5B%5D=2548&params%5Bselection%5D%5B%5D=2549&params%5Bselection%5D%5B%5D=2550&params%5Bselection%5D%5B%5D=2551&params%5Bselection%5D%5B%5D=2552&params%5Bselection%5D%5B%5D=2553&params%5Bselection%5D%5B%5D=2554&params%5Bselection%5D%5B%5D=2555&params%5Bselection%5D%5B%5D=2556&params%5Bselection%5D%5B%5D=2557&params%5Bselection%5D%5B%5D=2558&params%5Bselection%5D%5B%5D=2559&params%5Bselection%5D%5B%5D=2560&params%5Bselection%5D%5B%5D=2561&params%5Bselection%5D%5B%5D=2562&params%5Bselection%5D%5B%5D=2563&params%5Bselection%5D%5B%5D=2564&params%5Bselection%5D%5B%5D=2565&params%5Bselection%5D%5B%5D=2566&params%5Bselection%5D%5B%5D=2567&params%5Bselection%5D%5B%5D=2568&params%5Bselection%5D%5B%5D=2569&params%5Bselection%5D%5B%5D=2570&params%5Bselection%5D%5B%5D=2571&params%5Bselection%5D%5B%5D=2572&params%5Bselection%5D%5B%5D=2573&params%5Bselection%5D%5B%5D=2574&params%5Bselection%5D%5B%5D=2575&params%5Bselection%5D%5B%5D=2576&params%5Bselection%5D%5B%5D=2577&params%5Bselection%5D%5B%5D=2578&params%5Bselection%5D%5B%5D=2579&params%5Bselection%5D%5B%5D=2580&params%5Bselection%5D%5B%5D=2581&params%5Bselection%5D%5B%5D=2582&params%5Bselection%5D%5B%5D=2583&params%5Bselection%5D%5B%5D=2584&params%5Bselection%5D%5B%5D=2585&params%5Bselection%5D%5B%5D=2586&params%5Bselection%5D%5B%5D=2587&params%5Bselection%5D%5B%5D=2588&params%5Bselection%5D%5B%5D=2589&params%5Bselection%5D%5B%5D=2590&params%5Bselection%5D%5B%5D=2591&params%5Bselection%5D%5B%5D=2611&params%5Bselection%5D%5B%5D=2880&params%5Bselection%5D%5B%5D=2881&params%5Bselection%5D%5B%5D=2882&params%5Bselection%5D%5B%5D=2883&params%5Bselection%5D%5B%5D=2884&params%5Bselection%5D%5B%5D=2885&params%5Bselection%5D%5B%5D=2886&params%5Bselection%5D%5B%5D=2887&params%5Bselection%5D%5B%5D=2936&params%5Bselection%5D%5B%5D=2937&params%5Bselection%5D%5B%5D=2938&params%5Bselection%5D%5B%5D=2939&params%5Bselection%5D%5B%5D=2940&params%5Bselection%5D%5B%5D=2941&params%5Bselection%5D%5B%5D=2942&params%5Bselection%5D%5B%5D=2943&params%5Bselection%5D%5B%5D=2944&params%5Bselection%5D%5B%5D=2945&params%5Bselection%5D%5B%5D=2946&params%5Bselection%5D%5B%5D=2947&params%5Bselection%5D%5B%5D=2948&params%5Bselection%5D%5B%5D=2949&params%5Bselection%5D%5B%5D=2950&params%5Bselection%5D%5B%5D=2951&params%5Bselection%5D%5B%5D=2952&params%5Bselection%5D%5B%5D=2953&params%5Bselection%5D%5B%5D=2954&params%5Bselection%5D%5B%5D=2955&params%5Bselection%5D%5B%5D=2956&params%5Bselection%5D%5B%5D=2958&params%5Bselection%5D%5B%5D=2959&params%5Bselection%5D%5B%5D=2960&params%5Bselection%5D%5B%5D=2961&product-group-grid%5Blocale%5D=en_GB&product-group-grid%5BcurrentGroup%5D=1&product-group-grid%5Bid%5D=1&product-group-grid%5Bselection%5D%5B%5D=1583&product-group-grid%5Bselection%5D%5B%5D=2546&product-group-grid%5Bselection%5D%5B%5D=2547&product-group-grid%5Bselection%5D%5B%5D=2548&product-group-grid%5Bselection%5D%5B%5D=2549&product-group-grid%5Bselection%5D%5B%5D=2550&product-group-grid%5Bselection%5D%5B%5D=2551&product-group-grid%5Bselection%5D%5B%5D=2552&product-group-grid%5Bselection%5D%5B%5D=2553&product-group-grid%5Bselection%5D%5B%5D=2554&product-group-grid%5Bselection%5D%5B%5D=2555&product-group-grid%5Bselection%5D%5B%5D=2556&product-group-grid%5Bselection%5D%5B%5D=2557&product-group-grid%5Bselection%5D%5B%5D=2558&product-group-grid%5Bselection%5D%5B%5D=2559&product-group-grid%5Bselection%5D%5B%5D=2560&product-group-grid%5Bselection%5D%5B%5D=2561&product-group-grid%5Bselection%5D%5B%5D=2562&product-group-grid%5Bselection%5D%5B%5D=2563&product-group-grid%5Bselection%5D%5B%5D=2564&product-group-grid%5Bselection%5D%5B%5D=2565&product-group-grid%5Bselection%5D%5B%5D=2566&product-group-grid%5Bselection%5D%5B%5D=2567&product-group-grid%5Bselection%5D%5B%5D=2568&product-group-grid%5Bselection%5D%5B%5D=2569&product-group-grid%5Bselection%5D%5B%5D=2570&product-group-grid%5Bselection%5D%5B%5D=2571&product-group-grid%5Bselection%5D%5B%5D=2572&product-group-grid%5Bselection%5D%5B%5D=2573&product-group-grid%5Bselection%5D%5B%5D=2574&product-group-grid%5Bselection%5D%5B%5D=2575&product-group-grid%5Bselection%5D%5B%5D=2576&product-group-grid%5Bselection%5D%5B%5D=2577&product-group-grid%5Bselection%5D%5B%5D=2578&product-group-grid%5Bselection%5D%5B%5D=2579&product-group-grid%5Bselection%5D%5B%5D=2580&product-group-grid%5Bselection%5D%5B%5D=2581&product-group-grid%5Bselection%5D%5B%5D=2582&product-group-grid%5Bselection%5D%5B%5D=2583&product-group-grid%5Bselection%5D%5B%5D=2584&product-group-grid%5Bselection%5D%5B%5D=2585&product-group-grid%5Bselection%5D%5B%5D=2586&product-group-grid%5Bselection%5D%5B%5D=2587&product-group-grid%5Bselection%5D%5B%5D=2588&product-group-grid%5Bselection%5D%5B%5D=2589&product-group-grid%5Bselection%5D%5B%5D=2590&product-group-grid%5Bselection%5D%5B%5D=2591&product-group-grid%5Bselection%5D%5B%5D=2611&product-group-grid%5Bselection%5D%5B%5D=2880&product-group-grid%5Bselection%5D%5B%5D=2881&product-group-grid%5Bselection%5D%5B%5D=2882&product-group-grid%5Bselection%5D%5B%5D=2883&product-group-grid%5Bselection%5D%5B%5D=2884&product-group-grid%5Bselection%5D%5B%5D=2885&product-group-grid%5Bselection%5D%5B%5D=2886&product-group-grid%5Bselection%5D%5B%5D=2887&product-group-grid%5Bselection%5D%5B%5D=2936&product-group-grid%5Bselection%5D%5B%5D=2937&product-group-grid%5Bselection%5D%5B%5D=2938&product-group-grid%5Bselection%5D%5B%5D=2939&product-group-grid%5Bselection%5D%5B%5D=2940&product-group-grid%5Bselection%5D%5B%5D=2941&product-group-grid%5Bselection%5D%5B%5D=2942&product-group-grid%5Bselection%5D%5B%5D=2943&product-group-grid%5Bselection%5D%5B%5D=2944&product-group-grid%5Bselection%5D%5B%5D=2945&product-group-grid%5Bselection%5D%5B%5D=2946&product-group-grid%5Bselection%5D%5B%5D=2947&product-group-grid%5Bselection%5D%5B%5D=2948&product-group-grid%5Bselection%5D%5B%5D=2949&product-group-grid%5Bselection%5D%5B%5D=2950&product-group-grid%5Bselection%5D%5B%5D=2951&product-group-grid%5Bselection%5D%5B%5D=2952&product-group-grid%5Bselection%5D%5B%5D=2953&product-group-grid%5Bselection%5D%5B%5D=2954&product-group-grid%5Bselection%5D%5B%5D=2955&product-group-grid%5Bselection%5D%5B%5D=2956&product-group-grid%5Bselection%5D%5B%5D=2958&product-group-grid%5Bselection%5D%5B%5D=2959&product-group-grid%5Bselection%5D%5B%5D=2960&product-group-grid%5Bselection%5D%5B%5D=2961 HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
Accept: */*
Accept-Language: en-US,en;q=0.8,nl-BE;q=0.5,fr;q=0.3
Accept-Encoding: gzip, deflate
X-CSRF-Header: 1
X-Requested-With: XMLHttpRequest
Referer: http://localhost/system_info
Cookie: BAPID=f1il87d4gcbjjdtuqh6go4pcq4
Connection: keep-alive`

There seems to be a lot of duplication in this request, all IDs (81 in this case) are into the URI 3 times in separate parameters?

I'm not exactly sure where this should be fixed due to all AJAXy stuff...

[akeneo-pim-system-info_2017-05-10_14_47.txt](https://github.com/akeneo/pim-community-dev/files/989769/akeneo-pim-system-info_2017-05-10_14_47.txt)

**Comment by mickaelandrieu** [comment]
Hello @wimvds,

thank you for your feedback but even with icecat catalogue I can't reproduce your issue. Maybe did I misunderstood your instructions? I'm using the demo website (http://demo.akeneo.com/enrich/group/promotion/edit#url=/enrich/group/promotion/edit|g/i=1&p=25&s%5Bin_group%5D=1&f%5Bscope%5D%5Bvalue%5D=ecommerce&t=product-group-grid)

![issue](https://cloud.githubusercontent.com/assets/1247388/26060724/3166cbd0-3986-11e7-8ce0-94b3c69b716a.PNG)

Don't hesitate to use the demo website (credentials are admin/admin) to help us reproduce the bug you report.

Thank you

**Comment by wimvds** [comment]
I created a group called "Primeur" on the demo site and added products to it until the issue occurred.

http://demo.akeneo.com/#url=/enrich/group/primeur/edit

AFAICT It is due to the load call using GET parameters, which are limited (to around 8Kb - some browsers might already give up on less, regardless of server settings). Changing that to a POST could probably help as a quickfix, but there's still a lot of duplication of IDs in the load call that might need some looking into (I'm not that familiar with Akeneo yet, just started using it). If I have some spare time later this week, I'll try to see if that helps.

**Comment by LaurentPetard** [comment]
Hello, 

It will be fixed with the PR #6183 

For the same reason as the bug on the variant group page, the parameters `selection` are uselessly included in the URI used to load the Datagrid content.

**Comment by wimvds** [comment]
:+1: 

Just applied the patch on my dev environment, and it does indeed fix the problem.

**Comment by mickaelandrieu** [comment]
As the pull request have been merged and as @wimvds confirm it works as expected, I close this issue.

Thanks for report @wimvds and thank for the fix @LaurentPetard !

**Comment by LaureBro** [comment]
Hello @wimvds,

A quick message to let you know that the patch is available in the 1.7.5 released last Friday.

Thanks!
