### ISSUE TITLE
AkeneoBatchBundle => BatchCommand: JobInstance class is hardcoded

### ISSUE THREAD

**Issue by danielsan80** [akeneo/pim-community-dev#6159]
**I'm reporting a Bug**

[akeneo-pim-system-info_2017-05-12_11-51.txt](https://github.com/akeneo/pim-community-dev/files/995685/akeneo-pim-system-info_2017-05-12_11-51.txt)

This is not properly a bug but a little incoherence in how the code is written.
Because of this incoherence you cannot extends the JobInstance model. In fact I could... but I should completely rewrite the BatchCommand.

In the class Akeneo\Bundle\BatchBundle\Command\BatchCommand:82 you can see:

```
    $jobInstance = $this
        ->getJobManager()
        ->getRepository('Akeneo\Component\Batch\Model\JobInstance')
        ->findOneByCode($code);
```
As you can see the JobInstance FQCN is hardcoded. As I can see in other files of Akeneo, it should be written in this way:

```
    $jobInstance = $this
        ->getJobManager()
        ->getRepository(
            $this
                ->getContainer()
                ->getParameter('akeneo_batch.entity.job_instance.class')
        )
        ->findOneByCode($code);
```

so you can simply redefine the akeneo_batch.entity.job_instance.class parameter with you JobInstance class in your extension bundles.

**Comment by SamirBoulil** [comment]
See https://github.com/akeneo/pim-community-dev/pull/6161

**Comment by SamirBoulil** [comment]
Hello, Thank you for your bug report and your contribution. The fix you provided has been merged ! :tada:

Don't forget to claim your badge "Core contributor" on https://badger.akeneo.com (if you don't have it ^^).
