### ISSUE TITLE
API: Upload media file without product association?

### ISSUE THREAD

**Issue by pardahlman** [akeneo/pim-community-dev#6166]
I'm using the API to seed an empty Akeneo PIM instance with relevant products. All products we create have an image attribute, the logotype. Multiple products share the same logotype. I'm guessing this is a pretty common scenario.

The way I read the documentation a media file can only be uploaded in the context of a `product`. That is, the file needs to be related to an existing product when it is uploaded.

I've tried to associate an existing media file to a new product (as a value in the `values` array) and that works. I assume this is intentional for scenarios just like mine 🙂 .

Based on my understanding, I need to perform the following steps in order to associate multiple products to the same media file:

1. Create a product not associated with media file
2. Upload image associated with the product
3. Query the product endpoint for that product or media-files endpoint to get the `code` of the uploaded media file
4. Create the rest of the products associated with the media file and supply the media-file's `code` in the `values` array

It would be even more complicated if we had multiple media files that we wanted to share between multiple products.

Since a media file can be associated with multiple products, I think it would make sense if the media file could be uploaded as a separate entity that later can be associate with products. Semantically, it also makes more sense since the media file is equally "owned" by all products sharing the image, but it is created associated with one image.

The other thing I find cumbersome is the fact that it is the PIM that creates the media files code, and there the only way for me is to query the API to hold of the newly created media file (step 3 above). This is due to the fact that there is no response body when the media file is created.

It would simplify the flow if it was possible to get something like this:

1. Upload media file(s), API return a successful status code (201) and the code of the created media file
2. Create products and provide the desired media file(s) in the `values` array.

Any thoughts on this? Is there an easier way to achieve what I'm trying to do?

**Comment by ahocquard** [comment]
Hello @pardahlman,

Actually, the API already returns the URL to get the information of the media in the header Location of the response.
It's the complete URL `http://akeneo.com/api/rest/v1/media-files/code, not only the code though.

I think it's easier to request that URL in order to know the code that requesting the URL of the product and then parsing the Product values (because you should know the attribute name, etc).

I've seen that it's not documented. All URI creating/updating one single resource (not available on endpoint updating multiple resources) returns a `Location` header with the URL to the resource. 

On the fact that you can associate the same media file to multiple products, let me check with the team if it's on purpose or not.
I think it should be associated with one product at least to avoid orphan media files. That's why you could not create a media file alone.
And so, it's maybe related to you another ticket https://github.com/akeneo/pim-community-dev/issues/6167 about the deletion of media files.

**Comment by ahocquard** [comment]
Hello @pardahlman,

Some news after talking with the team.
It's normal to be able to associate the same media file to several products.

Your method is the good one.
We are well aware that is not very convenient and we are thinking about a solution to associate multiple products/locales to one file.

Do note that if your are associating the same media file to several products by calling the media file endpoint several times, you will get multiple media file codes (one for each product). But the file will be stored only one time (we use hash to know if the file already exist in the storage).

**Comment by pardahlman** [comment]
Based on @nidup's [comment](https://github.com/akeneo/pim-community-dev/issues/6167#issuecomment-301405137) in #6167 

> In Enterprise Edition, we can restore the previous version of a product and doing this, we can re-use a media not used anymore

Media files may exist without being associated with to any product in particular. It is excellent news that your are thinking about this area, and it sounds like you have a solution in mind that will make things easier to work with files in general. However, if it is possible for the files to exist without any association, I think it would make sense that it would be able to upload files without association as well.

IMHO, it would be easiest if the API supported basic CRUD for the media files as "stand alone resources". It would make the API more stream lined, as a you would work with a media file like other resources in the API. For example: If I want to introduce a new attribute, I first create the attribute and then create/update the product to be associated with the attribute. I would like to have the same ability for media files: first upload/create the media file and then create/update product(s) to be associated with it.

> We discussed several times about the way to handle the cleanup of old media with the team

A delete on a certain media file would remove it (and perhaps, based on your comment here, remove the actual file if it is the only "media file" associated with that file). Problem solved 😉 

I hope this makes sense!

**Comment by pardahlman** [comment]
@ahocquard I wanted to verified what you said

> Do note that if your are associating the same media file to several products by calling the media file endpoint several times, you will get multiple media file codes (one for each product). But the file will be stored only one time (we use hash to know if the file already exist in the storage).

But it looks like it is saves one actual file per media file, even though they where uploaded from the exact same file, uploaded in the exact same way. Not a big issue for me, just thought I'd tell you,
