### ISSUE TITLE
Update from 1.6 to 1.7 failed: Attribute::$attributeType

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#6188]
As every year, I try to update to the latest PIM version 1.7.

I've done all the steps from UPGRADE-1.7.md, deactivated all custom bundles and cleared the cache.

When I want to login to the PIM 1.7 I will get this error message:

Fatal error: Uncaught ReflectionException: Property Pim\Bundle\CatalogBundle\Entity\Attribute::$attributeType does not exist in /Users/bernhardberger/holzweg/eglo/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php on line 82

Do you have any hint where the problem is? 
I've found some changes attributeType => type in the dev commit history, but nothing that helps me.

**Comment by ahocquard** [comment]
Hello @Hocdoc,

Could you restart your Apache ? It's maybe due to APCU cache used by Doctrine.

**Comment by Hocdoc** [comment]
Thank you very much, after a simple Apache restart it works. :-)

**Comment by SaaqibBhat** [comment]
Hello @hocdoc ...could you please share the steps you followed while upgrading from 1.6 to 1.7..that would be helpful..
