### ISSUE TITLE
Completeness taking too long on save

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#6202]
**I'm reporting a Bug**

CE 1.6.6

Product saving takes quite a lot of time and specifically "completeness computation" takes around 12.5 sec on an average, as shown in the attached screenshot.

<img width="774" alt="screen shot 2017-05-22 at 3 27 10 pm" src="https://cloud.githubusercontent.com/assets/4486133/26313114/e38a11b6-3f1a-11e7-8c6f-b5ade250b36f.png">

**Comment by LaureBro** [comment]
Hello @wakqasahmed, 
Thanks for reporting this. 
This issue is similar to #3771, and the good news is that we are currently working on a fix (from 1.5 version for ODM and ORM). 
I'll keep you updated, our internal ticket reference is PIM-6429.
Thanks!

**Comment by ahocquard** [comment]
Hello @wakqasahmed,

Unfortunately, I don't think that the fix on the completeness widget will resolve your problem.

1. Could you tell me:
- your volumetry
- orm/mongo

2. Also, did you take a look at the status of the running request ? Do you have any row lock or something like that that could explain that time.

The best thing to do would be to isolate the request causing the problem and then try to understand why it takes so much time.

3. Did you have that problem in a previous version or is it since a patch ?

Thanks.

**Comment by pierallard** [comment]
Or, to answer the first question, just follow the Issue guidelines 
`For version >= 1.4, please go to "System > system info", download the text report and attach it to the issue`
Thanks !

**Comment by wakqasahmed** [comment]
[akeneo-pim-system-info_2017-05-22_16-51.txt](https://github.com/akeneo/pim-community-dev/files/1025485/akeneo-pim-system-info_2017-05-22_16-51.txt)

**Comment by ahocquard** [comment]
@wakqasahmed 

1.6.16 have been tagged today with the fix on the completeness for the widget. 

After thinking about your problem, **maybe** this fix it will resolve it. The long insert queries are maybe just locked by the request launched by the widget that is taking too much time, and locking the rows. Can you apply that fix and tell me if it resolves your problem ?

**Comment by wakqasahmed** [comment]
sure, i will apply this patch in a while and comment back soon.

**Comment by momoss** [comment]
Hi @wakqasahmed,

Did you have time to apply the patch ?
Is there any changes?

Thanks!

**Comment by ahocquard** [comment]
@wakqasahmed , a PR has been done on the calculation of the completeness. Maybe it will resolve your problem because it reduces the level of locking of the table in SQL requests to calculate completeness.

**Comment by wakqasahmed** [comment]
@ahocquard Fortunately, i didn't get that long time in inserting completeness afterwards (it was for half an hour and restarting apache server did the trick). However, i have applied the patch to speed up widget opening process.

Thanks
