### ISSUE TITLE
pim:install should take database parameters

### ISSUE THREAD

**Issue by QwertyZW** [akeneo/pim-community-dev#6221]
This is a developer/sysadmin feature request.

let the app/console pim:install command take database parameters.

See https://github.com/akeneo/pim-docs/issues/607

**Comment by mickaelandrieu** [comment]
Hello,

we already have a way to set database parameters at first installation using environment variables, I'm not sure this is documented but you can retrieve them in the [composer.json](https://github.com/akeneo/pim-community-dev/blob/master/composer.json#L133)

If exists, you need to delete ``app/config/parameters.yml`` file first.

```
PIM_DATABASE_HOST=127.0.0.1
...
app/console pim:install --force
```

Let me know if you need help, I won't let you down :-)

**Comment by QwertyZW** [comment]
I don't know how I feel about deleting `app/config/parameters.yml` right now

**Comment by mickaelandrieu** [comment]
It's an autogenerated file :)

**Comment by QwertyZW** [comment]
Brilliant. Thanks.

**Comment by mickaelandrieu** [comment]
Sarcasm ? :)

Let me know if it's ok for your needs :)

Mickaël

**Comment by QwertyZW** [comment]
Nope, not being sarcastic. 10/10 Genuine :)

I'm definitely grateful  for the information regarding the environment variables, and that is probably enough for most cases. But I think the `pim:install` command should definitely mention this, along with deleting the .yml file

```
root@ebd12080e6b1:/var/www/pim-community-standard# php5.6 app/console help pim:install 
Usage:
  pim:install [options]

Options:
      --force              Force installation
  -h, --help               Display this help message
  -q, --quiet              Do not output any message
  -V, --version            Display this application version
      --ansi               Force ANSI output
      --no-ansi            Disable ANSI output
  -n, --no-interaction     Do not ask any interactive question
  -s, --shell              Launch the shell.
      --process-isolation  Launch commands from shell as a separate process.
  -e, --env=ENV            The Environment name. [default: "dev"]
      --no-debug           Switches off debug mode.
  -v|vv|vvv, --verbose     Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Akeneo PIM Application Installer.
```

Feel free to close this issue if you see no reason for keeping it around.

**Comment by mickaelandrieu** [comment]
No hurry here, we want to help you :)

Should we improve the command help message, docs or both of them? If you want to make a pull request go for it: you can win a Contributor  badge on your Community Badger platform :D

**Comment by QwertyZW** [comment]
Sounds good

**Comment by mickaelandrieu** [comment]
@QwertyZW great! Let me know if you need help, I'm waiting for your contribution 🎆 

Mickaël

**Comment by QwertyZW** [comment]
It seems that the root issue with this is that both `https://download.akeneo.com/pim-community-standard-v1.7-latest-icecat.tar.gz`
`https://download.akeneo.com/pim-community-standard-v1.7-latest.tar.gz` are distributed with a parameters.yml.

Fix that issue and the composer install command should take care of taking in the required database parameters.

I think this issue can be closed now and a new one opened for what I just mentioned
