### ISSUE TITLE
Q: Migrate to 1.7 - Bootstrap CSS classes

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#6224]
**I'm asking a Question**

We are migrating our PIM from 1.6 to 1.7.

We have many custom pages which use the Bootstrap 2.
I've found the [Akeneo Styleguide](https://docs.akeneo.com/1.7/styleguide/index.php), but it's still unclear for me how we can migrate our pages to 1.7:

* Akeneo 1.7 doesn't use Bootstrap 2 anymore. Is this correct?
* Are there CSS Grid classes (like `container-fluid`..., not like `AknGrid` )?
  Should I rewrite basic CSS framework classes like grids myself?
* Can I add Bootstrap 2 for our pages and use it together with the BEM classes from Akeneo?

**Comment by pierallard** [comment]
Hi @Hocdoc !

You're right, in 1.7, we removed 90% of the bootsrap v2.3.
We implemented a BEM methodology in this version.

I will answer your questions:

- Yes. We just keep some CSS modules like "modal" or "tabs".
- There is no more "global" classes like "container-fluid" or something like this. All is "block / elements / modifiers". If you want to create a new block, you can easily follow the other ones to create your new behavior if no one exists.
- You can add Bootstrap 2 for your pages, but I can not assure you there will be no conflicts...

My turn ; can you give me a list of all the blocks you need ? It's always interesting to know what integrators added. If your modules are interesting and you think it can re-usable, don't hesitate to create a pull request on PIM + doc to add it :)

Pierre

**Comment by Hocdoc** [comment]
Thanks for your helpful feedback.

I see the advantages of the BEM methodology and like the small CSS files ;-) but it comes with a price. Maybe it would be better to use a popular, tested CSS framework like Bootstrap that most developer know as a base and than add your own BAM CSS classes on top of it.

Unfortunately adding Bootstrap 2 directly produce too many conflicts with the Akeneo CSS, so we manually adapt our old CSS classes. This was the most time consuming part of our Akeneo 1.6->1.7 migration. 

On the other side our custom pages share now much more the look&feel from the Akeneo pages. :-)

**Comment by pierallard** [comment]
@Hocdoc we discuss a long time to the strategy to adapt in this case. The fact is bootstrap is very famous framework but had disadvantages:
- it have no consistent methology like BEM
- it's very complete but too complete for our use case
- last but not least, Bootstrap is very cool to begin easily a project quickly. But in a certain maturity, you need your proper classes.

Best regards ;)
