### ISSUE TITLE
Change version in package.json file

### ISSUE THREAD

**Issue by R4ntanplan** [akeneo/pim-community-dev#6228]
**I'm asking a Question**

Hi,

We use package version for internal use to know which version of akeneo are installed. 
package.json version  is not updated or it's not the good meta for knowing quickly which version is installed ?

Thanks for showing me the right way.

**Comment by willy-ahva** [comment]
Hi @R4ntanplan !

In fact the purpose the package.json file is to manage js dependencies. It's not a reliable information to know which version of the PIM you are using. By the way, sorry for the inconvenience, we forgot to update it.
How do you want to use this information ? When you are logged you can see that the version is written at the bottom of the PIM and if your version is not up to date, you will have the information here.
We have a symfony service which can help you to get this `pim_catalog.version_provider` https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/CatalogBundle/Resources/config/versions.yml#L6 or this class https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/CatalogBundle/Version.php

These classes are reliable :)

Regards,
Willy

**Comment by momoss** [comment]
Hi @R4ntanplan,

Did you find answers to your questions?
If so, can we close this issue?

Thanks!

**Comment by pierallard** [comment]
No answers, I close the ticket, feel free to reopen it!
