### ISSUE TITLE
Field price-currency on channel

### ISSUE THREAD

**Issue by mauriau** [akeneo/pim-community-dev#6231]
Hi !
I got a channel which had the USD currency and EU. 
Few days later I delete the USD currency from my channel. But my products alway have the price-USD field  with them value.
So I delete the value. But the price-usd  field is always on my channel ! I want to remove it !
In prod I'm in 1.6.3. So I apply the last patch in my local environnment, but the  price-USD field is alway on my products !
Then, when I creat a new product, the price-USD field is display too.
So I think there is a bug.

[akeneo-pim-system-info_prod_2017-05-30_17_38.txt](https://github.com/akeneo/pim-community-dev/files/1044315/akeneo-pim-system-info_prod_2017-05-30_17_38.txt)

[akeneo-pim-system-info_local_2017-06-01_11_46.txt](https://github.com/akeneo/pim-community-dev/files/1044317/akeneo-pim-system-info_local_2017-06-01_11_46.txt)

**Comment by willy-ahva** [comment]
Hi Mauriau !

What you describe is a known behavior. When you remove the currency from your channel, the field is still visible but the completeness will not take it in account.
If you want to remove the field SD from your price, you'll need to disable the currency from the currency menu. It will remove the currency in all your channels.

Maybe a last thing, you can try to export, update and reimport your products removing all USD prices from your products.

Regards,
Willy

**Comment by mauriau** [comment]
Thx Willy for  answers.
In fact, I got an other channel which use the currency, so I can't remove the currency for all channel.
And I have already try to export, remove the column and reimport. It's only reset the values.

My client, dont want to display this field for this channel and for his users. 
May we have to overwrite the js/css to hidd this but, the field will appear at the export, so we again must have to overwrite the export to hid the field.

Do you think there is an other way to do this ?

Regards,
Maxime.

**Comment by damien-carcel** [comment]
Hello Maxime.

Indeed, I think you don't have the choice but to do a customization (or even a contribution 😉) on product export and PEF.

For export, you would have to check which locales are activated on the channel, and  remove the column corresponding to the non-activated locale.

For PEF, I guess you could override this form: https://github.com/akeneo/pim-community-dev/blob/1.6/src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/price-collection-field.js#L28
By pushing the amount and currency only if the currency is activated (this implies, of course, to get the list of activated currency for the channel).

Regards,
Damien

**Comment by mauriau** [comment]
Hi Damien,

Thx for the answers and the solutions to solve the problem.
For information, my mate, said me, there is this problem on others versions, 1.5, 1.7.

In this case, we said to the client, what you said we can do.

**Comment by damien-carcel** [comment]
Yes indeed, it currently impacts all the versions. This is something we will eventually handle in a coming version, but it has not yet been prioritize 😞 (and that's why if you can/have time to contribute on it, it would be gladly appreciated 😉).

I'll let you close the issue if you have the answers you wanted (feel free of course to re-open it if needed, or keep it open if you have other questions 😃).

Regards,
Damien.
