### ISSUE TITLE
[Community] Automatically check for CLA agreement in pull requests

### ISSUE THREAD

**Issue by mickaelandrieu** [akeneo/pim-community-dev#6235]
Hello,

as you may know, every contribution on PIM community dev and standard repositories from external contributors can't be accepted if they didn't sign our [Contributor License Agreement](https://www.akeneo.com/contributor-license-agreement/).

We need it because the code is shared between Community and Enterprise editions.

Some weeks ago, I've tested [cla-assistant](https://github.com/cla-assistant). Looking at the legal use of our data, we have decided with @BitOne that we can use it only in self-hosted.

So we need to host, install and setup cla-assistant for both ``pim-community-dev`` and ``pim-community-standard`` repositories **and** re-import the actual people who have already signed the CLA.

Demo: https://github.com/mickaelandrieu/test-cla-assistant/pull/1

**Comment by jmleroux** [comment]
Done with a custom integration
