### ISSUE TITLE
Akeneo 1.7.4 [Internal Server Error] when deleting channels

### ISSUE THREAD

**Issue by ljseals** [akeneo/pim-community-dev#6238]
Akeneo will not allow to delete all the channels and will give an internal server error. You must create a channel in order to delete it. God bless you!

**Comment by BatsaxIV** [comment]
You can't use the PIM without a channel, it's required by basic function (completeness, export...).

I guess the error message when deleting the last channel is not clear enough, is that what bothers you?

**Comment by ljseals** [comment]
Yes, it should not read internal server error, which speaks to somthing being wrong with your server instead of say One channel must remain or Akeneo needs at least one channel. God bless you. I will close this comment.
