### ISSUE TITLE
Create Variant Group, Popup fields alignment is not proper

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#6241]
**I'm reporting a Bug**

Found on demo.akeneo.com (Version	1.7.5)

Steps to reproduce:

Goto Enrich > Variant Groups > Create Variant Group

This is what you are going to see.

<img width="1278" alt="screen shot 2017-06-02 at 6 10 59 pm" src="https://cloud.githubusercontent.com/assets/4486133/26729696/74329d12-47bf-11e7-935c-8d68942cd5d3.png">

<img width="1276" alt="screen shot 2017-06-02 at 6 27 57 pm" src="https://cloud.githubusercontent.com/assets/4486133/26731129/1cc38302-47c4-11e7-81d3-5c23a24314f0.png">

**Proposed Solution:**
Changing width:auto to width:100% does the trick. Though i couldn't find where form-inline css class was written in the codebase.

<img width="1275" alt="screen shot 2017-06-02 at 6 49 39 pm" src="https://cloud.githubusercontent.com/assets/4486133/26731191/48a485de-47c4-11e7-8b9b-4fc9b910c0af.png">

**Comment by LaureBro** [comment]
Hello @wakqasahmed, what is your browser and are you using a Mac or PC?
I cannot reproduce this issue on my side :( it's displayed fine on my screen: 
![screenshotdemo](https://cloud.githubusercontent.com/assets/13367999/26731488/8daffc9a-47b4-11e7-812d-c19603403e33.png)
Thanks!

**Comment by wakqasahmed** [comment]
Oh! cool. I understand its because i opened **Chrome Canary** for some reason. Looks like its because of that unstanble chrome version.

Closing it. Thanks

**Comment by LaureBro** [comment]
Ok thanks for letting me know!
