### ISSUE TITLE
Changing Category tree of a channel doesn't effect export

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#6256]
**I'm reporting a Bug**

Verified on demo.akeneo.com v1.7.5

Logically, product export should export the product if the category is selected of Export Profile Channel.

If you change the category tree of the channel and then export the product it still looks for the old category tree, if the old category tree value is not selected in the product it doesn't export. No matter, if the newly selected category tree (of the channel) value is selected.

**So, in essence, changing category tree of a channel doesn't effect on product export.**

Steps:

1) Export a product by identifier from product export profile (it will export 1 product)
2) Now, Change the category tree of the channel
3) Goto product export profile
4) Select the value of the category (of step 2)
5) Unselect all the values of the category (old category tree of the channel)
6) Export the product by identifier again (it will not export the product, but it should)

Let me know if you have any query.

**Comment by damien-carcel** [comment]
Hello @wakqasahmed and thanks for raising this issue.

I can reproduce it on my machine too, but I think it is more a misunderstanding of how the category trees work with the channels 😉.

When you select some categories in the product export builder, you see only the categories from the tree that is set in the channel. So, in the case of `demo.akeneo.com`, if, for example, you switch the `mobile` channel from `master` tree to `sales` tree, then in the export builder, you can see only the categories from the `sales` tree.

If I do not customize the `Categories` field in the export builder, keeping the option `All products`, then I can export my product as before (as my product is categorized in the `master` tree, as long it is at least in one category, whatever the tree, it can be exported).

But if I select categories from the `sales` tree (even all of them), then my product is not exported, and it is normal as it is not categorized in this tree. If I add my product in one of the categories selected in the export builder, then I can export my product again.

I hope this can solve/explain your problem. Let me know if it is the case, or if I just completely misunderstood your issue.

Regards,
Damien.

**Comment by wakqasahmed** [comment]
Ah! definitely it was my ignorance. Saved the day!

It would have been nice, if there was a akeneo short video course to explain all the basics. Just before i felt i was advancing in akeneo customizations, this basic miss was about to hit me hard.

Thanks pal!
