### ISSUE TITLE
API: Problem with slashes in identifiers

### ISSUE THREAD

**Issue by DavidFeller** [akeneo/pim-community-dev#6264]
Hi there, 

I have a small problem with the getProduct-method of the new api. I imported all products from an old magento instance and used magento's sku as the identifier. Unfortunately some identifiers include special characters like slashes ("/"). Now, whenever I try to get the product information of one of these products I get an error 404 because the identifier is interpreted as an uri. Is there any workaround that allows me to e.g. url_encode the identifier? Changing the identifier is not an option because it might affect my export jobs.

PS: This issue is only meant to be a reminder. I already discussed this problem with @ahocquard on Slack.

**Comment by damien-carcel** [comment]
Hello @DavidFeller and thanks for raising this issue.

For other people who could have the same problem and end up on this issue, I will reproduce @ahocquard answer here:

> It’s a known problem. At this moment, you can’t, Symfony does not allow “/” in a placeholder by default, except if you configure it explicitly as an allowed character.
> 
> The second problem is, even if we accept “/” by configuring it, it will not accept “/” at the end of the identifier. The Symfony router deletes it automatically. For example, “products/my_id/” is transformed as “/products/my_id” by the Symfony Router. Then, depending if “my_id” is an existing product or not, you can get a 404 or a wrong product :wink:
> 
> The best solution would be to encode slash characters by a custom code. It means that you should encode it on the client side too.

As @ahocquard  said, we need to discuss with the team what is the best solution :wink:.

Again, thanks for raising the issue.

Regards,
Damien

**Comment by ahocquard** [comment]
Hello,

This PR fix the problem.

https://github.com/akeneo/pim-community-dev/pull/8258

Actually, it works with every cases ("/" at the start, middle or end of the string).

Therefore, I close the ticket, don't hesitate to re-open it if the problem still occurs after applying the patch containing the fix.

Regards,
Alexandre
