### ISSUE TITLE
PHP version incompatibility

### ISSUE THREAD

**Issue by bOnepain** [akeneo/pim-community-dev#6273]
Hello,
I can't figure out if I missed something while builder my stack: I installed PHP 5.6.30 but when I run php app/console c:c I get the following warning (I'm on branch master)

> akeneo@akeneo_php5:~/pim$ php app/console c:c
PHP Warning:  Unsupported declare 'strict_types' in /home/akeneo/pim/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19
PHP Stack trace:
PHP   1. {main}() /home/akeneo/pim/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/akeneo/pim/app/console:29
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/akeneo/pim/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:119
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/akeneo/pim/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/akeneo/pim/app/bootstrap.php.cache:2451
PHP   6. Symfony\Component\HttpKernel\Kernel->buildContainer() /home/akeneo/pim/app/bootstrap.php.cache:2672
PHP   7. Symfony\Component\HttpKernel\Kernel->getContainerBuilder() /home/akeneo/pim/app/bootstrap.php.cache:2720
PHP   8. class_exists() /home/akeneo/pim/app/bootstrap.php.cache:2750
PHP   9. spl_autoload_call() /home/akeneo/pim/app/bootstrap.php.cache:2750
PHP  10. Symfony\Component\Debug\DebugClassLoader->loadClass() /home/akeneo/pim/app/bootstrap.php.cache:0
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home/akeneo/pim/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 97
PHP Stack trace:
PHP   1. {main}() /home/akeneo/pim/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/akeneo/pim/app/console:29
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/akeneo/pim/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:119
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/akeneo/pim/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/akeneo/pim/app/bootstrap.php.cache:2451
PHP   6. Symfony\Component\HttpKernel\Kernel->buildContainer() /home/akeneo/pim/app/bootstrap.php.cache:2672
PHP   7. Symfony\Component\HttpKernel\Kernel->getContainerBuilder() /home/akeneo/pim/app/bootstrap.php.cache:2720
PHP   8. class_exists() /home/akeneo/pim/app/bootstrap.php.cache:2750
PHP   9. spl_autoload_call() /home/akeneo/pim/app/bootstrap.php.cache:2750
PHP  10. Symfony\Component\Debug\DebugClassLoader->loadClass() /home/akeneo/pim/app/bootstrap.php.cache:0

Looking at ocramiux proxy-manager composer.json, we can see it requires php7 while the pim-community-dev composer.json specifies php >= 5.6
I assume we should update the minimum requirements for php, and need to upgrade php version on our server ?

**Comment by damien-carcel** [comment]
What version of the PIM are you using? 1.7 or master branch?

**Comment by bOnepain** [comment]
Hello 

master branch

Regards

**Comment by jmleroux** [comment]
Not necessarily. The PIM requires `"ocramius/proxy-manager": "1.0.2|2.0.4"` and you should have the 1.0.2 version with php5.6. So the real question is why did you end up with with the 2.0.4 version.
Did you update composer after installing php5.6?

**Comment by damien-carcel** [comment]
Hello again @bOnepain .

Indeed, it "should" work, because of the double version. But we are in the process to set PHP 7.1 as the minimal version for the master branch, and we are already only working with PHP 7.x since a few weeks for this branch.

Now that we merged our new storage, you need PHP 7.x, MySQL 5.7 and Elasticsearch 5.x (we currently work with 5.2, and should recommend 5.4 very soon). To undestand why this new storage, I recommend you to read our posts on medium.com:
- https://medium.com/akeneo-labs/story-of-storage-9dbc27090de0
- https://medium.com/akeneo-labs/single-product-storage-28d92f35cbd7
- https://medium.com/akeneo-labs/re-building-the-storage-from-the-ground-up-d857bf497c32

Regards,
Damien.

**Comment by bOnepain** [comment]
Mea culpa: I ran composer install from the wrong container (with PHP7). 

Sorry for the disturbance
