### ISSUE TITLE
Selecting new Language

### ISSUE THREAD

**Issue by objecta** [akeneo/pim-community-dev#6287]
I have translated Danish 100% now and I have updated my PIM test site running 1.7.5. I have found a da.js file in the script folder, so I believe that the danish translated texts is installed on my site.

When I try to select the Danish language in System->Configuration in the Localization tab it's no showing in the list of possible languages.

Do I need to configure my installation somehow to include the new Danish translation?

Best regards
Klaus E. Frederiksen
Objecta Data
Denmark.

**Comment by pierallard** [comment]
Hi objecta! Sorry for the delay, these latests days were very busy.

I just look at the 1.7.5 version, and this version does not contains all the translations you made. In fact, they were merged the day after the tag, sorry the the bad information :(
So you now have 2 solutions:
- Wait for the 1.7.6 (and I assure it will be in it, I just downlaoded the latest 1.7 and have my PIM in Danish, it's cool! Thanks again!). Maybe @LaureBro should have a release date to give to you.
- Download the translations from crowdin (you have a download button), then copy paste into your current installation.

If you're blocked, don't hesitate a second to ping me.

**Comment by objecta** [comment]
Hi pierallard

Thanks for the reply. 

I',m not blocked and can/will wait for the 1.7.6 release. I am uncertain about how the update should be done and if I need to do any configuring for the Danish to show up?

I actually tried to download the translations from Crowdin earlier but the zip files are empty, this is the same for other languages, so maybe there is a problem with the download features on Crowdin?

**Comment by solivier** [comment]
Hi Objecta,

If you want you can download the Danish archive here https://crowdin.com/project/akeneo/da# and copy/paste the right version and folder into your project.

Tell me if it works :)

Cheers.

**Comment by objecta** [comment]
Hi solivier

Thank You very much for Your response.

I managed to download the translation package from crowin now and it looks the package now contains all files.

As I have no local "dev" project or setup, but only have a running PIM site, I'm not sure how to update the site using the language package?

Best regards
Objecta Data
Klaus E. Frederiksen
Denmark

**Comment by pierallard** [comment]
Hi @objecta 
The easiest way to benefit translation is to update your PIM following the releases. Each new version includes the translation files.
