### ISSUE TITLE
[Bug]Strange error with attribute FlatToStandard ArrayConverter on invalid dates.

### ISSUE THREAD

**Issue by oliverde8** [akeneo/pim-community-dev#6290]
The issue appears when converting a date such as 01/01/2017. 

`DateTime::getLastErrors` doesn't return any errors for some reasons but `DateTime::createFromFormat` returns `false` instead of the proper object.

When using the initExcelBundle this creates strange errors in the interface that are impossible to locate without looking deeper in the logs.

**Comment by momoss** [comment]
Hello @oliverde8!

Thank you for raising this issue.

Unfortunately, we did not manage to reproduce it on our side. Could you provide us with more information or precise steps so we can reproduce it? 
For example wich version of php did you use?

If I make a simple test in my local shell, wich is the following:
`php -a`
`php > DateTime::createFromFormat('Y-m-d', '01/01/2017');`
`php > var_dump(DateTime::getLastErrors());`

I have the following output:

`php shell code:1:
array(4) {
  'warning_count' =>
  int(0)
  'warnings' =>
  array(0) {
  }
  'error_count' =>
  int(5)
  'errors' =>
  array(3) {
    [2] =>
    string(22) "Unexpected data found."
    [5] =>
    string(22) "Unexpected data found."
    [8] =>
    string(13) "Trailing data"
  }
}`

In this case we have result for `'error_count'`, and the process doesn't in the if case.

If you need help on troubleshooting, you can visit our dedicated section in our Developer guide: https://docs.akeneo.com/latest/troubleshooting/index.html

Looking forward to hearing from you!

**Comment by oliverde8** [comment]
I quickly did the test & indeed I can't reproduce it this way, but when I use the initExcelBundle it doesn't work. I get a call format on null on line 138. 

I will investigate further to find what is happening and comeback to you.

**Comment by tamarasaurus** [comment]
Hi @oliverde8 - do you still experience this issue?

Regards,
Tamara

**Comment by oliverde8** [comment]
No we can close this still not sure what caused it originally. If I come across it again I will open it back.
