### ISSUE TITLE
Variant Group: Issue with Enrich Groups

### ISSUE THREAD

**Issue by prabhassharma** [akeneo/pim-community-dev#6293]
**I'm reporting an issue**

Hi,
We are using Akeneo CE (1.7.3), in order to allow for variant names to include a hyphen we changed the validation/.yml file. 

The import & frontend now allows us to create variant groups with hyphen in them, however there are 2 issues:

1. When execute "Enrich -> Variant Groups" and select a variant group with hyphen it redirects to the attribute options page.
2. If a product is imported with the group name having hyphens, none of the attributes for the product are editable.

I believe that just changing the group name validation was not enough, can someone please suggest what did we miss.

Regards,
Prabhas

**Comment by momoss** [comment]
Hi @prabhassharma,

We clearly do not recommend that you use hyphen in entity code, but if you have not other choices, you can apply the regex pattern that you have modified in the validation file on the variant_group routing file [variant_group.yml](https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/EnrichBundle/Resources/config/routing/variant_group.yml)

Regards

**Comment by momoss** [comment]
Hello @prabhassharma,

Did you find answers to your questions?
If so, can we close this issue?

Thanks!

**Comment by prabhassharma** [comment]
Hi @momoss, 

Thanks for your message, I am in the process of testing if the change solves the issue. Will update you ASAP.

Prabhas

**Comment by prabhassharma** [comment]
Hi @momoss, 

The changes to variant_group.yml is not helping, it still has the same issue.
Any thoughts.

Regards,
Prabhas

**Comment by solivier** [comment]
Hi @prabhassharma,

I modified the src/Pim/Bundle/CatalogBundle/Resources/config/validation/group.yml and the routing file to accept the hyphen and it works for me (I didn't test further but at least I can display properly the variant group) Did you modified other files ?

Cheers.

**Comment by prabhassharma** [comment]
Worked as suggested, we had to rebuild the cache folder.
