### ISSUE TITLE
Cannot delete category in prod mode

### ISSUE THREAD

**Issue by mathielen** [akeneo/pim-community-dev#6307]
[akeneo-pim-system-info_2017-06-18_14-57.txt](https://github.com/akeneo/pim-community-dev/files/1083087/akeneo-pim-system-info_2017-06-18_14-57.txt)

When in prod environment, I'm unable to delete a category:
Request URL: https://.../enrich/product-category-tree/33658/remove
Request Method:POST
Status Code:405 Method Not Allowed

Because:
[2017-06-18 14:59:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "POST /enrich/product-category-tree/33658/remove": Method Not Allowed (Allow: DELETE)" at .../app/cache/prod/classes.php line 2790 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /enrich/product-category-tree/33658/remove\": Method Not Allowed (Allow: DELETE) at .../app/cache/prod/classes.php:2790, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at .../app/cache/prod/appProdProjectContainerUrlMatcher.php:2585)"} []

When I remove the "methods: DELETE" restriction of "pim_enrich_categorytree_remove" in pim-community-dev/src/Pim/Bundle/EnrichBundle/Resources/config/routing/categorytree.yml - it works.

Kind regards
Markus

**Comment by iulyanp** [comment]
Hi @mathielen,

That error message tells you that you didn't make the request correctly, you should use the DELETE HTTP method when you perform the API call, not POST.
The reason why it works when you remove the `methods: DELETE` from the yml file, is because you removed the HTTP method restriction for that API endpoint.
REST methodology says that when you want to delete a resource you should use DELETE HTTP method. You can read more here https://spring.io/understanding/REST#delete .

Best regards,

**Comment by mathielen** [comment]
Hi iulyanp,

Thanks for your message. That actually is very clear to me :) but, as the Akeneo frontend is doing the call to their own backend, it is up to them to either change the call in the JavaScript part or change the route to allow POST.

Best,
Markus

**Comment by iulyanp** [comment]
Hello @mathielen,

Sorry, it was my mistake, I was under the impression that the url you were calling was from the API. Unfortunately, I couldn't reproduce your issue, I tried also on the demo env from Akeneo `http://demo.akeneo.com`. Could you please provide more information from where are you trying to delete the category.
Could you also tell us if you have `_method: DELETE` in the in the Form Data when you perform the request.
Thank you.

Regards,

**Comment by mathielen** [comment]
Hi @iulyanp ,

Yes, sorry, my message was a little misleading. Thanks for helping out. So, what I do is, I create a new category, select it afterwards and push the delete button:

![image](https://user-images.githubusercontent.com/1571485/27319514-25f02530-5592-11e7-9262-a7c4c3b78988.png)

![image](https://user-images.githubusercontent.com/1571485/27319585-82840b54-5592-11e7-93ef-fc12f2ff4935.png)

After that I can see in google chromes dev toolbar, that there was a POST call:
![image](https://user-images.githubusercontent.com/1571485/27319675-e6eedde4-5592-11e7-8f8b-a333e6c27f57.png)

Best regards,
Markus

**Comment by iulyanp** [comment]
Hi @mathielen,

I did the same thing and it's working for me. Could you take a look in your logs? 
Also look in your toolbar if you have in the form data `_method: DELETE`.
![pim](https://user-images.githubusercontent.com/6533422/27320726-213911b0-55a0-11e7-8e8b-6f880efa6b27.png)
![formdata](https://user-images.githubusercontent.com/6533422/27320733-26469830-55a0-11e7-8716-176aa3a113f8.png)

Regards

**Comment by mathielen** [comment]
Hi @iulyanp ,

Thank you so much! You gave me the right hint. So, the thing is: I did enable the AppCache (in web/app.php). This caused the problem.
There was a bug describing this behavior: https://github.com/symfony/symfony/issues/9464, though it seems to be fixed a long time ago. Anyways, when disabling the AppCache it works.

Thank you very much for your time!

Best regards,
Markus

**Comment by mathielen** [comment]
Ok, the perfect solution would be:

```
$kernel = new AppCache($kernel);
Request::enableHttpMethodParameterOverride(); //https://github.com/symfony/symfony-standard/pull/592/files
$request = Request::createFromGlobals();
```
