### ISSUE TITLE
Write invalid items process fails when it encounters a Date field in xlsx files

### ISSUE THREAD

**Issue by pablollorens** [akeneo/pim-community-dev#6337]
**I'm reporting a Bug**

I have tested an excel file with a missing SKU which will generate a warning and when trying to log the even it will fail with the ones that contain a filled date field, it doesn't matter which format as long as is defined as a Date field in Excel. If the date field is empty on that row everything goes fine.

The problem with this is that the writing process of the log is blocking the rest of the import :(

Here an example:
[test_github.xlsx](https://github.com/akeneo/pim-community-dev/files/1145336/test_github.xlsx)

This example in Akeneo 1.7.6 is not passing to the second item, in other words, a warning is blocking the whole process.

**Comment by pablollorens** [comment]
Ok, I got some more information.

I guess there are some errors with the images, some of them are missing. So the `AbstractInvalidItemWriter` is being executed to kind of collect all the invalid items, and when writing this file the errors appear after trying to write a date, because the dataRow is like this one:

```
array:14 [
  "Datum ingang" => array:3 [
    "date" => "2016-01-28 00:00:00.000000"
    "timezone_type" => 3
    "timezone" => "Europe/Amsterdam"
  ]
  "Bestelnummer groothandel" => "6531000005"
  "Artikelnummer fabrikant " => "G1NT05"
  "Omschrijving_1" => "Del Conca HNT5  G1NT05        15x15"
  "Omschrijving_2" => "vt Nat"
  "Verk Eenh" => "m2"
  "Prijs Per" => 1
  "Prijs inkoop excl btw" => 31.49
  "Catalogus Prijs excl btw" => 62.98
  "Leverancier" => "CERACLEM"
  "Basisverp" => "ds"
  "m2/ doos (1/getal)" => 0.92592593
  "EAN" => "0065310000058"
  "vrachtkosten" => "tegels "
]
```

So the first one is failing and provoking the error above. I hope this helps.

**Comment by pablollorens** [comment]
I think this bug is exactly the same as #5227

Forget about the image field, It can be for instance a missing SKU. Probably is related only with excel files and dates of a concrete type? I believe this should have been tested before, the date format I'm using is dd/mm/YYYY.

**Comment by pablollorens** [comment]
Ok. I have tested an excel file with a missing SKU which will generate a warning and when trying to write the invalid items it will fail with the ones that contain a date field, it doesn't matter which format as long as is defined as a Date field in Excel. If the date field is empty on that row everything goes fine.

The problem with this is that the writing process of the invalid item blocks the rest of the import :(

Here an example:
[test_github.xlsx](https://github.com/akeneo/pim-community-dev/files/1145185/test_github.xlsx)

This example in Akeneo 1.7.6 should not pass the second item, in other words, a warning is blocking the whole process.

**Comment by tamarasaurus** [comment]
Hey @pablollorens, your contribution to this bug fix has been merged here https://github.com/akeneo/pim-community-dev/pull/6423 🎉
