### ISSUE TITLE
Variant's Axes order not preserved 

### ISSUE THREAD

**Issue by QwertyZW** [akeneo/pim-community-dev#6342]
**I'm not sure whether this is a bug or as-designed**

Pim version: commit e9c67470e7c95a5e1a1230838f0da0e704001028 from branch 1.7

## The Issue ##

The pim alphabetically sorts variant's axes

## Expected behaviour ##

The pim maintains the order of the axes according to the way they were input

## Expected behaviour reasoning ##

I'm using this pim in conjunction with Magento2 using Pimgento2. The order in which the variants are exported by akeneo is the _same_ order in which they appear in the resulting configurable product's page, top to bottom. In Magento2 you cannot configure later axes before configuring the lower ones. An alphabetically sorted order for the axes means the products can only be configured in such an order by the customer

## How? ##

This happens on at least 3 levels

1. When selecting the axes from the select2 dropdown, the `<option>`s in the `<select>` are sorted by their value. To main the order here, one can listen on the `selected` [event](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/UIBundle/Resources/public/lib/select2/select2.js#L2662) emitted by the drop down, and keep the `<select>` `<option>`s in order. 

2. The ORM does not seem to guarantee an order for the many to many relationship declared between the groups and the attributes. One way in which the order can be artificially maintained here is by persisting an array of the order of the [relationships](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Group.orm.yml#L25) for each entity 

3. The attributes are **sorted** alphabetically by their code as they're [outputted](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Catalog/Normalizer/Standard/FamilyNormalizer.php#L90)

Line numbers are valid for commit 0d6eb679382ab220fa91861f3641a672c5385863 from the master branch

**Comment by grena** [comment]
Hello @QwertyZW !
Thank you for the very detailed post. 

Indeed, I understand your problem with sorted attributes for Magento2. 
Be sure that I'll explain your issue to Product Owners, to see what we can do in the next version about it.

Unfortunately, as it's not considered as a bug, we can't make a patch on 1.7 version for this behavior.
I advise you to make these modifications in your project by overriding needed files.

Kind regards,

**Comment by QwertyZW** [comment]
@grena  I already fixed this issue for myself

Just being considerate by posting here haha

**Comment by grena** [comment]
Yes you're right! 👍 

I've told the Product Owners about this behavior, thanks for noticing it :)
I close this issue, but feel free to answer back if you have any questions about it.

Have a nice day!
Kind regards,

**Comment by julienanquetil** [comment]
Hi
I got the same issue, how do you fix it on your site @QwertyZW  ?

Thanks

**Comment by QwertyZW** [comment]
I patched the source across several places

**Comment by simonrl** [comment]
Hi @julienanquetil @QwertyZW 

even after 6 years, I would still like to know how to fix this :) Any hint would help. Thanks
