### ISSUE TITLE
Variant Group Association to SKU

### ISSUE THREAD

**Issue by prabhassharma** [akeneo/pim-community-dev#6354]
**I'm reporting a Bug**
Hi, 

We are using AKENEO CE 1.7.5, the issue is that the variant group is not associated to the SKU in the CSV or XLS import. Details as below:

Step 1: We create variants on axis "size" using the variant CSV import.
Step 2: We create products using product CSV import, with groups column (same as variant name) and valid values for axis. All attributes are uploaded correctly, except the GROUPS are not associated with the SKUs.

When I execute a product CSV upload with only 2 columns - SKU & groups, the GROUPS are associated correctly.

We modified the variant group validations as per #6293, however even if I make the variants as per akeneo defaults the issue is same.

Any help is much appreciated.

Thanks,
Prabhas

**Comment by LaureBro** [comment]
Hello @prabhassharma, 

I have not succeeded in reproducing the same behaviour, could you send me an example of uploaded files?
I have created a  new Variant group with axis Size through import, and then created new products and added them through import to this new variant group. I had a sku, size, categories, enabled, groups, family and it worked fine, all my new products have been well added to my new variant group. Did I miss something?
Thanks!

**Comment by prabhassharma** [comment]
Hi @LaureBro 

Attached are the files that I am using. 

[Archive.zip](https://github.com/akeneo/pim-community-dev/files/1111502/Archive.zip)

Thanks,
Prabhas

**Comment by LaureBro** [comment]
Hi @prabhassharma, thanks for the files, but still no success to reproduce on my side :( The 1st import with all the rows works fine and add the products to the variant group. The only difference is that I could not import your variant group with dashes (-) I had to replace them with underscores.
Do you have the same issue for all variant groups and all axis?

**Comment by prabhassharma** [comment]
Hi @LaureBro,

Sad to hear that. 
Yes, we have the same issue with all variant groups and axis.

**Comment by prabhassharma** [comment]
Hi @LaureBro,

Seems like it was an issue only with my user ID on akeneo.
