### ISSUE TITLE
Products duplication with parallel import jobs

### ISSUE THREAD

**Issue by simoncarre** [akeneo/pim-community-dev#6363]
Hi!

We have issues about products duplication on our Akeneo project (version 1.7). It happens to us (inadvertently) launch import jobs simultaneously which seems to generate duplicates sku's in the database (see screenshots)(GTIN is our unique sku attribute).
![capture_002](https://user-images.githubusercontent.com/1229419/27730447-8db215bc-5d89-11e7-84aa-336bab7635ba.png)
![capture_001](https://user-images.githubusercontent.com/1229419/27730453-9253d678-5d89-11e7-8954-ad0d4f7206e1.png)

The command **CleanProductValueDuplicationsCommand** seems ineffective in this kind of situation: 
![capture_003](https://user-images.githubusercontent.com/1229419/27730541-d9cdfa24-5d89-11e7-931a-6a5ec5716c9f.png)

Do you have a solution to avoid this problem?
Thank you in advance!

Simon

**Comment by pierallard** [comment]
There is no easy solution to fix this kind of issue.
Sorry, but I have no other solution than do manual cleaning by removing duplicates products.
