### ISSUE TITLE
Empty files generation and log entries in grid having 0 records 

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#6376]
**I'm reporting a Bug**

Periodic export for many channels (via cron) makes it really hard to debug which log entry has records exported.

It just shows completed on the grid and to find out which entry has more than 0 records exported we need to click on the grid entry.

Steps to reproduce:

Spread > Exports history

To solve this issue, i have two suggestions.

1) stop generating empty files and log entries for 0 records.
2) show number of records exported in the grid itself and have a filter to exclude 0 records entries.

Is there anyway i can solve this issue quickly?

Thank You

**Comment by Doodoune** [comment]
hi @wakqasahmed!

Do you still have this issue?
What is your PIM version?

Regards,

**Comment by wakqasahmed** [comment]
I am on v1.6.19 and indeed this issue is there, however, i have written a simple cron script to check for the filesize and delete if less than 4KB (which in my case is an empty file).

**Comment by Doodoune** [comment]
Hi @wakqasahmed,
PIM v.1.6 is not maintained anymore and we don't reproduce this issue on PIM 2.X and 3.X (the jobs are launched asynchronously with a demon).
I close this issue. Feel free to reopen it if you have this error on a maintained version.
Regards,
