### ISSUE TITLE
symfony 3.3 problem with MeasureBundle

### ISSUE THREAD

**Issue by dnagirl** [akeneo/pim-community-dev#6378]
I'm using the stand-alone version of the AkeneoMeasureBundle. But you've asked for bugs to be reported here.

AkeneoMeasureBundle/DependencyInjection/AkeneoMeasureExtension is not compatible with Symfony 3.3. The following error is thrown:

>   [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]   
>   Invalid key "measures_config" found in arguments of method "setMeasureConfi  
>   g()" for service "akeneo_measure.manager": only integer or $named arguments  
>    are allowed. 

The error can be fixed by editing [line 63](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/MeasureBundle/DependencyInjection/AkeneoMeasureExtension.php#L63) to read:
`->addMethodCall('setMeasureConfig', [$config['measures_config']]);`

**Comment by momoss** [comment]
As the master branch is now compatible with Symfony 3.3, I close the issue.
