### ISSUE TITLE
Mass remove variant groups.

### ISSUE THREAD

**Issue by prabhassharma** [akeneo/pim-community-dev#6399]
Hi,

After doing data upload in PIM I have realized that there are some issues, when I try to correct the issues using data upload the lines are skipped since product is added to a variant group.

Is there a way to mass remove variant group from products.

I tried uploading a file with groups column as blanks but that doesn't work.

Thanks,
Prabhas

**Comment by LaureBro** [comment]
Hello @prabhassharma, 

It's not currently possible through imports, but you can use the API to do so: https://api.akeneo.com/api-reference.html#patch_api_rest_v1_products by setting  `variant_group` to `null`.

Kind regards,
Laure

**Comment by prabhassharma** [comment]
Hi @LaureBro 
Thanks for the response.

Is there a way to create variant groups using APIs. I did not find a mention in the API reference docs.

Thanks,
Prabhas

**Comment by LaureBro** [comment]
Hello @prabhassharma,

It's not possible to create or manage variant groups using the API.

Kind regards, 
Laure

**Comment by Doodoune** [comment]
I close this issue.
Feel free to reopen it if you still have a problem.

Regards,
