### ISSUE TITLE
Delete button generates an error

### ISSUE THREAD

**Issue by pablollorens** [akeneo/pim-community-dev#6414]
**I'm reporting a Bug**

When creating a new import or export profile, and after setting the 3 requested values in the popup. On the first edit screen that you see and before saving anything there is also a "delete" button. Pressing it generates an error 404 in the console.

Probably because the new resource has not been created, maybe the delete button should just dissappear from that screen in that situation.

**Comment by LaureBro** [comment]
Hello @pablollorens, you are right, this 'Delete' button should not appear. 

Do you feel like contributing to the PIM and have it removed? 
Our support team can help you if needed :)

Thanks, 
Laure

**Comment by latenzio** [comment]
The reason for this can be found:
- https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-export-remover.js#L26
- https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-import-remover.js#L26

The route definition expects `code` parameter, `identifier` is passed mistakenly

It is fixed already in `2.0` branch.

**Comment by grena** [comment]
Fixed by #7123 and available since 1.7.13, thanks @latenzio .
