### ISSUE TITLE
Writer of xlsx files cannot write invalid_items.xlsx with dates

### ISSUE THREAD

**Issue by pablollorens** [akeneo/pim-community-dev#6421]
Version 1.7.6

The XLSX writer for invalid items defined in ConnectorBundle, in this class `Pim\Component\Connector\Writer\File\Xlsx\Writer` is using the DummyConverter by default, defined in this class `Pim\Component\Connector\ArrayConverter\DummyConverter` which just casts everything to string. Well, this is failing for dates and you get the following error after importing.

![screen shot 2017-07-17 at 11 32 34](https://user-images.githubusercontent.com/1991002/28262693-3f49673c-6ae4-11e7-8b48-9a1e1359f7c3.png)

Which ends with a corrupted xlsx file.

My proposal is to extend DummyConverter to at least check some types and make proper casting to secure values.

I think this bug is exactly the same as #5227 

Example of imported file: [test.xlsx](https://github.com/akeneo/pim-community-dev/files/1152123/test.xlsx)

**Comment by Doodoune** [comment]
Hi @pablollorens!

I've tried today on a fresh v1.7.39 of the PIM and I don't have problem to import dates with the xslx import.

So I think that it has been fixed in a patch.

Regards,

**Comment by Doodoune** [comment]
Oh I just see that https://github.com/akeneo/pim-community-dev/issues/6337

So I close this issue.
