### ISSUE TITLE
Rendering last jobs is slow in Akeneo 1.7

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#6443]
Rendering the last jobs (last operations widget, Process tracker) got really slow for us in Akeneo 1.7. This blocks us from upgrading to Akeneo 1.7 from 1.6.

The PR #6308 would solve the problem for us, but I haven't heard any feedback since one month.
Since the PR I've read about "TIP-729: use UUIDs as product IDs" #6257 which wouldn't work with out PR, but maybe you can consider another solution (maybe an index for `startTime`).

**Comment by LaureBro** [comment]
Hi @Hocdoc, sorry for that and thanks for your PR, we'll review it ASAP.
Thanks!

**Comment by pierallard** [comment]
I close this issue, please show the description on the PR
