### ISSUE TITLE
Attribute values order with «Automatic option sorting» on

### ISSUE THREAD

**Issue by grosmanal** [akeneo/pim-community-dev#6448]
I need to sort attribute values for a simple select attribute, so I checked «Automatic option sorting» in attribute definition. But when I go to a product page, it seems the values are sorted by the English value label despite I'm using French localization.

**Comment by ahocquard** [comment]
Hello @grosmanal,

What is your PIM version ?
For your information, a fix is currently on track in this PR: https://github.com/akeneo/pim-community-dev/pull/6428

Regards,
Alexandre

**Comment by grosmanal** [comment]
I'm using version 1.7.6.

I can reproduce the issue on demo.akeneo.com : 
- connect with admin login
- find attribute clothing_size
- modify the French label of «xs» value to «A_XS»
- check «Automatic option sorting»
- go to [products list view](http://demo.akeneo.com/#url=/enrich/product/)
- select French locale
- find a «tshirt» product (i.e sku OROTS_BOXL)
- in «Taille» tab the «Taille du vêtement» select shows «A_XS» between «XL» and «XXL»
=> it should be the first one in alphabetical order

**Comment by ahocquard** [comment]
@grosmanal thanks for the steps to reproduce the issues.

As it's already fixed in the PR https://github.com/akeneo/pim-community-dev/pull/6428, it should be available in the next tag of the 1.7.
