### ISSUE TITLE
Feature Request: Functionality to add Attributes By Group in Products and Variant Groups

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#6470]
**I'm submitting a Feature Request**

The feature introduced in v1.7 to Add Attributes By Group in Families is really good but usually we rarely add new families. However, the feature can be really useful if added in **Variant Groups'** Attributes Tab and Products' Attributes Tab.

Any plans to release as a patch or in a new version?

<img width="1440" alt="screen shot 2017-07-25 at 7 52 17 pm" src="https://user-images.githubusercontent.com/4486133/28581316-f79a5fd2-7172-11e7-87dd-d27823f8f78c.png">

**Comment by LaureBro** [comment]
Hello @wakqasahmed, 

Thanks for your feedback, I'll inform the product team of your suggestion :)

Regards, 
Laure
