### ISSUE TITLE
Moving from MySQL to Hybrid SQL

### ISSUE THREAD

**Issue by prabhassharma** [akeneo/pim-community-dev#6476]
We did the DB migration (Mongo+MySQL) using the steps listed here [https://docs.akeneo.com/1.6/developer_guide/installation/setup_hybrid_storage_mysql_mongo.html]. All steps were executed successfully.

However, at the database level we are not seeing any data in the Mongo DB. 
To be precise:
When we add new products (import CSV/XLS) the information is OK, but the old data which was on MySQL doesn't show up.

Is there another way to switch to Hybrid SQL if we already have data in MySQL and also how do we migrate this data.

Thanks,
Prabhas

**Comment by masmrlar** [comment]
I guess it is

- export with MySQL only connection
- import with Hybrid SQL

**Comment by masmrlar** [comment]
But you should also have a look at the changelog of v1.8.
It looks like the MongoDB-connection is removed in favour of Elasticsearch.

**Comment by pierallard** [comment]
@prabhassharma , @masmrlar is right, there is no Mongo support since 2.0 version.
I close this issue, and hope you found a solution since July.
