### ISSUE TITLE
Issue in add property to the category

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [akeneo/pim-community-dev#6505]
Hi,

I'm new to akeneo. I followed the below link to add property to the category.

https://docs.akeneo.com/1.6/cookbook/category/add-properties-to-category.html#configure-the-mapping-override

But when I run the command, sudo php app/console doctrine:schema:update --dump-sql

It shows  the results as **Nothing to update - your database is already in sync with the current entity metadata.**

I'm in the almost deadline. Any one please help me.

Thanks in advance.

**Comment by aRn0D** [comment]
Hi @Vanitha-Ramkumar,

You must not run that command with sudo. Could share with us the files that you have created with the path where they are stored, please?

Thank you
