### ISSUE TITLE
Bug:  Issue in Override the ORM Product Value (Color and Fabric) - default akeneo code

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [akeneo/pim-community-dev#6519]
Hi,

I have installed akeneo 1.6 and custom entity bundle 1.8. 

I have found the code for *Override the ORM Product Value (Color and Fabric - Reference data)* after the installation of akeneo.

When I execute the mapping info and sql update commands, 

php app/console doctrine:mapping:info
php app/console doctrine:schema:update --dump-sql --force

I got the results *Nothing to update - your database is already in sync with the current entity metadata.*.

As per the code, while running the above commands the entity mapping and database table has to be created. But actually it is not happening.

Does any thing else required to execute to create the reference data ?

**Comment by aRn0D** [comment]
hi @Vanitha-Ramkumar ,

Could you share with us: the product value mapping, the reference data bundle (pim_reference_data)  and akeneo storage utils (akeneo_storage_utils) configuration?

Thank you
