### ISSUE TITLE
Bug : digits for category codes

### ISSUE THREAD

**Issue by LordVizor** [akeneo/pim-community-dev#6551]
I created an entire tree of categories with the initialization excel file (xlsx_init_import).

All the category codes are only containing "digits" like 504020 (given by our ERP).

The creation of categories went well trough the import.

Unfortunately, I got an error while specifying products categories with a excel product import 
 The field "categories" should contain a string, "504020" provided

![image](https://user-images.githubusercontent.com/31010103/29277027-c0164320-8110-11e7-88c1-a1981623a1de.png)

src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php:351

**Comment by LordVizor** [comment]
Update : 
There is no problem while using a csv product import : the products can be created or updated with a category code with only "digits".

But it does not works with the excel product import. 
There is the error mentioned above  : "The field "categories" should contain a string,"

**Comment by LordVizor** [comment]
Hi @LaureBro , any news regarding this issue ? Did you manage to reproduce it ?
This really blocks us in our project.

Thx  ;)

**Comment by LaureBro** [comment]
Hello @LordVizor, 

Yes, the issue can be reproduced, but we did not work on it yet. 
Would you like to contribute to a patch? Let us know if you're interested and if you need some help.

Kind regards, 
Laure

**Comment by LordVizor** [comment]
Thx @LaureBro 

I'm sorry, but as a merchant, we rely on a partner for Akeneo integration, we don't have the abilities to help you directly on this one ;).

Good luck anyway !

**Comment by pierallard** [comment]
Hi @LordVizor 
I'm pretty sure to have seen a Pull Request to fix this issue last months, and just checked, it's fixed on demo.akeneo.com (2.1)
You should use the latest version of the PIM to be able to use it!
I close the ticket, please feel free to reopen it if you have issues with 2.1.
