### ISSUE TITLE
Duplicate sku attribute value

### ISSUE THREAD

**Issue by QwertyZW** [akeneo/pim-community-dev#6582]
**I'm reporting a Bug**
Version: 1.7

```
mysql> select value_string,count(*) c from pim_catalog_product_value where attribute_id=1 group by value_string having c > 1;
+--------------+---+
| value_string | c |
+--------------+---+
| 45461        | 2 |
+--------------+---+
1 row in set (0.02 sec)

mysql>
```

![duplicatesku](https://user-images.githubusercontent.com/8478946/29475107-551a35a8-842c-11e7-9b83-86c78f6f1b19.png)

Only difference I see is that one of those is assigned a group and the other isn't. Other than all their other attributes are equal

**Comment by aRn0D** [comment]
hi @QwertyZW,

Could you provide us the info.txt (System -> System information) to know which storage is impacted? Could you tell us what I tried to do? I did a quick check it is impossible to create a product with an existing SKU from the UI. 

Thank you.

**Comment by QwertyZW** [comment]
It wasn't from the UI, I'm importing products using the cli

**Comment by mathewrapid** [comment]
I've encountered the same problem. Through import, not gui.

**Comment by wa-daniel-fahl** [comment]
Same here. info.txt attached.
[akeneo-pim-system-info_2017-11-24_10_46.txt](https://github.com/akeneo/pim-community-dev/files/1501193/akeneo-pim-system-info_2017-11-24_10_46.txt)

**Comment by pierallard** [comment]
We added a mechanism in the >2.0 to be sure this bug will not be reproduced.
I will close this ticket as it's fixed (even not in your versions)
Please feel free to reopen it if you still encountered it in the latest PIM version.
