### ISSUE TITLE
[SOLVED] / Feature Request: Images get exported although no images selected as attribute

### ISSUE THREAD

**Issue by wucherpfennig** [akeneo/pim-community-dev#6583]
If I create a new export from the type "csv_product_export" images will be exported although no attributes from type image are selected.

Any suggestions?

best regards

wucherpfennig

**Comment by wucherpfennig** [comment]
and additionally the files are also exported to 

```
app/archive/export/csv_product_export/
``` 

I assume this is a bug?

**Comment by aRn0D** [comment]
Hi @wucherpfennig,

I am not sure that I understand what you mean. "no attributes from type image are selected." Your products don't have images? Your set "Export files and images" (export profil parameter) to no? 

Could you give us more information by adding `info.txt`  (System ->  System information ).

Thank you.

**Comment by wucherpfennig** [comment]
@aRn0D 

Thank you for your hint... I found out that everything works as expected I just forgot to uncheck the "Export files and images" Option. :-/

with "no attributes from type image are selected" I meant that the products had images but the attributes containing them were not selected for an export.

Although my "bug" can be closed I would like to mention, that the option "Export files and images" does not make 100% sense: Shouldn't it be rename to something like "Export files and images if selected attributes contain media files" or something like that? 
The reason why I am suggesting this is simple: Like in my case if you forget about the option in the first place you can easily run out of disk space if you do not pay any attention to this behavior.

Best regards

wucherpfennig

**Comment by aRn0D** [comment]
Ok, that's cool! I will close this issue and I will send your request to our PO.
