### ISSUE TITLE
Type error: Argument 2 passed to Akeneo\Component\Batch\Job\RuntimeErrorException

### ISSUE THREAD

**Issue by riconeitzel** [akeneo/pim-community-dev#6639]
**I'm reporting a Bug**

I try to run  an export profile while the process is not able to write to or create a directory.

It tries to throw an Exception in https://github.com/akeneo/pim-community-dev/blob/c17a7f28c2662b3804093ebec16a4e39c1010d44/src/Akeneo/Component/Batch/Job/Job.php#L351-L355 but fails because https://github.com/akeneo/pim-community-dev/blob/494b2c108427556e2818a3c2f18ede40b585c144/src/Akeneo/Component/Batch/Job/RuntimeErrorException.php#L22 expects argument 2 to be an array instead of a string

[akeneo-pim-system-info_2017-08-29_13_30.txt](https://github.com/akeneo/pim-community-dev/files/1260080/akeneo-pim-system-info_2017-08-29_13_30.txt)

**Comment by momoss** [comment]
Hello @riconeitzel,

thank you for your feedback.
I agree this is a bug and I can reproduce it, thanks for the detailed report!
Would you like to contribute to a patch? Let me know if you need help (smile)
Regards

**Comment by riconeitzel** [comment]
hey there … I'm absolutely new to the system. I don't know yet how a suitable fix could look like. for me I just wrapped the second argument with [ ] :D that works BUT i don't know if it's a FIX or just a HACK 😂

**Comment by aRn0D** [comment]
Those exceptions need to be instantiated like that `new RuntimeErrorException('Failed to write to file %path%', ['%path%' => $this->getPath()]);`. Like Pilipe said every PR are very welcome :)

**Comment by dnd-tyler** [comment]
#6704

**Comment by dnd-tyler** [comment]
So, I did it here : #6704

**Comment by nidup** [comment]
Thank you for your PR, the fix is now available on master (cherry-picked + merged here https://github.com/akeneo/pim-community-dev/pull/6869)
