### ISSUE TITLE
Invalid Entities

### ISSUE THREAD

**Issue by xElysioN** [akeneo/pim-community-dev#6657]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Branch | master
| Edition | CE
| PHP | 7.1.8

Doctrine mapping is invalid in master.

> php bin/console doctrine:schema:validate

> `[Mapping]  FAIL - The entity-class 'Pim\Bundle\CatalogBundle\Entity\Category' mapping is invalid:
 The field Pim\Bundle\CatalogBundle\Entity\Category#products is on the inverse side of a bi-  directional relationship, but the specified mappedBy association on the target-entity Pim\Component\Catalog\Model\Product#categories does not contain the required 'inversedBy="products"' attribute.

> [Mapping]  FAIL - The entity-class 'Pim\Bundle\CatalogBundle\Entity\Group' mapping is invalid:
  The field Pim\Bundle\CatalogBundle\Entity\Group#products is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity Pim\Component\Catalog\Model\Product#groups does not contain the required 'inversedBy="products"' attribute.

> [Mapping]  FAIL - The entity-class 'Pim\Component\Catalog\Model\Product' mapping is invalid: The field Pim\Component\Catalog\Model\Product#uniqueData is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity Pim\Component\Catalog\Model\ProductUniqueData#product does not contain the required 'inversedBy="uniqueData"' attribute.

Solutions :
In file
> Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.orm.yml
add 
> inversedBy: products
in the category (manyToMany)

**Comment by aRn0D** [comment]
Hi Maxime,

Thank for this complete bug report! You're right, the doctrine mapping is invalid. Laure told me that you're interested in sending a PR. That would great !!
