### ISSUE TITLE
Prodcut image export issue

### ISSUE THREAD

**Issue by e-v-medvedev** [akeneo/pim-community-dev#6771]
I tried to export demo products with images in .csv file. Result is - empty column "picture" and no directory with image files. Version - 1.7.6.

**Comment by KarenMayo** [comment]
Hi @e-v-medvedev, 

If products are related to images, you will have two download options: 

- **Download generated file** : CSV file with all products information and images paths
- **Download generated archive** : ZIP file containing all pictures

![downloadoptions](https://user-images.githubusercontent.com/31764310/30749247-1951f004-9fb3-11e7-8520-0432812429f5.png)

If no images are related to your products, you will only have the first option and the column "picture" will be empty. 

Are you sure iimages are linked to your products? 

Regards, 
Karen

**Comment by e-v-medvedev** [comment]
I tested export on demo data. I am absolutely sure that images a linked to products.

**Comment by KarenMayo** [comment]
Hi @e-v-medvedev, 

 I tested the product export in our demo environment and I could get both files (CSV and ZIP) :

[export_Demo_CSV_product_export_2017-09-26_17-03-07.zip](https://github.com/akeneo/pim-community-dev/files/1333647/export_Demo_CSV_product_export_2017-09-26_17-03-07.zip)

If there are images related to the products, you should get the images path in the  column "picture". 

It is quite difficult for us to help you if we cannot reproduce your issue. 

Regards, 
Karen

**Comment by e-v-medvedev** [comment]
Sorry Karen. It's my fault. I found out my mistake. All works fine.

**Comment by KarenMayo** [comment]
@e-v-medvedev, 

Thanks for letting me know! 

Regards, 
Karen
