### ISSUE TITLE
Update gitignore for web-server-bundle

### ISSUE THREAD

**Issue by xElysioN** [akeneo/pim-community-dev#6824]
| Q                | A
| ---------------- | -----
| Bug report? | no
| Branch | master
| Edition | CE
| PHP | 7.1.8
| Pull Request | #6825 

Since Symfony 3.3, when we're using the web-server-bundle, it create a file at root : 
```.web-server-pid```
And this file is not in .gitignore 

**Step to reproduce :** 
php bin/console server:start 

**cf:** https://github.com/symfony/web-server-bundle/commit/38770ff1dc691ffb5c813c616322398b1339cacc?diff=split#diff-0cf8191ef78b0cebbc06622026f80856R153

**Comment by LaureBro** [comment]
Thanks Maxime :)
I've informed our dev team, they'll review your PR.
Best,
