### ISSUE TITLE
Wrong click area for header buttons (everywhere)

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#6847]
**I'm reporting a Bug**

Version:2.0.0-alpha1
Chrome 61.0.3163.100

If you open product page - all fine. but then you scroll down, and you can see that links for all buttons (Cancel, Save, Channels and Locales) on wrong place.

This bug on all pages.

screenshots:
![area1](https://user-images.githubusercontent.com/2612186/30935561-bed2068e-a3d9-11e7-8a06-3b4fee16cf22.jpg)

here, you can't click on product variant:
![area2](https://user-images.githubusercontent.com/2612186/30935565-c26ab66a-a3d9-11e7-9aec-a14d2195bb60.jpg)

Family page:
![area3](https://user-images.githubusercontent.com/2612186/30937432-6d950310-a3df-11e7-80fd-6d4be60e81cd.jpg)

**Comment by pierallard** [comment]
Hi @userz58 ! 
Thanks for raising this issue ! Can you send more information about your system ? OS, OS version, browser, etc.
I did a fix https://github.com/akeneo/pim-community-dev/pull/685 , if you have some time to test if it fixes your issue it may be cool!
Thanks again!

**Comment by userz58** [comment]
Windows 10
Chrome 61.0.3163.100
Akeneo Version:2.0.0-alpha1

**Comment by tamarasaurus** [comment]
Hi @userz58, this issue has been fixed in v2.0.0. 

- Tamara
