### ISSUE TITLE
Product attributes disappear

### ISSUE THREAD

**Issue by Ghoubali** [akeneo/pim-community-dev#6852]
https://drive.google.com/file/d/0BxMqOeCZ7IwlQkxKazVnajNOVzQ/view
As you can see in the video attached.
After selecting a product and selecting the menu option "Attributes".
If you click on the "Display" filter and do not select one of the option but rather click on the filter name ("Display") a error make disappear everything.
Then even is you go in an other menu option as "Categories" and then come back to "Attribute" nothing change, the error still remind.

**Comment by LaureBro** [comment]
Hello @Ghoubali, 
Thanks for raising this issue, our development team will fix it, I'll keep you posted. 
Regards,

**Comment by LaureBro** [comment]
Hello @Ghoubali, this issue will be fixed in the next 2.0 patch, the 2.0.26 that will be released very soon.
The fix will also be available very soon in the 2.2.

Kind regards, 
Laure

**Comment by LaureBro** [comment]
Hello,

this issue is fixed in the 2.0.26 released yesterday and in the 2.2.8 released this morning.

Best, 
Laure
