### ISSUE TITLE
Completeness does not update when changing Locale in Product Attributes View

### ISSUE THREAD

**Issue by Ghoubali** [akeneo/pim-community-dev#6856]
https://drive.google.com/file/d/0BxMqOeCZ7IwlRTZoRWtGNmJHMlk/view

As you can see in the video attached.
The completeness does not update when changing the Locale option.
To update it, you have to re-select the Channel.

**Comment by LaureBro** [comment]
Hello @Ghoubali, 

The issue is fixed on the latest version, the 2.0.5. 

Kind regards, 
Laure
