### ISSUE TITLE
Completeness UX bug

### ISSUE THREAD

**Issue by Ghoubali** [akeneo/pim-community-dev#6858]
![completeness ux bug - copie](https://user-images.githubusercontent.com/32258621/30966691-1a040766-a45a-11e7-9e4a-5db00c6d70a3.jpeg)

As you can see in the screen shot. The percentage completeness label is out of his box when the width screen is reduce.

**Comment by Ghoubali** [comment]
![completeness ux bug 2](https://user-images.githubusercontent.com/32258621/30968725-813c3844-a460-11e7-84e9-62981e92f054.jpeg)

**Comment by LaureBro** [comment]
Hello @Ghoubali, thanks for raising this. It will be handled by our dev team - internal ref : PIM-6835.
we'll keep you posted.

**Comment by LaureBro** [comment]
Hello @Ghoubali,

This issue is fixed: ![completeness](https://user-images.githubusercontent.com/13367999/31720369-b6987596-b416-11e7-936a-1b84873746a9.png)
You can update your installation to benefit from this fix.

Kind regards, 
Laure
