### ISSUE TITLE
Bug on 1.7.9 / Edit user with admin profile

### ISSUE THREAD

**Issue by alecourtes** [akeneo/pim-community-dev#6874]
We update the pim-community and pim entreprise on 1.7.9

The fix on src/Oro/Bundle/UserBundle/Controller/UserController.php (https://github.com/akeneo/pim-community-dev/commit/eb6600a47cb8c7c1f70ae0e3eac09150b719e041#diff-96da74b7eb9827b12fe4c04eca9d62a2), so now when I am admin and I want to edit an user profile I have all the time 403 on url user/update/:id .... even if I have all the role access in database.

I downgrade to 1.7.8 and the problem not appear.

Context : we use akeneo entreprise edition (with pim2catalog and Tessa Dam).

**Comment by LaureBro** [comment]
Hello @alecourtes, did you empty all you caches and restart Apache after you upgraded to the 1.7.9? 
Kind regards, 
Laure

**Comment by alecourtes** [comment]
Hello @LaureBro. Yes I clear all cache and restart apache. We open an ticket directly to your Jira (Entreprise Edition).

**Comment by LaureBro** [comment]
Hello @alecourtes, 
I've answered you few seconds ago in the Jira ticket. I've manage to reproduce the issue and we'll fix this problem asap. I'll keep you posted.
Regards.

**Comment by LaureBro** [comment]
Hello, this issue has been fixed in the 1.7.11 patch.
I'm closing this issue.
