### ISSUE TITLE
Product grid category filters don't work

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#6876]
**I'm reporting a Bug**
Akeneo 2
maybe it's problem only with demo data.

you can see it on your demo site http://demo.akeneo.com/#/enrich/product/

if you select:
Master catalog > Men
or
Master catalog > Men > Pants
or
Master catalog > Women

you don't see products

![- -1](https://user-images.githubusercontent.com/2612186/31038825-87a31bb8-a581-11e7-9e16-63f9879334a0.jpg)

**Comment by LaureBro** [comment]
Hello @userz58, 

It's linked to the demo set, our product models have do not have categories :(

Kind regards, 
Laure

**Comment by nidup** [comment]
Hi @userz58
Thank you for the feedback.
We'll fix it in upcoming patch :)

**Comment by LaureBro** [comment]
Hi @userz58 

This issue has been fixed! I'm closing this issue.

Thanks!
