### ISSUE TITLE
Bug : Using docker-compose doesn't work out of the box

### ISSUE THREAD

**Issue by oliverde8** [akeneo/pim-community-dev#6885]
There are 2 issues when using docker installation

1. The httpd configuration is missing the apache2 mod_dir. 
I have created a PR to fix : https://github.com/akeneo/pim-community-standard/pull/409/files

~~2. The elasticsearch docker has xpack installed, akeneo can't therefore connect. Not sure what that best solution is. 
    1. I use `docker-compose exec elasticsearch bin/elasticsearch-plugin remove x-pack`
    2. To configure the akeneo php docker with the proper password~~

**Comment by acoelhosantos** [comment]
Following the [instructions](https://docs.akeneo.com/latest/install_pim/docker/installation_docker.html) I am also getting an error while running `bin/docker/pim-initialize.sh`:

- `PHP Fatal error:  Uncaught Error: Class 'Oro\Bundle\AsseticBundle\OroAsseticBundle' not found in /srv/pim/app/AppKernel.php:168`
- `Error: Cannot find module '/srv/pim/vendor/akeneo/pim-community-dev/webpack/check-dependencies.js'`

**Comment by oliverde8** [comment]
I am closing this issue, for me all is okay. 
I deleted the image and it fixed the issue.

**Comment by renatokhirata** [comment]
> The above error was a misconfiguration between the `docker-compose environment vars of mysql` and the values within the `parameters.yml` file.

@acoelhosantos Can you help me with this? What could be wrong here? I can't get through this issue.. Thanks in advance!

<img width="1025" alt="Screenshot 2019-10-14 at 17 21 55" src="https://user-images.githubusercontent.com/14020350/66780412-22a99900-eea7-11e9-9b77-190cafed374e.png">

**Comment by acoelhosantos** [comment]
> > The above error was a misconfiguration between the `docker-compose environment vars of mysql` and the values within the `parameters.yml` file.
> 
> @acoelhosantos Can you help me with this? What could be wrong here? I can't get through this issue.. Thanks in advance!
> 
> <img alt="Screenshot 2019-10-14 at 17 21 55" width="1025" src="https://user-images.githubusercontent.com/14020350/66780412-22a99900-eea7-11e9-9b77-190cafed374e.png">

I don't remember exactly what I was doing wrong (more than a year ago), but I retraced all my steps and eventually got it running. I suggest reviewing every step and if you still have problems contact the support directly. Good luck.

**Comment by omerimuni** [comment]
> 
> 
> > The above error was a misconfiguration between the `docker-compose environment vars of mysql` and the values within the `parameters.yml` file.
> 
> @acoelhosantos Can you help me with this? What could be wrong here? I can't get through this issue.. Thanks in advance!
> 
> <img alt="Screenshot 2019-10-14 at 17 21 55" width="1025" src="https://user-images.githubusercontent.com/14020350/66780412-22a99900-eea7-11e9-9b77-190cafed374e.png">

Hello @renatokhirata 

Did you fixed this error?
