### ISSUE TITLE
Dynamic date in filename disable the download button in export UI

### ISSUE THREAD

**Issue by vfaisse** [akeneo/pim-community-dev#6886]
https://github.com/akeneo/pim-community-dev/blob/ecb3898f5860b47f068fe9166476673fab5f8210/src/Pim/Component/Connector/Writer/File/AbstractFileWriter.php#L47

Using dynamic datetime with seconds in path, sometimes, disable the possibility to download the generated file from the interface.

When getPath is called by the [FileWriter](https://github.com/akeneo/pim-community-dev/blob/ecb3898f5860b47f068fe9166476673fab5f8210/src/Pim/Component/Connector/Writer/File/Csv/Writer.php#L122) and then later by the [FileWriterArchiver](https://github.com/akeneo/pim-community-dev/blob/ecb3898f5860b47f068fe9166476673fab5f8210/src/Pim/Component/Connector/Archiver/FileWriterArchiver.php#L108), the returned path can be different, because the timestamp may have changed.

**Comment by mathewrapid** [comment]
Would a possible solution to use `$this->stepExecution->getJobExecution()->getStartTime()->format($this->datetimeFormat)` (cached internally by the class of course)?

**Comment by vfaisse** [comment]
Yes, use Start time of the job execution works.
