### ISSUE TITLE
v2.0.0 User without system configuration tab, crash on dashboard

### ISSUE THREAD

**Issue by kpitn** [akeneo/pim-community-dev#6900]
I'm on v2.0.0 tag version.

When i create a user without system configuration tag, i get this error : 
`
Uncaught TypeError: Cannot read property 'route' of undefined (tab.js:87)
`

If i check system configuration the dashboard is load correctly : 
![sytem](https://user-images.githubusercontent.com/41059/31168588-252b9230-a8f6-11e7-86a6-b79498a77363.png)

It's not a bug it's a feature ?

**Comment by skeleton** [comment]
Hi @kpitn,

Thanks to report this issue, I just tested and can reproduce the bug. It will be fixed soon.

**Comment by Doodoune** [comment]
Hi!

Tested today on the version 2.0.45 and I don't reproduce the bug, so it has been fixed.
I close this issue.
Feel free to reopen it if needed.

Regards,
