### ISSUE TITLE
showing category filter

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#6971]
**I'm reporting a Bug**
Akeneo 2
Chrome

please open http://demo.akeneo.com/
1. click Products
2. select category filter (Cameras, for example). click button DONE
3. click on any another filter (family or status)
the category filter will open itself

**Comment by LaureBro** [comment]
Hello @userz58, 

thanks for reporting this, I'll inform our Product team. I'll keep you posted!

**Comment by tamarasaurus** [comment]
Hi @userz58, this issue has been fixed in v2.0.7 (available since 2017-11-23)
