### ISSUE TITLE
Wrong path for js routing generation during assets install

### ISSUE THREAD

**Issue by amansilla** [akeneo/pim-community-dev#6983]
I'm reporting a bug which is affecting the PimInstallerBundle of all 1.X and 2.X versions.

Whenever you execute the command `pim:installer:assets` the `js/routes.js` file is not always going to be generated in the right path.

To reproduce the problem, just execute the command from outside the project root. For example if the PIM is installed in the path `/var/www/html` and you try to install the assets executing `php /var/www/html/bin/console pim:installer:assets` the routes js files is gonna be generated in `/web/js/routes.js` instead in `/var/www/html/web/js/routes.js`.

I hope this examples helps to understand the issue.

**Comment by LaureBro** [comment]
Hello @amansilla, 

Thanks a lot for this contribution! We have released the 1.6.20 yesterday, it contains your fix.

Kind regards, 
Laure

**Comment by amansilla** [comment]
Thx for the info @LaureBro and the fast feedback! ;)
