### ISSUE TITLE
Can't delete product model

### ISSUE THREAD

**Issue by crapougnax** [akeneo/pim-community-dev#7022]
Hi,

In v2.0.2, I created a family variant then a product model and its children from CSV. 

If i click the delete button on the product line in the grid, I get a "Cannot delete this product" (Delete Error).

The AJAX request debug stats shows a 404 error when trying to execute `DELETE /enrich/product/{id}`

![capture d ecran 2017-10-18 a 11 48 01](https://user-images.githubusercontent.com/1242077/31712391-35aedd50-b3fb-11e7-8f84-a141e35bd93a.png)

[akeneo-pim-system-info_2017-10-18_11_52.txt](https://github.com/akeneo/pim-community-dev/files/1394169/akeneo-pim-system-info_2017-10-18_11_52.txt)

**Comment by LaureBro** [comment]
Hello @crapougnax, 

Thanks for raising this. Please note that currently it is not possible to remove product models, because it’s very impactful, but this possibility will be added in the future. 
For now, the button will be removed.

Regards, 
Laure

**Comment by crapougnax** [comment]
Thanks Laure. 

Just hoping the Future is near. ;-)

Looking forward to, anyway.

**Comment by juskor-mt** [comment]
I hope that we could get this feature implemented soon...

**Comment by LaureBro** [comment]
Hello, 
Yes, the ability to delete a product model should be part of the 2.1 :) The release is planned for the 21st of December. We'll keep you updated.

**Comment by LaureBro** [comment]
Hello @crapougnax and @juskor-mt, I have good news! 
This feature will be available in the 2.0.9 :)
We'll let you know when the patch is available (very soon).

**Comment by crapougnax** [comment]
Such a wonderful christmassy piece of news ! 

You guys are on fire ! 

Many thanks.

**Comment by docteurklein** [comment]
closed by https://github.com/akeneo/pim-community-dev/pull/7170
