### ISSUE TITLE
English (United States) is always preselected as locale in the edit user screen even if the user uses a different locale setting

### ISSUE THREAD

**Issue by simonkub** [akeneo/pim-community-dev#7062]
**I'm reporting a Bug**

If you show a view (`/#/user/view/5`) a user that is using another locale than English (United States) the correct locale is shown. If you edit this user (`#/user/update/5`) the locale dropdown defaults to English (United States) no matter what locale is set on the user. It seems like the wrong locale is set on the user, even though it is not.

Tested on 2.0.4 CE with Chrome/Firefox.

#### Steps to reproduce

1. Set a users locale to something different than English (United States) and save
2. Reload the page and confirm the right locale is saved when you view the user (`/#/user/view/5`)
3. Click on edit and go to the interfaces tab
4. The dropdown value is English (United States) instead of the saved locale

![systeminfo](https://user-images.githubusercontent.com/16416949/31950872-e66f3898-b8dc-11e7-8b22-fc4e27aa397b.png)

**Comment by LaureBro** [comment]
Hello @simonkub, 
Yes it's something that we also noticed, the new language is well applied but English_US remains. 
We'll let you once it's fixed :)
Kind regards, 
Laure

**Comment by LaureBro** [comment]
Hello @simonkub, we have fixed this issue, the fix will be available in the next version, the 2.0.6. We should release it this Thursday.
Kind regards, 
Laure

**Comment by LaureBro** [comment]
Hello @simonkub, we have released the 2.0.6 last Friday, and the bug is fixed, you can update your PIM.

Thanks!
