### ISSUE TITLE
[2.0.2] product grid buttons wrong product reference

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#7069]
**BUG**

1. Have a product model with id 1
2. Have a product with id 1 not associated to any product model
3. Have a product with id 2, that is part of product model 1 (variant)
4. Try any button for the _product model 1_ in the _product grid_ (edit, classify, delete, toggle status). They all point to _product 1_ instead of _product model 1_.

This way you can delete the wrong _products_ when you think you are deleting _product models_

relates to #7022

**Comment by aRn0D** [comment]
Hi Matias,

Could you upgrade to the 2.8 and check that you still have this problem, please?

Thank you.

**Comment by mathewrapid** [comment]
Hi @aRn0D,

That I cannot do. I don't have Akeneo 2.x installed atm. This bug report was based on demo.akeneo.com version 2.0.2.

**Comment by aRn0D** [comment]
This is fixed by https://github.com/akeneo/pim-community-dev/pull/7091 (2.0.6). Anyway, thank you for reporting this issue.
