### ISSUE TITLE
Yarn install, no surch file or directory

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#7095]
Hello, i try to install akeneo 2.0 CE and when i run the command yarn install i have the message :

`ERROR: [Errno 2] No such file or directory: 'install'`

```
root@e2ec3f6f21b9:/var/www/html/pim-project# ll
total 800
-rw-r--r--.  1 root     root      17102 Oct 31 15:01 CHANGELOG-1.0.md
-rw-r--r--.  1 root     root      11092 Oct 31 15:01 CHANGELOG-1.1.md
-rw-r--r--.  1 root     root      29419 Oct 31 15:01 CHANGELOG-1.2.md
-rw-r--r--.  1 root     root      38379 Oct 31 15:01 CHANGELOG-1.3.md
-rw-r--r--.  1 root     root      32870 Oct 31 15:01 CHANGELOG-1.4.md
-rw-r--r--.  1 root     root      18874 Oct 31 15:01 CHANGELOG-1.5.md
-rw-r--r--.  1 root     root      60981 Oct 31 15:01 CHANGELOG-1.6.md
-rw-r--r--.  1 root     root      37524 Oct 31 15:01 CHANGELOG-1.7.md
-rw-r--r--.  1 root     root      97879 Oct 31 15:01 CHANGELOG-2.0.md
-rw-r--r--.  1 root     root        143 Oct 31 15:01 LICENCE.txt
-rw-r--r--.  1 root     root       2322 Oct 31 15:01 README.md
-rw-r--r--.  1 root     root       5038 Oct 31 15:01 UPGRADE-1.1.md
-rw-r--r--.  1 root     root      10969 Oct 31 15:01 UPGRADE-1.2.md
-rw-r--r--.  1 root     root       9422 Oct 31 15:01 UPGRADE-1.3.md
-rw-r--r--.  1 root     root      24149 Oct 31 15:01 UPGRADE-1.4.md
-rw-r--r--.  1 root     root      24718 Oct 31 15:01 UPGRADE-1.5.md
-rw-r--r--.  1 root     root      58972 Oct 31 15:01 UPGRADE-1.6.md
-rw-r--r--.  1 root     root          0 Oct 31 15:01 UPGRADE-1.7.md
-rw-r--r--.  1 root     root      16370 Oct 31 15:01 UPGRADE-2.0.md
drwxr-xr-x.  6 root     root       4096 Oct 31 15:16 app
drwxr-xr-x.  3 root     root       4096 Oct 31 15:13 bin
-rw-r--r--.  1 root     root       3623 Oct 31 15:02 composer.json
-rw-r--r--.  1 root     root     193812 Oct 31 15:11 composer.lock
drwxr-xr-x.  2 root     root       4096 Oct 31 15:01 docker
-rw-r--r--.  1 root     root       1519 Oct 31 15:01 docker-compose.yml.dist
-rw-r--r--.  1 root     root       1871 Oct 31 15:01 package.json
drwxr-xr-x.  2 root     root       4096 Oct 31 15:01 src
drwxr-xr-x.  9 root     root       4096 Oct 31 15:11 upgrades
drwxr-xr-x.  4 root     root       4096 Oct 31 15:16 var
drwxr-xr-x. 43 root     root       4096 Oct 31 15:13 vendor
drwxr-xr-x.  5 www-data www-data   4096 Oct 31 15:15 web
```

I use this documentation https://docs.akeneo.com/2.0/install_pim/installation_ce_archive.html
I'm testing with pim-community-dev with composer and it's identical.

I'm testing with this very simple DockerFile 

```
FROM debian:latest
LABEL "maintainer"="Philippe Maladjian" \
"web"="https://www.blogoflip.fr" \
"description"="Docker for Akeneo" \
"version.os"="debian"
EXPOSE 80

RUN apt-get -y update
```

And install dependancy with this do https://docs.akeneo.com/2.0/install_pim/system_requirements/manual_system_installation_debian9.html, it's ok for yarn.

- Docker akeneo-fpm
- Debian 9.2
- Php 7.1.11-1
- Apache Server version: Apache/2.4.25 (Debian) - Server built:   2017-09-19T18:58:57
- mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- yarn 0.27

**Comment by tamarasaurus** [comment]
Hi @Philippe-M

Could you try with nodejs 8.2.1 and yarn 1.0.0 and let us know if you have any issues? 

Regards,
Tamara

**Comment by janmyszkier** [comment]
Let me add one comment here, because I hit this on new ubuntu install: 
The output:
`ERROR: [Errno 2] No such file or directory: 'install'`
is the output from `yarn` command installed from `cmdtest` package.
If you type `yarn`, ubuntu will suggest you to install `cmdtest` package that DOES provide yarn, but that's the not yarn you should be installing. do:
```
sudo apt-get remove cmdtest
```
and then follow normal yarn package installation suggested by:
https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_install_ubuntu_1604.html
once you run `yarn install` it will be all fine.
@tamarasaurus I think you can close this issue, it's not about PIM

**Comment by Doodoune** [comment]
Hi!

Thanks @janmyszkier for your answer! 

I close this issue.

Regards,
Elodie
