### ISSUE TITLE
ElasticSearch Notice: Undefined index: document_type

### ISSUE THREAD

**Issue by akosglue** [akeneo/pim-community-dev#7116]
@SamirBoulil 
Dear,
I got this 'Notice: Undefined index: document_type' on here:
https://github.com/akeneo/pim-community-dev/blob/1a8f43cf0834512c6288824b1c14809b4d2582e7/src/Pim/Bundle/EnrichBundle/Elasticsearch/FromSizeCursor.php#L130

What do you suggest? This happened after using the migration tool for migrating from 1.7 icecat to 2.0.6.
What would the effect be if we added a check if $hit['_source']['document_type'] is set?

**Comment by Doodoune** [comment]
Hi @akosglue!

Do you still have this issue?

Regards,

**Comment by akosglue** [comment]
Well, I have no idea, it was more than 1 year ago ... I moved on with this, it has not been a problem in the past year ...

**Comment by Doodoune** [comment]
Sorry for the delay...

I close this issue, but if you reproduce this issue, feel free to reopen it.

Regards,
