### ISSUE TITLE
How to move an attribute in variant level in product model

### ISSUE THREAD

**Issue by walkwizus** [akeneo/pim-community-dev#7129]
Hi,

I try to move an attribute in variant level but I don't see interface to do that. Is it possible ?

**Comment by LaureBro** [comment]
Hello @walkwizus, 

We're working on it :) It should be available soon from the UI. Currently it's only doable through imports.
We will keep you updated,

Kind regards, 
Laure

**Comment by walkwizus** [comment]
Hi @LaureBro ,

Thanks you so much ! If works through imports or API it's perfect :).

Regards,
Jimmy

**Comment by tamarasaurus** [comment]
Hi @walkwizus, this feature has been implemented in 2.0.7 (available since 2017-11-23)
