### ISSUE TITLE
Setting correct permissions

### ISSUE THREAD

**Issue by passboltUser** [akeneo/pim-community-dev#7143]
Following https://github.com/akeneo/pim-community-dev/issues/7131 where I set `chmod 777` to the whole Akeneo directory. What are the correct permissions to set?

**Comment by BitOne** [comment]
Hey @passboltUser ,

As you know, chmod 777 is definitely a bad practice. The correct permissions for the Akeneo directory would depend on your setup. From #7137, it seems you're using Ubuntu 16.04 with Akeneo 2.0.

In this case, once you setup FPM with the right users, Apache just need read only access to the Akeneo PIM `web/` directory.

It could be done this way:
 - Add read access for everybody to the web directory
`$ chmod -R a+rX /path/to/akeneo/web`
 - Make sure that everybody can reach the the `web/` directory
`$ chmod a+X /path/`
`$ chmod a+X /path/to/`
`$ chmod a+X /path/to/akeneo/`

The `web/` directory doesn't contains any data, so it's pretty safe.
Also, you may need to do it after each deployment or set the correct umask for the akeneo CLI user.

A slightly more secure approach would be to allow only the www-data group to access the `web/` directory.

**Comment by passboltUser** [comment]
Thanks, I'm using v2.0 on Ubuntu 16.04.
I decided to allow only the `www-data` group to access the `web/` directory:
`/var/www/html/akeneo/pim-community-standard# chown www-data:www-data web`, is this the correcy way to do it?

- Regarding `chown`: My directory looks like this:
```
/var/www/html/akeneo/pim-community-standard# ls -l
total 944
drwxrwxrwx   6 ubuntu   ubuntu     4096 Nov  9 16:15 app
drwxrwxrwx   3 ubuntu   ubuntu     4096 Nov 13 10:53 bin
-rwxrwxrwx   1 ubuntu   ubuntu    17102 Nov  3 18:27 CHANGELOG-1.0.md
-rwxrwxrwx   1 ubuntu   ubuntu    11092 Nov  3 18:27 CHANGELOG-1.1.md
-rwxrwxrwx   1 ubuntu   ubuntu    29419 Nov  3 18:27 CHANGELOG-1.2.md
-rwxrwxrwx   1 ubuntu   ubuntu    38379 Nov  3 18:27 CHANGELOG-1.3.md
-rwxrwxrwx   1 ubuntu   ubuntu    32870 Nov  3 18:27 CHANGELOG-1.4.md
-rwxrwxrwx   1 ubuntu   ubuntu    18874 Nov  3 18:27 CHANGELOG-1.5.md
-rwxrwxrwx   1 ubuntu   ubuntu    60981 Nov  3 18:27 CHANGELOG-1.6.md
-rwxrwxrwx   1 ubuntu   ubuntu    37524 Nov  3 18:27 CHANGELOG-1.7.md
-rwxrwxrwx   1 ubuntu   ubuntu    99869 Nov  3 18:27 CHANGELOG-2.0.md
-rwxrwxrwx   1 ubuntu   ubuntu     3623 Nov 10 11:11 composer.json
-rwxrwxrwx   1 ubuntu   ubuntu   193812 Nov 13 10:37 composer.lock
drwxrwxrwx   2 ubuntu   ubuntu     4096 Nov  3 18:27 docker
-rwxrwxrwx   1 ubuntu   ubuntu     1519 Nov  3 18:27 docker-compose.yml.dist
-rwxrwxrwx   1 ubuntu   ubuntu      143 Nov  3 18:27 LICENCE.txt
drwxrwxrwx 609 root     root      20480 Nov  9 15:05 node_modules
-rwxrwxrwx   1 ubuntu   ubuntu     1871 Nov  3 18:27 package.json
-rwxrwxrwx   1 ubuntu   ubuntu     2322 Nov  3 18:27 README.md
drwxrwxrwx   2 ubuntu   ubuntu     4096 Nov  3 18:27 src
-rwxrwxrwx   1 ubuntu   ubuntu     5038 Nov  3 18:27 UPGRADE-1.1.md
-rwxrwxrwx   1 ubuntu   ubuntu    10969 Nov  3 18:27 UPGRADE-1.2.md
-rwxrwxrwx   1 ubuntu   ubuntu     9422 Nov  3 18:27 UPGRADE-1.3.md
-rwxrwxrwx   1 ubuntu   ubuntu    24149 Nov  3 18:27 UPGRADE-1.4.md
-rwxrwxrwx   1 ubuntu   ubuntu    24718 Nov  3 18:27 UPGRADE-1.5.md
-rwxrwxrwx   1 ubuntu   ubuntu    58972 Nov  3 18:27 UPGRADE-1.6.md
-rwxrwxrwx   1 ubuntu   ubuntu        0 Nov  3 18:27 UPGRADE-1.7.md
-rwxrwxrwx   1 ubuntu   ubuntu    16370 Nov  3 18:27 UPGRADE-2.0.md
drwxrwxrwx  10 ubuntu   ubuntu     4096 Nov  3 18:50 upgrades
drwxrwxrwx   4 ubuntu   ubuntu     4096 Nov 13 10:53 var
drwxrwxrwx  43 ubuntu   ubuntu     4096 Nov 13 10:53 vendor
drwxrwxrwx   8 www-data www-data   4096 Nov 10 13:15 web
-rwxrwxrwx   1 root     root     163612 Nov  9 15:05 yarn.lock
```
There's `ubuntu`, `www-data` and `root`. Not sure if this is correct.

Ok, so `web` is better to be owned by `www-data` (`chown www-data:www-data web` ?), but how would the `chown` on the rest of the directorys look like?

- Regarding `chmod`: How the settings here look like?


You say permissions depend on the setup (maybe you can explain this?). My setup is to use it normally through the browser in a production environment. What would the permissions here look like?

**Comment by passboltUser** [comment]
I found http://symfony.com/doc/current/setup/file_permissions.html. Does this concern Akeneo? They mention `ACL`, but it's now for me. Do I need it or can I set everything using `chmod` and `chown`?

**Comment by BitOne** [comment]
This documentation definitely concerns Akeneo, and Akeneo documentation proposes the first solution (Use the same User for the CLI and the Web Server), but in our case, the "web server" is FPM (the solution title should be "application server", not "webserver").

In your current situation, I see 2 problems:
 - `node_modules` and `yarn.lock` belonging to root, which is really bad and shows that you executed yarn commands with the root user (which is very bad as well ;) )
 - `web` directory belonging to `www-data`. It should belongs to `ubuntu` and, as I said, be accessible for the `www-data` **group**

So I suggest you try the first solution I provided. And if everything works properly, you can try narrowing further the permissions with only the `www-data` **group**.

**Comment by passboltUser** [comment]
Ok, thanks.
