### ISSUE TITLE
MSSQL Server - Incorrect syntax near the keyword

### ISSUE THREAD

**Issue by inpronet** [akeneo/pim-community-dev#7145]
For MSSQL DB configuration I have a lot of errors related to using keywords

Example url:
/widget/last_operations

Error:
An exception occurred while executing 'SELECT a0_.id AS id_0, a0_.start_time AS start_time_1, a1_.type AS type_2, a1_.label AS label_3, a0_.status AS status_4, COUNT(a2_.id) AS sclr_5 FROM akeneo_batch_job_execution a0_ INNER JOIN akeneo_batch_job_instance a1_ ON a0_.job_instance_id = a1_.id LEFT JOIN akeneo_batch_step_execution a3_ ON a0_.id = a3_.job_execution_id LEFT JOIN akeneo_batch_warning a2_ ON a3_.id = a2_.step_execution_id WHERE a0_.user = 'admin' GROUP BY a0_.id, a0_.start_time, a1_.type, a1_.label, a0_.status ORDER BY a0_.start_time DESC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY':

SQLSTATE [42000, 156]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near the keyword 'user'.
SQLSTATE [42000, 153]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid usage of the option NEXT in the FETCH statement.
SQLSTATE [42000, 8180]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared.

**Comment by inpronet** [comment]
In this case the problem is in the file:
/src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobExecutionRepository.php
line: 102

I create own QuoteStrategy what solves that problem:
```
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Mapping\DefaultQuoteStrategy;

class QuoteStrategy extends DefaultQuoteStrategy
{
    private function quote($token, AbstractPlatform $platform)
    {
        switch ($platform->getName()) {
            case 'mssql':
                return '[' . $token . ']';
            default:
                return $token;
        }
    }

    public function getColumnName($fieldName, ClassMetadata $class, AbstractPlatform $platform)
    {
        return $this->quote($class->fieldMappings[$fieldName]['columnName'], $platform);
    }
}
```

**Comment by gplanchat** [comment]
@inpronet would you mind creating a compatibility bundle on [Foa](https://github.com/friendsofakeneo) ?

**Comment by BitOne** [comment]
Hello,

I'm sorry MSSQL server is not supported. See https://docs.akeneo.com/2.0/technical_architecture/technical_information/server_side_setup_for_hosting.html#system-requirements, section "Database server".

However, if you are able to reproduce the same problem on a supported environment (PHP, MYSQL, and Linux), we would be happy to look at it.
