### ISSUE TITLE
MSSQL Server does not support named parameters to queries, use question mark (?) placeholders instead

### ISSUE THREAD

**Issue by inpronet** [akeneo/pim-community-dev#7147]
For MSSQL DB configuration I have error

url:
/system_info

error:
sqlsrv does not support named parameters to queries, use question mark (?) placeholders instead.

**Comment by inpronet** [comment]
Problem is in:
/src/Pim/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManager.php
method: getPimInstallDateTime()

MSSQL Server don't have INFORMATION_SCHEMA table

**Comment by BitOne** [comment]
Hello,

I'm sorry MSSQL server is not supported. See https://docs.akeneo.com/2.0/technical_architecture/technical_information/server_side_setup_for_hosting.html#system-requirements, section "Database server".

Moreover, named parameter are far better for readability and maintainability.
