### ISSUE TITLE
MSSQL Server conversion problem

### ISSUE THREAD

**Issue by inpronet** [akeneo/pim-community-dev#7148]
For MSSQL DB configuration I have error

url:
/datagrid/import-profile-grid/load?jobType=import&localeCode=en_GB&params%5BjobType%5D=import&params%5BlocaleCode%5D=en_GB&import-profile-grid%5BjobType%5D=import&import-profile-grid%5BlocaleCode%5D=en_GB

error:
An exception occurred while executing 'SELECT a0_.id AS id_0, a0_.code AS code_1, a0_.label AS label_2, a0_.job_name AS job_name_3, a0_.status AS status_4, a0_.connector AS connector_5, a0_.raw_parameters AS raw_parameters_6, a0_.type AS type_7, a0_.job_name AS job_name_8, ('pim_import_export.status.' + a0_.status) AS sclr_9 FROM akeneo_batch_job_instance a0_ WHERE a0_.type = ? ORDER BY a0_.label ASC OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY' with params ["import"]:

SQLSTATE [22018, 245]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting the varchar value 'pim_import_export.status.' to data type int.

**Comment by inpronet** [comment]
Error is generated by
/src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobInstanceRepository.php
line: 36

The problem no longer appears after I change type field 'status' in 'akeneo_batch_job_instance' teble to varchar.

**Comment by BitOne** [comment]
Hello,

I'm sorry MSSQL server is not supported. See https://docs.akeneo.com/2.0/technical_architecture/technical_information/server_side_setup_for_hosting.html#system-requirements, section "Database server".

However, if you are able to reproduce the same problem on a supported environment (PHP, MYSQL, and Linux), we would be happy to look at it.
