### ISSUE TITLE
Confusing code at VersioningBundle/Normalizer/Flat/CollectionNormalizer.php

### ISSUE THREAD

**Issue by igormukhingmailcom** [akeneo/pim-community-dev#7159]
Hi, guys.

There are some confusing manipulations with `$result` variable at https://github.com/akeneo/pim-community-dev/blob/2.0/src/Pim/Bundle/VersioningBundle/Normalizer/Flat/CollectionNormalizer.php causing next warnings:

```
Warning: array_merge(): Argument #1 is not an array in vendor/akeneo/pim-community-dev/src/Pim/Bundle/VersioningBundle/Normalizer/Flat/CollectionNormalizer.php on line 47
PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in vendor/akeneo/pim-community-dev/src/Pim/Bundle/VersioningBundle/Normalizer/Flat/CollectionNormalizer.php on line 42

Warning: array_key_exists() expects parameter 2 to be array, string given in vendor/akeneo/pim-community-dev/src/Pim/Bundle/VersioningBundle/Normalizer/Flat/CollectionNormalizer.php on line 42
PHP Warning:  array_merge(): Argument #1 is not an array in vendor/akeneo/pim-community-dev/src/Pim/Bundle/VersioningBundle/Normalizer/Flat/CollectionNormalizer.php on line 47
```

[akeneo-pim-system-info_2017-11-15_02_30.txt](https://github.com/akeneo/pim-community-dev/files/1472982/akeneo-pim-system-info_2017-11-15_02_30.txt)

**Comment by Doodoune** [comment]
Hi!

Since 2 Janury 2018 (PR https://github.com/akeneo/pim-community-dev/commit/2948b2ff9160a87159cad812c1702cc60dc634e5#diff-04a9dfc0431a2c9bfa3825d743837f7b) we correct this issue. (replacing array_merge by array_replace)

I close this issue, but if you still have a problem feel free to re-open it.

Regards,
