### ISSUE TITLE
How to remove demo products?

### ISSUE THREAD

**Issue by passboltUser** [akeneo/pim-community-dev#7162]
I followed this tutorial: https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_install_ubuntu_1604.html ?
But unfortunately I can't remove any products if I select a product and click the remove button in here `/#/enrich/product/``the product is still there.

**Comment by passboltUser** [comment]
https://docs.akeneo.com/latest/install_pim/manual/installation_ce_archive.html -> wget https://download.akeneo.com/pim-community-standard-v2.0-latest.tar.gz #for minimal version
I dropped the database and the whole `pim-community-standard` folder. Downloaded this time the non-icecat, non-demo version `pim-community-standard-v2.0-latest.tar.gz`, installed, but unfortunately there are still 1049 Products.

**Comment by RainerBlessing** [comment]
This can be solved by adding "installer_data: 'PimInstallerBundle:minimal'" to app/config/parameters.yml.
This is described here: https://docs.akeneo.com/2.0/install_pim/customize_dataset/index.html
Running the command "php bin/console pim:installer:db --env=prod" didn't work for me, so I reinstalled akeneo. I am using the Docker containers.

**Comment by passboltUser** [comment]
Thanks. We froze Akeneo until next year. I will try it then.

**Comment by BatsaxIV** [comment]
Hi @passboltUser,

As @RainerBlessing answer your issue, you should probably closed it :)
You can also define your own datasets see [here](https://docs.akeneo.com/2.0/install_pim/customize_dataset/index.html#using-your-own-dataset)

**Comment by passboltUser** [comment]
Ok, thanks. I'm closing but may reopen if it wont work.

**Comment by andypmw** [comment]
I am facing the same issue,

answer from @RainerBlessing is correct. 
But if it doesn't fix your problem, please make sure you reset cache by using this command:
`php bin/console cache:clear --env=prod`
