### ISSUE TITLE
List category

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#7163]
Version : 2.0.6CE

In the category list the full name is not visible.

![image](https://user-images.githubusercontent.com/4558101/32886535-42a39b0e-cac1-11e7-8dc4-f05d9f1cf74c.png)

**Comment by LaureBro** [comment]
Hello @Philippe-M, this issue will be fixed in the next patch, the 2.0.7.
The patch will be released shortly, we'll keep you updated :)

**Comment by Philippe-M** [comment]
Ok, thanks

**Comment by tamarasaurus** [comment]
Hi @Philippe-M, this fix has been made in the 2.0.7 patch (available since 2017-11-23).
