### ISSUE TITLE
attribute group page not updated

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#7164]
Version : 2.0.6CE

After creating an attribute group or category, the page that lists them is not updated. I have to press the F5 key to force refresh and with the new element created.

My browser cache is disabled (Firefox 56, Fedora 26).

Before create group
![image](https://user-images.githubusercontent.com/4558101/32887579-a3749cdc-cac4-11e7-8d8d-9a686715c0d8.png)

Create "test" group
![image](https://user-images.githubusercontent.com/4558101/32887649-eb6d1ca8-cac4-11e7-896a-2881298ecc57.png)

![image](https://user-images.githubusercontent.com/4558101/32887657-f4af71da-cac4-11e7-8134-374ace5080e0.png)

When i'm return on "Attribute groups" page
![image](https://user-images.githubusercontent.com/4558101/32887664-fcad6cca-cac4-11e7-96d7-c3f2f7d1bbf0.png)

After press F5
![image](https://user-images.githubusercontent.com/4558101/32887672-02b9d5e0-cac5-11e7-9512-d1dfadee6853.png)

**Comment by Doodoune** [comment]
Hi!
I try on the version 2.0.51 and I don't reproduce this issue. So I think it's already resolved.
I close this ticket. 
Iif you still have an issue after upgrading your PIM on the last patch, feel free to reopen it.

Regards,
