### ISSUE TITLE
NODE_PATH=node_modules not recognized / yarn run webpack Error

### ISSUE THREAD

**Issue by KarlsDaddy** [akeneo/pim-community-dev#7191]
**I'm reporting a Bug / using the CommunityEdition**

I follow-up the akeneo-install-instruction (pim-community-standard-v2.0)
https://docs.akeneo.com/latest/install_pim/manual/installation_ce_archive.html#initializing-akeneo

**yarn run webpack** give me a error:

```
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
$ NODE_PATH=node_modules node $npm_package_config_check --source=$npm_package_config_source
'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
```

what am I doing `wrong?`

**Comment by pierallard** [comment]
Hi @Nico-Lausch 
What's your environment? OS? PIM exact version?

Regards

**Comment by Doodoune** [comment]
Hi!

I close this issue.
Feel free to reopen it with more detail if you still have this issue.

Regards,
