### ISSUE TITLE
Question: Feasibility for an option same like Channel

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [akeneo/pim-community-dev#7192]
Hi,

I would like to create an option (Region) which is same like Channel (Setting attributes for channel specific, locale specific) and allow to enter unique values for multiple Channel and locale specific attribute value in the product form.

Is it possible in Akeneo by Custom override ?

**Comment by aRn0D** [comment]
I am not sure I understand, What is the different between a Region and a Channel ?

**Comment by Vanitha-Ramkumar** [comment]
Hi aRn0D,

I want to create a generic product for different website and region specific attribute values with different locale.  Each website has different regions and locales. I will mention the value for channel, region and locale specific.

I'm using channel for specify different websites / stores and locales. I would like to create one more option as region which functions same like channel. Also creating the attributes which is specific to region.

Hope you can understand. Please let me know is this possible in the akeneo by custom development.

**Comment by Doodoune** [comment]
Hi @Vanitha-Ramkumar!

If you want to do this behavior you need to add custom development, but I can't say how many custom development you need. 

I close this issue, feel free to re-open it if needed.

Regards,
