### ISSUE TITLE
Can not install akeneo 1.7 with mongodb

### ISSUE THREAD

**Issue by RainerBlessing** [akeneo/pim-community-dev#7193]
When I run bin/docker/pim-initialize.sh I get this error message:

```
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  Unable to replace alias "pim_catalog.object_manager.product" with actual definition "doctrine.odm.mongodb.document_manager".



  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "doctrine.odm.mongodb.document_manager".


Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:


    [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]

    Unable to replace alias "pim_catalog.object_manager.product" with actual definition "doctrine.odm.mongodb.document_m
  anager".



    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
    You have requested a non-existent service "doctrine.odm.mongodb.document_manager".

  .

```

**Comment by RainerBlessing** [comment]
It seems the documentation (https://docs.akeneo.com/1.7/developer_guide/installation/docker/installation_docker.html) for mongodb is incomplete so I used https://github.com/s7b4/docker-akeneo/blob/master/akeneo/apache/scripts/entrypoint.sh

**Comment by damien-carcel** [comment]
Hello @RainerBlessing .

Indeed, it is incomplete, it misses this part: https://docs.akeneo.com/1.7/developer_guide/installation/setup_hybrid_storage_mysql_mongo.html.
I will add a link to it in the mongo part of the Docker installation.

Thanks for raising this issue to us.

Regards,
Damien

**Comment by damien-carcel** [comment]
Hello @RainerBlessing 

The documentation is now up to date for both 1.6 and 1.7, so I am closing the issue. Don't hesitate to reopen it (or a new one) if you find another error.

Regards,
Damien
