### ISSUE TITLE
session table missin

### ISSUE THREAD

**Issue by Saadkhalid87** [akeneo/pim-community-dev#7196]
**I'm reporting a Bug**

Getting this error message on fresh installation of Akeneo 2.0 CE any help would be great

[Wed Nov 22 22:50:27.509162 2017] [proxy_fcgi:error] [pid 23026:tid 140076893841152] [client 178.8.87.159:56214] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 144\nPHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 144\nPHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 144\nPHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist in /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105\nStack trace:\n#0 /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)\n#1 /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(509): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(278): Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\PdoSessionHandler->doRead('2pr5a4dn4n699cf...')\n#3 /var/www/html/pim.cubitabo.de/pim-community-standard/vendor/symfony/symfony/src/Symfony/Com...\n'

**Comment by Saadkhalid87** [comment]
Got it issue was related to server memory!

**Comment by Navds** [comment]
I'm having this after docker-compose down and up:

/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 145

Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /srv/pim/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 145

Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /srv/pim/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 145

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist in /srv/pim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 Stack trace: #0 /srv/pim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL) #1 /srv/pim/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(531): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /srv/pim/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php(92): Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler->doRead('nea8srqf5kq9231...') #3 /srv/pim/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(278): Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler->read('nea8srqf5kq9231...') #4 /srv/pim/vendor/symfony/symfony/src/Symfony/Component/HttpFoundati in /srv/pim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 107`

**Comment by benjR** [comment]
I have the exact the same issue, what was the solution for you @Navds ?

**Comment by Navds** [comment]
Sorry mate, totally forgot about his. 
I guess I made sure /var/lib/php/sessions exists and writable

**Comment by Aerendir** [comment]
For me creating the `sessions` folder and making it writable doesn't work.

How did you solved? I continue to get the error about the missing `akeneo_pim.pim_session` table in the database.

**Comment by Aerendir** [comment]
@Saadkhalid87 , how did you solved?

**Comment by Aerendir** [comment]
Ok, in the end I solved running `bin/docker/pim-front.sh`...

**Comment by sugalvojau** [comment]
I had the same error just few minutes ago. 
However, the root reason for such error was failing connection to Elasticsearch on my side.
The solution to this one may be found here:
https://github.com/akeneo/pim-community-dev/issues/6783

In short. Updating `index_hosts` (`app/config/parameters.yml` file) to `index_hosts: 'elastic:changeme@elasticsearch:9200'` solved the issue here..

**Comment by samarshahzad** [comment]
I am having the same issue but unable to resolve

request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist

**Comment by ppenelon** [comment]
Setting `index_hosts` in `app/config/parameters.yml` to `elasticsearch: 9200` and re-starting `bin/docker/pim-initialize.sh` did the trick.

Thanks @sugalvojau

**Comment by tallcoder** [comment]
> Using `docker-compose` (https://github.com/akeneo/pim-community-dev/blob/master/docker-compose.yml).
> 
> Setting `index_hosts` in `app/config/parameters.yml` to `elasticsearch: 9200` and re-starting `bin/docker/pim-initialize.sh` did the trick.
> 
> Thanks @sugalvojau

Thank you ... this was driving me nuts.
