### ISSUE TITLE
Selecting new Language in 2.0

### ISSUE THREAD

**Issue by objecta** [akeneo/pim-community-dev#7211]
Hi
I have finally successfully installed Akeneo PIM 2.0 and is now trying to select the Danish translation I have  translated using the following commands (in 1.7 this used to work)

php bin/console oro:translation:dump fr de en da --env=prod

Also this this the stpes descriped here

https://docs.akeneo.com/latest/install_pim/customize_dataset/add_translation_packs.html

But I'm getting this error

root@AkeneoPIM:/akeneo/pim-community-standard# php bin/console oro:translation:dump fr de en da --env=prod
08:59:44 ERROR     [console] Error thrown while running command "oro:translation:dump fr de en da --env=prod". Message: "Too many arguments, expected arguments "command" "locale"." ["error" => Symfony\Component\Console\Exception\RuntimeException { …},"command" => "oro:translation:dump fr de en da --env=prod","message" => "Too many arguments, expected arguments "command" "locale"."] []
08:59:44 ERROR     [console] Command "oro:translation:dump fr de en da --env=prod" exited with code "1" ["command" => "oro:translation:dump fr de en da --env=prod","code" => 1] []

The same error is shown with this command (no da)

php bin/console oro:translation:dump fr de en --env=prod

Best regards
Klaus E. Frederiksen
Denmark

**Comment by aRn0D** [comment]
You should use:
 
```bash
bin/console oro:translation:dump 'fr, de, en' --env=prod
```

Don't hesitate to ask help on the slack user group : https://akeneopim-ug.slack.com/?redir=%2Fmessages%2Fgeneral
