### ISSUE TITLE
Create an attribute with date time type

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [akeneo/pim-community-dev#7217]
Hi,

How to create an attribute with date time type ?

Any custom option is available to create ?

**Comment by aRn0D** [comment]
Hi Vanitha-Ramkumar

There is not complete documentation to explain how create a custom attribute type but you can use help on the slack user group https://akeneopim-ug.slack.com/?redir=%2Fmessages%2Fgeneral

**Comment by jahnaviL** [comment]
@Vanitha-Ramkumar were you able create attribute with type DateTime?
