### ISSUE TITLE
Unrecognized option "merge_strategy" under "oro_menu_config.tree.application_menu"

### ISSUE THREAD

**Issue by volkovmqx** [akeneo/pim-community-dev#7274]
In the navigation.yml i tried using the option merge_strategy according to the documentation, but there is no reference to that option, i tried to look into the code of pim but also i couldn't find any reference.

**Comment by aRn0D** [comment]
Which documentation? Akeneo, Oro? If it is Oro, we are using a old version of Oro, this option may not be supported.

**Comment by volkovmqx** [comment]
https://docs.akeneo.com/1.7/cookbook/ui_customization/how_to_customize_menu.html

**Comment by SamirBoulil** [comment]
Hello @volkovmqx !

Thank you for your question, as you identified an error in our documentation. The only supported options are specified in this configuration definition: https://github.com/akeneo/pim-community-dev/blob/1.7/src/Oro/Bundle/NavigationBundle/DependencyInjection/Configuration.php#L136.

I'm afraid the merge_strategy option is not available in our version of Oro.

**Comment by volkovmqx** [comment]
Hello @SamirBoulil, 
Thanks for your follow up, would you recommend any other idea to do the same behavior as the merge_strategy without statically write the menu entries ?

**Comment by LaureBro** [comment]
Hello @volkovmqx, 

I've checked with Samir and unfortunately we do not have any other solution to provide you on support's side. Like mentioned in the Support ticket, we advise you to contact our PS team with your specific needs for this customisation.

Kind regards, 
Laure

**Comment by Doodoune** [comment]
Hi!

I close this issue. Feel free to reopen it if needed.

Regards,
