### ISSUE TITLE
Job configuration 'since last job' doesn't work on install with fixtures

### ISSUE THREAD

**Issue by CNibbering** [akeneo/pim-community-dev#7309]
I can't add the 'updated' filter for a job on installation.

Method of reproduction:

* create a custom job for xls export
* create the fixtures for installation
* add a data filter for the field 'updated' with operator 'SINCE LAST JOB'  and value the name of the job. 

Result: Installation of job-fixtures fails. 
It errors that JobRepository::getLastJobExecution()  returns null, and there is no JobInstance given. 

Is there any way to go around this or can the filter really only be set on the job edit screen in the browser?

**Comment by Doodoune** [comment]
Hi!

What is the version of your PIM ?

Regards,

**Comment by Doodoune** [comment]
I close this issue. 
Feel free to reopen it if you still have this problem.

Regards,
