### ISSUE TITLE
[v2.0.8] No family when creating product

### ISSUE THREAD

**Issue by grosmanal** [akeneo/pim-community-dev#7314]
In Akeneo 2.0.8, I'm trying to create a product. When I want to choose the product family, none are shown.

It works fine in Akeneo 2.0.7 : the rest webservice called when clicking on the family field is : 
http://myAkeneoServer/configuration/family/rest?search=&options[locale]=fr_FR

whereas in Akeneo 2.0.8 the url called is : 
http://myAkeneoServer/?search=&options[limit]=20&options[page]=1&options[catalogLocale]=fr_FR

**Comment by akosglue** [comment]
any updates?

**Comment by aRn0D** [comment]
Hello @grosmanal

Could you reproduce this bug on the latest 2.0? Do your families have a translated label for the current locale?

Thank you.

**Comment by grosmanal** [comment]
I've just installed the fresh 2.0.10 version. I still reproduce the issue.
Every families have a label for each locale.

**Comment by pierallard** [comment]
On demo.akeneo.com, it works perfectly
Request URL:http://demo.akeneo.com/configuration/family/rest?search=&options%5Blimit%5D=20&options%5Bpage%5D=1&options%5BcatalogLocale%5D=en_US

Do you have some custom code on your installation ?

**Comment by grosmanal** [comment]
I've made a fresh install of Akeneo 2.0.9 and I cannot reproduce the issue… weird

Let's close it.
