### ISSUE TITLE
deleting attribute used as user grid filter, causes user view page can be displayed

### ISSUE THREAD

**Issue by jotalops** [akeneo/pim-community-dev#7319]
**I'm reporting a Bug**

**I'm using the Enterprise Edition** 1.7.14

After I deleted an attribute (rd_markets) used as a User grid filter, 
I can't access to the User page, because this error is thrown

[2017-12-14 16:43:07] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Attribute "rd_markets" does not exists")." at /local/akeneo-roca/vendor/akeneo/pim-enterprise-dev/src/PimEnterprise/Bundle/UserBundle/Resources/views/User/view.html.twig line 113 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Attribute \"rd_markets\" does not exists\"). at /local/akeneo-roca/vendor/akeneo/pim-enterprise-dev/src/PimEnterprise/Bundle/UserBundle/Resources/views/User/view.html.twig:113, LogicException(code: 0): Attribute \"rd_markets\" does not exists at /local/akeneo-roca/vendor/akeneo/pim-community-dev/src/Pim/Bundle/DataGridBundle/Twig/FilterExtension.php:51)"} []

System information
[akeneo-pim-system-info_2017-12-14_16_43.txt](https://github.com/akeneo/pim-community-dev/files/1559825/akeneo-pim-system-info_2017-12-14_16_43.txt)

**Comment by aRn0D** [comment]
Hello @jotalops,

Did you add this attribute to `Product grid filters`? I think it happens because we try to display the attribute in the form but it does not exists anymore. Thank for raising this issue.

**Comment by jotalops** [comment]
I dont think so, the Page that was raising the error was the user Page, not the product view.

Enviado desde IBM Verse


   Arnaud Langlade --- Re: [akeneo/pim-community-dev] deleting attribute used as user grid filter, causes user view page can be displayed (#7319) --- 
    De:"Arnaud Langlade" <notifications@github.com>A:"akeneo/pim-community-dev" <pim-community-dev@noreply.github.com>Cc:"jotalops" <jlopez@asmws.com>, "Mention" <mention@noreply.github.com>Fecha:mar., 26 dic. 2017 17:04Asunto:Re: [akeneo/pim-community-dev] deleting attribute used as user grid filter, causes user view page can be displayed (#7319)
  
  Hello @jotalops, 
 Did you add this attribute to Product grid filters? I think it happens because we try to display the attribute in the form but it does not exists anymore. Thank for raising this issue. 
 —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

P   Antes de imprimir este mensaje, asegúrese de que es necesario. El medio ambiente es cosa de todos. 
AVISO DE CONFIDENCIALIDAD 
Este mensaje se dirige exclusivamente a su destinatario y puede contener información privilegiada o confidencial. Si no es vd. el destinatario indicado, queda notificado de que la utilización, divulgación y/o copia sin autorización está prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción. 
This message is intended exclusively for its addressee and may contain information that is CONFIDENTIAL and protected by professional privilege. If you are not the intended recipient you are hereby notified that any dissemination, copy or disclosure of this communication is strictly prohibited by law. If this message has been received in error, please immediately notify us via e-mail and delete it.

**Comment by Doodoune** [comment]
Hi!
This issue is solved in the 2.3 version. (I tested it on demo.akeneo.com).
I close this issue, feel free to reopen it if you still have a problem.

Regards,
