### ISSUE TITLE
An error occurred during the fixtures execution.

### ISSUE THREAD

**Issue by kafayka** [akeneo/pim-community-dev#7359]
Hey,

I've tried to install akeneo on Ubuntu and face with this issue. I've test elasticsearch and it running, Here is an exception: 
Fixtures fixtures_user_csv has been successfully executed.
13:04:44 ERROR     [batch] Encountered an error executing the step: {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}} [] []
An error occurred during the fixtures execution.
Error #0 in class Akeneo\Bundle\ElasticsearchBundle\Exception\IndexationException: {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}}
#0 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/ElasticsearchBundle/Client.php(134): Akeneo\Bundle\ElasticsearchBundle\Client->throwIndexationExceptionFromReponse(Array)
#1 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Elasticsearch/Indexer/ProductModelIndexer.php(115): Akeneo\Bundle\ElasticsearchBundle\Client->bulkIndexes('pim_catalog_pro...', Array, 'id', Object(Akeneo\Bundle\ElasticsearchBundle\Refresh))
#2 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/EventSubscriber/IndexProductModelsSubscriber.php(96): Pim\Bundle\CatalogBundle\Elasticsearch\Indexer\ProductModelIndexer->indexAll(Array)
#3 [internal function]: Pim\Bundle\CatalogBundle\EventSubscriber\IndexProductModelsSubscriber->bulkIndexProductModels(Object(Symfony\Component\EventDispatcher\GenericEvent), 'akeneo.storage....', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\EventDispatcher\GenericEvent), 'akeneo.storage....', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#5 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'akeneo.storage....', Object(Symfony\Component\EventDispatcher\GenericEvent))
#6 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php(102): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('akeneo.storage....', Object(Symfony\Component\EventDispatcher\GenericEvent))
#7 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Component/Connector/Writer/Database/ProductModelWriter.php(62): Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSaver->saveAll(Array)
#8 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php(185): Pim\Component\Connector\Writer\Database\ProductModelWriter->write(Array)
#9 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php(130): Akeneo\Component\Batch\Step\ItemStep->write(Array)
#10 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/AbstractStep.php(100): Akeneo\Component\Batch\Step\ItemStep->doExecute(Object(Akeneo\Component\Batch\Model\StepExecution))
#11 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(263): Akeneo\Component\Batch\Step\AbstractStep->execute(Object(Akeneo\Component\Batch\Model\StepExecution))
#12 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(226): Akeneo\Component\Batch\Job\Job->handleStep(Object(Akeneo\Component\Batch\Step\ItemStep), Object(Akeneo\Component\Batch\Model\JobExecution))
#13 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(160): Akeneo\Component\Batch\Job\Job->doExecute(Object(Akeneo\Component\Batch\Model\JobExecution))
#14 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php(155): Akeneo\Component\Batch\Job\Job->execute(Object(Akeneo\Component\Batch\Model\JobExecution))
#15 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(264): Akeneo\Bundle\BatchBundle\Command\BatchCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(892): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Akeneo\Bundle\BatchBundle\Command\BatchCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(81): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(130): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php(60): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php(200): Pim\Bundle\InstallerBundle\CommandExecutor->runCommand('akeneo:batch:jo...', Array)
#22 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php(110): Pim\Bundle\InstallerBundle\Command\DatabaseCommand->loadFixturesStep(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(264): Pim\Bundle\InstallerBundle\Command\DatabaseCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(892): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\DatabaseCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(81): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(130): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php(60): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php(119): Pim\Bundle\InstallerBundle\CommandExecutor->runCommand('pim:installer:d...')
#30 /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php(69): Pim\Bundle\InstallerBundle\Command\InstallCommand->databaseStep()
#31 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(264): Pim\Bundle\InstallerBundle\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(892): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(81): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(130): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/pim-community-standard/bin/console(30): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#37 {main}
13:04:44 ERROR     [console] Command "akeneo:batch:job fixtures_product_model_csv --no-debug=1 --no-log=1 -v=1 --env=prod" exited with code "1" ["command" => "akeneo:batch:job fixtures_product_model_csv --no-debug=1 --no-log=1 -v=1 --env=prod","code" => 1] []
The command terminated with an error code: 1.

  [Exception (1)]
  The command terminated with an error code: 1.

Exception trace:
 () at /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php:66
 Pim\Bundle\InstallerBundle\CommandExecutor->runCommand() at /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php:200
 Pim\Bundle\InstallerBundle\Command\DatabaseCommand->loadFixturesStep() at /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php:110
 Pim\Bundle\InstallerBundle\Command\DatabaseCommand->execute() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:892
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:228
 Symfony\Component\Console\Application->doRun() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:130
 Symfony\Component\Console\Application->run() at /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php:60
 Pim\Bundle\InstallerBundle\CommandExecutor->runCommand() at /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php:119
 Pim\Bundle\InstallerBundle\Command\InstallCommand->databaseStep() at /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php:69
 Pim\Bundle\InstallerBundle\Command\InstallCommand->execute() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:892
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:228
 Symfony\Component\Console\Application->doRun() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:130
 Symfony\Component\Console\Application->run() at /var/www/html/pim-community-standard/bin/console:30

**Comment by akosglue** [comment]
any updates on this?

**Comment by akosglue** [comment]
I have installed ES version 6.0.1, whereas the sys. req. of akeneo is 5.5 ≤ version < 6.0

I am trying the installation now with the correct version.

**Comment by akosglue** [comment]
the installation is successful with elastic search 5.6.4

**Comment by Vanitha-bujjinga** [comment]
I have successfully installed Akeneo 2.0 with Elastic search 6.1.1. But when I try to install Akeneo 2.1, I got the below error.

Fixtures fixtures_user_csv has been successfully executed.
14:28:35 WARNING   [translation] Translation not found. ["id" => "{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}}","domain" => "messages","locale" => "en"] []
14:28:35 ERROR     [batch] Encountered an error executing the step: {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}} [] []
An error occurred during the fixtures execution.
Error #0 in class Akeneo\Bundle\ElasticsearchBundle\Exception\IndexationException: {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}}
#0 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/ElasticsearchBundle/Client.php(134): Akeneo\Bundle\ElasticsearchBundle\Client->throwIndexationExceptionFromReponse(Array)
#1 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Elasticsearch/Indexer/ProductModelIndexer.php(115): Akeneo\Bundle\ElasticsearchBundle\Client->bulkIndexes('pim_catalog_pro...', Array, 'id', Object(Akeneo\Bundle\ElasticsearchBundle\Refresh))
#2 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/EventSubscriber/IndexProductModelsSubscriber.php(96): Pim\Bundle\CatalogBundle\Elasticsearch\Indexer\ProductModelIndexer->indexAll(Array)
#3 [internal function]: Pim\Bundle\CatalogBundle\EventSubscriber\IndexProductModelsSubscriber->bulkIndexProductModels(Object(Symfony\Component\EventDispatcher\GenericEvent), 'akeneo.storage....', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#4 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(104): call_user_func(Array, Object(Symfony\Component\EventDispatcher\GenericEvent), 'akeneo.storage....', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#5 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\EventDispatcher\GenericEvent), 'akeneo.storage....', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#6 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'akeneo.storage....', Object(Symfony\Component\EventDispatcher\GenericEvent))
#7 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('akeneo.storage....', Object(Symfony\Component\EventDispatcher\GenericEvent))
#8 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php(102): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('akeneo.storage....', Object(Symfony\Component\EventDispatcher\GenericEvent))
#9 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Component/Connector/Writer/Database/ProductModelWriter.php(62): Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSaver->saveAll(Array)
#10 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php(185): Pim\Component\Connector\Writer\Database\ProductModelWriter->write(Array)
#11 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php(130): Akeneo\Component\Batch\Step\ItemStep->write(Array)
#12 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/AbstractStep.php(100): Akeneo\Component\Batch\Step\ItemStep->doExecute(Object(Akeneo\Component\Batch\Model\StepExecution))
#13 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(263): Akeneo\Component\Batch\Step\AbstractStep->execute(Object(Akeneo\Component\Batch\Model\StepExecution))
#14 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(226): Akeneo\Component\Batch\Job\Job->handleStep(Object(Akeneo\Component\Batch\Step\ItemStep), Object(Akeneo\Component\Batch\Model\JobExecution))
#15 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(160): Akeneo\Component\Batch\Job\Job->doExecute(Object(Akeneo\Component\Batch\Model\JobExecution))
#16 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php(155): Akeneo\Component\Batch\Job\Job->execute(Object(Akeneo\Component\Batch\Model\JobExecution))
#17 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): Akeneo\Bundle\BatchBundle\Command\BatchCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(954): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRunCommand(Object(Akeneo\Bundle\BatchBundle\Command\BatchCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(240): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Akeneo\Bundle\BatchBundle\Command\BatchCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php(60): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php(200): Pim\Bundle\InstallerBundle\CommandExecutor->runCommand('akeneo:batch:jo...', Array)
#25 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php(110): Pim\Bundle\InstallerBundle\Command\DatabaseCommand->loadFixturesStep(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): Pim\Bundle\InstallerBundle\Command\DatabaseCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(954): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\DatabaseCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(240): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\DatabaseCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php(60): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php(119): Pim\Bundle\InstallerBundle\CommandExecutor->runCommand('pim:installer:d...')
#34 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php(69): Pim\Bundle\InstallerBundle\Command\InstallCommand->databaseStep()
#35 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): Pim\Bundle\InstallerBundle\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(954): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(240): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/html/learning/akeneo/akeneo_composer_2_1/pim-community-standard/bin/console(30): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#42 {main}
The command terminated with an error code: 1.

In CommandExecutor.php line 66:
                                                 
  [Exception (1)]                                
  The command terminated with an error code: 1.

**Comment by akosglue** [comment]
For akeneo 2.1 you need this: 
Elasticsearch | 5.5 ≤ version < 6.0


https://docs.akeneo.com/2.1/install_pim/manual/system_requirements/system_requirements.html

**Comment by Vanitha-bujjinga** [comment]
Thanks for the response.
The same Elasticsearch | 5.5 ≤ version < 6.0 is mentioned in the 2.0 too. But I installed 2.0 without any error.
https://docs.akeneo.com/2.0/install_pim/manual/system_requirements/system_requirements.html

Have you installed 2.1 version after changing the elastic search (5.6.4) ?

**Comment by akosglue** [comment]
Yep, I could install 2.1.0 with ES 5.6.4

**Comment by Doodoune** [comment]
Hi!

Do you still have this issue in the latest version?

Regards,
Elodie

**Comment by Doodoune** [comment]
Hi! I close this issue. Feel free to reopen it, if you still have this problem.

Regards,
