### ISSUE TITLE
Throw an actual error message in product import

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [akeneo/pim-community-dev#7364]
Hi,

I got the below error for import product with a large CSV file. I didn't receive any warning / validation error message. I have debugged the Job execution/tracker. But I couldn't get the root cause of the issue.  How to throw an actual error during the import process?

**PRODUCT IMPORT IN CSV  An exception occured during the job execution.**

**Comment by aRn0D** [comment]
Hello @Vanitha-Ramkumar,

Could you have a look to your symfony logs (vat/logs or app/logs depending on your version) BTW, which version are you using please?

Thank you

**Comment by Doodoune** [comment]
Hi!

I'm closing this issue.
Feel free to re-open it if you still have this issue.

Regards,
Elodie
