### ISSUE TITLE
Reference Data Collection doesn't load when attached Entity has multiple cardinalities

### ISSUE THREAD

**Issue by Schwierig** [akeneo/pim-community-dev#7365]
It's pretty hard to easily reproduce this bug, but I'm sure that everyone is on par with me that an `in_array` function which compares objects should be strict anyway.

This bug will be fixed by changing the `ReferenceDataCollectionValueFactory::getReferenceDataCollection` function to use a strict `in_array`

**Comment by aRn0D** [comment]
Hello @Schwierig,

Which version are you using please ?

Thank you.

**Comment by aRn0D** [comment]
ah I did not see https://github.com/akeneo/pim-community-dev/pull/7366

**Comment by pierallard** [comment]
The PR was merged, I close this, thanks again @Schwierig !! :tada:
