### ISSUE TITLE
It's not possible to close compare / translate view in product sheet

### ISSUE THREAD

**Issue by juskor-mt** [akeneo/pim-community-dev#7371]
I'm reporting a Bug 

When user opens compare / translate view in the product sheet, he is not able to close that view without leaving a product context. This has been a problem since at least 2.0.6 and exists also in the 2.0.9.

**Comment by LaureBro** [comment]
Hello @juskor-mt, 
Thanks for raising this, it issue will be fixed in the next patch :)
It should be available very soon.

**Comment by aRn0D** [comment]
I close this issue because the 2.0.10 has been release, please reopen it you still encounter this issue.
