### ISSUE TITLE
Product Export Connector - Output channel in the filter value does not change

### ISSUE THREAD

**Issue by AndreSalier** [akeneo/pim-community-dev#7379]
If I add a filter value, it is not possible to change the output channel for the filter value. The first value of the selection list is always selected.
<img width="584" alt="bildschirmfoto 2017-12-22 um 04 20 28" src="https://user-images.githubusercontent.com/34760035/34284232-beb369ec-e6d0-11e7-8a1e-d92d135a64f0.png">
<img width="532" alt="bildschirmfoto 2017-12-22 um 04 20 38" src="https://user-images.githubusercontent.com/34760035/34284237-c5d101f8-e6d0-11e7-9d95-ac2136213483.png">

**Comment by aRn0D** [comment]
Hello @AndreSalier,

Could tell us a little bit more? Which version are you using? Moreover could you describe step by step what happens? I am not sure that I understand on which page you are.

Thank you.

**Comment by AndreSalier** [comment]
Hello Arnaud,
we use the Akeneo version 2.0.6.
The demo system at http://demo.akeneo.com/ uses version 2.1.0 and the same error occurs there.
The problem is at the csv product export connector.
http://demo.akeneo.com/#/spread/export/csv_product_export/edit
Under the tab "Content" there is the possibility to add attributes for filtering in "Filter the Products".
If an added attribute for multiple channels has values, you can set the output channel to apply the filter for the selected channel. But it does not work.
I can not select the output channels "print" or "mobile".
It always shows the first entry in the "Ecommerce" list as a selection.
Thank you for your help


<img width="1389" alt="bildschirmfoto 2017-12-27 um 04 56 22" src="https://user-images.githubusercontent.com/34760035/34370450-781ed2a8-eac4-11e7-95b7-653d42f0b5df.png">



<img width="1374" alt="bildschirmfoto 2017-12-27 um 04 52 31" src="https://user-images.githubusercontent.com/34760035/34370459-8d2ebbfe-eac4-11e7-9609-def545444003.png">



<img width="1389" alt="bildschirmfoto 2017-12-27 um 04 58 01" src="https://user-images.githubusercontent.com/34760035/34370475-a3e57cde-eac4-11e7-96e9-02943a1f138d.png">



<img width="1383" alt="bildschirmfoto 2017-12-27 um 04 58 35" src="https://user-images.githubusercontent.com/34760035/34370482-af30d340-eac4-11e7-9aef-459dc5c6edd0.png">

**Comment by riconeitzel** [comment]
:+1:

**Comment by pierallard** [comment]
Hi @AndreSalier @riconeitzel 
I just take a look at the issue, and you're right, there is a bug on this part. We added it to our internal bug list under number SDS-2488.
Please consider than Akeneo PIM is open source (implying no "ASAP") and any pull request is welcome!

Regards
Pierre

**Comment by LaureBro** [comment]
Hello,

This issue cannot be reproduced anymore on the latest 2.0 version, the 2.0.52 nor on above versions, like 2.3.43.

I will close this issue.

Kind regards, 
Laure
