### ISSUE TITLE
BUG: Type error: Return value of Pim\Component\Catalog\Model\AbstractAssociation::getProductModels() must implement interface Doctrine\Common\Collections\Collection, null returned

### ISSUE THREAD

**Issue by omolto** [akeneo/pim-community-dev#7417]
Hi folks,

It seems maybe Santa didn't ran all the tests for the new 2.1 version... ;)

Steps to reproduce:
1. Install a fresh 2.1 version using composer
2. Create a new attribute called name
3. Create a new family and add the sku and name fields
3. Create a product with the new family and fill the sku and name fields
4. Try to edit the created product, a 500 error shows. On var/logs/prod.log it shows:
`Type error: Return value of Pim\Component\Catalog\Model\AbstractAssociation::getProductModels() must implement interface Doctrine\Common\Collections\Collection, null returned`

Trying to debug it, we found that this error doesn't happen on the following scenarios:
A. You create a new product without a family and try to edit it.
B. You create a new product with a family but only fill the sku field on the creation. You would be able to edit the product but if you fill the name and save it you would not be able to edit again.

We would appreciate your help.

Thanks,

**Comment by crapougnax** [comment]
Same here after an upgrade from 2.0.9 with all preexisting products.

Thanks.

**Comment by crapougnax** [comment]
Rollback to 2.0.10 is impossible because of an exception during post-update with the symfony/symfony package updated to 3.4.2:

[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "setMinDepth" of class "Symfony\Component\
  VarDumper\Cloner\VarCloner"

Rollback to 2.0.9 works fine.

**Comment by akosglue** [comment]
any updates ?

**Comment by omolto** [comment]
Hi,

We have tried with icecat and minimal dataset and the same error occurs. Also updating from an early version as @crapougnax said.

Unfortunately version 2.1.0 is completely useless.

**Comment by juliensnz** [comment]
Hi guys,

I take a look at this issue and will keep you updated.

**Comment by juliensnz** [comment]
Hi guys,

I will take this issue and try to reproduce it. I will get back to you as soon as I have update.

**Comment by juliensnz** [comment]
Ok so I cannot reproduce this bug on my local machine and I just checked with @omolto and it seems that it's cache related.

Please can you tell me if doing:

    rm -rf ./var/cache

and restart your apache/php server fix the issue?

**Comment by omolto** [comment]
Hi,

As @juliensnz says, clearing the cache and restarting php solves the problem.

It seems it is related to a weird opcache messing.

Thanks!!
