### ISSUE TITLE
Issue in elasticsearch during akeneo installation

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7440]
I am trying to install the akeneo community edition v2.0, that the time I got an issue in elastic search. 
Please find the error given below and advice to fix it

_**Elasticsearch\Common\Exceptions\BadRequest400Exception  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No han  
  dler for type [keyword] declared on field [identifier]"}],"type":"mapper_pa  
  rsing_exception","reason":"Failed to parse mapping [pim_catalog_product]: N  
  o handler for type [keyword] declared on field [identifier]","caused_by":{"  
  type":"mapper_parsing_exception","reason":"No handler for type [keyword] de  
  clared on field [identifier]"}},"status":400} .**_

**Comment by akosglue** [comment]
is your elastic search version the same as the required version for akeneo ?

**Comment by juliensnz** [comment]
As the elastic search version seems to be the problem, I close the issue. DOn't hesitate to reopen it if needed :)
