### ISSUE TITLE
Cannot Bulk Delete Products

### ISSUE THREAD

**Issue by oritzvielli** [akeneo/pim-community-dev#7444]
**I'm reporting a Bug**

CE Version 2.0.10, go to "Products", checkbox specific product, go down to select dropdown and select all and click on "Delete". 

Next window shows delete button but it says, you click on it and after click, confirmation says "no products to remove"

**Comment by pierallard** [comment]
Hi @oritzvielli !
This bug should be fixed with the 2.0.11
https://github.com/akeneo/pim-community-dev/pull/7406

Feel free to repoen the ticket if this patch does not fix your issue.
