### ISSUE TITLE
Download link for Communiity edition 2.1

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7455]
Hi,

Where I can download the latest version (2.1) of the minimal archive

**Comment by pierallard** [comment]
You will find releases in this page
https://github.com/akeneo/pim-community-standard/releases

Regards

**Comment by Vanitha-bujjinga** [comment]
pierallard,

I want to download 2.1.0, but you have shared the link for 2.0.11.

**Comment by Vanitha-bujjinga** [comment]
@pierallard , 
Thank you.
