### ISSUE TITLE
Issue in installing akeneo 2.1

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7459]
Hi,

I got the following error while installing akeneo 2.1. Please suggest me to fix this issue.

13:28:03 ERROR     [batch] Encountered an error executing the step: {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}} [] []
An error occurred during the fixtures execution.
Error #0 in class Akeneo\Bundle\ElasticsearchBundle\Exception\IndexationException: {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}}

**Comment by pierallard** [comment]
Can you provide us the version of ElasticSearch you installed and check it's the same than the one asked in the requirements ?
https://docs.akeneo.com/2.1/install_pim/manual/system_requirements/system_requirements.html

Regards

**Comment by Vanitha-bujjinga** [comment]
Thanks for the response.
I have installed Elastic search 6.1 and I downgrade to 5.6.4 now. It is working fine.

My question is Akeneo 2.0 successfully installed with ES 6.1, but Akeneo 2.1 requires to install less than 6.0.

**Comment by pierallard** [comment]
Yes, the signature of ES queries changes a little bit between versions that's why we recommend to use strict version numbers.
I close this ticket, thanks for your return.

Regards
