### ISSUE TITLE
Export and Import are not responding in akeneo enterprise and community edition v2.1.0

### ISSUE THREAD

**Issue by nandhinimaris** [akeneo/pim-community-dev#7464]
Hi 
In Akeneo Enterprise / Community Edition Version 2.1.0., The export and import are not responding, when the click on the export it will show only starting it never get ended.

**Comment by omolto** [comment]
Hi @nandhinimaris ,

Did you check if job queue daemon is running? 

You can check it here: https://docs.akeneo.com/2.1/install_pim/manual/daemon_queue.html


Best,

**Comment by nandhinimaris** [comment]
Thank you, this issue was fixed
