### ISSUE TITLE
Export product attributes by attribute sort order

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7476]
Hi,

I want to export product attribute data with the same sorting order (assigned in the attribute group) which is shown in the product form. Any one please help me ?

**Comment by Vanitha-bujjinga** [comment]
I'm waiting for the response.

**Comment by Doodoune** [comment]
Hi @Vanitha-bujjinga!

Did you still have this issue? 
Normally when you export product values it's exported in the order defined in your export profile for your selected attributes, but the order is not applicable to the locales (for localizable attributes).
If you need a different behavior you need custom development. 

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to re-open if you still have an issue.

Regards,
