### ISSUE TITLE
Update the ES query builder for boolean fields

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#7510]
The system requirements currently states Akeneo requires ES 5.5, it works with 5.6, but not with 6.0 and next. It was already mentioned in #7459

The ES docs states :

> Deprecated in 5.1.0.
> While Elasticsearch will currently accept the above values during index time. Searching a boolean field using these pseudo-boolean values is deprecated. Please use "true" or "false" instead.
> 
> Deprecated in 5.3.0.
> Usage of any value other than false, "false", true and "true" is deprecated.

https://www.elastic.co/guide/en/elasticsearch/reference/5.6/boolean.html

**Comment by wimulkeman** [comment]
Is ES 5 the only supported ES version? If so, then that should make supporting both 5 and 6 easier as most things which are supported in 6 are also already available in 5.

**Comment by damien-carcel** [comment]
Hi there.

We currently only support ES 5.5 and 5.6, as stated in the system requirements: `Elasticsearch : 5.5 ≤ version < 6.0`

There is new stuff in ES 6 that will probably broke the PIM. So we will not do an update on ES 6 before Akeneo PIM 3.0, our next major update.

Regards,
Damien.

**Comment by wimulkeman** [comment]
@damien-carcel Would you accept an pull request if I could invest some time looking into the support possibilities of ES 6?

**Comment by damien-carcel** [comment]
Of course. If it doesn't break the current behavior with ES 5.5, no problem with that 😃.

**Comment by damien-carcel** [comment]
We love contributions 🎉

**Comment by simonmaass** [comment]
@wimulkeman any update here?

**Comment by wimulkeman** [comment]
@simonmaass Unfortunately not. Up to this far I didn't have the time to dive into it.

**Comment by simonmaass** [comment]
@wimulkeman oright :-) no probs..
