### ISSUE TITLE
Product Import: Unable to import large amount of products with the attributes

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7522]
Hi,

I'm using Akeneo 2.1. I have tried to import 1008 attributes and 47000 products. But it allows me to import only 2000 records. Please assist me.

**Comment by Doodoune** [comment]
Hi!

If you still have this issue, can you explain me in detail your problem step by step?
Does it import 2000 records of attributes or products?

Regards,
Elodie

**Comment by Doodoune** [comment]
I close this issue,
Feel free to reopen it if you still have this issue.

Regards,
