### ISSUE TITLE
How to update from 2.0.6 to 2.0.12?

### ISSUE THREAD

**Issue by passboltUser** [akeneo/pim-community-dev#7528]
We have version 2.0.6, but 2.0.12 is available, how to update to this version?

**Comment by passboltUser** [comment]
I'm asking because e.g. Passbolt does document and help one on how to update, even with the different versions (MAJOR/MINOR/PATCH): https://www.passbolt.com/help/tech/update.

**Comment by damien-carcel** [comment]
Hello.

This is documented here: https://docs.akeneo.com/latest/migrate_pim/index.html#patch-version

Regards,
Damien.

**Comment by Doodoune** [comment]
Hi!

I close this issue. Feel free to open it if you still have a problem.

Regards,
Elodie
