### ISSUE TITLE
Deleting a product family fails

### ISSUE THREAD

**Issue by mmergenthaler** [akeneo/pim-community-dev#7529]
[akeneo-pim-system-info_2018-01-23_16_57.txt](https://github.com/akeneo/pim-community-dev/files/1656642/akeneo-pim-system-info_2018-01-23_16_57.txt)
If you try to delete a product family, that fails with following error in prod.log:

`[2018-01-23 16:18:04] request.INFO: Matched route "pim_enrich_family_rest_remove". {"route":"pim_enrich_family_rest_remove","route_parameters":{"_controller":"pim_enrich.controller.rest.family:removeAction","code":"Einzelbeitrag2","_route":"pim_enrich_family_rest_remove"},"request_uri":"http://akeneo.raabe.mosaiq.com/configuration/family/rest/Einzelbeitrag2","method":"DELETE"} []
[2018-01-23 16:18:04] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'DELETE FROM pim_catalog_family WHERE id = ?' with params [3]:  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`akeneo`.`pim_catalog_family_variant`, CONSTRAINT `FK_FBA5AB45C35E566A` FOREIGN KEY (`family_id`) REFERENCES `pim_catalog_family` (`id`))" at /pool/akeneo/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'DELETE FROM pim_catalog_family WHERE id = ?' with params [3]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`akeneo`.`pim_catalog_family_variant`, CONSTRAINT `FK_FBA5AB45C35E566A` FOREIGN KEY (`family_id`) REFERENCES `pim_catalog_family` (`id`)) at /pool/akeneo/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`akeneo`.`pim_catalog_family_variant`, CONSTRAINT `FK_FBA5AB45C35E566A` FOREIGN KEY (`family_id`) REFERENCES `pim_catalog_family` (`id`)) at /pool/akeneo/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`akeneo`.`pim_catalog_family_variant`, CONSTRAINT `FK_FBA5AB45C35E566A` FOREIGN KEY (`family_id`) REFERENCES `pim_catalog_family` (`id`)) at /pool/akeneo/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[akeneo-pim-system-info_2018-01-23_16_57.txt](https://github.com/akeneo/pim-community-dev/files/1656629/akeneo-pim-system-info_2018-01-23_16_57.txt)
`

How to reproduce:
* Log in to http://demo.akeneo.com/ with "admin:admin"
* Go to Settings > Families
* Try to delete family with name "Accessories"

**Comment by rainmikko** [comment]
I found same problem. Delete fails if family has variants. And UI does not allow you to delete family variants. There is not such action available when editing families. It should be allowed to delete variants from family.

**Comment by silwol** [comment]
This is the one single biggest issue I've stumbled upon when using Akeneo. It totally blocks me from getting back to a clean data pool as soon as employees made a mistake when creating variants. The attributes used as axes are locked. Either being able to delete the variants (provided that no products exist for them) or product families which contain variants would provide an escape here.

**Comment by nblock** [comment]
Three foreign key constraints are missing `ON CASCADE DELETE`. A workaround is to use the following SQL script:
```
START TRANSACTION;

-- Add cascading deletes to constraints
ALTER TABLE `pim_catalog_family_variant` DROP FOREIGN KEY `FK_FBA5AB45C35E566A`;
ALTER TABLE `pim_catalog_family_variant` ADD CONSTRAINT `FK_FBA5AB45C35E566A` FOREIGN KEY (`family_id`) REFERENCES `pim_catalog_family` (`id`) ON DELETE CASCADE;
ALTER TABLE `pim_catalog_family_variant_has_variant_attribute_sets` DROP FOREIGN KEY `FK_1F4DC7028A37AD0`;
ALTER TABLE `pim_catalog_family_variant_has_variant_attribute_sets` ADD CONSTRAINT `FK_1F4DC7028A37AD0` FOREIGN KEY (`family_variant_id`) REFERENCES `pim_catalog_family_variant` (`id`) ON DELETE CASCADE;
ALTER TABLE `pim_catalog_product_model` DROP FOREIGN KEY `FK_5943911E8A37AD0`;
ALTER TABLE `pim_catalog_product_model` ADD CONSTRAINT `FK_5943911E8A37AD0` FOREIGN KEY (`family_variant_id`) REFERENCES `pim_catalog_family_variant` (`id`) ON DELETE CASCADE;

-- Delete the desired entry
DELETE FROM pim_catalog_family WHERE id=THE_ID_TO_DELETE;

-- Restore the original constraints
ALTER TABLE `pim_catalog_family_variant` DROP FOREIGN KEY `FK_FBA5AB45C35E566A`;
ALTER TABLE `pim_catalog_family_variant` ADD CONSTRAINT `FK_FBA5AB45C35E566A` FOREIGN KEY (`family_id`) REFERENCES `pim_catalog_family` (`id`);
ALTER TABLE `pim_catalog_family_variant_has_variant_attribute_sets` DROP FOREIGN KEY `FK_1F4DC7028A37AD0`;
ALTER TABLE `pim_catalog_family_variant_has_variant_attribute_sets` ADD CONSTRAINT `FK_1F4DC7028A37AD0` FOREIGN KEY (`family_variant_id`) REFERENCES `pim_catalog_family_variant` (`id`);
ALTER TABLE `pim_catalog_product_model` DROP FOREIGN KEY `FK_5943911E8A37AD0`;
ALTER TABLE `pim_catalog_product_model` ADD CONSTRAINT `FK_5943911E8A37AD0` FOREIGN KEY (`family_variant_id`) REFERENCES `pim_catalog_family_variant` (`id`);

COMMIT;
```
* Set the `pim_catalog_family` ID accordingly
* Update the names of the foreign key constraints to match your installation: `FK_*`
* Excute the script in MySQL shell

**WARNING:** This may obviously have unwanted side effects, you should make a backup.

**Comment by nblock** [comment]
In addition to https://github.com/akeneo/pim-community-dev/issues/7529#issuecomment-364365771 it is also required to remove relevant records form `pim_catalog_variant_attribute_set_has_axes` and subsequently from `pim_catalog_attribute` tables.

**Comment by damien-carcel** [comment]
Hello all.

This is a wanted behavior of the PIM in 2.1 and 2.0. A user cannot delete a family if it posses family variants.

This behavior is improved in 2.2: you can now remove family variants (if you don't have any product models using them). Once all family variants are removed, it is then possible to remove the family.

What's more, in 2.2, when you try to delete a family having family variants, you'll have a clear message telling you you cannot and why, and not just an error 500.

Regards,
Damien.

**Comment by StephaneHe** [comment]
> This behavior is improved in 2.2: you can now remove family variants (if you don't have any product models using them). Once all family variants are removed, it is then possible to remove the family.

How do you do that ? How do you remove family variants ?

**Comment by damien-carcel** [comment]
Hi @StephaneHe .

Go on the family screen, in "settings → Families". Then edit the family you want to delete, go on the "Family Variants" tab. Here, you can delete them from the grid (a little garbage icon will appear when you move your cursor on the family variant line).
Of course, you need to first delete all variant products and product models that belongs to this family variant, or you will not be able to delete it.

Regards,
Damien.

**Comment by StephaneHe** [comment]
Many thanks for your fast answer. There is no product yet, as I am setting everything now. I just realize we are using Version:2.0.15, so we will need to upgrade first.
Any issue on data structure to expect ?

**Comment by damien-carcel** [comment]
There should not. The migrations between minor versions are quite flowless using the provided Doctrine migration scripts. You can upgrade to the 2.2, then to the 2.3 (which is an LTS) version when it will be released by the end of this month.

**Comment by StephaneHe** [comment]
Many thanks
