### ISSUE TITLE
2.1.1 : Textarea template has additional spaces, thus prefixing existing data with spaces on save

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#7532]
I'm creating a custom entity that allows the customer to edit data in a form type `textarea`:

    pim-faq-edit-answer:
        module: pim/form/common/fields/textarea
        parent: pim-faq-edit-form-properties-translation-section
        targetZone: content
        position: 100
        config:
            fieldName: answer
            label: acme_custom.faq.field.label.answer

The template responsible for rendering the textarea is `vendor/akeneo/pim-community-dev/src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/textarea.html`. This template adds these extra spaces:

```
<textarea
    id="pim_enrich_form_<%- fieldId %>"
    class="AknTextareaField"
    name="<%- fieldName %>"
    <% if (readOnly) { %>readonly disabled<% } %>
>
    <%- value %>
</textarea>
```

The extra linebreak on the closing textarea tag and the 4 spaces before the `<%-` cause the textarea to be pre-populated. It should be:

```
<textarea
    id="pim_enrich_form_<%- fieldId %>"
    class="AknTextareaField"
    name="<%- fieldName %>"
    <% if (readOnly) { %>readonly disabled<% } %>
><%- value %></textarea>

```

**Comment by Doodoune** [comment]
Hi!

This fix is available in the version 2.0.43 & 2.3.18 of the PIM.
I close this issue. Don't hesitate to re-open it if you still have this issue.

Regards,
