### ISSUE TITLE
api product-models pagination `page` broken

### ISSUE THREAD

**Issue by EtienneBruines** [akeneo/pim-community-dev#7581]
**I'm reporting a Bug**

For version >= 1.4, please go to "System > system info", download the text report and attach it to the issue.
[akeneo-pim-system-info_2018-02-01_09_35.txt](https://github.com/akeneo/pim-community-dev/files/1684890/akeneo-pim-system-info_2018-02-01_09_35.txt)

## Scenario
Requesting `product-models` (GET) per API on the latest version of Akeneo. 

## Expected behavior
Similar results for `pagination_type` being `page` and `search_after` (especially for a non-changing database). 

## Encountered behavior
For `pagination_type=page`, it gave back 50 results, no "additional page", and an `item_count` of `568`. (Turning off the counting had no effect.)

So in part, it knows there are `568` total results, but only `50` are given. 

For `pagination_type=search_after`, I get the full 100 results (`limit`), as well as a link to the next page to retrieve the rest. 

## Steps to reproduce:

1. Have a bunch (100+) of product-models
2. Request them per API, first using `pagination_type=page`, and then `pagination_type=search_after`. 
3. Compare results.

**Comment by ahocquard** [comment]
Hello,

This issue is fixed: https://github.com/akeneo/pim-community-dev/pull/8222

It will be available in the next patch (2.0.26).

Regards,
Alexandre
