### ISSUE TITLE
Use a web subdirectory for Akeneo root installation

### ISSUE THREAD

**Issue by BitOne** [akeneo/pim-community-dev#759]
Right now, Akeneo PIM must be installed in the root of a VirtualHost. It's a hosting and HTTP server configuration best practice, and it's not supported by Oro Platform.

Even if we do not recommend it, in some very specific case, it could be useful to have Akeneo in a subdir of the web root (http://my-host.tld/subdir/ instead of http://my-host/).

**Comment by willy-ahva** [comment]
A TIP ticket has been created.
