### ISSUE TITLE
[1.7.16] Versioning does not differentiate between "0123" and "123" in text fields

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#7594]
Because in `VersionBuilder::filterChangeset` https://github.com/akeneo/pim-community-dev/blob/v1.7.16/src/Pim/Bundle/VersioningBundle/Builder/VersionBuilder.php#L175 the comparison is done with `!=` instead of `!==` changes from `1234` to `01234` won't get caught by the versioning system.

This causes problems when dealing with text attributes where only numbers are stored, e.g. with validation `/^\d+$/`.

**Comment by Doodoune** [comment]
Hi @mathewrapid!

Thanks for raise this issue.
I've created a ticket for our maintenance team to correct this issue. I'll keep up updated.

Regards,

**Comment by Doodoune** [comment]
Hi!

This issue is solved in the 1.7.37 version. 
Thanks again to raise this issue.
I close this issue, feel free to re-open it if needed.

Regards,
