### ISSUE TITLE
1.7 attributes are not getting normalized in mongodb

### ISSUE THREAD

**Issue by volkovmqx** [akeneo/pim-community-dev#7598]
**I'm reporting a Bug**

after digging into https://github.com/akeneo/pim-community-dev/issues/7563 i know why some attributes are not getting into normalizedData array in mongodb, for some reasons we are using attribute codes that starts with a number(e.g : 0_Label) which causing a not reported JS exception (identifier starts immediately after numeric literal somewhere) when accessing "normalizedData.0_Label", this causes a lot of problems in other areas (like variants grid).

a possible fix is to not allow numeric values in the first position of the attribute code.

**Comment by volkovmqx** [comment]
another solution is to use normalizedData[code] instead of normalizedData.code

**Comment by Doodoune** [comment]
Hi @volkovmqx!
Do you still have this issue? 
If yes, can you please provide us a step by step scenario to reproduce this behavior and the version of your PIM?
Regards,

**Comment by volkovmqx** [comment]
Hello, 
we migrated to attribute codes that starts with a character, something like "a_0_Label" 
to reproduce this just use a code that starts with a number like "0_Label"

**Comment by Doodoune** [comment]
@volkovmqx - i've created in a PIM v1.7.40 an attribute text with the code "0_Label" and I can export / import / quick export without problems.
So please, provide me a step by step scenario to reproduce it.
If you are on a lower version of the PIM can you upgrade it to see if it solve your issue?

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it with a step by step scenario to help me to reproduce this behavior.
Regards,
