### ISSUE TITLE
Select on multiple pages for mass editing

### ISSUE THREAD

**Issue by francescopis** [akeneo/pim-community-dev#7599]
If you select some products from the list, and then change the page , in order to select more and proceed to a mass edit, products from previous page are not anymore in the products list to elaborate

**Comment by LaureBro** [comment]
Hello @francescopis, this issue will be fixed in the next 2.0 and 2.1 patches :) They will be released very shortly. Here's the PR that fixes the problem #7776 

Kind regards, 
Laure
