### ISSUE TITLE
Categories won't save on first save of a newly created product.

### ISSUE THREAD

**Issue by glasgowunion** [akeneo/pim-community-dev#7605]
**I'm reporting a Bug**

[Edition]
CE

[Version]
2.1.4

[Environment]
prod

[Install time]
2018-01-24T06:39:31+0000

[Server version]
Apache/2.4.18 (Ubuntu)

[Number of channels]
2

[Number of locales]
1

[Number of products]
8

[Number of product models]
16

[Number of variant products]
51

[Number of family variants]
10

[Number of families]
10

[Number of users]
1

[Number of attributes]
30

[Number of scopable attributes]
0

[Number of localizable attributes]
6

[Number of localizable and scopable attributes]
8

[OS version]
Linux akeneopim.local 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64

[PHP version]
7.1.12-3+ubuntu16.04.1+deb.sury.org+1

[MySQL version]
5.7.21-0ubuntu0.16.04.1

[PHP extensions]
Core
date
libxml
openssl
pcre
zlib
filter
hash
Reflection
SPL
session
standard
cgi-fcgi
mysqlnd
PDO
xml
apcu
apc
bcmath
calendar
ctype
curl
dom
exif
fileinfo
ftp
gd
gettext
iconv
imagick
intl
json
mcrypt
mysqli
pdo_mysql
Phar
posix
readline
shmop
SimpleXML
soap
sockets
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xmlreader
xmlwriter
xsl
zip
Zend OPcache

[Registered bundles]
Akeneo\Bundle\BatchBundle\AkeneoBatchBundle
Akeneo\Bundle\BatchQueueBundle\AkeneoBatchQueueBundle
Akeneo\Bundle\BufferBundle\AkeneoBufferBundle
Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle
Akeneo\Bundle\ElasticsearchBundle\AkeneoElasticsearchBundle
Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle
Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle
Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle
Doctrine\Bundle\DoctrineBundle\DoctrineBundle
Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle
Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle
Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle
Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle
FOS\JsRoutingBundle\FOSJsRoutingBundle
FOS\OAuthServerBundle\FOSOAuthServerBundle
FOS\RestBundle\FOSRestBundle
JMS\SerializerBundle\JMSSerializerBundle
Knp\Bundle\MenuBundle\KnpMenuBundle
Liip\ImagineBundle\LiipImagineBundle
Oneup\FlysystemBundle\OneupFlysystemBundle
Oro\Bundle\AsseticBundle\OroAsseticBundle
Oro\Bundle\ConfigBundle\OroConfigBundle
Oro\Bundle\DataGridBundle\OroDataGridBundle
Oro\Bundle\FilterBundle\OroFilterBundle
Oro\Bundle\SecurityBundle\OroSecurityBundle
Oro\Bundle\TranslationBundle\OroTranslationBundle
Oro\Bundle\UserBundle\OroUserBundle
Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle
Pim\Bundle\ApiBundle\PimApiBundle
Pim\Bundle\CatalogBundle\PimCatalogBundle
Pim\Bundle\CommentBundle\PimCommentBundle
Pim\Bundle\ConnectorBundle\PimConnectorBundle
Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle
Pim\Bundle\DashboardBundle\PimDashboardBundle
Pim\Bundle\DataGridBundle\PimDataGridBundle
Pim\Bundle\EnrichBundle\PimEnrichBundle
Pim\Bundle\FilterBundle\PimFilterBundle
Pim\Bundle\ImportExportBundle\PimImportExportBundle
Pim\Bundle\InstallerBundle\PimInstallerBundle
Pim\Bundle\LocalizationBundle\PimLocalizationBundle
Pim\Bundle\NavigationBundle\PimNavigationBundle
Pim\Bundle\NotificationBundle\PimNotificationBundle
Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle
Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle
Pim\Bundle\UIBundle\PimUIBundle
Pim\Bundle\UserBundle\PimUserBundle
Pim\Bundle\VersioningBundle\PimVersioningBundle
Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
Symfony\Bundle\AsseticBundle\AsseticBundle
Symfony\Bundle\FrameworkBundle\FrameworkBundle
Symfony\Bundle\MonologBundle\MonologBundle
Symfony\Bundle\SecurityBundle\SecurityBundle
Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
Symfony\Bundle\TwigBundle\TwigBundle

## Categories won't save on first save of a newly created product.

- Create a new product or product model
- enter data into fields ( under attributes section )
- change categories in two channels
- save

I expect that the categories have been updated
unfortunately they are still set at default values

- I open the product / product model again
- make the same changes
- save

This time the category changes have been updated

**Comment by Doodoune** [comment]
Hi!
I don't reproduce the problem in a 2.0 and 2.3 environment. 
Do you still have this problem?

I close this issue but feel free to re-open it if you still have this issue.

Regards,
Elodie
