### ISSUE TITLE
text garbling  

### ISSUE THREAD

**Issue by HisakaKoji** [akeneo/pim-community-dev#7607]
[environment]
http://demo.akeneo.com

Edition 　CE　
version  2.1.2

[step]
1. system  >  user > interface > japanese

[issue]
text garbling  

1.  "] - Inf ファイル、1] "   in product list.
2.  "はい  いいえ　(yes,no)" protrude.
3.  The string of Calender per month in date attribute  is garbled.

**Comment by jmleroux** [comment]
Sorry, i'm not proficient in Japanese but we use Crowdin to translate our messages and you could fix them for Japanese if needed. More info on this page: https://docs.akeneo.com/1.5/contributing/translate.html

Regards
