### ISSUE TITLE
API: numeric amount values are JSON strings

### ISSUE THREAD

**Issue by silwol** [akeneo/pim-community-dev#7617]
Using version 2.1.

For products which contain unit attributes, the API returns JSON code like this:
`"data":{"amount":400,"unit":"MILLIMETER"}`
for one attribute, but
`"data":{"amount":"34.0000","unit":"KILOGRAM"}`
for another one.

The "amount" attribute is a JSON number in one case, a JSON string in the other. I would expect all numeric values to be JSON numbers, which is the case for the first entry, but not the second. This inconsistent behavior requires additional effort in my API client to detect the type of the field instead of just expecting a number.

**Comment by mathewrapid** [comment]
Iirc, isn't that to avoid rounding errors?

**Comment by phawxby** [comment]
This handling is wrong. Numbers are numbers and rounding to 4 decimal places loses necessary precision.

**Comment by omolto** [comment]
Hi,

Has it been fixed? Found the same problem in v 6.0.42

Thanks,
