### ISSUE TITLE
[2.x] Search on attribute with code is number gets error

### ISSUE THREAD

**Issue by naolis** [akeneo/pim-community-dev#7646]
On my 2.0.15 and also on demo.akeneo.com today.

If you create an attribute (Text, usable as grid) and made a search on this attribute content you get an error.

Error from var/log/prod.log

> [2018-02-12 16:42:00] request.CRITICAL: Uncaught PHP Exception Pim\Component\Catalog\Exception\UnsupportedFilterException: "Filter on property "1" is not supported or does not support operator "CONTAINS"" at /var/www/html/ecf_pim/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Query/ProductQueryBuilder.php line 138 {"exception":"[object] (Pim\\Component\\Catalog\\Exception\\UnsupportedFilterException(code: 0): Filter on property \"1\" is not supported or does not support operator \"CONTAINS\" at /var/www/html/ecf_pim/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Query/ProductQueryBuilder.php:138)"} []

**Comment by naolis** [comment]
Test on 2.1.5 : same bug

**Comment by naolis** [comment]
Test on 2.2.x : same bug

**Comment by LaureBro** [comment]
Hello, 

this issue has been fixed in the 2.0.25 version and is also fixed on the 2.2.8 version.

Kind regards, 
Laure

**Comment by Doodoune** [comment]
Hi!

Issue solve on 2.0.25, 2.2.8 versions.
I close this issue,
Feel free to reopen it if you still have the issue.

Regards,
