### ISSUE TITLE
Create different nodes for elastic search

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7684]
Hi,

I have installed Akeneo Community and Enterprise edition instance on my machine. I'm having the issue with the products. Product count is displaying and the product grid shows empty records. But the product is in the database. I found that this issue is due to the elastic search using the same port (9200).

Anyone, please let me know how to create different nodes for elastic search?

**Comment by xElysioN** [comment]
Hi @Vanitha-bujjinga ,
You have to re-index all products into Elasticsearch with this command : 
`php bin/console pim:product:index --all -e=prod`

And if you wanna change index in ES, you have to edit those lines in parameters.yml like this 
https://github.com/akeneo/pim-community-dev/blob/c3ed9512c54701be6b94e1bdcd00846598e07ddc/app/config/parameters.yml.dist#L10-L12

**Comment by Vanitha-bujjinga** [comment]
Hi @xElysioN,

Thank you so much. The issue has been resolved.
