### ISSUE TITLE
Create downloadable product in Akeneo

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7685]
Hi,

I want to create a downloadable product in the Akeneo. Can anyone please let me know how to create?

**Comment by Doodoune** [comment]
Hi! 

I close this issue, feel free to reopen it if you still have this issue.

Regards,

**Comment by jaisudhakar** [comment]
![akeneo products page issues](https://user-images.githubusercontent.com/25986394/57908614-17bdee80-789e-11e9-9297-766091a78202.png)

**Comment by jaisudhakar** [comment]
How to solve this isses?

**Comment by Doodoune** [comment]
Can you tell me what is the error in your pim/var/log/prod.log?
