### ISSUE TITLE
More docs for beginner

### ISSUE THREAD

**Issue by maseen** [akeneo/pim-community-dev#7691]
Hi,

i need more docs to install Akeneo with Docker for noob like me.

I follow  : 

https://docs.akeneo.com/2.2/install_pim/docker/installation_docker.html#

I download the "pim-community-standard" version
But at this step : 

**Install Akeneo**
Now, you can initialize Akeneo by running:
```
$ bin/docker/pim-dependencies.sh
$ bin/docker/pim-initialize.sh
```

I have this error : 

**ERROR**: No such service: fpm
**ERROR**: No such service: node

**Comment by damien-carcel** [comment]
Issue on the Dockerfiles repository, with an answer => https://github.com/akeneo/Dockerfiles/issues/315
