### ISSUE TITLE
Akeeno 1.6: Reduce the time for Product Import

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7693]
Hi,

I'm using Akeneo 1.6 version. It will take more than 6 hours to import 43k product data. Anyone, can you please suggest me to add tweaks to reduce the time?

**Comment by Doodoune** [comment]
Hi @Vanitha-bujjinga, 
Could you share with us your system file information?

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it with more detail to help us to reproduce your issue.
Regards,
