### ISSUE TITLE
Wrong setCookie behavior

### ISSUE THREAD

**Issue by muspelheim** [akeneo/pim-community-dev#7709]
**I'm reporting a Bug**

Response from REST API returned a lot of headers setCookie what was broke my Load balancer.

It wrong behavior for application, because doesn't match with [HTTP specification](https://tools.ietf.org/html/rfc6265#section-4.1.1)

`Servers SHOULD NOT include more than one Set-Cookie header field in the same response with the same cookie-name.`

![selection_358](https://user-images.githubusercontent.com/1663352/36549609-3e4d268e-1804-11e8-9bd2-1fc2fbf85531.png)

**Comment by Doodoune** [comment]
Hi!
Did you still have an issue?
Regards,

**Comment by jmleroux** [comment]
Closed after inactivity
