### ISSUE TITLE
2.1.4 : Images are not imported from CSV for Variant Products

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#7744]
I'm importing products in Akeneo 2.1.4 using a CSV format, but now I want to import images to existing SKU's. I do this by preparing a file like:

    sku |image_1
    ----+-------------------------
    ABC | relative/path/to/abc.jpg
    XYZ | relative/path/to/xyz.jpg

This worked before (in an older version of Akeneo), but now I can't get it back to work. Where does Akeneo look for images? I thought it was relative to the location of the CSV file.

~~**update:**~~

~~I found a way to reproduce this. Appearantly, executing it from the command line like this works:~~

~~`bin/console akeneo:batch:job csv_product_import --config="{\"filePath\":\"/absolute/path/to/images.csv\"}"`~~

~~However, when it's done by adding it to the queue it doesn't work:~~

~~`bin/console akeneo:batch:publish-job-to-queue csv_product_import --config="{\"filePath\":\"/absolute/path/to/images.csv\"}"`~~

~~So why is it that as soon as I'm using the queue the images are not found?~~

**update 2:**

Upon further investigation, it seems that this has nothing to do with the queue. It just looks like I cannot add images to **variant products**. Can anyone else confirm?

**Comment by damien-carcel** [comment]
Hello @kanduvisla.

I just tested this on 2.2 (2.1 is now deprecated). Updating media through imports work fine, even for variant products. But for it to work, you need to upload a ZIP archive (using the product import).

It is very important that this ZIP archive contains directly the CSV file alongside the folder containing the images (and respecting the relative path you have in the CSV file, of course). You must not generate the ZIP from a folder that contains the file and the files folder as it will not work. Look at the screenshots below to better understand what I mean.

This is wrong:
![image](https://user-images.githubusercontent.com/5039018/38139192-ab21d386-342e-11e8-80e6-430f8ed043a8.png)

This is right:
![image](https://user-images.githubusercontent.com/5039018/38139171-9474f05a-342e-11e8-920a-211e27d5323a.png)

Did you have any error/warnings in your import logs?

Kind regards,
Damien.

**Comment by kanduvisla** [comment]
@damien-carcel : The files that are imported are generated by a different process. In fact: there are 4 feeds that are generated from a single feed so that Akeneo can import them. To make a long story short: the family variant feeds are generated automatically.

However: I'm now running into the problem that if I change a product to a variant product (upon importing by setting a parent), the image gets lost. Any idea to why this is? Or should I create a new ticket for this?

I'm running Akeneo 2.1.6. Which brings me to another question: you state that _"2.1 is now deprecated"_. But the last release of 2.1.x was 8 days ago (March 27th), and there is now a 2.2 and 2.3 branch. The 2.1 branch was released December 21st 2017 and already deprecated after 3 months? Is there any information on the release cycle / LTS of Akeneo? How can we implement our solutions in such short cycles? Will 2.2.x be deprecated in the next 3 months? And 2.3.x after a half year? We now have a highly customized Akeneo setup with a lot of custom code, and the software is already deprecated before we even have done the official release for our client! Perhaps not the best place to put these questions here, but I am just wondering.

**Comment by damien-carcel** [comment]
Hello @kanduvisla 

> However: I'm now running into the problem that if I change a product to a variant product (upon importing by setting a parent), the image gets lost. Any idea to why this is? Or should I create a new ticket for this?

Are you sure this media attribute was defined in the right level? It must be defined in the last level of your family variant (meaning the level of the variant product). What you describe looks like your media attribute is in another level or in the common attributes.

> Is there any information on the release cycle / LTS of Akeneo?

Yes there is: https://www.akeneo.com/blog/a-faster-way-to-benefit-from-akeneo/.
To summarize, X being the major version (2, 3, etc.), there is for each major 4 minor versions. The first and the last ones, X.0 and X.3, are LTS (long-term support), supported 18 months. X.1 and X.2 are STS (short-term support), supported 3 months. It means the moment X.2 is released, X.1 is not supported anymore. The same with X.3 vs X.2, but X.3 will be supported 18 months.

Kind regards,
Damien.

**Comment by Doodoune** [comment]
Hi @kanduvisla!

Do you still have an issue or we can close this issue?

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it if needed.

Regards,
