### ISSUE TITLE
Invalid HTTP status on case a exception is thrown

### ISSUE THREAD

**Issue by amansilla** [akeneo/pim-community-dev#7760]
This is an issue which is affecting a controller for all Akeneo PIM versions from 1.6 to 2.2.

When deleting a option from a attribute of type "Single Choice" or "Multiple Choice" a invalid HTTP status will be sent due the exception code is used as HTTP response status.

**Comment by damien-carcel** [comment]
Closing as the PR was merged. Thanks for this @amansilla . I'll do a PR to add your contrib on the changelog :tada: .

**Comment by amansilla** [comment]
Wow sounds great!!! Thanks to you as well @damien-carcel. Create the PR and get this reviewed, tested and merged within the same day is awesome!!!
