### ISSUE TITLE
Standalone Batch component and BatchBundle bundle not up to date

### ISSUE THREAD

**Issue by ste93cry** [akeneo/pim-community-dev#7802]
The [Batch component](https://github.com/akeneo/batch) and the [BatchBundle bundle](https://github.com/akeneo/BatchBundle) are available standalone, and this is a great thing. However since 2016 they are not updated with respect to the changes made in this repository. May be possible to set up something that syncs automatically the standalone repositories like e.g. Symfony does?

**Comment by damien-carcel** [comment]
Hello @ste93cry.

Indeed it is not up to date at all. It is a very experimental project.

It may be synchronized again in a near future, but we have no plan at the moment to automate this. It would mean ensuring that the bundle and component are reliable as standalone software, something we don’t test today. We only ensure that the BatchBundle works correctly inside Akeneo PIM.

Kind regards,
Damien.

**Comment by ste93cry** [comment]
I would like to use it on one of my projects, this is why I asked it. Maybe you could mark it as experimental, but still keep it in sync? If something won't work people can eventually open PR or raise issues which anyway will benefit you and third parties

**Comment by Doodoune** [comment]
I close this issue,
feel free to reopen it if needed.
Best regards,
