### ISSUE TITLE
[2.x] Internal Server Error when filtering on SKU with forward slash "/"

### ISSUE THREAD

**Issue by chrishodgsonplt** [akeneo/pim-community-dev#7806]
Steps to reproduce:

1. Product listing
2. Filter on SKU contains SKU/1234 (full SKU is SKU/1234/234)
3. Akeneo present a popup with title 'Server Error' and text 'Error! Incorrect server response.'  and an elastic search error appears in the logs 

What should happen:

Akeneo should be escaping any reserved characters (ie forward slashes) before sending a query to elastic search.  This is explained here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters 

![screen shot 2018-03-13 at 10 05 00](https://user-images.githubusercontent.com/33623278/37336918-b72c9210-26aa-11e8-96af-a60b305038b2.png)

[akeneo-pim-system-info_2018-03-13_10_37.txt](https://github.com/akeneo/pim-community-dev/files/1806545/akeneo-pim-system-info_2018-03-13_10_37.txt)

**Comment by naolis** [comment]
In the same kind of issue : 
https://github.com/akeneo/pim-community-dev/issues/7646

**Comment by LaureBro** [comment]
Hello,

As mentioned in https://github.com/akeneo/pim-community-dev/issues/7646.
This issue has been fixed in the 2.0.25 version and is also fixed on the 2.2.8 version.

Kind regards,
Laure

**Comment by Doodoune** [comment]
Hi!

I close this issue.
Feel free to reopen it if you still have this issue.

Regards,
