### ISSUE TITLE
Nesting Level Too Deep in Abstract Value

### ISSUE THREAD

**Issue by Schwierig** [akeneo/pim-community-dev#7816]
**I'm reporting a Bug**

Akeneo Version: 2.1.5

`src/Pim/Component/Catalog/Model/AbstractValue.php:60` doesn't use strict comparison which leads to `Nesting level too deep` error when comparing objects.

**Comment by damien-carcel** [comment]
Hello @Schwierig .

This non strict comparison was done on purpose => https://github.com/akeneo/pim-community-dev/pull/6430.

It is not ideal, and a better value comparison will eventually be done to avoid this workaround. But for now the simplest solution is to increase the `max_nesting_level` value. Usually setting it to 500 is enough.

Kind regards,
Damien.

**Comment by Schwierig** [comment]
It's pretty unlucky that the max_nesting_level is too low to compare single heritance objects on the official cloud system then. Will open a separate ticket there then. Thanks!
