### ISSUE TITLE
Navigation on family config page

### ISSUE THREAD

**Issue by francescopis** [akeneo/pim-community-dev#7817]
**I'm reporting a Bug**

Akeneo 2.1.6 EE

Steps to reproduce
Navigate to Settings->families
"Search on label" any of existing family e.g. Accessories on demo.akeneo.com
click on family row to enter the edit page
Browser back button or click on family menu to go back on families list

Expected behaviour
Filtered families with search input field filled with previous search keyword

Result
Filtered families with empty search input field
we can't reset filter or change keyword until we force the page reload

**Comment by LaureBro** [comment]
Hello @francescopis, thanks for raising this. It impacts several pages in the PIM :( 
I have informed our Product team of this issue.
We will keep you informed.

Kind regards, 
Laure

**Comment by jmleroux** [comment]
Hello @francescopis ,

Akeneo 2.1 is not supported anymore and we will close this issue. Do not hesitate to reopen it if you are still experiencing this issue on more recent PIM version.

Regards
