### ISSUE TITLE
Pim Requirements doesn't check mysql port in 2.0

### ISSUE THREAD

**Issue by Schwierig** [akeneo/pim-community-dev#7932]
You fixed this bug in the 2.2 branch, but not the 2.0 branch

**Comment by Doodoune** [comment]
Hi!

We created a ticket for this issue: https://github.com/akeneo/pim-community-dev/issues/7932.

Thanks for notified us about that!

I'll keep you updated about which version you will find this correction.

Regards,

**Comment by Doodoune** [comment]
Hi!

The fix is available on 2.0.45! Thanks for notified us about that!
I close this issue.

Regards,
