### ISSUE TITLE
Breadcrumbs don't work after saving attribute

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#7939]
**I'm reporting a Bug**
PIM 2.3

Attribute edit page. Breadcrumbs don't work after saving.

example:
http://demo.akeneo.com/#/configuration/attribute/auto_exposure/edit
1. click on SAVE button
2. click on breadcrumbs

![atr](https://user-images.githubusercontent.com/2612186/38415980-e6d3ae3c-399b-11e8-861f-9cdf7020b06e.jpg)

**Comment by skeleton** [comment]
Hello, 

this bug has been fixed 3 days ago by the team on the 2.0 branch (see https://github.com/akeneo/pim-community-dev/pull/7903). The patch will be able in few days in 2.3 branch.
