### ISSUE TITLE
2.1.8 : export with --no-log still writes log files to var/logs/batch

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#8042]
Im running an export job from the CLI like so:

    bin/console akeneo:batch:job csv_attribute_option_export \
        --env=prod \
        --config={"filePath": "/home/www/var/export/attribute_options.csv"} \
        --no-log \
        --email=name@domain.tld \
        --no-debug

As you can see, I'm using the `--no-log`-flag, but log files are still written to the `var/logs/batch`-folder. Should this happen with this flag enabled? Or am I missing here. Also, the `--no-debug` still writes `[DEBUG]`-messages in those mentioned log files. (even though I explicitly set `--env=prod`).

**Comment by kanduvisla** [comment]
I see, is there any way to disable the creating of log files though?

**Comment by jmleroux** [comment]
Not with a CLI option. But IMHO, logs are always usefull. You could set a logrotate policy or something like that if you don't want logs to take to much disk space.

**Comment by kanduvisla** [comment]
You're right. Much better solution. I'm closing this issue, since it's not really an issue.
