### ISSUE TITLE
Unable to add products

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#8061]
Hi.
I have installed Akeneo fresh installation with the version 2.0.20. I can add Attribute groups, Attribute, Family., Category and Product model. (edited)
But I can add simple or variant product.
It shows the below error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
Can any one assist me?

**Comment by damien-carcel** [comment]
Hello @Vanitha-bujjinga.

You should have more detailed output in the logs. Can you see any `ERROR` in `var/logs/prod.log`?
You can also try to run Akeneo in dev mode (adding `/app_dev.php/` after your domain name or IP address), and you'll have errors directly in the debug bar.

Regards,
Damien.

**Comment by Vanitha-bujjinga** [comment]
Hello @damien-carcel,

Thank you for your response. I have fixed this issue by rerun PHP7 fpm service. It is working fine now.
