### ISSUE TITLE
2.2.4 : Product list is not visible

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#8071]
I recently updated from Akeneo 2.1.8 to 2.2.4, did a complete reinstall, flushed my caches, but for some reason my product list is not visible. Everything else in Akeneo seems to work. The XHR request to load the data also comes through properly.

I do notice 3 exceptions in my console:

```
module-registry.js:5 oro/datagrid/mass_delete-action is missing from the registry - include it in your requirejs.yml and clear the app cache

bootstrap c5aadc857b4174af2787:146 TypeError: Cannot read property 'extend' of undefined

datagrid-builder.js:1 Uncaught (in promise) TypeError: Cannot read property 'extend' of undefined
```

Screenshot:

![screen shot 2018-05-02 at 11 46 48 am](https://user-images.githubusercontent.com/346681/39516891-89f09f82-4dfe-11e8-9de6-67ebfdd91c55.png)

Something tells me this is the root of my problem. Does anyone has an idea what's going on here?

**Comment by kanduvisla** [comment]
Never mind, I guess I forgot to run webpack again. Running this command fixed this issue for me:

    bin/console pim:installer:assets --symlink --clean --env=prod && yarn run webpack && rm -rf var/cache

**Comment by prakharsaxena2** [comment]
No mapping file found named 'AbstractProduct.orm.yml' for class 'Pim\Component\Catalog\Model\AbstractProduct'.

i am facing this issue can anybody can help me ?
