### ISSUE TITLE
Sequential edit when sorting scopable attribute

### ISSUE THREAD

**Issue by francescopis** [akeneo/pim-community-dev#8091]
If you have a scopable attribute in product grid and sort by that, then you cannot use sequential edit 
Akeneo throws this exception

`request.CRITICAL: Uncaught PHP Exception Akeneo\Component\StorageUtils\Exception\InvalidPropertyException: "Attribute "des" expects an existing scope, "Array" given." at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyException.php line 239 {"exception":"[object] (Akeneo\\Component\\StorageUtils\\Exception\\InvalidPropertyException(code: 0): Attribute \"des\" expects an existing scope, \"Array\" given. at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyException.php:239, LogicException(code: 0): Attribute \"des\" expects an existing scope, \"Array\" given. at /srv/pim/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Validator/AttributeValidatorHelper.php:160)"} []
`

that because of on SequentialEditController.php line 60-64
```
$cursor = $this->getProductsCursor($filters, [
            'locale' => $parameters['dataLocale'],
            'scope'  => $parameters['dataScope'],
            'sort'   => $parameters['sort']
        ]);
```
$parameters['dataScope'] contain an array instead of a string

Reproducible on the online akeneo demo page

**Comment by daniel-rose** [comment]
Me too.

**Comment by Doodoune** [comment]
Hi!

I try to reproduce it on http://demo.akeneo.com, I sort on release_date (that is scopable), I select 3 rows and launch sequential edit => I have no errors.

Can you explain me step by step how to reproduce your error?

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it with a step by step scenario to help us to reproduce it.
Please also provide your PIM version.

Regards,
