### ISSUE TITLE
Memory Leaks on reindex

### ISSUE THREAD

**Issue by triada63** [akeneo/pim-community-dev#8125]
Hello, we have 1 500 000 product in our Database, on reindex we catch error. When debugging code we found what on every iteration memory is stacks, when we logging time and memory usages we see that picture:
http://joxi.ru/J2bbGPYUXx86v2
1 column - loading batch products time
2 column - processing batch time
3 column - memory usage (memory_get_usage())

Loggin in file:
/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Elasticsearch/Indexer/ProductIndexer.php:indexAll()

We try to found memory leaks within xdebug, but not found it, there is an assumption what Doctrine cached or logging some data. 

Version - master
Community Edition

**Comment by gplanchat** [comment]
@ahocquard

**Comment by Doodoune** [comment]
Hi!

A solution was provided for this issue (see the comment of gplanchat), so I close this issue.
Feel free to re-open it if you still have the problem.

Regards,
Elodie
