### ISSUE TITLE
Wrong version in package.json for PIM > 2.0

### ISSUE THREAD

**Issue by LudovicTOURMAN** [akeneo/pim-community-dev#8143]
Version in package.json has not been upgraded since PIM 2.0.
So, for example, PIM 2.3 package.json is telling [`"version": "2.0.0",`](https://github.com/akeneo/pim-community-dev/blob/2.3/package.json#L3)

Please, set the corresponding versions for each tags of pim CE and EE
Please also add a licence field to avoid yarn warnings :
```
yarn install v1.6.0
warning package.json: No license field
info No lockfile found.
warning pim-enterprise-standard@2.0.0: No license field
```

**Comment by jmleroux** [comment]
Hello @LudovicTOURMAN 

Why would you not create PRs?

:wink:
