### ISSUE TITLE
Error after update from 2.1.8 to 2.2.4

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#8145]
I've updated Akeneo locally from 2.1.8 to 2.2.4 without problems, but when I run it on production it gets stuck and shows the following error:

    Duplicate definition of column 'id' on entity 'Pim\Component\Catalog\Model\Product' in a field or discriminator column mapping.

What's causing this issue?

**Comment by kamranmalikawan** [comment]
@kanduvisla have you find a solution for that ??

**Comment by kanduvisla** [comment]
I'm not sure anymore. I'm not having the problem anymore. It could be that it was a problem with the opcache. If you're running php-fpm, try restarting that service. If that fixes the problem for you, I guess this ticket can be closed.

**Comment by Doodoune** [comment]
Hi!

I close this ticket, if you still have the issue, feel free to re-open it.

Regards,
Elodie

**Comment by prakharsaxena2** [comment]
Duplicate definition of column 'id' on entity 'Pim\Component\Catalog\Model\Product' in a field or discriminator column mapping.
 i also facing same error ... please help
