### ISSUE TITLE
Can't delete attribute as its part of the 'other' attribute group

### ISSUE THREAD

**Issue by nblock** [akeneo/pim-community-dev#8147]
We encountered an issue while trying to remove some attributes: "Cannot remove this attribute used as a variant axis in a family variant". We found that the attribute is only used in the attribute group 'others'. And from there, one can't delete it. The 'delete' button is missing. Is there anything we are missing?

Version: 2.2.5

**Comment by nblock** [comment]
Said attribute previously defined an axis, but this axis no longer exists.

**Comment by drewgillson** [comment]
+1, I also have this problem, have tried everything I can think of but unable to delete certain attributes that were once used as a variant axis.

**Comment by Doodoune** [comment]
Hi @nblock & @drewgillson!

For me, do not allow the user to delete an attribute that is used as an axis in a family variant, it's a natural behavior. 
If you delete the family variant that uses this attribute as axes, you can finally delete the attribute.

If you still have this issue can you explain me step by step what is your problem?

Regards,
Elodie

**Comment by Doodoune** [comment]
Hi!

I close this issue, feel free to reopen it if you still have this issue.

Regards,
