### ISSUE TITLE
Cannot import > 5000 products with the Akeneo XLSX Product Connector

### ISSUE THREAD

**Issue by annapivniak** [akeneo/pim-community-dev#8170]
Hi guys, 

**I'm reporting a Bug**

STR
I am using the latest version of Akeneo CE (2.2.5) 
I am importing the xlsx file with 11,000 products. I import only 2 columns - identifier and one text attribute.
Some of the products are new, and some - already exist in the system.  
After 5000 products is imported I get an error: 
"Error #0 in class Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Pim\Component\Catalog\Model\Association#products' that was not configured to cascade persist operations for entity: <my_identifier>. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." 
The products that are failing do not have any associations and did not have them in the system before the import. 
If I remove the failing product from the file, the import fails on a later product. 
If I import only failing products - they are imported fine (updated or skipped if necessary)

*Expected behaviour*
It is possible to import files with more than 10000 products.

**Comment by Doodoune** [comment]
Hi @annapivniak,

Sorry for the delay, did you still have this issue on v2.3 or v3.0?

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it with more details.
Regards,
