### ISSUE TITLE
[BUG] Akeneo allows the creation of an attribute whose code is 'idenfitier' whose type is not identifier

### ISSUE THREAD

**Issue by oliverde8** [akeneo/pim-community-dev#8234]
**I'm reporting a Bug**

**Actual behaviour**
* I am creating a new attribute.
* The type of my attribute is "Text" or anything else that isn't an identifier
* The code of my attribute is "identifier"
* I save the changes.
* I go to the product association page
* i got an error: `Filter on property "identifier" is not supported or does not support operator "IN"`

**Expected Behaviour**
* Either I get an explicit message telling me `identifier` is a reserved name. 
* Everything continues to work because reserved codes do not conflict with attributes. 

**What happens**

Whatever the name of the `identifier` field akeneo keeps the data stored in a field named `identifier`. So if we create an actual attribute named `identifier` the query engine queries the new field instead of querying the sku field. 

I just reproduced the issue on the demo site as well, but originally it's present on the 2.0 version as well.

Edit: The checks are in place to prevent creating attribute whose code is family already. Same needs to be put in place

**Comment by Doodoune** [comment]
Hi @oliverde8!

Thanks for raise this issue.
Actually we have a blacklist of code that can't be used as a code for an attribute. We will add it (and a couple of other).
I've created a ticket for our maintenance team to correct this issue. I'll keep up updated.

Regards,

**Comment by Doodoune** [comment]
Hi @oliverde8!

We add in our documentation that "identifier" attribute code cannot be used.
https://help.akeneo.com/pim/v2/articles/manage-your-attributes.html#create-an-attribute

Regards,

**Comment by Doodoune** [comment]
Hi, I close this issue. Feel free to reopen it if needed.
Regards,
