### ISSUE TITLE
Product Updater should (probably) ignore field 'metadata' just like it ignores fields 'created' and 'updated'

### ISSUE THREAD

**Issue by rpeltola** [akeneo/pim-community-dev#8252]
According to api-documentation (https://api.akeneo.com/api-reference.html#patch_products__code_) metadata-field is 'Read only property, not present in creation mode' just like created and updated fields.

Created and updated fields are excluded in Product Updater so product creation via api works fine even if those fields are included with null values. But if you include field metadata with value null, then product creation fails with http 422:

```
{
    "code": 422,
    "message": "Property \"metadata\" does not exist. Check the expected format on the API documentation.",
    "_links": {
        "documentation": {
            "href": "http:\/\/api.akeneo.com\/api-reference.html#patch_products__code_"
        }
    }
}
```
.

I would expect deserialized api-payload like this to work:

```
{
    "identifier": "16c4e792",
    "enabled": false,
    "family": "mugs",
    "categories": [],
    "groups": [],
    "parent": null,
    "values": {
        "name": [{
            "scope": null,
            "locale": null,
            "data": "test mug name"
        }]
    },
    "associations": {},
    "created": null,
    "updated": null,
    "metadata": null
}
```

**Comment by Doodoune** [comment]
Hi @rpeltola!

This field is only existing in the EE edition. 
That's why you can't edit it in CE edition, so you have an error when you try to send it.

Regards,

**Comment by Doodoune** [comment]
I close this issue.

Feel free to reopen it if you have questions.

Regards,
