### ISSUE TITLE
PHP 7.2 not supported which results in missing menu entries

### ISSUE THREAD

**Issue by wimulkeman** [akeneo/pim-community-dev#8289]
**Type:** Bug
**Version:** Akeneo 1.7 - 2.2.8

When you install Akeneo 2 on a system using PHP version 7.2, the installation goes without error. When afterwards you log into the admin panel, you only see the menu entry for the dashboard. The other items are unavailable. Also clicking on a log for recent run task results in a authentication error.

**Stepts to reproduce**
1. Run a installation of Akeneo using `bin/console pim:install` on a system using PHP version 7.2
2. Go to the site to log into the system
3. When logged in, you will see the menu entries missing on the left side on the screen

Trying the same steps on a system using PHP v7.1 results in a working admin interface.

**Comment by ahocquard** [comment]
Hello,

PHP 7.2 is not currently supported.
Only PHP 7.1 is supported on the last version (2.2).

https://docs.akeneo.com/2.2/install_pim/manual/system_requirements/system_requirements.html

Regards,
Alexandre

**Comment by wimulkeman** [comment]
@ahocquard Will PHP 7.2 be supported in Akeneo v3?

**Comment by wimulkeman** [comment]
As for now it seems PHP 7.2 will be supported in the v3 release of Akeneo https://github.com/akeneo/pim-community-dev/blob/master/CHANGELOG-3.0.md.
