### ISSUE TITLE
Code improvment

### ISSUE THREAD

**Issue by ptitkosmos** [akeneo/pim-community-dev#8330]
I would like to improve custom development by suggesting to avoid private attributes and methods.

For example (FamilyVariantUpdater) : 

- https://github.com/akeneo/pim-community-dev/blob/159b27a2fc51481e33d4b4d75f1fbd570c278452/src/Pim/Component/Catalog/Updater/FamilyVariantUpdater.php#L31
- https://github.com/akeneo/pim-community-dev/blob/159b27a2fc51481e33d4b4d75f1fbd570c278452/src/Pim/Component/Catalog/Updater/FamilyVariantUpdater.php#L84

There are many of them in the whole project.

**Comment by jmleroux** [comment]
Hello @ptitkosmos 

`protected` vs `private` is a vast subject, but you still can customize the code quite easily by implementing a whole new service and use your own implementation by replacing the DI declaration in the Symfony container.

**Comment by ptitkosmos** [comment]
Hello @jmleroux ,

That is what i did. I also override the `FamilyUpdater`, and since everything is protected, i could inherit from the standard class and only updated the method I want to. `protected` lets override by keeping the standard code and on version upgrade, it is easier to migrate.
