### ISSUE TITLE
composer failed

### ISSUE THREAD

**Issue by seitosan** [akeneo/pim-community-dev#8343]
Hi 

I have an issue, when i run composer install, 

` Problem 1
    - The requested package akeneo/pim-community-dev 2.3.x-dev@dev exists as akeneo/pim-community-dev[v2.3.0-ALPHA2, v2.3.0-ALPHA1, v2.2.9, v2.2.8, v2.2.7, v2.2.6, v2.2.5, v2.2.4, v2.2.3, v2.2.2, v2.2.1, v2.2.0, v2.2.0-BETA1, v2.2.0-ALPHA2, v2.2.0-ALPHA1, v2.2.0-ALPHA0, v2.1.9, v2.1.8, v2.1.7, v2.1.6, v2.1.5, v2.1.4, v2.1.3, v2.1.2, v2.1.1, v2.1.0] but these are rejected by your constraint.
`

I solved it to edit composer.json and replace

  "minimum-stability": "stable", to   "minimum-stability": "dev" 

can you fix it ?

**Comment by jmleroux** [comment]
Hello @seitosan 

I don't think we will fix it as it is a normal behavior: 2.3 branch is not relased as stable and it is normal to have to change the minimum stability.
