### ISSUE TITLE
Akeneo is really really slow: Bad gateway, timeout

### ISSUE THREAD

**Issue by Aerendir** [akeneo/pim-community-dev#8363]
I've just made Akeneo work on my local machine, using Docker.

But it is really really slow and while trying to access the Products, I get a timeout error.

Is something I missed? How can I make Akeneo work at a decent speed on my local machine?

**Comment by jmleroux** [comment]
Hello @Aerendir ,

which version of Akeneo do you use and what is your catalog size?

**Comment by Aerendir** [comment]
I’m using the version 2.3 and my catalog is of 0 products.

I didn’t started to add them yet as I’m exploring... I installed the fixtures minimal, so I think there are 0 products...

**Comment by Aerendir** [comment]
Ok, I gave Akeneo another try...

With the experience of yesterday, tomorrow I installed the standard community edition and all now works well.

It is still slow, but I think it is normal as it is running on my machine and through Docker.

The problem, yesterday, was that I installed the dev version and that it was the 2.3 version that I discovered be an alpha release.

Now that I've installed the standard edition version 2.2 all wrks well: I can see the products and the interface is usable.

Now I'm going to try to deply it on Heroku to see its real performances.

Anyway it is a really good product: well designed and, for what I saw in the documentation, really helpful: thank you for developing it! :)

I'm going to close this issue as I've practically solved my problem!

**Comment by ankit-sf** [comment]
Akeneo 2.3 is really slow comparison to previous Akeneo versions

**Comment by samarshahzad** [comment]
i want Akeneo 2.3 on windows, can someone help me?

**Comment by jmleroux** [comment]
Hello @samarshahzad ,

we do not officially support Windows, but you should find windows users on the [Akeneo Slack User Group](https://akeneopim-ug.herokuapp.com/)

**Comment by samarshahzad** [comment]
thanks, please provide some easier documentation for 2.3, i have gone through the offical one but that is not very helpful.I am trying to create a custom connector for csv upload but having validation issues, it only add validations as on product csv import.
