### ISSUE TITLE
2.2.8 : "Download Generated Files" not shown for Quick Export on production server

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#8379]
When I use the "Quick Export"-functionality locally, the job is executed and when I go to the report page, I can see a "Download Generated Files"-button in the top right corner of my screen.

However, when I try to do the same on our production server, the button is not shown. Does anyone know what might cause this button to not be rendered? I've looked at the batch log but I can't see anything strange there.

**Comment by kanduvisla** [comment]
Oh never mind, it's there now. Probably a caching issue or something?

**Comment by stefandoorn** [comment]
I'm actually experiencing the same issue, but on v3.0.1. It's never showing up.. I do see the generated files on the local filesystem, but that's not easy to use for anyone not a developer.

**Comment by eporsche** [comment]
Same here with current master  - must be missing sth. obvious.
