### ISSUE TITLE
Attributes Create with name categories and parent after then product not update.

### ISSUE THREAD

**Issue by navneetbhardwaj** [akeneo/pim-community-dev#8383]
Akeneo version >= 2.0.27
When I created attributes with the code parent or categories, attributes created fine with no warning. after then I will try to update the product but product not updated.  

Logs : 
request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The directory "/var/www/pim-community-standard/var/cache/prod/oro_acl_annotations" is not writable." at /var/www/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php line 92 {"exception":"[object] (InvalidArgumentException(code: 0): The directory \"/var/www/pim-community-standard/var/cache/prod/oro_acl_annotations\" is not writable. at /var/www/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92, Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/pim-community-standard/var/cache/prod\" directory. at /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:681)"} []
[2018-06-23 00:31:20] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "/var/www/pim-community-standard/var/cache/prod/oro_acl_annotations" is not writable. at /var/www/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php line 92) {"exception":"[object] (InvalidArgumentException(code: 0): The directory \"/var/www/pim-community-standard/var/cache/prod/oro_acl_annotations\" is not writable. at /var/www/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92)"} []

**Comment by Doodoune** [comment]
Hi @navneetbhardwaj!

Thanks for raise this issue.
Actually, we have a blacklist of code that can't be used as a code for an attribute. We will add it (and a couple of other).
I've created a ticket for our maintenance team to correct this issue. I'll keep up updated.

Regards,

**Comment by Doodoune** [comment]
Hi!

I've added the code "attributes" to the blacklist of code that can't be used as a code for attribute for the new version of the PIM (3.0).
In 2.3, codes "parent" and "categories" are already in this blacklist.

I close this issue. Don't hesitate to re-open it if you need more information.

Regards,

**Comment by navneetbhardwaj** [comment]
@Doodoune 
yes, you did blacklist the categories code, but if I create with the name **Categories** (C capital) it will again create the issue.
