### ISSUE TITLE
Upgrade from 2.1.9 to 2.2 Issue

### ISSUE THREAD

**Issue by kamranmalikawan** [akeneo/pim-community-dev#8409]
Duplicate definition of column 'id' on entity 'Pim\Component\Catalog\Model\  
  Product' in a field or discriminator column mapping.   

Please comer one help on this

**Comment by Doodoune** [comment]
Hi!

Do you still have this issue? Do you upgrade your PIM in the last version?

Regards,
Elodie

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it if needed.

Regards,
