### ISSUE TITLE
2.3 CE, error 400 on /rest/media

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#8415]
When I want to add an image in an image field or a file in a file field. The upload starts and stops very quickly. with app_dev.php I have a 400 error on / rest / media but no error in the logs.

![image](https://user-images.githubusercontent.com/4558101/42036898-291b390e-7ae7-11e8-905e-4b4e6db528d4.png)

**Comment by diglin** [comment]
What says your var/logs/ files ?

**Comment by travnewmatic** [comment]
i'm having the same issue.  try to upload, little progress bar flies across, but the image isn't actually uploaded.

In apache logs:
111.222.333.444 - - [31/Jul/2018:05:28:02 +0000] "POST /rest/media/ HTTP/1.1" 400 642 "https://xxx.yyy.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"

Nothing in var/logs/prod.log or var/logs/command_execute.log

**Comment by travnewmatic** [comment]
during install, a directory is made in /tmp

if the commands issued during the install process are run by user root, then the resulting directories created in /tmp are owned by root and are not accessible by the webserver owner www-data

the trick was to change the ownership of /the directory created in /tmp as such:
chown -R www-data:www-data /tmp/pim/

from what i've seen there are two directories that akeneo needs to access in /tmp/pim:
/tmp/pim/file_storage and /tmp/pim/upload_tmp_dir

for safety's sake, i've changed ownership to the top level of the akeneo directory in /tmp (/tmp/pim)

**Comment by Doodoune** [comment]
Hi!

I close this issue.
Feel free to re-open it if you still have this problem.

Regards,
Elodie

**Comment by TheZepo** [comment]
I am having the same problem. There was no folder generated in tmp during installation. I manually created  and took ownership of that folder and the required sub folders. Still receiving the same errors.
