### ISSUE TITLE
2.3 CE, Permission denied loading_messages.txt

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#8419]
Hello, i've this error in my apache log 

`
[Fri Jun 29 11:21:01.345582 2018] [proxy_fcgi:error] [pid 17772:tid 139791882430208] [client 172.17.0.5:52482] AH01071: Got error 'PHP message: PHP Warning:  file_put_contents(/var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/UIBundle/Resources/config/loading_messages.txt): failed to open stream: Permission denied in /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Oro/Bundle/ConfigBundle/Controller/Rest/ConfigurationController.php on line 90\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /var/www/html/pim-community-standard/web/app.php:0\nPHP message: PHP   2. AppKernel->handle() /var/www/html/pim-community-standard/web/app.php:30\nPHP message: PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202\nPHP message: PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68\nPHP message: PHP   5. Oro\\Bundle\\ConfigBundle\\Controller\\Rest\\ConfigurationController->postAction() /var/www/html/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151\nPHP message: PHP   6. file_put_contents() /var/www/html/pim-community-standard/vendor/akeneo/pim-community-dev/src/Oro/Bundle/ConfigBundle/Controller/Rest/ConfigurationController.php:90\n', referer: http://akeneo-dev.dom.dddddd/`

```
drwxr-xr-x  43 root     root       4096 juin  28 11:27 vendor
-- > drwxr-xr-x  3 root root  31 juin  28 10:41 akeneo
---- > drwxr-xr-x 14 root root 4096 juin  25 20:00 pim-community-dev
------ > drwxr-xr-x  7 root root     84 juin  25 19:16 src
-------- > drwxr-xr-x 4 root root 37 juin  28 10:41 Pim
---------- > drwxr-xr-x 22 root root 4096 juin  25 19:16 Bundle
------------ > drwxr-xr-x  9 root root  140 juin  28 10:41 UIBundle
-------------- > drwxr-xr-x 6 root root  67 juin  28 10:41 Resources
---------------- > drwxr-xr-x 2 root root  231 juin  28 10:41 config
------------------ > -rw-r--r-- 1 root root  274 juin  25 19:16 loading_messages.txt
```

Apache and php7.1-fpm use www-data user.

**Comment by jmleroux** [comment]
Hello @Philippe-M ,

It seems you installed your dependencies as root. This is not the right thing to do and it can effectively have  bad effects on file permissions.

**Comment by Philippe-M** [comment]
Hello @jmleroux ,

I'm change root to www-data for the directory pim-community-standard and the sub-directories, and i've always this error
