### ISSUE TITLE
Update constructor using EntityWithFamilyVariantNormalizer to NormalizerInterface.

### ISSUE THREAD

**Issue by OttoHermansson** [akeneo/pim-community-dev#8429]
These two classes are not using the interface in the constructor which makes it really hard to override the /src/Pim/Bundle/EnrichBundle/Normalizer/EntityWithFamilyVariantNormalizer.php class.

Pim\Bundle\EnrichBundle\Controller\Rest\ProductModelController.php
Pim\Bundle\EnrichBundle\Normalizer\VariantNavigationNormalizer.php

**Comment by KarenMayo** [comment]
Hello, 

These changes are available in the patch 2.3.47.

Regards,
