### ISSUE TITLE
Empty array of items where limit=1 in GET /products API

### ISSUE THREAD

**Issue by ducho** [akeneo/pim-community-dev#8458]
**I'm reporting a Bug**
[akeneo-pim-system-info_2018-07-05_11_51.txt](https://github.com/akeneo/pim-community-dev/files/2166419/akeneo-pim-system-info_2018-07-05_11_51.txt)

When I call endpoint for product's list with limit=1 than response is empty array of items. When I set limit=2 or more, query working correctly.

`/api/rest/v1/products?limit=1`

```{
{
    "_links": {
        "self": {
            "href": "https://url/api/rest/v1/products?page=1&with_count=false&pagination_type=page&limit=1"
        },
        "first": {
            "href": "https://url/api/rest/v1/products?page=1&with_count=false&pagination_type=page&limit=1"
        }
    },
    "current_page": 1,
    "_embedded": {
        "items": []
    }
}

**Comment by Doodoune** [comment]
Hi @ducho!

I don't reproduce the problem on the demo.akeneo.com. 
Do you still have the problem with a recent version?

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to re-open it if you still have this issue.

Regards,
