### ISSUE TITLE
Header is missing when you create Attribute group or Channel

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#8482]
**I'm reporting a Bug**
CE 2.3

http://demo.akeneo.com/#/configuration/attribute-group/create
http://demo.akeneo.com/#/configuration/channel/create

Header is missing when you create Attribute group or Channel
![attribute_group_create](https://user-images.githubusercontent.com/2612186/42757955-7dd7c238-890a-11e8-8d60-aeb015b94b45.jpg)

**Comment by Doodoune** [comment]
Hi! 

Effectively, the breadcrumb is missing on these pages.
I create a pull request to solve this issue. 
Thank you for raising this issue.
I'll keep you updated when it will available.

Regards,

**Comment by Doodoune** [comment]
The fix is available in 2.3.22 !

I close this issue, feel free to reopen it if you still have a problem.

Regards,
