### ISSUE TITLE
Move attribute in variants not working

### ISSUE THREAD

**Issue by JanKyselica** [akeneo/pim-community-dev#8501]
Problem:
I want to change order of attributes in the product form. When I move attribute in the family variant edit form order doesn't change.

Moving attribute in variants not working in your demo at http://demo.akeneo.com/#/configuration/family/clothing/edit.
Step to reproduce at your demo:

1. Go to Settings -> Families -> Clothing
2. In the Family edit form go to Variants tab and edit Clothing by color and size
3. In Common attributes drag Brand attribute, move at the first position before Name attribute and click on the Save button
4. In the Process tracker is new completed job compute_family_variant_structure_changes without warnings or errors.
5. Open again edit Clothing by color and size and attributes have old order (Name attribute is first). All products in this family have old order of attributes too.

[Our system information](https://github.com/akeneo/pim-community-dev/files/2209519/akeneo-pim-system-info_2018-07-19_10_38.txt)

**Comment by Doodoune** [comment]
Hi @JanKyselica!

It's a normal behavior.
This screen is here to select attributes useable for the variant axis. You can't order attributes in this screen.
If you want to order attributes you need to go on "Settings > Attribute groups" and here you can order attributes and for example, by drag&drop, put "Brand" before "Name" and save.

Regards,
Elodie

**Comment by Doodoune** [comment]
Hi!

I close this issue.
Feel free to reopen it if needed.

Regards,
