### ISSUE TITLE
Webpack touches redundant files. Critical for deployment of big projects.

### ISSUE THREAD

**Issue by vasiliy-sam** [akeneo/pim-community-dev#8550]
**I'm reporting a Bug**

Reproduced on Akeneo 2.3.1.
Not reproducible on Akeneo 2.1.2.

The cause of issue was involved by changes of this commit:
https://github.com/akeneo/pim-community-dev/commit/a6e509591ecc2b48f26d4f8a17fbf7b6a53a749c

The command 'yarn run webpack' takes too much time during execution of 'yarn run webpack' on large projects that have a lot of files in the project directory.

**Steps to reproduce:**
- as a part of command 'yarn run webpack' needs to debug the command 
`strace -v node /var/www/current/node_modules/.bin/webpack --debug --config vendor/akeneo/pim-community-dev/webpack.config.js --env=prod 2>&1 | grep "file_storage"`
(project directory may be different)

**Actual result:**
- execution process touches for example files in the 'file_storage' directory
`stat("/var/www/current/app/file_storage/asset", {st_dev=makedev(8, 6), st_ino=1449222, st_mode=S_IFDIR|0777, st_nlink=2, st_uid=33, st_gid=33, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2018/07/25-19:54:24.632669658, st_mtime=2018/04/06-13:02:05.142453000, st_ctime=2018/07/24-16:39:02.855001635}) = 0`

All existed files will be checked on maching of .tsx scripts at least in the next directories :
- app/archive
- app/file_storage
- web/media
- web/cache
- var/cache
- var/logs

**Expected result:**
- webpack schouldn't search any files at least in described directories

Execution time of this command was increased more than 5x times after updating to Akeneo v2.3+
I'm getting a deployment timeout error.

______
UPD; exact cause was added some later with this commit
https://github.com/akeneo/pim-community-dev/commit/40a821a4a6b7d32b04c5f5067d8b20e5b93cf0ef

Loader context with root directory in webpack.config.js

**Comment by juliensnz** [comment]
Hello @vasiliy-sam and thank you for this detailed bug report. We will take a look at it as soon as possible and keep you updated on the subject :)

**Comment by vasiliy-sam** [comment]
@juliensnz

UPD; exact cause was added some later with this commit
https://github.com/akeneo/pim-community-dev/commit/40a821a4a6b7d32b04c5f5067d8b20e5b93cf0ef

Loader context with root directory in webpack.config.js

**Comment by juliensnz** [comment]
Here is a fix: https://github.com/akeneo/pim-community-dev/pull/8554

before: 33s to build in Enterprise edition
after: 26s to build in Enterprise edition

**Comment by vasiliy-sam** [comment]
@juliensnz

The webpack time seems much better with this fix. Strace doesn't show files in the big directories more.

Before: 
Done in 310.38s.
After: 
Done in 17.36s.

Thanks.
