### ISSUE TITLE
Translation labels in forms don't show validation errors

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#8571]
**I'm reporting a Bug**
CE 2.3

In each form, where you have translation labels (family, attribute) you won't see wich input have error.

you can try enter very long label here:
http://demo.akeneo.com/#/configuration/family/camcorders/edit
input will not see string with error message

**Comment by Doodoune** [comment]
Hi,
This issue has been fixed in version 3.2. 
You can check on the demo.akeneo.com:
![Screenshot from 2019-11-13 15-50-33](https://user-images.githubusercontent.com/34027529/68774413-5c4bfc00-062d-11ea-8a09-7a86c8f2fea5.png)

Regards,
