### ISSUE TITLE
Missing translation for yes/no attributes.

### ISSUE THREAD

**Issue by oliverde8** [akeneo/pim-community-dev#8580]
**I'm reporting a Bug**

Boolean attributes translation are missing,  we therefore see pim_common.yes and pim_common.no instead. 

![image](https://user-images.githubusercontent.com/3658513/43404785-99309276-9418-11e8-8853-77554801378f.png)

Tested on the demo website (akeneo 2.3.2) as well. 

Thanks

**Comment by LaureBro** [comment]
Hello @oliverde8, 

The PR #8531 fixes the issue, it will be merged soon in higher versions. I'll let you know once the patch is available.

Thanks for the contribution :)

Kind regards,
Laure

**Comment by oliverde8** [comment]
This was fixed in 2.3.6
