### ISSUE TITLE
Issue Migrating from 2.2 to 2.3

### ISSUE THREAD

**Issue by paultvis** [akeneo/pim-community-dev#8583]
When upgrading the from 2.2 to 2.3 the following error occured when migrating the database. The command run is php -d memory_limit=3G ../composer.phar update

Error
--------------------------------------------------------
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:

  The service "pim_analytics.data_collector.database" has a dependency on a non-existent service "pim_volume_monitoring.persistence.query.count_channels".

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

  [RuntimeException]
An error occurred when executing the "'cache:clear --no-warmup'" command:

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:

The service "pim_analytics.data_collector.database" has a dependency on a non-existent service "pim_volume_monitoring.persistence.query.count_channels".
----------------------------------------------------------

**Comment by oliverde8** [comment]
You need to check your config files. 
That particular error is due to a new Bundle that you don't have in your AppKernel.php file. 

https://github.com/akeneo/pim-community-standard/blob/master/UPGRADE-2.3.md

**Comment by paultvis** [comment]
Thanks for the response. So does that not mean that something has been missed in the upgrade script though? I downloaded the package, followed the instructions (which worked fine going from 2.0 - 2.1 then 2.1 - 2.2).

**Comment by Doodoune** [comment]
Hi!

As @oliverde8 says, in the file https://github.com/akeneo/pim-community-standard/blob/master/UPGRADE-2.3.md you have all the modifications to apply when you migrate from a 2.2 to a 2.3 version. 
I think you miss the number 5 (Register PimCatalogVolumeMonitoringBundle in the AppKernel.php).

I close this issue, if you still have the problem, feel free to reopen it.

Regards,
