### ISSUE TITLE
Curly brace in front of search results with 1 result in UI locale german

### ISSUE THREAD

**Issue by khoyer-reply** [akeneo/pim-community-dev#8616]
*Account setting UI locale to german language e.g. "German (Germany)"
*Search at products with a result of 1 product
*Curly brace in front of number of results
![curlybrace](https://user-images.githubusercontent.com/22073864/43712415-660165d4-9976-11e8-927c-6252d86ddb6a.jpg)

**Comment by jmleroux** [comment]
Hell @khoyer-reply ,
Thanks for reporting this bug. It can be reproduced on the demo environment and we will add it to our backlog.

**Comment by pierallard** [comment]
Hi @khoyer-reply ! I fixed it in Crowdin, our translation tool : 
https://crowdin.com/translate/akeneo/all/en-de#q=%7D%7D+Ergebnis
The translations are synchronized every week, so you will have the correct translation in a couple of days.
Thanks for reporting!

Pierre
