### ISSUE TITLE
Go to for page in Pagintation

### ISSUE THREAD

**Issue by ztruex** [akeneo/pim-community-dev#8620]
Hello,
I am having problems creating a Go to Page in Akeneo 2.2.  I was able to create the text field in the grid view using `src/Pim/Bundle/DataGridBundle/Resources/public/templates/datagrid/pagination.html`.
The code that makes the field is:
```
<span><input type="number" step="1" name="pageNumber" id="page-number" value="" placeholder="" class="AknActionButton AknGridToolbar-actionButton active AknActionButton--highlight"></span>
```

Once I created the field I began to edit `pagination.js` and `pagination-input.js`.  The `pagination-input.js`   defines and calls `pagination.html`.
I am using lines based on some one had a similar issue, but the solution is working for me.  The 2 hooks are:
```
       /** @property */
        events: {
            "click a": "onChangePage",
            "keyup #page-number": "onChangePage"
        },
```

and
```
            if (e.keyCode === 13) {
                collection.getPage(parseInt($(e.target).val()));
            } else if (e.type === 'click') {
                collection.getPage(state.firstPage === 0 ? pageIndex : pageIndex + 1);
            }
```

I tried putting these is either .js file, but the UI is not reflect the funtions.  I used `alert` functions to see what values are being passed and I noticed that while clicking the next page it produced a value, no value was passed in the numeric field that I created in the `.html` file.

When I edit the files, I run the following commands to update the UI:
`rm -rf ./var/cache/*`
`bin/console pim:installer:dump-require-paths`
`bin/console pim:install:assets`
`bin/console assets:install web`
`yarn run webpack`

What do I need to change, add, and/or remove in the code to allow my to type in a page and go to it?

**Comment by ztruex** [comment]
So I managed to solve my issue.  The steps were:
In `src/Pim/Bundle/DataGridBundle/Resources/public/templates/datagrid/pagination.html` I added
```
<span>
<input type="number" step="1" name="pageNumber" id="page-number" value="" placeholder="" class="AknActionButton AknGridToolbar-actionButton active AknActionButton--highlight">
</span>
```
This creates the numeric field.
Next in `pagination-input.js` I added a new hook and edited the events:
```
       /** @property */
        events: {
            "click a": "onChangePage",
            "blur input": "onChangePageByInput",
            "change input": "onChangePageByInput",
            'keyup input': function(e) {
                if (e.which == 13) {
                    // fix for IE 8, bacause change event is not fired when enter is pressed
                    this.onChangePageByInput(e);
                }
            }

        },
```
and
```
        /**
         * Apply change of pagination page input
         *
         * @param {Event} e
         */
        onChangePageByInput: function(e) {
            e.preventDefault();

            var pageIndex = parseInt($(e.target).val());
            var collection = this.collection;
            var state = collection.state;

            if (_.isNaN(pageIndex)) {
                $(e.target).val(state.currentPage);
                return;
            }

            pageIndex = state.firstPage == 0 ? pageIndex - 1  : pageIndex;
            if (pageIndex < state.firstPage) {
                pageIndex = state.firstPage;
                $(e.target).val(state.firstPage == 0 ? state.firstPage + 1 : state.firstPage);
            } else if (state.lastPage <= pageIndex) {
                pageIndex = state.lastPage;
                $(e.target).val(state.firstPage == 0 ? state.lastPage + 1 : state.lastPage);
            }

            if (state.currentPage !== pageIndex) {
                collection.getPage(pageIndex);
            }
        },
```
I am now able to type in a page number and the console jumps to that page.
Now this is still limited by the elastic search issues that I have been reading about concerning pages beyond 10k records.
Also `onChangePageByInput` is based off of Akeneo 1.6 and may need to be updated, but this solution works for the time being.

**Comment by Doodoune** [comment]
@ztruex, I see that you found a fix for your issue. Can we close this ticket?

Regards,

**Comment by Doodoune** [comment]
Hi! I close this issue, feel free to reopen it if you still have an issue.
Regards,
