### ISSUE TITLE
Can not use PHP 7.2 since mcrypt extension is still required

### ISSUE THREAD

**Issue by tautelis** [akeneo/pim-community-dev#8668]
I guess this line should be removed since PHP 7.2 has deprecated mcrypt extension and it seems it is not used anywhere in the project.
https://github.com/akeneo/pim-community-dev/blob/master/app/PimRequirements.php#L34

**Comment by tadcka** [comment]
Akeneo pim support php 7.2? https://github.com/akeneo/pim-community-dev/pull/6081

**Comment by tautelis** [comment]
Yesterday I tried to run pim on php72. It started with no menu entries. Then I found there is an issue created for that https://github.com/akeneo/pim-community-dev/issues/8289

**Comment by tadcka** [comment]
Thanks :)

**Comment by Patdundee** [comment]
Hi Guys
New to this Akeneo. I am trying to install the latest version 2.3 and I am running PHP7.2 I am still getting the error message Install and enable the mcrypt extension. This is already installed and enabled Version 2.6.8

Any ideas how to get around this please

Many thanks
P

**Comment by Doodoune** [comment]
Hello,

PHP 7.2 is not currently supported.
Only PHP 7.1 is supported on the last version (2.3).

https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/system_requirements.html

Regards,
Elodie
