### ISSUE TITLE
Pim incompatible with docker-based production env

### ISSUE THREAD

**Issue by proArtex** [akeneo/pim-community-dev#8698]
Lets imagine you use Kubernetes. You have to use mounted volume for each directory accessed from multiple pods (or docker instances) such as uploads, file_storage, media etc. Most of them are configurable through pim_parameters.yml. But file exports and job-queue-consumer-daemon works with /tmp folder by default (e.g. 'filePath' => sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'export_%job_label%_%datetime%.xlsx',), that is system and cannot be mounted to persistent storage. There is no way to set the parameter like "%export_dir%. Moreover 'filePath' can be changed in UI for each export profile, so you cannot guess what folder should be mounted as persistent.

Solution for this issue may be configuring of path prefix parameter such as %export_dir%. All the UI filePaths could be relative instead of absolute.

**Comment by stefandoorn** [comment]
Experiencing the same issue here while setting up deployments on GCP. Also the PIM requirements checker doesn't keep in account other FlySystem adapters might be in place while checking for the existence of certain directories.

**Comment by wakqasahmed** [comment]
Just wondering if this change fixes the issue (yet to be tested)
https://github.com/akeneo/pim-community-dev/blob/master/CHANGELOG-4.0.md#storage-configuration
