### ISSUE TITLE
Akeneo 2.3.5. Missing translation for 'pim_common.yes' and 'pim_common.no'

### ISSUE THREAD

**Issue by vasiliy-sam** [akeneo/pim-community-dev#8751]
I'm reporting a Bug

Akeneo CE 2.3.5
Boolean attributes have no translations for  'pim_common.yes' and 'pim_common.no' labels.

Reproduced on Akeneo demo. Example:
http://demo.akeneo.com/#/enrich/product/1045

![screenshot from 2018-08-24 10-01-20](https://user-images.githubusercontent.com/2675947/44569938-ad4fa600-a784-11e8-90cb-4e3b3a084f7e.png)

**Comment by oliverde8** [comment]
I already reported this **a month** #8580 ago. It was fixed in 1.7 but still no fix in the 2.3 ....

**Comment by vasiliy-sam** [comment]
@oliverde8 Thanks, I close this ticket as a duplicate.
Waiting for solving of https://github.com/akeneo/pim-community-dev/issues/8580
