### ISSUE TITLE
extra spaces in the common textarea field

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#8757]
**I'm reporting a Bug**

PIM CE 2.3

pls, remove extra spaces around value in this template:
https://github.com/akeneo/pim-community-dev/blob/2.3/src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/textarea.html

**Comment by Doodoune** [comment]
Hi !

Why ? We do that everywhere in our js templates.

Regards,
Elodie

**Comment by Doodoune** [comment]
Hi!

This fix is available in the version 2.0.43 & 2.3.18 of the PIM.
I close this issue. Don't hesitate to re-open it if you still have this issue.

Regards,
