### ISSUE TITLE
Wrong ancestors category filtering on product grid. Variants are displayed together with models.

### ISSUE THREAD

**Issue by vasiliy-sam** [akeneo/pim-community-dev#8781]
**I'm reporting a Bug**

Reproduced on Akeneo 2.3.5.
Not reproduced on Akeneo Demo because of version. (2.3.2 at the moment).

Steps to reproduce:
1. Create a product model with some category.
2. Create a variant based on this model.
3. Open product grid and add category filter for example with root catalog (not "All products").

Actual result:
- Variant products are displayed together with their parent model, not aggregated.
![screenshot from 2018-08-30 15-54-35](https://user-images.githubusercontent.com/2675947/44852992-67577e00-ac6d-11e8-92ba-d011f8957921.png)

Expected result:
- Product models are displayed without child variants.

Possible related to this PR:
https://github.com/akeneo/pim-community-dev/pull/8645
According to the description, business logic changes wasn't planned in the fix, but it was changed.

Explanation:
After filters are applied query builder will aggregate results.
\Pim\Bundle\EnrichBundle\ProductQueryBuilder\ProductAndProductModelQueryBuilder::aggregateResults 

Here is a filter of categories that let to exclude categories of parents ('categories_of_ancestors' filtering)
After category filtering was changed from collected 'IN' list to the 'IN CHILDREN' identifier variable $categoryCodes contains only one category identifier. So ancestor category filtering isn't working as expected.

Pay attention to the last lines from the screenshots below. Terms of 'categories_of_ancestors'.

Version 2.3.1 query builder. 139 ancestor categories:
![qb 2 3 1](https://user-images.githubusercontent.com/2675947/44854454-324d2a80-ac71-11e8-9542-b99a52c5b981.png)

Version 2.3.5 query builder. 1 ancestor category:
![qb 2 3 5](https://user-images.githubusercontent.com/2675947/44854469-46912780-ac71-11e8-9031-86e4cc4ad02d.png)

A possible fix is to reload children categories in the method getCategoryCodes if an operator is 'IN CHILDREN'.
So we can see that all changes connected to the improvement of child categories loading will be not applicable (partially excepting scalability)ю The result ES query will be exactly the same as was before.

**Comment by Delphineray** [comment]
Hello,

Thanks for the details, we reproduced this bug and opened a ticket to fix it, we will keep you in touch about its resolution.
We also deploy the 2.3.5 on demo.akeneo.com, thanks for your feedback.

Regards,
Delphine
