### ISSUE TITLE
 PROPERTY "COMPLETENESS" EXPECTS A VALID LOCALE 

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#8837]
**I'm reporting a Bug**

Hello, I'm using the last version (2.3.7). Using a simple export of product model, I get this error :
 
 PROPERTY "COMPLETENESS" EXPECTS A VALID LOCALE 

>> what does that mean, and how to fix please ?

**Comment by grabelle** [comment]
16:51:34 ERROR     [batch] Encountered an error executing the step: Property "completeness" expects a valid locale. [] []
An error occurred during the export execution.
Error #305 in class Akeneo\Component\StorageUtils\Exception\InvalidPropertyException: Property "completeness" expects a valid locale.
16:51:34 ERROR     [batch] Encountered an error executing the step: Property "completeness" expects a valid locale. [] []

**Comment by ankit-sf** [comment]
Hello,
this problem occurs when
1. you create a product model export job  (like csv export)
and don't change completeness value http://i.prntscr.com/9GgMACi8RVmYock6lV1j4w.png
2. then run job
*workaround*
change completeness value (you can even revert to same value after changing dropdown value twice)
and run export job

*Some more insight*
job parameters for job instance with error: http://i.prntscr.com/KEpGLU0gTQmOTabrWF5C6Q.png
job parameters for job instance without error:http://i.prntscr.com/Kj45zeEeRuyN3qutgyEl8w.png

Possible solutions: Add context in default values for product model jobs based on default locales
maybe add context in file Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\DefaultValueProvider\ProductModelCsvExport and others like xls etc

**Comment by Doodoune** [comment]
Hi @grabelle!

Did you still have a problem or can we close this issue?

Regards,
