### ISSUE TITLE
Doubt about Pim 3.0 version

### ISSUE THREAD

**Issue by mauroandres** [akeneo/pim-community-dev#8844]
Hi! I download Pim in composer.json have "require": {"akeneo/pim-community-dev": "3.0.x-dev@dev"} but this branch is master. I should use master or 2.3 brach?

**Comment by mauroandres** [comment]
master is a stable version?

**Comment by BitOne** [comment]
Hello @mauroandres !

Not exactly, master is the ongoing development version. It will be version 3.0 in the future, but it's definitely not stable right now ;)

You should use a release or a tag instead of a branch, see https://github.com/akeneo/pim-community-dev/releases.

Thank you!

**Comment by BitOne** [comment]
By the way, you should use the standard edition. This repo is the one for the development edition, for developing *inside* the PIM.

If you want to do a project, use the standard, it's made for that. You can use a tag too: https://github.com/akeneo/pim-community-standard/releases/tag/v2.3.6

**Comment by mauroandres** [comment]
@BitOne Thanks for the answer!
