### ISSUE TITLE
Not showing thumbnails

### ISSUE THREAD

**Issue by jbrion** [akeneo/pim-community-dev#8873]
Hi everyone,

Im uploading pictures to my products but they are not shown as thumbnails, is there any option to select which is the thumbnail for each product?

Thanks in advance.

**I'm reporting a Bug**

Please update to the last available patch for the version.

For version >= 1.4, please go to "System > system info", download the text report and attach it to the issue.

Then explain the expected behavior, the encountered behavior and the steps to reproduce.

**I'm asking a Question**

Please submit your question via the forum https://www.akeneo.com/forums/forum/programming-questions/

**I'm submitting a Feature Request**

Please submit your feature request via the forum https://www.akeneo.com/forums/forum/feature-request/

**I'm using the Enterprise Edition**

Please use your access to our support service desk.

**Comment by ankit-sf** [comment]
Hello jbrion,
maybe you mean to select attribute used as image in family
http://i.prntscr.com/cA_c1wTVQtiPwBTaRiWIhA.png

**Comment by Doodoune** [comment]
As ankit-sf says, you can use the "Attribute used as the main picture" in the family edition.

I close this issue, feel free to reopen it if you still have a problem with thumbnails.

Regards,
