### ISSUE TITLE
How to extend Doctrine entities

### ISSUE THREAD

**Issue by fjlenatz** [akeneo/pim-community-dev#8886]
Hi guys.

I'm in the need of extending Product Entity. I've to add some fields for filtering elastic search results. There is no other alternative, other than rewriting LOTS of code, and that's not an option. The entities aren't super mapped class, so I can't use doctrine tools for extending and adding properties. Any ideas?

Thanks!

**Comment by fjlenatz** [comment]
Of course, I have no intentions on changing vendor code.

**Comment by Doodoune** [comment]
Hi ! 

You explain the process in our documentation here : https://docs.akeneo.com/2.3/manipulate_pim_data/category/add_new_properties_to_a_category.html
This example is for category but you can do the same on product.

Regards,
Elodie
