### ISSUE TITLE
Database error on installing

### ISSUE THREAD

**Issue by Patdundee** [akeneo/pim-community-dev#8898]
**I'm reporting a Bug**
Hi Guys
I am trying to install the latest version 2.3 Community Edition and I am running PHP7.2 Running on Ubuntu Server 16.04
I have managed to get as far as this command bin/console pim:install --force --symlink --clean --env=prod which is just befoe the Yarn Run Webpack. When it gets to installing the tables I keep getting errors. I have attached a copy of the log for you to see.
[InstallDatabaseError.txt](https://github.com/akeneo/pim-community-dev/files/2422561/InstallDatabaseError.txt)

Any ideas how to get around this please

Many thanks
P

**Comment by Patdundee** [comment]
Hi Guys
Has anyone got any idea how to fix this issue please?

**Comment by Doodoune** [comment]
Hi @Patdundee!

Did you solve your issue? 
I see that you use PHP 7.2 to running a 2.3 version, but the PIM in 2.3 version only work with a PHP 7.1 version: https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/system_requirements.html

Regards,

**Comment by Doodoune** [comment]
I close this issue.

Feel free to reopen it if needed.

Regards,
