### ISSUE TITLE
Add attributes values on Custom Reference Error 

### ISSUE THREAD

**Issue by taniot** [akeneo/pim-community-dev#8923]
Hello,
I am trying to use the functionality "Add attributes values" on a custom reference field, but I'm having some problems.

Let me try to explain it.
If I add a value to an empty field, it works correctly.
If I add a value to a populated field, it fails and returns this error:

```
console.ERROR: Error thrown while running command "akeneo:batch:job add_attribute_value 602 --env=prod". Message: "Call to undefined method Pim\Component\ReferenceData\Value\ReferenceDataCollectionValue::getOptionCodes()" {"error":"[object] (Error(code: 0): Call to undefined method Pim\\Component\\ReferenceData\\Value\\ReferenceDataCollectionValue::getOptionCodes() at /var/www/www.mydomain.com/pim-project/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Updater/Adder/MultiSelectAttributeAdder.php:73)","command":"akeneo:batch:job add_attribute_value 602 --env=prod","message":"Call to undefined method Pim\\Component\\ReferenceData\\Value\\ReferenceDataCollectionValue::getOptionCodes()"} []
```

Do you have any suggestion?
Regards

[akeneo-pim-system-info_2018-10-02_18_10.txt](https://github.com/akeneo/pim-community-dev/files/2441008/akeneo-pim-system-info_2018-10-02_18_10.txt)

**Comment by Doodoune** [comment]
Hi!

Visibly you try to call a function getOptionCodes that is doesn't exist in Pim\Component\ReferenceData\Value\ReferenceDataCollectionValue (cf https://github.com/akeneo/pim-community-dev/blob/2.3/src/Pim/Component/ReferenceData/Value/ReferenceDataCollectionValue.php).

Can you explain me step by step what you try to do // how to reproduce this error ?

Regards,

**Comment by Doodoune** [comment]
Hi, I close this issue, feel free to re-open it if you still have a problem.

Regards,
