### ISSUE TITLE
Database error on install

### ISSUE THREAD

**Issue by Patdundee** [akeneo/pim-community-dev#8947]
**I'm reporting a Bug**

Hi Guys
I am trying to install the latest version 2.3 Community Edition and I am running PHP7.2 Running on Ubuntu Server 16.04
I have managed to get as far as this command bin/console pim:install --force --symlink --clean --env=prod which is just befoe the Yarn Run Webpack. When it gets to installing the tables I keep getting errors. I have attached a copy of the log for you to see.
[InstallDatabaseError.txt](https://github.com/akeneo/pim-community-dev/files/2452821/InstallDatabaseError.txt)
Any ideas how to get around this please

Many thanks
P

**Comment by Doodoune** [comment]
Hi! 

Link to this issue : https://github.com/akeneo/pim-community-dev/issues/7440

It seems that is a problem about your ElasticSearch version.
Is your ElasticSearch version is the same as the required version for Akeneo ?
-> https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/system_install_ubuntu_1604.html#elasticsearch-5-5-or-5-6

Regards,

**Comment by Doodoune** [comment]
Hi, I close this issue, feel free to reopen it, if you still have a problem.

Regards,
