### ISSUE TITLE
Unable to update attribute label

### ISSUE THREAD

**Issue by unxsist** [akeneo/pim-community-dev#8966]
**I'm reporting a Bug >= 2.3.x**

I am unable to update an attribute label because it tries to update some other properties of the attribute as well. As a response I get a 400 - Bad Request containing the following information:

`[{"path":"metric_family","message":"This property cannot be changed.","global":false}]`

The strange thing is that this is an image attribute with nothing relating to any metrics at all. It seems that it somehow does not detect that only the labels have been changed.

**Comment by LaureBro** [comment]
Hello @unxsist , where are you trying to update this attribute? In a product form? 
On which exact patch are you (2.3.?), if you are not on the latest patch, could you update your PIM? If you are on the latest patch, could you guide me so I can try to reproduce the issue?

Thanks a lot, 
Laure

**Comment by unxsist** [comment]
Hi Laure,

We are on version 2.3.11.

We are trying to update the attribute labels through the attribute edit form:

**Steps to reproduce**
1. Navigate to Settings -> Attribute
2. Select an attribute
3. Navigate to the Label Translations Tab
4. Change the label for any locale
5. Save the attribute

**Result**
400 - Bad request - The attribute could not be updated.

It's important to know that we migrated from 1.7 to 2.0 in the past and the error does not occur on all attributes.

**Comment by Doodoune** [comment]
Hi!

I don't reproduce this behaviour on http://demo.akeneo.com. 

Can you provide me an export of the attribute that has this problem? 

Regards,
Elodie

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it if you reproduce it.

Regards,
Elodie
