### ISSUE TITLE
“Nesting level too deep – recursive dependency?” for some custom reference_data attributes

### ISSUE THREAD

**Issue by ankit-sf** [akeneo/pim-community-dev#9023]
**I'm reporting a Possible Bug**
got error 

> Uncaught PHP Exception SymfonyComponentDebugExceptionFatalErrorException: "Error: Nesting level too deep - recursive dependency?" at /pim/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributesValidator.php line 60

https://github.com/akeneo/pim-community-dev/blob/2.3/src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributesValidator.php#L60

Please note  in_array does non-strict comparison (equivalent to an == operation) when testing the haystack for the needle
so for in_array($object, $doctrineCollection);
with objects of medium complexity, i step into this error

> Nesting level too deep – recursive dependency

so maybe code should be 

> if (!in_array($modelAttribute, $levelAttributes, true)) {

for stricttype check to avoid circular references.

**Comment by jmleroux** [comment]
Thank you @ankit-sf for raising this issue.
I made the corresponding PR.

**Comment by jmleroux** [comment]
At last i merged and tagged.
Thanks for your patience. :+1:
