### ISSUE TITLE
Simple List Attribute Export the Code of the Option, not the value of the Locale

### ISSUE THREAD

**Issue by vbidou** [akeneo/pim-community-dev#9049]
**I'm reporting a Bug**

Hello,
There are already fewdays that I block on an issue which I reproduced to the Akeneo Test environment with the same error result.

I wanted to export (csv or xls, it doesn't matter) Product data for a given locale (was "French" but it's not important). My Product data contains one Attribute "Vendor Pricing Group" which is Simple List, which I associate to the Group ERP. For this simple List, I created several lines of options, all starting with a code which contain an Underscore (ex: "MB_156" - because code doesn't accept hyphens), and then a value for each Locale which is made of hyphens (English: MB-156-EN; French: MB-156-FR; Russian: MB-156-RU). For the Attributes "Simple List", I expected that the exporting job will send the content of the French Locale (Here MB-156-FR). It doesn't work and always export the value of the Option code with the Underscore (MB_156).

I suppose that it's a bug occurring only on Simple Select field, since TEXT attributes aren't affected and allow export of the proper Locale entry. I attempted to play with the ATTRIBUTE properties (like "Value per Channel = Yes" or/And "Value per Locale = Yes") but the result is always the same no matter what.

It's very easy to reproduce this bug, and I must say that I don't know if/how it can be resolved.
Any idea welcome.

vbidou

**Comment by oliverde8** [comment]
This is not a bug, 

It's expected behaviour. Akeneo exports what it expects in the imports. And for Simple Select & Multiple Select fields it will always export codes & will always import codes. 

It works the same way for categories. 

You may very well have 2 option values with the same label, its not prohibited, the only thing that is unique for a given attribute sure is the code. 

Regards

**Comment by vbidou** [comment]
Thanks for your feedback.
Indeed, I understood with your feedback that Attribute Options which are attached to another table are rendered as a code in the export. Hence I have to base my work on the locales from the data of those dedicated tables, and not from the Product export. Thanks a lot. Case closed.

**Comment by oliverde8** [comment]
Ideally you should have more then 1 file. You have the attribute option export, so you need to use those 2 files. Not use the database from another application. 

You can also use api's with the same logic,
