### ISSUE TITLE
How we set a path of images in akeneo

### ISSUE THREAD

**Issue by parveen12345** [akeneo/pim-community-dev#9110]
Hello,
How are you
I don't know how we set a path of images to import images from magento1.9 to Akeneo, using CSV.

Any Suggestions !

Thanks
Regards 
Parveen Narwal

**Comment by Doodoune** [comment]
Hi!

This is a functionality of Enterprise Edition: https://docs.akeneo.com/2.3/manipulate_pim_data/product_asset/mass_import.html#how-to-mass-import-assets

Regards,

**Comment by Doodoune** [comment]
Hi! I close this issue. Feel free to reopen it if needed.

Regards,
