### ISSUE TITLE
Update doc to show 2.3 instead of 3.0 

### ISSUE THREAD

**Issue by ankit-sf** [akeneo/pim-community-dev#9148]
**This is just a suggestion**
pim version in command should be 2.3, till stable version of Akeneo 3.0 is release on https://github.com/akeneo/pim-community-standard#using-composer-to-create-the-project

    $ php composer.phar create-project --prefer-dist akeneo/pim-community-standard ./pim-project "3.0.*@stable"

http://i.prntscr.com/Ew3R_fKfRgOjO5qCHcPZ-Q.png

**Comment by wa-daniel-fahl** [comment]
IMHO this is correct behaviour - check the tag 2.3, it's correct there. master is (as far as I have seen so far) the most recent development stage

**Comment by ankit-sf** [comment]
@wa-daniel-fahl , yes you are right https://github.com/akeneo/pim-community-dev/issues/8844#issuecomment-421055561
