### ISSUE TITLE
Cannot install Akeneo usin MariaDB 10.1, 10.2 or 10.3

### ISSUE THREAD

**Issue by masanzsa** [akeneo/pim-community-dev#9210]
Steps to reproduce
1. Get either the git version or the tar package
2. Deploy tar or git clone into your installation dir (in my case `/var/www/html/`)
3. Run installation as follows:
  3.1. `php -d memory_limit=3G ../composer.phar install --optimize-autoloader --prefer-dist`
  3.2. `yarn install`
  3.3. `php bin/console cache:clear --no-warmup --env=prod`
  3.4. `php bin/console pim:installer:assets --symlink --clean --env=prod`
  3.5. `bin/console pim:install --force --symlink --clean --env=prod`

Actual Behavior
```
+---------+-----------------------------------------------------------------------------------------------------------+
| Check   | Errors                                                                                                    |
+---------+-----------------------------------------------------------------------------------------------------------+
| ERROR   | Install MySQL greater or equal to 5.7.0 and lower than 5.8.0 (installed version is 5.5.5-10.2.19-MariaDB) |
+---------+-----------------------------------------------------------------------------------------------------------+
```

Expected behavior
The SW should run fine on MariaDB 10.2.19 being this the equivalent for MySQL 5.7.x
Please note that also 10.1 and 10.3 were tried, with the same exact result. 

Is Akeneo only compatible with Oracle's MySQL ?

**Comment by jmleroux** [comment]
From what i read, the requirements checker see your MariaDB as the equivalent of a MySQL 5.5

> installed version is 5.5.5-10.2.19-MariaDB

**Comment by masanzsa** [comment]
yes, true, but:
```
$ mysql -V
mysql  Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1
```
I dont know where the checker is taking the 5.5.5 from (maybe I am missing something?)

And as per the MariaDB RN: https://downloads.mariadb.org/
> MariaDB 10.2 is a stable release of MariaDB. It is built on MariaDB 10.1 with features from MySQL 5.6 & 5.7, and entirely new features not found anywhere else.

Is there something I am doing wrong?

I am using CentOS Linux release 7.6.1810 (Core).

**Comment by masanzsa** [comment]
Hi @jmleroux ,

Thanks for your reply. Will do so. 

So far, removing MariaDB service and installing MySQL community 5.7 solved my problem, but just would like to validate if MariaDB is supported, and if it is, flavor and version.

Will ask at slack and will report back here if I get feedback.

Thanks!

Mariano Sanz

**Comment by cypx** [comment]
To get MariaDB returning the right value to the the requirement checker you could update the version suffix
https://stackoverflow.com/questions/44179725/how-to-upgrade-mysql-in-mariadb-10-2-6/49381343#49381343

But Akeneo 2 use mysql json data type which is implemented with some difference on MariaDB https://mariadb.com/kb/en/library/json-data-type/ 
As i have tested it's working but i could not say if it's 100% safe to use.

**Comment by bpxsw** [comment]
This is still an issue with installing Akeneo on a server with MariaDB (10.2) installed.

Followed the stackoverflow link @cypx posted to set the version being returned by MariaDb. Verified the MySQL version installed is actually 5.7.26 but still receive the following error:

`| ERROR   | Install MySQL greater or equal to 5.7.22 and lower than 5.8.0 (installed version is 5.5.5) |`

Other software installed on this server, namely Magento 2.3, have MySQL 5.6/5.7 requirements and install without flagging 5.5.5 being the installed version of MySQL.

**Comment by ExperienceUK** [comment]
Still an issue in 2022

Install MySQL greater or equal to 8.0.18 and lower than 8.1.0 (installed version is 5.5.5)
Version installed:
mysql  Ver 15.1 Distrib 10.4.24-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by amirhmoradi** [comment]
still an issue in 2023 !
please provide a fix :)

**Comment by mautz-et-tong** [comment]
Still an issue in 2024 in v6 (and I haven't found code changes in v7 for this...
I use [this patch file](https://gist.github.com/mautz-et-tong/4b9b5df1d7089841c6c723f16f347007) for latest Akeneo v6.
Maybe that helps someone...
