### ISSUE TITLE
Export have some duplicate products 

### ISSUE THREAD

**Issue by gregoirepaqueron** [akeneo/pim-community-dev#9231]
Hi,

I'm on 2.3.15 CE.

I have a catalog of ~ 3600 products.
3000 are variant products, and so ~ 600 products are single products.

On an export job : 
- Exporting products in CSV
- 1 channel
- 1 locale 
- only 1 attribute to export (i want to export only SKU, but i'm forced to select at least 1 other attribute, otherwise it exports every attributes)
- No conditions about filtering, no family, no state, no completion, no date, all categories, no IDs list.

I have like ~ 13 products in duplicate (2 lines for each). If i choose to export every attributes, my duplicate have exactly the same information.

I filtered the export on the ID of one of this duplicate, and my export contains 2 lines, the same two line of my product.

Do you have any idea ? 

Thanks in advance

**Comment by gregoirepaqueron** [comment]
Thank you,

but i cannot access this slack user group : 
Si vous avez une adresse e-mail @akeneo.com ou @kiboko.fr , vous pouvez créer un compte.

**Comment by jmleroux** [comment]
Hey @gregoirepaqueron ,

i just tried to join in a anonymous chrome session and it worked.

I was on this page: https://akeneopim-ug.herokuapp.com/
entered my personal email address (not akeneo) and received my invitation in minutes.

**Comment by gregoirepaqueron** [comment]
@jmleroux thanks ! Could not find the link !

**Comment by wa-daniel-fahl** [comment]
@gregoirepaqueron I wrote you on slack

**Comment by gregoirepaqueron** [comment]
@wa-daniel-fahl thanks, i answered you

**Comment by jmleroux** [comment]
I will close this issue and let you continue on the Slack UG.
