### ISSUE TITLE
Installation fails on last step

### ISSUE THREAD

**Issue by UncleRemus** [akeneo/pim-community-dev#9239]
I'm working on the last step of the install and I have no clue what to do. I've followed the extremely complex, not complete installation instructions but cannot get past this step. 

I've double checked my dependencies, tried the download version of the install as well as the Composer "pim-project" version.

When running `sudo bin/console pim:install --force --symlink --clean --env=prod`

Here's what I get.

```
ERROR     [batch] Encountered an error executing the step: {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [extension.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}}}
```

I really wish I could install this software without 20 hours of work. I'm about to give up and just use something else since I cannot even get it installed. Also, This is the most difficult repo I've ever tried to install. If you want to get people to use it, you will have to make it easier.

This is on Ubuntu 16.04.4 x64

**Comment by pierallard** [comment]
Hi @UncleRemus 
Thanks for your feedback about the installation. If you find any gap in the documentation, we will be glad to fix issues / merge some PRs on the docs repository https://github.com/akeneo/pim-docs .

To fix your issue, it's probably an issue with one of the .yml configuration file. Could you review your app/config/ parameters files ? (parameters, pim_parameters, etc) ? There is probably a 'no' value on a field, when 'true' or 'false' is required.
Did you do some custom development on your installation ? What's the version you're trying to install ?

Regards
Pierre

**Comment by UncleRemus** [comment]
> Maybe coming from the ElasticSearch version like in this issue: #7459
> 
> You're getting old @pierallard when you don't remember your own answers 😉 😄

Downgrading was the issue. For some reason when I copied the instructions it still wanted to install ES v6.
