### ISSUE TITLE
What is the label field ?

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#9240]
Hi,
Sorry if my question is stupid but I don't see what is the "Label" field (on the product tabs you can search by "Label or by identifier" ... it looks like the Label is in fact the "code" so in many case it will look like a code :-/ .... I can't imagine to use a real label like "Break pad" for a code. I have many product that can have the same name 

Example : name "break pad"  collection 2018 and another collection 2017 ... as you can imagine in the code I prefer to use the same value as the ID. At the end I can't search "break pad" in the search bar
>> so for me we should be able to select the field to be indexed for the search

Thanks for your help

**Comment by jmleroux** [comment]
The search is based on the "attribute as label" setting. This is a family setting as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/1516770/49784417-801c0900-fd1d-11e8-84f9-568acb272cdf.png)

**Comment by grabelle** [comment]
@jmleroux : thanks a lot !!
