### ISSUE TITLE
Import a file with only partial data 

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#9256]
Hi,
I have a question : if I import a file with only partial data (ie only one attribute for a product model ... like description) ... all the other attributes are deleted ! Should I add something in the file to say "hey this is a partial update !" ?

Thx for your help
-----------------------------
Akeneo CE 2.3.21

**Comment by mmetayer** [comment]
Hello @grabelle,

If you wish to partially update product/product models, you should only let the columns (and headers) corresponding to the values you want to change in your import file (e.g if you only want to update the *name* value of your entities, just import a file with `code` and `name` headers, and delete the other columns).
Another way is to first perform an export, update the desired values in the generated file and re-import it.

Regards,
Mathias

**Comment by grabelle** [comment]
Hi,
Sorry but if you do so, it will erase all the data and just let the new one.

**Comment by grabelle** [comment]
sorry ... I did import this for product update (price)

identifier;price-CHF;price-EUR;wholesale_price-CHF;wholesale_price-EUR
CHR220191007600008000;10.9;9.59;5.45;4.8
CHR220191007500018000;59.900000000000006;52.7;29.950000000000003;26.35
CHR440802134000008000;67.9;59.74;47.550000000000004;41.84
CHR440802135000008000;65.9;57.980000000000004;46.150000000000006;40.61
CHR190600031000008000;24.9;21.91;14.95;13.15
.....
.....

>> my PIM is now "empty" I have only those column for my product :-(

**Comment by Doodoune** [comment]
Hi @grabelle,

Natively, update a file with partial updates don't delete other values; it will update only the value that you send in the file.

Ex: for product
{code}
sku;price-EUR;price-USD
13710067;175;250
{code}

for product model
{code}
code;price-EUR;price-USD
amor;175;250
{code}
Will only update price eur & price usd attribute values for the product 13710067 and the product model amor.

Can you reproduce this issue without your custom code? 
If yes, can you give me step by step how to reproduce this error? Don't forget to send us your current PIM version.

Regards,

**Comment by Doodoune** [comment]
Yes, it's normal for us, it will create a product with just the information that you provide.

If you want a family you have to specify it with a column family:
**Ex: for product**
sku;family;price-EUR;price-USD
13710067;clothing;175;250

Regards,

**Comment by grabelle** [comment]
Hi, Strange because the family is a mandatory field ?

**Comment by Doodoune** [comment]
It's mandatory through the UI yes. But not through import/export. It's a "work as design" behavior.

**Comment by Doodoune** [comment]
I close this issue, feel free to re-open it if needed.
Regards,
