### ISSUE TITLE
Import Product error CATCHABLE FATAL ERROR: OBJECT OF CLASS DATETIME

### ISSUE THREAD

**Issue by nervusdm** [akeneo/pim-community-dev#9268]
**I'm reporting a Bug**

Akeneo 2.3 CE. Php 7.1 (fresh install on a VM for Akeneo)

While importing data (without any datatime attribute at all), I have this failure in red : 

CATCHABLE FATAL ERROR: OBJECT OF CLASS DATETIME COULD NOT BE CONVERTED TO STRING

Daemons says that  : 
15:37:06 WARNING   [batch] The Pim\Component\Connector\Processor\Denormalization\ProductProcessor was unable to handle the following item: [family => 0808, enabled => true, values => [sku => [0 => [locale => , scope => , data => IDOP00520L0]], image => [0 => [locale => , scope => , data => /tmp/pim/upload_tmp_dir/export/8823_10041.jpg]], name => [0 => [locale => fr_FR, scope => catalogue, data => Ceinture Abdominale Triple sécurités - Taille L], 1 => [locale => fr_FR, scope => ecommerce, data => ], 2 => [locale => es_ES, scope => ecommerce, data => ], 3 => [locale => fr_FR, scope => orthop, data => Ceinture Abdominale Triple sécu - L]]], identifier => IDOP00520L0] (REASON: image: Property "image" expects a valid pathname as data, "/tmp/pim/upload_tmp_dir/export/8823_10041.jpg" given.) [] []
15:37:07 ERROR     [batch] Encountered an error executing the step: Catchable Fatal Error: Object of class DateTime could not be converted to string [] []

**Comment by nervusdm** [comment]
Ok. It's all about xlsx files... Should column in text mode.

**Comment by padmapriya126** [comment]
We got the same error and found the following:

The excel file had a data issue. We had a column to save "ratio" value and when added a ratio (eg: 3:2), the excel auto-converted the value in date format as follows: 3:02:00 AM. In order to fix this issue, we changed the format to Text and saved the file and imported it. The file was successfully imported.
