### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sm7297** [akeneo/pim-community-dev#9314]
**I'm reporting a Bug**

For version 2.3 on Ubuntu 2.3 with Php 7.1 and maria db. 
Getting this error on the apache errorlog when accessing akeneo

[Thu Jan 03 01:52:48.360729 2019] [php7:warn] [pid 4600] [client 192.168.0.150:60530] PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 145
[Thu Jan 03 01:52:48.361526 2019] [php7:warn] [pid 4600] [client 192.168.0.150:60530] PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 145
[Thu Jan 03 01:52:48.362526 2019] [php7:warn] [pid 4600] [client 192.168.0.150:60530] PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 145
[Thu Jan 03 01:52:48.362703 2019] [php7:error] [pid 4600] [client 192.168.0.150:60530] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo.pim_session' doesn't exist in /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105\nStack trace:\n#0 /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)\n#1 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(523): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php(92): Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\PdoSessionHandler->doRead('i6el706lvt83dg7...')\n#3 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(278): Symfon in /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 107

**Comment by mmetayer** [comment]
Hello @sm7297, 
it looks like your `pim_session` table was not created, did you run all the steps of the [installation guide](https://docs.akeneo.com/2.3/install_pim/manual/installation_ce_archive.html) (especially `bin/console pim:install --force --symlink --clean --env=prod`) ?
Also, please note that Akeneo does not officially support MariaDB (see system requirements [here](https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/system_requirements.html))

Regards,
Mathias

**Comment by sm7297** [comment]
Hey Mathias,
When used with Mysql5.7 it worked for Requirement check but after when creating database schema getting these error.
[Error while Installing.txt](https://github.com/akeneo/pim-community-dev/files/2728465/Error.while.Installing.txt)

**Comment by mmetayer** [comment]
Hello again @sm7297,

- it seems that you didn't create `app/config/parameters.yml`, try to run `composer run-script post-install-cmd`, and **be sure to clear your cache afterwards**
- your DB does not seem to be properly configured (ACCESS denied for user 'root'@'192.168.0.103'... anyway I wouldn't advise to use the root user, try creating another user : https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/manual_system_installation_debian9.html#system-installation)

Regards,
Mathias

**Comment by sm7297** [comment]
Hello Mathias,
After performing above operation I got 
"Reset elasticsearch indexes

In StaticNoPingConnectionPool.php line 51:
                                        
  No alive nodes found in your cluster  
                                        

The command terminated with an error code: 1.
Error during PIM installation. The command terminated with an error code: 1."

Then I ran yarn run webpack
Everything works fine but when I try to access it gives 
[Mon Jan 07 21:26:40.940240 2019] [php7:error] [pid 13456] [client 192.168.0.150:38156] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo.pim_session' doesn't exist in /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105\nStack trace:\n#0 /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)\n#1 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(523): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php(92): Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\PdoSessionHandler->doRead('dui489qnpv1p1of...')\n#3 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php(278): Symfon in /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 107, referer: http://192.168.0.103/akeneo/pim-community-standard/

**Comment by mmetayer** [comment]
Hello,

the Elasticsearch error means you forgot to configure (or misconfigured) your ES connection; this is mandatory to install the PIM, and explains the following error (the DB was not properly installed). Please be sure to follow all the steps described in our guide: 
https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_install_ubuntu_1604.html#system-installation-on-ubuntu-16-04-xenial-xerus
https://docs.akeneo.com/latest/install_pim/docker/installation_docker.html#install-and-run-akeneo

BTW, this issue tracker is meant to report issues about the codebase of akeneo; for install problems I suggest you ask your questions on [StackOverflow](https://stackoverflow.com/questions/tagged/akeneo) :slightly_smiling_face: 

Regards,

**Comment by Doodoune** [comment]
Hi @sm7297! Does it solve your issue? Can we close this ticket?

Regards,

**Comment by Doodoune** [comment]
I close this issue,
Feel free to reopen it if you still have an error.

Regards,

**Comment by patefoniq** [comment]
I had the same problem and after eliminating elastic error I have:

```
Load jobs for fixtures. (data set: src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal)

In FixturePathProvider.php line 39:

  Installer data directory cannot be found.


The command terminated with an error code: 1.
Error during PIM installation. The command terminated with an error code: 1.

```

**Comment by mertyakan** [comment]
look #13132
