### ISSUE TITLE
Port number not considered on the System information page so it breaks

### ISSUE THREAD

**Issue by nei** [akeneo/pim-community-dev#9332]
**I'm reporting a Bug**

If you are running PIM in a non standard port from Mysql the page system information will break since it does not generate the correct DSN.

**Comment by nei** [comment]
I've done a fix for that on https://github.com/akeneo/pim-community-dev/pull/9333

**Comment by damien-carcel** [comment]
Hello @nei and thank you so much for this contribution. I ask the core team to review your PR.

Best regards,
Damien.

**Comment by damien-carcel** [comment]
And the PR is merged :tada:! Thanks again @nei.
