### ISSUE TITLE
Slow performance on product export profile

### ISSUE THREAD

**Issue by muspelheim** [akeneo/pim-community-dev#9358]
**I'm reporting a Bug**

[akeneo-pim-system-info_2019-01-11_13_36.txt](https://github.com/akeneo/pim-community-dev/files/2749757/akeneo-pim-system-info_2019-01-11_13_36.txt)

The problem related to product export profile.

1. Create a product/product model export profile
2. Edit created profile
3. Go to the `Content` tab
4. Pick `List` field filter with 10000-15000 values for example

A super slow performance appeared because of render of all of those elements in the select box, there is no behavior such as in grid filter in main product panel as expected.

https://drive.google.com/file/d/141BSGWMjEX2mnNi6tscMzVLVrhLR8Jaj/view?usp=sharing

**Comment by Doodoune** [comment]
Hi @newQuery!

Since this issue concerns a EE client, please use our dedicated Helpdesk (http://helpdesk.akeneo.com) to raise it. We'll handle this request according to the EE license terms :)

Thanks!
