### ISSUE TITLE
[API][RestSharp] Creating a new product with ErrorException - "Invalid JSON string"

### ISSUE THREAD

**Issue by mcichonqa** [akeneo/pim-community-dev#9364]
Hello, I used your API for my automated tests and I got some problems with POST method /api/rest/v1/products. In RestSharp response I got StatusCode - Created, ErrorException - "Invalid JSON string" and ResponseStatus - Error. I added new product.

How it is possible, mayby it's something wrong with my model or request? I used for tests your web application DEMO http://demo.akeneo.com, version - 2.3.24.
![screen1](https://user-images.githubusercontent.com/37254162/51075548-25176200-168d-11e9-897c-b21330784c4e.png)
![screen2](https://user-images.githubusercontent.com/37254162/51075549-28125280-168d-11e9-81a6-1f9b138144ad.png)
![screen3](https://user-images.githubusercontent.com/37254162/51075550-29dc1600-168d-11e9-8521-24336cf68a2a.png)

Also I have other question, it is possible to send request with null for attributes like color_scanning or display_color?

Please for answer.
Michał

**Comment by Doodoune** [comment]
Hi!

You probably had an error in your json. Can you send the complete json?

What do you mean by "send request with null for attributes like color_scanning or display_color", you mean for an update of product? a search?

Regards,

**Comment by mcichonqa** [comment]
Hey Doodoune, if I had an incorrect json then I would not create a product. What's wrong with my JSON https://pastebin.com/msiCFkSb
The second question is not important, I understand what I was doing wrong.

Thanks for answer.
Michał

**Comment by mcichonqa** [comment]
Hey Doodoune, probably RestSharp got problems with deserialize and its not error from your application. All clear ;) Thanks for help.

Michał

**Comment by Doodoune** [comment]
I close this issue so.

Regards,
