### ISSUE TITLE
[API][RestSharp] Getting product link

### ISSUE THREAD

**Issue by Alex-Shevtsov** [akeneo/pim-community-dev#9388]
Hi everyone,

Could you explain to me how you can get a link to the product using REST API. 
![capture](https://user-images.githubusercontent.com/26141697/51326098-06dba880-1a77-11e9-9451-80b0a86bea70.PNG)

Or how can I get technical_id of my product via REST API. Or how can I execute a GET request for a url: http://demo.akeneo.com/datagrid/product-grid?dataLocale=en_US&product-grid%5B_filter%5D%5Blabel_or_identifier%5D%5Bvalue%5D=13710067
using a access token via RestSharp.
 I need to create a link to go to the product page.
I using for tests your web application DEMO http://demo.akeneo.com

**Comment by Doodoune** [comment]
Hi @Alex-Shevtsov!

We provide an API. This is a link of the documentation of this API: https://api.akeneo.com/.
You can use this endpoint: https://api.akeneo.com/api-reference.html#get_products__code_ to get information about your product.

Regards,

**Comment by Doodoune** [comment]
Hi! I close this issue. Feel free to re-open it if needed.
Regards,
