### ISSUE TITLE
[CE 2.0] ProductAndProductModelQueryBuilderIntegration

### ISSUE THREAD

**Issue by ahocquard** [akeneo/pim-community-dev#9484]
Path:
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php

Failing test:
testStatusOnProductWithoutParent

Cause: test is working with a batch size of 50 (Jenkins), not with 10 (Circle CI)

**Comment by jmleroux** [comment]
Linked/duplicate to #9474 ?

**Comment by ahocquard** [comment]
@jmleroux yes, I think we can keep this one as there is more information (batch size).
