### ISSUE TITLE
Safari product field data being hidden

### ISSUE THREAD

**Issue by andrew-smart** [akeneo/pim-community-dev#9485]
Akeneo Version: 2.3.25

In Safari, fields are being hidden by the AknTextareaField-layer AknTextareaField-layer--first and AknTextareaField-layer AknTextareaField-layer--second divs.

In Chrome you see;
![screenshot 2019-01-31 at 08 58 59](https://user-images.githubusercontent.com/1692003/52042997-7ef5a400-2536-11e9-9d15-f5bdb99d9dfd.png)

In Safari you see;
![screenshot 2019-01-31 at 08 59 05](https://user-images.githubusercontent.com/1692003/52043006-8452ee80-2536-11e9-859c-bf5bc610c90e.png)

**Comment by Doodoune** [comment]
Hi @andrew-smart!
We only support Chrome 30+, Firefox 29+ as you can see in our documentation: https://docs.akeneo.com/2.3/technical_architecture/technical_information/client_side_compatibilities.html
Regards,
