### ISSUE TITLE
Filter options ... should be filtered when a filter is selected

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#9500]
Hi,

Akeneo 2.3.27

For example, if I have 2 filters (Filter 1 (with a list of options) and filter 2 (with a list of options))
if I select a value for filter 1..... I would expect the list of filter 2 options to be updated (and only the options available for the products in the grid to be visible).

not sure to be very clear ;-/

Best Regards

**Comment by grabelle** [comment]
Hi,
Akeneo 2.3.28 ...

Anyone to answer or give their opinion? Maybe I'm not clear, but I really think it would be very useful and more logical

Thanks.

**Comment by Doodoune** [comment]
Hi Grabelle,
It doesn't exist natively in the PIM. You have to create custom code to do that.
Regards,

**Comment by Doodoune** [comment]
I close this issue.
Feel free to reopen it if needed.
Regards,

**Comment by grabelle** [comment]
Hi,
Well I really think that most of akeneo user would love this feature (that is common in faceted search)
