### ISSUE TITLE
Run "Reference Entity" bounded context tests with CircleCI

### ISSUE THREAD

**Issue by grena** [akeneo/pim-community-dev#9579]
We have to run same tests as Travis.ci is running

**Comment by jmleroux** [comment]
Yes it mut be done to avoid some uncommon side effects.

**Comment by grena** [comment]
For record, those 2 PRs already broke our tests:

- https://github.com/akeneo/pim-community-dev/commit/4818b11db3c70fea8eced90b2325c819412d6110
- https://github.com/akeneo/pim-community-dev/commit/1d8c3b4f49d4974e18f1c65f8d8e58f81496c122

**Comment by jmleroux** [comment]
What is the status of this ticket?
I think we already have some Reference Entities steps in the current workflow.

**Comment by grena** [comment]
Yes, done via https://github.com/akeneo/pim-enterprise-dev/pull/5706
