### ISSUE TITLE
Download export files link never visible

### ISSUE THREAD

**Issue by stefandoorn** [akeneo/pim-community-dev#9616]
I'm using Akeneo v3.0.1, running on Kubernetes (similar setup as Docker). I can export data, and I also get the files visible on the local file system. What I get from documentation though, is that there should also become a link visible to download the files via the UI. I never get to see that link though. 

The PHP container has access to the filesystem as the export itself landed properly in there. The files are in non-public folders, therefore I don't think the 'httpd' container needs to have access to it. I'm not sure what's the best way to debug this though.

**Comment by stefandoorn** [comment]
When running on production (output of the call to `/job-execution/rest/<id>?id=<id>&cached=false` endpoint):

```
{"failures":[],"stepExecutions":[{"label":"export","job":"csv_attribute_export","status":"Completed","summary":{"read":"85","written":"85"},"startedAt":"2\/20\/19, 11:46 AM","endedAt":"2\/20\/19, 11:46 AM","warnings":[],"failures":[]}],"isRunning":false,"status":"Completed","jobInstance":{"code":"csv_attribute_export","job_name":"csv_attribute_export","label":"Demo CSV attribute export","connector":"Akeneo CSV Connector","type":"export","configuration":{"filePath":"\/tmp-php\/attribute.csv","delimiter":";","enclosure":"\u0022","withHeader":true,"user_to_notify":null,"is_user_authenticated":false}},"meta":{"logExists":false,"archives":[],"id":"35"}}
```

Local:

```
{"failures":[],"stepExecutions":[{"label":"export","job":"csv_attribute_export","status":"Completed","summary":{"read":"77","written":"77"},"startedAt":"2\/20\/19, 12:47 PM","endedAt":"2\/20\/19, 12:47 PM","warnings":[],"failures":[]}],"isRunning":false,"status":"Completed","jobInstance":{"code":"csv_attribute_export","job_name":"csv_attribute_export","label":"Demo CSV attribute export","connector":"Akeneo CSV Connector","type":"export","configuration":{"filePath":"\/tmp\/attribute.csv","delimiter":";","enclosure":"\u0022","withHeader":true,"user_to_notify":null,"is_user_authenticated":false}},"meta":{"logExists":true,"archives":{"output":{"label":"pim_enrich.entity.job_execution.module.download.output","files":{"attribute.csv":"export\/csv_attribute_export\/19\/output\/attribute.csv"}}},"id":"19"}}
```

I do see the difference that it marks the `logExists` as false and no files available in the call, but it's unclear why that is. The log files do exist (checked on the file system), so does the export file. I'll dig further, but any guidance would be appreciated.

**Comment by stefandoorn** [comment]
Issue solved, wrong paths.

**Comment by maximgubar** [comment]
@stefandoorn what was exactly with the paths ?
atm I'm facing kinda similar issue.
pim version 5.x
two containers, one for regular web access, another is for daemon queue.

paths: 
- var/file_storage/jobs
- var/logs/batch
are shared between both containers.

logExists is true, but archives is [].

I'm asking cause probably you've already solved this one.

Regards,

**Comment by maximgubar** [comment]
ok, found it.
looks like path var/file_storage/archive/export should also be shared.
