### ISSUE TITLE
Currency toggle does not change status

### ISSUE THREAD

**Issue by stefandoorn** [akeneo/pim-community-dev#9629]
Akeneo v3.0.4, using the minimal data fixtures, in production mode. After that I want to disable the USD currency, but  clicking on the toggle does not change anything. The toggle GET call returns a 200 status code though.

**Comment by Doodoune** [comment]
Hi @stefandoorn!

We have a process that don't prevent to disable currencies that are used in your Channel configuration.
Remove the currency in your channel configuration and you will be able to disable it after.

Regards,

**Comment by stefandoorn** [comment]
Ah, thanks! It would be great though to have a message telling that :-) Then this issue can be a feature request for that.

**Comment by Doodoune** [comment]
If you want to contribute to this feature, don't hesitate. 
Regards,

**Comment by Doodoune** [comment]
Hi,
We fix this issue by adding a flash error message that explain why you can't disable it in the v3.0.64.
It will be available in the 3.2 version soon.
I close this issue. Feel free to reopen it if needed.
Regards,
