### ISSUE TITLE
[CE 3.0] edit_product_with_localized_attributes.feature:59

### ISSUE THREAD

**Issue by rouliane** [akeneo/pim-community-dev#9662]
Circle CI build : https://circleci.com/gh/akeneo/pim-enterprise-dev/4313#tests/containers/12
PR : https://github.com/akeneo/pim-enterprise-dev/pull/5736

We encountered an unstable behat when running a EE build.

vendor/akeneo/pim-community-dev/tests/legacy/features/pim/enrichment/product/pef/edit_product_with_localized_attributes.feature:59 - Edit a product with localized attributes
Then the field Date should contain "05/28/2015": Spin : timeout of 50 excedeed, with message : Expected product field "Date" to contain "05/28/2015", but got "150.8675". (Context\Spin\TimeoutException)

**Comment by ahocquard** [comment]
No problem anymore with that.
