### ISSUE TITLE
PROCESS TRACKER stuck on starting export

### ISSUE THREAD

**Issue by kamranmalikawan** [akeneo/pim-community-dev#9664]
Export process stuck on starting not able to purge as well
akeneo:batch:purge-job-execution

Akeneo Version 3.0.3 Super-Rabbit

**Comment by kamranmalikawan** [comment]
@Doodoune Can you please help on that 
<img width="1440" alt="screen shot 2019-02-26 at 5 14 31 pm" src="https://user-images.githubusercontent.com/4948399/53412307-d4fd2080-39ea-11e9-9271-b186aef49236.png">

**Comment by kamranmalikawan** [comment]
supervisorctl start akeneo_queue_daemon already started!

**Comment by ankit-sf** [comment]
try restarting supervisor queue, maybe a job is running which is blocking other jobs

supervisorctl restart akeneo_queue_daemon

**Comment by Doodoune** [comment]
Did you have a job running ?
The deamon run job one by one, so if one is really long to execute, it blocks other jobs.
(cf https://docs.akeneo.com/3.0/install_pim/manual/daemon_queue.html#purpose-of-the-queue)

**Comment by Doodoune** [comment]
I close this issue.
If you have more information about this problem, don't hesitate to reopen it.

Regards,

**Comment by ramin83de** [comment]
Hello,

I would like to reopen this issue. I'm running Akeneo Version:CE 3.2.45 by Bitnami and my process is stucked in the "starting" status. In the previous version of Akeneo I could use the following command to "kill" the process:

bin/console akeneo:batch:purge-job-execution --days=0 --env=prod

"days=0"

Now I have to add a value >0, e.g. 1, but this deletes just the jobs from yesterday. How can I stop the process?

I also went through the documentation of the supervisor:
https://docs.akeneo.com/3.2/install_pim/manual/daemon_queue.html#option-1-supervisor

But unfortunately nothing helps. The process is still on "starting" status.

Addition info: I've set up a new Akeneo Bitnami Stack and imported the database from another Akeneo Bitnami Stack which was 3.2.26 or something like this.

Can someone help?

Thx

**Comment by kamranmalikawan** [comment]
@ramin83de  please clear and restart redi server

and then apply those commands

php bin/console cache:clear --no-warmup --env=prod
php bin/console akeneo:elasticsearch:reset-indexes --env=prod
php bin/console pim:product:index --all --env=prod
php bin/console pim:product-model:index --all --env=prod
php bin/console pim:completeness:calculate --env=prod
php bin/console pim:volume:aggregate --env=prod
chmod 777 -R tmp var vendor

**Comment by ramin83de** [comment]
@kamranmalikawan 

Not sure what the redi server is, but I restarted the whole bitnami server and performed all mentioned commands. the process is still in "starting" status

**Comment by bhatir** [comment]
I see the same issue as well. Has there been any progress on this?

**Comment by bhatir** [comment]
Solved!!! This [article ](https://github.com/akeneo/pim-community-dev/issues/7070) worked for me. 

Basically I had to run this command to get the batch daemon to run - 
_bin/console akeneo:batch:job-queue-consumer-daemon --env=prod --run-once_

**Comment by hRevault** [comment]
I'm still having this issue, I can't stop some processes ( option is not available on the left of "View" button) 

And when I can stop a process ( exports, most of the time ), they are blocked in " Stopping" status and I can't do anything about that 

![image](https://user-images.githubusercontent.com/102515510/160365216-9f45c3b1-f0f5-45ed-9b5b-29cae2c7451a.png)

Does anyone have an idea to fix this ?
