### ISSUE TITLE
'Variable "image" does not exist.' in dashboard (> v3.0.3)

### ISSUE THREAD

**Issue by nu-fp** [akeneo/pim-community-dev#9666]
There seems to be a problem with the dashboard. If I install version v3.0.5 I get an error 'Variable "image" does not exist.'.  As of version v3.0.4 the line
       {% set image %}
            <img
                class="AknTitleContainer-image"
                src="{{ app.user.imagePath ? app.user.imagePath | imagine_filter('thumbnail_small') : asset('bundles/pimui/images/info-user.png') }}"
            >
        {% endset %}
disappeared in vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/DashboardBundle/Resources/views/Dashboard/index.html.twig
and this leads to this error (commit 36babac7b6). 
Can anyone confirm this?

[akeneo-pim-system-info_2019-02-26_14_22.txt](https://github.com/akeneo/pim-community-dev/files/2905703/akeneo-pim-system-info_2019-02-26_14_22.txt)

**Comment by maximgubar** [comment]
I have similar issue, 500 error on dashboard

**Comment by Doodoune** [comment]
Hi! 

We solve this issue in the v3.0.7 of the PIM.
Please upgrade your PIM to the last version to solve this issue.

I close this issue, feel free to re-open it if this is not fixing your error.

Regards,
