### ISSUE TITLE
pim_common.copy.none translation key missing in en_US

### ISSUE THREAD

**Issue by stefandoorn** [akeneo/pim-community-dev#9671]
Clicking on the 'Select' dropdown on this URL revealed a missing translation key: https://akeneo/#/enrich/product-model/1

**Comment by Doodoune** [comment]
Hi @stefandoorn!
Can you send me a screenshot of this missing translation to help me to reproduce? I don't find this missing translation.

Regards,

**Comment by Doodoune** [comment]
Visibly it's corrected in v3.0.11. => PIM-8258: Fix missing translation for "copy none"

Regards,

**Comment by stefandoorn** [comment]
Thanks!
