### ISSUE TITLE
[2.3 EE] field_display.feature

### ISSUE THREAD

**Issue by jmleroux** [akeneo/pim-community-dev#9683]
**Branch:** EE 2.3

**Test to fix:** tests/legacy/features/product_draft/compare_and_copy/field_display.feature

**Failing build example:** https://circleci.com/gh/akeneo/pim-enterprise-dev/4614#tests/containers/5

**Frequency:** very common

**Comment by ahocquard** [comment]
@jmleroux what is the status of this issue?
