### ISSUE TITLE
[BUG] Filter behavior

### ISSUE THREAD

**Issue by newQuery** [akeneo/pim-community-dev#9686]
**I'm reporting a Bug**
[akeneo-pim-system-info_2019-02-28_16_19.txt](https://github.com/akeneo/pim-community-dev/files/2915860/akeneo-pim-system-info_2019-02-28_16_19.txt)

Hi I'm having an issue with **filters**, particularly **select2-choice-filter**
On the product datagrid, I add a filter "Couleur matière". 
Once it is added to the filter's list, here is how it looks like once I click on it:
Screenshot: https://i.imgur.com/rzN72z3.png

Now I want it to be set for "**not empty**" only, as you can see, when I select "**not empty**" the input field **disappear**.
Screenshot: https://i.imgur.com/lmZ5XFU.png

After I click "**Update**" (Mettre à jour), my grid gets updated as wanted. However, when I click on my filter which was set to "not empty", the input field is **showing up**. This is very confusing for the client because he may think he can filter by value while it was already set to "**not empty**".
Screenshot: https://i.imgur.com/sGlsY47.png

**Comment by Doodoune** [comment]
Hi @newQuery!

Since this issue concerns a EE client, please use our dedicated Helpdesk (http://helpdesk.akeneo.com) to raise it. We'll handle this request according to the EE license terms :)

Thanks!
