### ISSUE TITLE
Product page loads slow with >800k products

### ISSUE THREAD

**Issue by AykutCevik** [akeneo/pim-community-dev#9709]
As I wrote in https://github.com/akeneo/pim-community-dev/issues/9271#issuecomment-462860193 I'm using the community edition and running 2.3.29. The product pages takes up to 6 seconds to load and I can't figure out why. Please also see the screenshots I've shared. We have more than 800k products upload. Filters, search and paging works pretty well after the initial load.

**Comment by Doodoune** [comment]
Hi @AykutCevik!

We do some improvements on the Datagrid, in the v3.0 version.
That can help you with your loading issue.

It also can come from you volumetry (the number of attribute per product, the number of locales & scopes, the number of attributes localizable, scopable, localizable & scopable etc.). Can you send us your System Information file (in System > System Information)?

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it with more details to help us to reproduce the behavior.

Regards,
