### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by paveq** [akeneo/pim-community-dev#9717]
**Expected behavior**

`composer install` works with project repository containing just composer.json and lock files.

**What happened**

Install fails with errors such as:

`Could not open input file: app/console`

**Notes**

It should not be required for user of Akeneo to track upstream files in their project repository (such as app/console), these files should come from Akeneo's own package index, and placed into correct locations during composer install. Installation should pull in all the files that are not part of the project specific customizations or it's configuration.

As example, Magento 2 handles this issue by [file marshalling](https://devdocs.magento.com/guides/v2.3/cloud/reference/cloud-composer.html#base-packages-and-file-marshalling):

> Magento contains two base packages: magento/magento2-base and magento/magento2-ee-base. These packages contain interstitial files that cannot be classified as extensions, themes, frameworks, or language packages; for example, sample server configuration files, PHP entry points, and so on.
> 
> These files are location-dependent, and cannot reside in the vendor directory. They are distributed as part of the base packages, and they rely on hooks located in the magento/magento-composer-installer package, which marshals them to the appropriate locations.

**Comment by Doodoune** [comment]
Hi @paveq!

Can you say what is the PIM version you tried to install?

Note that for PIM v1.x you can found the console in `app/console` but in PIM v2.x and v3.x the console is in `bin/console`.

This file is provided when you download the PIM: https://github.com/akeneo/pim-community-dev/blob/3.0/bin/console

Regards,

**Comment by Doodoune** [comment]
I close this issue,
feel free to reopen it if you still have an error.
Regards,
