### ISSUE TITLE
pim_enrich.form.family.tab.attributes.not_required_label shown when hovering over attribute required state

### ISSUE THREAD

**Issue by stefandoorn** [akeneo/pim-community-dev#9747]
To be seen on this page: https://pim.local/#/configuration/family/family_code/edit. Then hover over the attribute requiredness. Another label is shown when it's required.

Using Akeneo v3.0.6.

**Comment by Doodoune** [comment]
Hi @stefandoorn! 
A new version was released today that fixes this glitch: v3.0.8.
Please upgrade your PIM.

I close this issue, but if you still have a problem with this key translation missing, feel free to re-open it.
Regards,
