### ISSUE TITLE
Twig version CVE

### ISSUE THREAD

**Issue by stefandoorn** [akeneo/pim-community-dev#9787]
https://symfony.com/blog/twig-sandbox-information-disclosure

`composer.json` requires v1.6, but:

Twig 1.0.0 to 1.37.1 and 2.0.0 to 2.6.2 are affected by this security issue.

**Comment by Doodoune** [comment]
Thanks for your contribution @stefandoorn! :tada: 
It will be available in our next release (v3.0.11).

Regards,
