### ISSUE TITLE
doctrine\Common\Collections\ArrayCollection was never imported

### ISSUE THREAD

**Issue by PatrWeste** [akeneo/pim-community-dev#9839]
When i try this: $ bin/docker/pim-initialize.sh

then get i this Error-Message: 
10:20:04 ERROR     [batch] Encountered an error executing the step: [Semantical Error] The annotation "@psalm" in class Doctrine\Common\Collections\ArrayCollection was never imported. Did you maybe forget to add a "use" statement for this annotation? [] []

How can i fix it?

**Comment by Doodoune** [comment]
Hi!

We solve this issue in v2.3.35 and v3.0.10. 

Can you upgrade your PIM to fix this issue?
It came from an update of "doctrine/collection". We fix it in the composer.json `"doctrine/collections": "1.5.0"`.

Regards,

**Comment by Doodoune** [comment]
I close this issue, feel free to reopen it if needed.
Regards,

**Comment by yann-eugone** [comment]
FYI this issue is still here for lower (unsupported) versions of Akeneo : (`<2.3`)
You can solve it by adding a direct dependency to `doctrine/collections:1.5.0` to your project :

```
composer require doctrine/collections:1.5.0 --prefer-dist
```
