### ISSUE TITLE
Empty filter field

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#9841]
With Akeneo 3.0.7 CE, on the "Product" page I added a list of 118 references in the sku field. How to empty this list in one manipulation?

![image](https://user-images.githubusercontent.com/4558101/55164525-1577c780-516c-11e9-9552-a9d433f963f6.png)

**Comment by LeoBenoist** [comment]
Solution 1 Use backspace
![solu1](https://user-images.githubusercontent.com/2912614/55165455-bc109800-516d-11e9-99e8-4a43d05a6273.gif)
Solution 2 Clic X to remove the filter
![solu2](https://user-images.githubusercontent.com/2912614/55165456-bc109800-516d-11e9-84d2-47350faec683.gif)

**Comment by Doodoune** [comment]
I close this issue.
Regards,
