### ISSUE TITLE
Add properties to categories not working

### ISSUE THREAD

**Issue by SukeshiniR** [akeneo/pim-community-dev#9953]
I'm using Akeneo 3.0 version. I tried to add a new property to Categories and followed the below official documentation. 
https://docs.akeneo.com/latest/manipulate_pim_data/category/add_new_properties_to_a_category.html

It causes the below error when I click to edit an existing category.

> Neither the property "description" nor one of the methods "description()", "getdescription()"/"isdescription()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView".

```
Twig\Error\
RuntimeError
in src/Acme/Bundle/EnrichBundle/Resources/views/CategoryTree/Tab/property.html.twig (line 4)
<div class="tab-pane tab-property {{ viewElement.loop.first ? 'active' : '' }}" id="{{ viewElement.alias|replace({' ': '-', '.': '-'})|lower }}"> 
   {% set generalProperties %}     
   {{ form_row(form.code) }}      
  {{ form_row(form.description) }} # this line causes the error
   {% endset %}   
 {% set nodeValues %}      
  {{ form_row(form.label) }}  
  {% endset %} 
   {{ elements.tabSections({
```

**Comment by SukeshiniR** [comment]
Can anyone kindly check this please. It seems the code examples provided in official documentation now work.

**Comment by Doodoune** [comment]
Hi @SukeshiniR!

We release a new fix of our documentation. It contains a fix for the "how to add a new property to a category" page.

https://docs.akeneo.com/3.0/manipulate_pim_data/category/add_new_properties_to_a_category.html

Please, clean your browser cache to show the new version.

Regards,
