### ISSUE TITLE
Installer is broken 

### ISSUE THREAD

**Issue by oefterdal** [akeneo/pim-community-dev#9972]
**I'm reporting a Bug**

Documentation has been updated to reflect upcoming release. 

`php composer.phar create-project --prefer-dist akeneo/pim-community-standard ./pim-project "3.1.*@stable"` 

```
[InvalidArgumentException]                                                   
Could not find package akeneo/pim-community-standard with version 3.1.*@stable.   
```

**Comment by Doodoune** [comment]
Effectively, the documentation was updated before the release. 
I've shared this info with our product team to improve our release processes.
Regards,

**Comment by Reiner030** [comment]
yesterday it was working but today I get also - tested with different create call variants (parameters, quotes, ...):

```
$ php -d memory_limit=3G $(which composer) create-project --no-interaction --no-ansi --no-dev --no-install --prefer-dist akaneo/pim-community-standard /var/www/pim-community-standard '3.1.*@stable'       
In CreateProjectCommand.php line 317:

  Could not find package akaneo/pim-community-standard with version 3.1.*@stable.

```
